In [16]:
import numpy as np
from scipy.stats import binom

# draw a single sample
np.random.seed(42)
# rvs(n, p, loc=0, size=1, random_state=None)	Random variates.
print(binom.rvs(p=0.3, n=10), end="\n\n")

# draw 10 samples
print(binom.rvs(p=0.3, n=10, size=10), end="\n\n")

print(binom.rvs(p=0.3, n=10, size=(2, 3)))

2

[5 4 3 2 2 1 5 3 4 0]

[[6 4 2]
 [2 2 2]]


In [17]:
# Draw samples from a binomial distribution.
print(np.random.binomial(p=0.3, n=10), end='\n\n')  # draw a single sample

print(np.random.binomial(p=0.3, n=10, size=10), end='\n\n')  # draw 10 samples

print(np.random.binomial(p=0.3, n=10, size=(2, 5)))

3

[3 2 3 1 2 2 3 4 2 3]

[[3 1 3 2 1]
 [5 6 4 2 1]]


In [19]:
# Draw samples from a multinomial distribution
'''
n : int
    Number of experiments.
pvals : sequence of floats, length p
    Probabilities of each of the ``p`` different outcomes.  These
    must sum to 1 (however, the last element is always assumed to
    account for the remaining probability, as long as
    ``sum(pvals[:-1]) <= 1)``.
'''
np.random.multinomial(100, [1 / 7.] * 5 + [2 / 7.], size=(3, 3))

array([[[19, 11, 15, 12, 14, 29],
        [15, 11, 21, 16, 17, 20],
        [19, 14, 18,  8, 11, 30]],

       [[ 9, 13, 15, 14, 19, 30],
        [13, 12, 15, 11, 19, 30],
        [ 9, 23, 16, 10,  7, 35]],

       [[17, 16, 15, 15,  8, 29],
        [13, 10, 19, 15, 13, 30],
        [ 9, 13, 14, 18, 16, 30]]])