In [12]:
import tensorflow as tf

### 参考numpy.mean

In [13]:
a = tf.random.stateless_normal(mean=2, stddev=3, shape=(2, 3, 4), seed=(1, 2))
a

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[ 3.6323304 ,  2.622141  ,  2.220693  ,  2.1393037 ],
        [-1.9047699 , -0.8615699 ,  4.5251856 ,  7.8190603 ],
        [ 3.9537735 ,  5.31466   ,  6.1238685 ,  5.4462557 ]],

       [[ 5.246394  ,  3.6531477 ,  2.2102885 ,  4.122155  ],
        [ 4.6657124 ,  0.60701835,  5.6253    , -0.37034798],
        [-0.1914711 , -0.16226149,  3.0958257 ,  1.4914773 ]]],
      dtype=float32)>

In [14]:
# Computes the mean of elements across dimensions of a tensor.
tf.math.reduce_mean(a)

<tf.Tensor: shape=(), dtype=float32, numpy=2.9593403>

In [15]:
# The dimensions to reduce. If None (the default), reduces all dimensions
tf.math.reduce_mean(a, axis=0)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 4.4393625 ,  3.1376443 ,  2.2154908 ,  3.1307294 ],
       [ 1.3804712 , -0.12727576,  5.075243  ,  3.7243562 ],
       [ 1.8811512 ,  2.5761993 ,  4.609847  ,  3.4688663 ]],
      dtype=float32)>

In [16]:
# 注意:axis参数也可以为元组;第0个维度上所有数据的均值
tf.math.reduce_mean(a, axis=(1, 2))

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([3.419244 , 2.4994366], dtype=float32)>

In [17]:
# If true, retains reduced dimensions with length 1.
tf.math.reduce_mean(a, axis=0, keepdims=True).shape  # 保留缩减的维度(广播时使用)




TensorShape([1, 3, 4])