In [42]:
import tensorflow as tf

### 参考numpy

#### 加法add

In [43]:
a = tf.constant([1.])
b = tf.constant([2.])
print(a + b)
print(tf.math.add(a, b))

tf.Tensor([3.], shape=(1,), dtype=float32)
tf.Tensor([3.], shape=(1,), dtype=float32)


#### 减法substract

#### 乘法multiply

In [44]:
a = tf.constant([1.])
b = tf.constant([2.])
print(a * b)
print(tf.math.multiply(a, b))

tf.Tensor([2.], shape=(1,), dtype=float32)
tf.Tensor([2.], shape=(1,), dtype=float32)


#### 除法divide

In [45]:
a = tf.constant([-5, 5, 7, 9, -13])
b = tf.constant([2, 3, 4, 2, 4])

print(a / b)
print(tf.math.divide(a, b))

tf.Tensor([-2.5         1.66666667  1.75        4.5        -3.25      ], shape=(5,), dtype=float64)
tf.Tensor([-2.5         1.66666667  1.75        4.5        -3.25      ], shape=(5,), dtype=float64)


In [46]:
# 地板除法
a // b

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([-3,  1,  1,  4, -4])>

#### other

In [ ]:
a % b  # 取余(结果必大于0)

In [48]:
a > b

<tf.Tensor: shape=(5,), dtype=bool, numpy=array([False,  True,  True,  True, False])>

In [49]:
a >= b

<tf.Tensor: shape=(5,), dtype=bool, numpy=array([False,  True,  True,  True, False])>

In [50]:
a < b

<tf.Tensor: shape=(5,), dtype=bool, numpy=array([ True, False, False, False,  True])>

In [51]:
a <= b

<tf.Tensor: shape=(5,), dtype=bool, numpy=array([ True, False, False, False,  True])>

In [52]:
a == b

<tf.Tensor: shape=(5,), dtype=bool, numpy=array([False, False, False, False, False])>

In [53]:
a != b

<tf.Tensor: shape=(5,), dtype=bool, numpy=array([ True,  True,  True,  True,  True])>