In [13]:
import tensorflow as tf

### 参考numpy.power

In [14]:
x1 = tf.range(6)
x1

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5])>

In [15]:
# 结果可能为浮点数,则输入也要求为浮点数
print(tf.math.pow(tf.cast(x1, tf.double), 0.5))

print(tf.math.pow(x1, 1))
print(tf.math.pow(x1, 2))

tf.Tensor([0.         1.         1.41421356 1.73205081 2.         2.23606798], shape=(6,), dtype=float64)
tf.Tensor([0 1 2 3 4 5], shape=(6,), dtype=int32)
tf.Tensor([ 0  1  4  9 16 25], shape=(6,), dtype=int32)


In [16]:
print(x1 ** 3)
print(tf.math.pow(x1, 3))  # 与上等价

tf.Tensor([  0   1   8  27  64 125], shape=(6,), dtype=int32)
tf.Tensor([  0   1   8  27  64 125], shape=(6,), dtype=int32)


In [17]:
print(3 ** x1)
print(tf.math.pow(3, x1))  # 与上等价

tf.Tensor([  1   3   9  27  81 243], shape=(6,), dtype=int32)
tf.Tensor([  1   3   9  27  81 243], shape=(6,), dtype=int32)


In [18]:
x2 = tf.constant([1, 2, 3, 3, 2, 1])
tf.math.pow(x1, x2)

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([ 0,  1,  8, 27, 16,  5])>

In [19]:
x1 ** x2  # 与上等价

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([ 0,  1,  8, 27, 16,  5])>