In [6]:
import tensorflow as tf

a = tf.reshape(tf.range(32), (2, 4, 4))
a

<tf.Tensor: shape=(2, 4, 4), dtype=int32, numpy=
array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]]])>

### 参考numpy.max/min

In [7]:
tf.math.reduce_max(a)

<tf.Tensor: shape=(), dtype=int32, numpy=31>

In [8]:
tf.math.reduce_max(a, axis=0)

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])>

In [9]:
# 注意:axis参数也可以为元组;第0个维度上所有数据的最大值
tf.math.reduce_max(a, axis=(0, 1))

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([28, 29, 30, 31])>

In [10]:
tf.math.reduce_max(a, axis=(0, 1), keepdims=True)  # 保留缩减的维度(广播时使用)


<tf.Tensor: shape=(1, 1, 4), dtype=int32, numpy=array([[[28, 29, 30, 31]]])>