In [5]:
import tensorflow as tf

### 参考numpy.std

In [6]:
a = tf.random.stateless_normal(mean=2, stddev=3, shape=(2, 3, 4), seed=(1, 2))
a

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[ 3.6323304 ,  2.622141  ,  2.220693  ,  2.1393037 ],
        [-1.9047699 , -0.8615699 ,  4.5251856 ,  7.8190603 ],
        [ 3.9537735 ,  5.31466   ,  6.1238685 ,  5.4462557 ]],

       [[ 5.246394  ,  3.6531477 ,  2.2102885 ,  4.122155  ],
        [ 4.6657124 ,  0.60701835,  5.6253    , -0.37034798],
        [-0.1914711 , -0.16226149,  3.0958257 ,  1.4914773 ]]],
      dtype=float32)>

In [7]:
# 注意:std函数dim参数也可以为元组;第0个维度上所有数据的标准差(有偏)
tf.math.reduce_std(a, axis=(1, 2))

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2.6818779, 2.112889 ], dtype=float32)>

In [8]:
tf.math.reduce_std(a, axis=(1, 2), keepdims=True)  # 保留缩减的维度(广播时使用)

<tf.Tensor: shape=(2, 1, 1), dtype=float32, numpy=
array([[[2.6818779]],

       [[2.112889 ]]], dtype=float32)>