In [1]:
import tensorflow as tf

### 参考numpy.prod/numpy.cumprod

In [2]:
print(tf.math.reduce_prod(tf.constant([0.5, 0.7, 0.2, 1.5])))  # 求积
print(tf.math.cumprod(tf.constant([0.5, 0.7, 0.2, 1.5])))  # 累积

tf.Tensor(0.105000004, shape=(), dtype=float32)
tf.Tensor([0.5   0.35  0.07  0.105], shape=(4,), dtype=float32)


In [3]:
a = tf.constant([[1, 2, 3],
                 [4, 5, 6]])
print(tf.math.reduce_sum(a))

# 注意:axis参数也可以为元组
print(tf.math.reduce_prod(a, axis=(0, 1)))
print(tf.math.reduce_prod(a, axis=(0, 1), keepdims=True))  # 保留缩减的维度(广播时使用)

tf.Tensor(21, shape=(), dtype=int32)
tf.Tensor(720, shape=(), dtype=int32)
tf.Tensor([[720]], shape=(1, 1), dtype=int32)


In [4]:
tf.math.cumprod(a, axis=0)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 4, 10, 18]])>

In [5]:
tf.math.cumprod(tf.reshape(a, (-1,)))


<tf.Tensor: shape=(6,), dtype=int32, numpy=array([  1,   2,   6,  24, 120, 720])>