In [1]:
from transformers import AutoModel, AutoTokenizer, ErnieModel, BertTokenizer

In [2]:
tokenizer = AutoTokenizer.from_pretrained("nghuyong/ernie-health-zh")
print(tokenizer.model_input_names)
print(tokenizer.all_special_tokens)

Downloading:   0%|          | 0.00/491 [00:00<?, ?B/s]

C:\Users\dcdmm\anaconda3\envs\pytorch_env\lib\site-packages\huggingface_hub\file_download.py:123: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\dcdmm\.cache\huggingface\hub. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to see activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)


Downloading:   0%|          | 0.00/112k [00:00<?, ?B/s]

['input_ids', 'token_type_ids', 'attention_mask']
['[UNK]', '[SEP]', '[PAD]', '[CLS]', '[MASK]']


In [3]:
model = AutoModel.from_pretrained("nghuyong/ernie-health-zh")
model

Downloading:   0%|          | 0.00/411M [00:00<?, ?B/s]

Some weights of ErnieModel were not initialized from the model checkpoint at nghuyong/ernie-health-zh and are newly initialized: ['ernie.pooler.dense.weight', 'ernie.pooler.dense.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


ErnieModel(
  (embeddings): ErnieEmbeddings(
    (word_embeddings): Embedding(22608, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (token_type_embeddings): Embedding(2, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): ErnieEncoder(
    (layer): ModuleList(
      (0): ErnieLayer(
        (attention): ErnieAttention(
          (self): ErnieSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): ErnieSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
   

In [4]:
model.config

ErnieConfig {
  "_name_or_path": "nghuyong/ernie-health-zh",
  "architectures": [
    "ErnieModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "embedding_size": 768,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 512,
  "model_type": "ernie",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "task_type_vocab_size": 3,
  "transformers_version": "4.23.1",
  "type_vocab_size": 2,
  "use_cache": true,
  "use_task_id": false,
  "vocab_size": 22608
}

In [5]:
for name, para in model.named_parameters():
    print(name)

embeddings.word_embeddings.weight
embeddings.position_embeddings.weight
embeddings.token_type_embeddings.weight
embeddings.LayerNorm.weight
embeddings.LayerNorm.bias
encoder.layer.0.attention.self.query.weight
encoder.layer.0.attention.self.query.bias
encoder.layer.0.attention.self.key.weight
encoder.layer.0.attention.self.key.bias
encoder.layer.0.attention.self.value.weight
encoder.layer.0.attention.self.value.bias
encoder.layer.0.attention.output.dense.weight
encoder.layer.0.attention.output.dense.bias
encoder.layer.0.attention.output.LayerNorm.weight
encoder.layer.0.attention.output.LayerNorm.bias
encoder.layer.0.intermediate.dense.weight
encoder.layer.0.intermediate.dense.bias
encoder.layer.0.output.dense.weight
encoder.layer.0.output.dense.bias
encoder.layer.0.output.LayerNorm.weight
encoder.layer.0.output.LayerNorm.bias
encoder.layer.1.attention.self.query.weight
encoder.layer.1.attention.self.query.bias
encoder.layer.1.attention.self.key.weight
encoder.layer.1.attention.self.key

In [6]:
text = '浅表器官彩色多普勒超声检查（甲状腺+双侧颈部淋巴结）:右侧甲状腺囊性回声，C-TIRADS 2类。  '
encoded_input = tokenizer(text, return_tensors='pt')
print(encoded_input)
print(encoded_input.keys())
print(encoded_input['input_ids'].shape)

{'input_ids': tensor([[    2,  1276,   380,   710,  1257,   607,   294,    34,   899,  2103,
           247,   584,    72,    52,     1,   361,   107,   283,   894,   526,
           442,   373,   125,   680,   579,   150,     1,     8,   274,   442,
           361,   107,   283,   296,    49,   193,   584,     1,  1026,   246,
         14727,   249,   391,    10,     3]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}
dict_keys(['input_ids', 'token_type_ids', 'attention_mask'])
torch.Size([1, 45])


In [7]:
result = model(**encoded_input)
print(result.last_hidden_state)
print(result.last_hidden_state.shape)  # [1, 45](限制input_ids最大长度为512)

tensor([[[-0.0706, -0.2264,  0.2430,  ...,  0.0048,  0.1487, -0.4339],
         [-0.0776,  0.3773, -0.2424,  ..., -0.0373, -0.1223, -0.1551],
         [-0.3959, -0.0680, -0.1069,  ...,  0.1916,  0.0488, -0.2020],
         ...,
         [ 0.5982,  0.5061, -0.1198,  ..., -0.1833, -0.2860,  0.1238],
         [ 0.3649, -0.0703, -0.1436,  ..., -0.0112,  0.0233, -0.0195],
         [-0.0706, -0.2264,  0.2430,  ...,  0.0048,  0.1487, -0.4339]]],
       grad_fn=<NativeLayerNormBackward0>)
torch.Size([1, 45, 768])


In [8]:
tokenizer_ernie = BertTokenizer.from_pretrained("nghuyong/ernie-3.0-medium-zh")
print(tokenizer_ernie.model_input_names)
print(tokenizer_ernie.all_special_tokens)

Downloading:   0%|          | 0.00/504 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/187k [00:00<?, ?B/s]

['input_ids', 'token_type_ids', 'attention_mask']
['[UNK]', '[SEP]', '[PAD]', '[CLS]', '[MASK]']


In [9]:
'''
nghuyong/ernie-3.0-medium-zh: 6-layer, 768-hidden, 12-heads, 75M parameters. Trained on Chinese text.
nghuyong/ernie-3.0-base-zh: 12-layer, 768-hidden, 12-heads, 118M parameters. Trained on Chinese text.
nghuyong/ernie-3.0-xbase-zh: 20-layer, 1024-hidden, 16-heads, 296M parameters. Trained on Chinese text.
'''
model_ernie = ErnieModel.from_pretrained("nghuyong/ernie-3.0-medium-zh")
model_ernie

Downloading:   0%|          | 0.00/299M [00:00<?, ?B/s]

Some weights of ErnieModel were not initialized from the model checkpoint at nghuyong/ernie-3.0-medium-zh and are newly initialized: ['ernie.pooler.dense.weight', 'ernie.pooler.dense.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


ErnieModel(
  (embeddings): ErnieEmbeddings(
    (word_embeddings): Embedding(40000, 768, padding_idx=0)
    (position_embeddings): Embedding(2048, 768)
    (token_type_embeddings): Embedding(4, 768)
    (task_type_embeddings): Embedding(16, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): ErnieEncoder(
    (layer): ModuleList(
      (0): ErnieLayer(
        (attention): ErnieAttention(
          (self): ErnieSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): ErnieSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        

In [10]:
model_ernie.config

ErnieConfig {
  "_name_or_path": "nghuyong/ernie-3.0-medium-zh",
  "architectures": [
    "ErnieForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 2048,
  "model_type": "ernie",
  "num_attention_heads": 12,
  "num_hidden_layers": 6,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "task_type_vocab_size": 16,
  "transformers_version": "4.23.1",
  "type_vocab_size": 4,
  "use_cache": true,
  "use_task_id": true,
  "vocab_size": 40000
}

In [11]:
for name, para in model_ernie.named_parameters():
    print(name)

embeddings.word_embeddings.weight
embeddings.position_embeddings.weight
embeddings.token_type_embeddings.weight
embeddings.task_type_embeddings.weight
embeddings.LayerNorm.weight
embeddings.LayerNorm.bias
encoder.layer.0.attention.self.query.weight
encoder.layer.0.attention.self.query.bias
encoder.layer.0.attention.self.key.weight
encoder.layer.0.attention.self.key.bias
encoder.layer.0.attention.self.value.weight
encoder.layer.0.attention.self.value.bias
encoder.layer.0.attention.output.dense.weight
encoder.layer.0.attention.output.dense.bias
encoder.layer.0.attention.output.LayerNorm.weight
encoder.layer.0.attention.output.LayerNorm.bias
encoder.layer.0.intermediate.dense.weight
encoder.layer.0.intermediate.dense.bias
encoder.layer.0.output.dense.weight
encoder.layer.0.output.dense.bias
encoder.layer.0.output.LayerNorm.weight
encoder.layer.0.output.LayerNorm.bias
encoder.layer.1.attention.self.query.weight
encoder.layer.1.attention.self.query.bias
encoder.layer.1.attention.self.key.we

In [35]:
text = '当地时间10月30日晚间，巴西总统选举第二轮投票约93%的选票已统计完成。'
encoded_input = tokenizer_ernie(text, return_tensors='pt')
print(encoded_input)
print(encoded_input.keys())
print(encoded_input['input_ids'].shape)  # [1, 682](用多层Transformer XL作为主干网络)

{'input_ids': tensor([[    1,   153,    31,    36,   143,   530,   136,   853,   139,  1010,
           143,     4,   822,   213,   238,   214,   352,   682,   131,   177,
           991,   447,  1039,   450,  2474, 12062,     5,   352,  1039,   265,
           214,   159,   328,    33, 12043,     2]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}
dict_keys(['input_ids', 'token_type_ids', 'attention_mask'])
torch.Size([1, 36])


In [36]:
model_ernie(**encoded_input).last_hidden_state  #  [1, 36, 768](限制input_ids最大长度为2048)

tensor([[[ 0.3654,  0.9508, -0.2878,  ..., -0.3308,  0.2555,  0.8598],
         [-0.5227, -0.2687, -0.4923,  ..., -0.0573, -0.2221,  0.2572],
         [ 0.1727, -0.3163, -0.3881,  ...,  0.2346,  0.8342,  0.1467],
         ...,
         [-1.1135,  0.0524,  0.5207,  ..., -0.0828,  0.1924,  0.2729],
         [ 0.0657,  0.4001, -0.4377,  ..., -0.2372, -0.1854,  0.2532],
         [-0.0119, -0.3709, -0.1830,  ..., -0.1006,  0.3359,  0.0879]]],
       grad_fn=<NativeLayerNormBackward0>)

In [45]:
hs = model_ernie(**encoded_input, output_hidden_states=True).hidden_states
hs

(tensor([[[-0.4660, -0.1470, -0.4473,  ..., -0.2991, -0.0975, -0.2264],
          [-0.6989,  0.1076, -1.0279,  ..., -0.4431,  0.9843,  0.3006],
          [ 1.4230, -1.3373,  0.0693,  ..., -0.0076,  1.0272, -0.0433],
          ...,
          [-2.2252, -1.3034,  0.8699,  ..., -0.5647, -0.0779,  1.1808],
          [ 0.0389,  0.6098, -0.1417,  ..., -0.4288, -0.1857,  0.3887],
          [ 0.6719, -0.1999, -0.0574,  ..., -0.3666, -0.0487,  0.1319]]],
        grad_fn=<NativeLayerNormBackward0>),
 tensor([[[ 0.0563,  0.0101,  0.0556,  ...,  0.0524,  0.1155, -0.0837],
          [-0.4702,  0.1969, -1.4114,  ..., -0.1612,  0.9066, -0.1641],
          [ 1.6446, -1.0025,  0.7328,  ...,  0.1338,  0.9623, -0.7354],
          ...,
          [-2.2860, -0.8681,  0.9259,  ..., -0.6667,  0.3637,  1.0847],
          [ 0.0653,  0.5463, -0.4075,  ..., -0.3563,  0.1787,  0.0078],
          [ 0.5312, -0.6948,  0.1262,  ...,  0.1633,  0.0138, -0.1265]]],
        grad_fn=<NativeLayerNormBackward0>),
 tensor([[[ 

In [47]:
for i in hs:
    print(i.shape)

torch.Size([1, 36, 768])
torch.Size([1, 36, 768])
torch.Size([1, 36, 768])
torch.Size([1, 36, 768])
torch.Size([1, 36, 768])
torch.Size([1, 36, 768])
torch.Size([1, 36, 768])
