In [40]:
import tensorflow as tf

### sigmoid激活函数
### 参考torch.nn.Sigmoid

In [41]:
x = tf.linspace(-5, 5, 200)

In [42]:
# 函数
tf.nn.sigmoid(x)

<tf.Tensor: shape=(200,), dtype=float64, numpy=
array([0.00669285, 0.00703534, 0.00739523, 0.00777338, 0.00817071,
       0.00858818, 0.00902677, 0.00948756, 0.00997163, 0.01048013,
       0.01101428, 0.01157533, 0.01216461, 0.01278351, 0.01343346,
       0.01411598, 0.01483266, 0.01558515, 0.01637519, 0.01720457,
       0.01807518, 0.018989  , 0.01994809, 0.02095457, 0.0220107 ,
       0.02311881, 0.02428131, 0.02550075, 0.02677974, 0.02812103,
       0.02952746, 0.03100199, 0.03254769, 0.03416773, 0.03586542,
       0.03764418, 0.03950753, 0.04145915, 0.04350281, 0.04564241,
       0.04788198, 0.05022565, 0.0526777 , 0.05524249, 0.05792451,
       0.06072839, 0.06365881, 0.06672059, 0.06991865, 0.07325795,
       0.07674359, 0.08038068, 0.08417443, 0.08813008, 0.09225289,
       0.09654816, 0.10102115, 0.10567713, 0.11052132, 0.11555887,
       0.12079485, 0.12623421, 0.13188177, 0.13774216, 0.14381982,
       0.15011896, 0.15664352, 0.16339714, 0.1703831 , 0.17760434,
       0.18506

In [43]:
# 类
layer = tf.keras.layers.Activation(tf.nn.sigmoid, name='sigmoid')  # 可简称为'sigmoid'
output = layer(x)

print(layer.name)
print(output)

sigmoid
tf.Tensor(
[0.00669285 0.00703534 0.00739523 0.00777338 0.00817071 0.00858818
 0.00902677 0.00948756 0.00997163 0.01048013 0.01101428 0.01157533
 0.01216461 0.01278351 0.01343345 0.01411598 0.01483266 0.01558516
 0.01637518 0.01720457 0.01807518 0.018989   0.01994809 0.02095457
 0.0220107  0.02311881 0.02428131 0.02550074 0.02677974 0.02812103
 0.02952746 0.03100199 0.03254768 0.03416773 0.03586543 0.03764418
 0.03950754 0.04145915 0.04350282 0.04564242 0.04788198 0.05022566
 0.0526777  0.05524249 0.05792452 0.06072839 0.06365881 0.06672059
 0.06991865 0.07325795 0.07674358 0.08038067 0.08417442 0.08813007
 0.09225289 0.09654815 0.10102116 0.10567714 0.11052132 0.11555887
 0.12079483 0.12623422 0.13188176 0.13774216 0.14381982 0.15011896
 0.15664351 0.16339713 0.1703831  0.17760433 0.18506338 0.19276223
 0.20070249 0.20888522 0.21731082 0.2259792  0.23488958 0.24404058
 0.25342995 0.26305488 0.27291173 0.2829961  0.29330274 0.3038257
 0.3145582  0.32549253 0.3366203  0.34793228

### 激活函数tanh
### 参考torch.nn.Tanh

In [44]:
x = tf.linspace(-20, 20, 200)

In [45]:
tf.nn.tanh(x)

<tf.Tensor: shape=(200,), dtype=float64, numpy=
array([-1.        , -1.        , -1.        , -1.        , -1.        ,
       -1.        , -1.        , -1.        , -1.        , -1.        ,
       -1.        , -1.        , -1.        , -1.        , -1.        ,
       -1.        , -1.        , -1.        , -1.        , -1.        ,
       -1.        , -1.        , -1.        , -1.        , -1.        ,
       -1.        , -1.        , -1.        , -1.        , -1.        ,
       -1.        , -1.        , -1.        , -1.        , -1.        ,
       -1.        , -1.        , -1.        , -1.        , -1.        ,
       -1.        , -1.        , -1.        , -1.        , -1.        ,
       -1.        , -1.        , -1.        , -1.        , -1.        ,
       -1.        , -0.99999999, -0.99999999, -0.99999998, -0.99999998,
       -0.99999997, -0.99999995, -0.99999992, -0.99999989, -0.99999983,
       -0.99999975, -0.99999962, -0.99999943, -0.99999915, -0.99999873,
       -0.999998

In [46]:
layer = tf.keras.layers.Activation(tf.nn.tanh)  # 可简称为'tanh'
output = layer(x)
output

<tf.Tensor: shape=(200,), dtype=float32, numpy=
array([-1.        , -1.        , -1.        , -1.        , -1.        ,
       -1.        , -1.        , -1.        , -1.        , -1.        ,
       -1.        , -1.        , -1.        , -1.        , -1.        ,
       -1.        , -1.        , -1.        , -1.        , -1.        ,
       -1.        , -1.        , -1.        , -1.        , -1.        ,
       -1.        , -1.        , -1.        , -1.        , -1.        ,
       -1.        , -1.        , -1.        , -1.        , -1.        ,
       -1.        , -1.        , -1.        , -1.        , -1.        ,
       -1.        , -1.        , -1.        , -1.        , -1.        ,
       -1.        , -1.        , -1.        , -1.        , -1.        ,
       -1.        , -1.        , -1.        , -1.        , -1.        ,
       -1.        , -1.        , -1.        , -1.        , -1.        ,
       -1.        , -0.9999997 , -0.9999994 , -0.9999993 , -0.99999887,
       -0.999998

### 激活函数relu
### 参考torch.nn.ReLU

In [47]:
x = tf.linspace(-5, 5, 200)

In [48]:
tf.nn.relu(x)

<tf.Tensor: shape=(200,), dtype=float64, numpy=
array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.     

In [49]:
layer = tf.keras.layers.Activation(tf.nn.relu)  # 可简称为'relu'
output = layer(x)
output

<tf.Tensor: shape=(200,), dtype=float32, numpy=
array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.     

### 激活函数leaky_relu
### 参考torch.nn.LeakyReLU

In [50]:
x = tf.linspace(-5, 5, 200)

In [51]:
tf.nn.leaky_relu(x, alpha=0.1)

<tf.Tensor: shape=(200,), dtype=float64, numpy=
array([-5.00000007e-01, -4.94974882e-01, -4.89949756e-01, -4.84924630e-01,
       -4.79899505e-01, -4.74874379e-01, -4.69849253e-01, -4.64824128e-01,
       -4.59799002e-01, -4.54773876e-01, -4.49748750e-01, -4.44723625e-01,
       -4.39698499e-01, -4.34673373e-01, -4.29648248e-01, -4.24623122e-01,
       -4.19597996e-01, -4.14572870e-01, -4.09547745e-01, -4.04522619e-01,
       -3.99497493e-01, -3.94472368e-01, -3.89447242e-01, -3.84422116e-01,
       -3.79396991e-01, -3.74371865e-01, -3.69346739e-01, -3.64321613e-01,
       -3.59296488e-01, -3.54271362e-01, -3.49246236e-01, -3.44221111e-01,
       -3.39195985e-01, -3.34170859e-01, -3.29145734e-01, -3.24120608e-01,
       -3.19095482e-01, -3.14070356e-01, -3.09045231e-01, -3.04020105e-01,
       -2.98994979e-01, -2.93969854e-01, -2.88944728e-01, -2.83919602e-01,
       -2.78894477e-01, -2.73869351e-01, -2.68844225e-01, -2.63819099e-01,
       -2.58793974e-01, -2.53768848e-01, -2.48743722

In [52]:
# 自定义leaky_relu激活函数层
class MyLeakyRelu():
    pass