## 相关系数(线性关系)

<font color='red' size='4'>定义:</font>    
随机变量$ X $ 和$ Y$ 的相关系数定义为:
$$ \rho_{XY} = \frac{Cov(X,Y)}{\sigma_X \sigma_Y} $$

<font color='red' size='4'>性质:</font>  
设$ X $ 和 $ Y $ 是任意随机变量,
1. $ -1 \leq \rho_{XY} \leq 1  $
2. $ |\rho_{XY}| =1 $当且仅当存在数$ a \neq 0 $ 以及 $ b $ 使得 $ P(Y = aX +b)=1 $.
若$ \rho_{XY}=1 $,则$ a>0 $, 若$ \rho_{XY}=-1 $,则$ a<0 $

## 相关阵
&emsp;&emsp;若$X=(X_{1},X_{2},...,X_{1})$的协差阵存在,且每个分量的方差大于零<br/>
则称随机向量$X$的相关阵为$R=(r_{ij})_{p \times p}$,其中，<br/>
$$ r_{ji}=\frac{ Cov(X_{i}, X_{j}) } {\sqrt{Var(X_{i})} \sqrt{Var(X_{j})}} \quad j,i=1,...p$$  
为相关系数

In [27]:
import numpy as np
# np.corrcoef(x, y)--> x : array_like, y : array_like, optional

In [28]:
a = [-2.1, -1, 4.3, 3, 5]
b = [3, 1.1, 0.12, 5, 32]
c = np.array([a, b])
print(c, end='\n\n')
print(np.corrcoef(a, b), end='\n\n')
'''
rowvar : bool, optional
    If `rowvar` is True (default), then each row represents a
    variable, with observations in the columns. Otherwise, the relationship
    is transposed: each column represents a variable, while the rows
    contain observations.
'''
# 每行表示一个变量
print(np.corrcoef(c, rowvar=True))  # 与上等价

[[-2.1  -1.    4.3   3.    5.  ]
 [ 3.    1.1   0.12  5.   32.  ]]

[[1.         0.53744663]
 [0.53744663 1.        ]]

[[1.         0.53744663]
 [0.53744663 1.        ]]


In [29]:
# 每列表示一个变量
np.corrcoef(c.transpose(), rowvar=False)


array([[1.        , 0.53744663],
       [0.53744663, 1.        ]])