In [174]:
import tensorflow as tf

### 参考numpy网格索引

In [ ]:
indices = [[0, 0],
           [1, 1]]
tor = tf.constant([['a', 'b'],
                   ['c', 'd']])

print(tf.stack([tor[0, 1], tor[1, 1], tor[0, 1]]))

# 选取索引为(0, 0),(1, 1),(0, 1)处的元素值
print(tf.gather_nd(tor, [[0, 0], [1, 1], [0, 1]]))  # 与上等价

In [176]:
tor = tf.reshape(tf.range(24), (2, 3, 4))
tor

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])>

In [177]:
print(tf.stack([tor[0, 0, 1], tor[1, 2, 1], tor[1, 2, 3]]))
# 选取索引为(0, 0, 1),(1, 2, 1),(1, 2, 3)处的元素值
print(tf.gather_nd(tor, [[0, 0, 1], [1, 2, 1], [1, 2, 3]]))  # 与上等价

tf.Tensor([ 1 21 23], shape=(3,), dtype=int32)
tf.Tensor([ 1 21 23], shape=(3,), dtype=int32)
