In [1]:
import tensorflow as tf

In [2]:
a = tf.ones((2, 3, 4))
a

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>

### 参考torch.nn.Dropout1d

In [3]:
# This version performs the same function as Dropout, however, it drops entire 1D feature maps instead of individual elements.
layder1d = tf.keras.layers.SpatialDropout1D(rate=0.2)
# 对中间1个特征维度整体进行dropout
layder1d(inputs=a,  # 3D张量
         training=True)  # 是否为训练模式(eval模式下不执行Dropout操作)

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[0.  , 1.25, 1.25, 1.25],
        [0.  , 1.25, 1.25, 1.25],
        [0.  , 1.25, 1.25, 1.25]],

       [[1.25, 1.25, 1.25, 1.25],
        [1.25, 1.25, 1.25, 1.25],
        [1.25, 1.25, 1.25, 1.25]]], dtype=float32)>

In [4]:
b = tf.ones((2, 3, 4, 5))
b

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]], dtype=float32)>

### 参考torch.nn.Dropout1d

In [5]:
# This version performs the same function as Dropout, however, it drops entire 2D feature maps instead of individual elements.
layder2d = tf.keras.layers.SpatialDropout2D(rate=0.5)
# 对中间2个特征维度整体进行dropout
layder2d(inputs=b,  # 4D张量
         training=True)  # 是否为训练模式(eval模式下不执行Dropout操作)

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 2., 2., 0., 0.],
         [0., 2., 2., 0., 0.],
         [0., 2., 2., 0., 0.],
         [0., 2., 2., 0., 0.]],

        [[0., 2., 2., 0., 0.],
         [0., 2., 2., 0., 0.],
         [0., 2., 2., 0., 0.],
         [0., 2., 2., 0., 0.]],

        [[0., 2., 2., 0., 0.],
         [0., 2., 2., 0., 0.],
         [0., 2., 2., 0., 0.],
         [0., 2., 2., 0., 0.]]],


       [[[2., 0., 2., 2., 2.],
         [2., 0., 2., 2., 2.],
         [2., 0., 2., 2., 2.],
         [2., 0., 2., 2., 2.]],

        [[2., 0., 2., 2., 2.],
         [2., 0., 2., 2., 2.],
         [2., 0., 2., 2., 2.],
         [2., 0., 2., 2., 2.]],

        [[2., 0., 2., 2., 2.],
         [2., 0., 2., 2., 2.],
         [2., 0., 2., 2., 2.],
         [2., 0., 2., 2., 2.]]]], dtype=float32)>