In [42]:
import numpy as np

In [43]:
arr = np.arange(80).reshape(16, 5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79]])

In [44]:
cond0 = arr[:, 0] >= 15
cond1 = arr[:, 0] <= 65
cond2 = arr[:, 1] <= 66
cond3 = arr[:, 1] >= 11

print(cond0)
print(cond1)
print(cond2)
print(cond3)

[False False False  True  True  True  True  True  True  True  True  True
  True  True  True  True]
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True False False]
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True False False]
[False False  True  True  True  True  True  True  True  True  True  True
  True  True  True  True]


### 计算cond0 and cond1 and cond2 and cond3

In [45]:
whole = np.stack([cond0, cond1, cond2, cond3], axis=1)
whole

array([[False,  True,  True, False],
       [False,  True,  True, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True, False, False,  True],
       [ True, False, False,  True]])

In [46]:
np.all(whole, axis=1)

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False, False])

### 计算(cond0 and cond1) or (cond2 and -cond3)

In [47]:
font = np.all(np.stack([cond0, cond1], axis=1), axis=1)
font

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False, False])

In [48]:
after = np.all(np.stack([cond2, np.logical_not(cond3)], axis=1), axis=1)
after

array([ True,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [49]:
# 只有两组数据进行逻辑运算时,推荐使用logical_and/logical_or
result = np.logical_or(font, after)
result

array([ True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False, False])