In [101]:
import numpy as np
from sklearn.preprocessing import OrdinalEncoder

In [102]:
enc = OrdinalEncoder(categories='auto')  # 默认categories='auto'
X = np.array([['Male', '1'],
              ['Female', '3'],
              ['Female', '2']])
X

array([['Male', '1'],
       ['Female', '3'],
       ['Female', '2']], dtype='<U6')

In [103]:
'''
X : array-like, shape [n_samples, n_features]
            The data to determine the categories of each feature.
'''
enc.fit(X)  # X必须为2D数据(n_samples, n_features)

OrdinalEncoder()

In [104]:
# The categories of each feature determined during fitting (in order of the features in X and corresponding with the output of transform).
enc.categories_

[array(['Female', 'Male'], dtype='<U6'), array(['1', '2', '3'], dtype='<U6')]

In [105]:
# Transform X to ordinal codes.
"""
解析:
根据enc.categories_
'Female'的编码是0
'Male'的编码是1
'3'的编码是2
'1'的编码是0
"""
enc.transform([['Female', '3'],
               ['Male', '1']])

array([[0., 2.],
       [1., 0.]])

In [106]:
enc.transform(X)

array([[1., 0.],
       [0., 2.],
       [0., 1.]])

In [107]:
# Convert the data back to the original representation.
"""
解析:
根据enc.categories_
第一个特征编码1的原始表示是'Male'
第一个特征编码0的原始表示是'Female'
第二个特征编码0的原始表示是'1'
第二个特征编码1的原始表示是'2'
"""
enc.inverse_transform([[1, 0],
                       [0, 1]])  # 必须为2D数据(n_samples, n_features)

array([['Male', '1'],
       ['Female', '2']], dtype=object)

In [108]:
enc.inverse_transform(enc.transform(X))

array([['Male', '1'],
       ['Female', '3'],
       ['Female', '2']], dtype=object)

In [109]:
seq_init = np.array([['红', '恒星'],
                     ['白', '卫星'],
                     ['红', '行星'],
                     ['黑', '卫星']])

# ★★★★★指定categories
enc1 = OrdinalEncoder(categories=[['红', '黑', '白'],
                                  ['卫星', '恒星', '行星']])

In [110]:
seq = enc1.fit_transform(seq_init)
seq

array([[0., 1.],
       [2., 0.],
       [0., 2.],
       [1., 0.]])

In [111]:
enc1.categories_

[array(['红', '黑', '白'], dtype='<U2'), array(['卫星', '恒星', '行星'], dtype='<U2')]