In [322]:
import tensorflow as tf

In [323]:
# 常量的值不能被修改
c = tf.constant([1.0, 2.0])
print(c)
print(id(c))

# 常量没有assign/assign_add/assign_sub等方法
# c[0].assign(100)

c += tf.constant([1.0, 1.0])
print(c)
print(id(c))  # c指向新的内存地址

tf.Tensor([1. 2.], shape=(2,), dtype=float32)
2616653218560
tf.Tensor([2. 3.], shape=(2,), dtype=float32)
2616653121840


In [324]:
# 变量的值可以被修改
v = tf.Variable(tf.reshape(tf.range(15), (3, 5)))

print(id(v))
print(v.numpy())

2616653890800
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [325]:
v.assign_add(tf.ones_like(v))
v.assign_sub(tf.ones_like(v))

print(id(v))  # v指向的地址不变
print(v.numpy())

2616653890800
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [326]:
# 仅支持通过基本索引的方式修改变量的值
v[0:2, 3:].assign(tf.constant([[-11, -22],
                               [-33, -44]]))
v[0, 0].assign(100)

print(id(v))  # v指向的地址不变
print(v.numpy())

2616653890800
[[100   1   2 -11 -22]
 [  5   6   7 -33 -44]
 [ 10  11  12  13  14]]


In [327]:
v.assign(tf.zeros_like(v))

print(id(v))  # v指向的地址不变
print(v.numpy())

2616653890800
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [328]:
v = v + tf.fill((3, 5), -999)
print(id(v))  # 指向新的内存地址
print(v.numpy())

2616653194336
[[-999 -999 -999 -999 -999]
 [-999 -999 -999 -999 -999]
 [-999 -999 -999 -999 -999]]
