In [1]:
import tensorflow as tf
import numpy as np

### 常量;参考numpy.array

In [2]:
# Creates a constant tensor from a tensor-like object
# All tensors are immutable like Python numbers and strings: you can never update the contents of a tensor, only create a new one.
x = tf.constant(3.0)  # 标量
x

<tf.Tensor: shape=(), dtype=float32, numpy=3.0>

In [3]:
x = tf.constant([5.5, 3])  # 向量
x

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([5.5, 3. ], dtype=float32)>

In [4]:
x = tf.constant(range(10))
x

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [5]:
a = np.array([[1.2, 2, 3],
              [2, 3, 4]])
x = tf.constant(a)  # 从numpy创建(矩阵)
x

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[1.2, 2. , 3. ],
       [2. , 3. , 4. ]])>

In [6]:
x = tf.constant(['1', '2'])  # 支持string数据类型
x

<tf.Tensor: shape=(2,), dtype=string, numpy=array([b'1', b'2'], dtype=object)>

In [7]:
x = tf.constant([1, 2, 3, 4, 5],
                dtype=tf.float32)  # 指定数据类型
x.dtype

tf.float32

In [10]:
x = tf.constant([1, 2, 3, 4, 5],
                shape=(5, 1))  # Optional dimensions of resulting tensor.

<tf.Tensor: shape=(5, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3],
       [4],
       [5]])>