In [10]:
import torch

### 参考类似numpy/基本操作/数组乘积/数据类型之间的转换

In [ ]:
tor_scalar_vetor = torch.tensor(10).reshape(1)  # 标量转向量(法一)
tor_scalar_vetor.shape

In [12]:
tor_scalar_vetor1 = torch.tensor(10).unsqueeze(0)  # 标量转向量(法二)
tor_scalar_vetor1

tensor([10])

In [13]:
tor_scalar_matrix = torch.tensor(10).reshape(1, 1)  # 标量转矩阵(法一)
tor_scalar_matrix.shape

torch.Size([1, 1])

In [14]:
tor_scalar_matrix1 = torch.tensor(10).unsqueeze(0).unsqueeze(0)  # 标量转矩阵(法二)
print(tor_scalar_matrix.shape)  # (0维度尺寸=1, 1维度尺寸=1)
print(tor_scalar_matrix)

torch.Size([1, 1])
tensor([[10]])


In [15]:
tor_vector_matrix = torch.tensor([1, 2, 3]).reshape(1, 3)  # 向量转矩阵(法一)
print(tor_vector_matrix.shape)  # (0维度尺寸=1, 1维度尺寸=3)
print(tor_vector_matrix)

torch.Size([1, 3])
tensor([[1, 2, 3]])


In [16]:
tor_vector_matrix1 = torch.tensor([1, 2, 3]).unsqueeze(0)  # 向量转矩阵(法二)
print(tor_vector_matrix1.shape)  # (0维度尺寸=1, 1维度尺寸=3)--->数学中的行向量
print(tor_vector_matrix1)

torch.Size([1, 3])
tensor([[1, 2, 3]])


In [17]:
tor_vector_mul_matrix = torch.tensor([1, 2, 3]).reshape(1, 1, 3, 1, 1)  # 高维矩阵
tor_vector_mul_matrix

tensor([[[[[1]],

          [[2]],

          [[3]]]]])

In [18]:
tor_vector_mul_matrix = torch.tensor([1, 2, 3]).unsqueeze(0).unsqueeze(0).unsqueeze(-1).unsqueeze(-1)  # 高维矩阵
tor_vector_mul_matrix

tensor([[[[[1]],

          [[2]],

          [[3]]]]])