In [ ]:
import torch

### 类似numpy/基本操作/数组乘积/数据类型之间的乘积

#### 标量 $ \times $ 标量

In [1]:
scalar1 = torch.tensor(3)
scalar2 = torch.tensor(4)

scalar1 * scalar2

tensor(12)

#### 标量 $ \times $ 向量

In [2]:
vector1 = torch.tensor([1, 2, 3, 4])
print(scalar1 * vector1)  # 等价于3 * vector1(广播)

tensor([ 3,  6,  9, 12])


#### 标量 $ \times $ 矩阵

In [3]:
martrix1 = torch.tensor([[1, 2, 3, 4],
                         [2, 3, 4, 5]])
print(scalar1 * martrix1)  # 等价于 3 * martrix1(广播机制)

tensor([[ 3,  6,  9, 12],
        [ 6,  9, 12, 15]])


#### 向量 $ \times @ $ 向量

In [4]:
vector1 = torch.tensor([1, 2, 3, 4])
vector2 = torch.tensor([2, 3, 4, 5])
vector1 * vector2  # 对应元素相乘

tensor([ 2,  6, 12, 20])

In [5]:
vector1 @ vector2  # ★★★★★向量的(典范)内积(点积,数量积)

tensor(40)

In [6]:
torch.matmul(vector1, vector2)  # 于上等价

tensor(40)

In [7]:
vector1.reshape(4, 1) @ vector2.reshape(1, 4)  # [4, 1] @ [1, 4] --> [4, 4](矩阵代数)

tensor([[ 2,  3,  4,  5],
        [ 4,  6,  8, 10],
        [ 6,  9, 12, 15],
        [ 8, 12, 16, 20]])

#### 向量 $ \times @ $ 矩阵

In [8]:
martrix1 = torch.tensor([[1, 2, 3, 4],
                         [2, 3, 4, 5]])
print(vector1 * martrix1)  # 广播机制[2, 4] broadcasting [4] --> [2, 4]
print(martrix1 * vector1)  # 可交换顺序

tensor([[ 1,  4,  9, 16],
        [ 2,  6, 12, 20]])
tensor([[ 1,  4,  9, 16],
        [ 2,  6, 12, 20]])


In [9]:
torch.tensor([1, 2]) @ martrix1  # [2] @ [2, 4] --> [4]

tensor([ 5,  8, 11, 14])

In [10]:
martrix1 @ vector1  # [2, 4] @ [4] --> [2]

tensor([30, 40])

In [11]:
torch.matmul(martrix1, vector1)  # 与上等价

tensor([30, 40])

In [12]:
martrix1 @ vector1.reshape(4, 1)  # [2, 4] @ [4, 1] --> [2, 1](矩阵代数)

tensor([[30],
        [40]])

#### 矩阵 $ \times @ $ 矩阵

In [13]:
martrix1 = torch.tensor([[1, 2, 3, 4], [2, 3, 4, 5]])
martrix2 = torch.tensor([[0, 0, 0, 0], [1, 1, 1, 1]])

martrix1 * martrix2  # 对应元素相乘

tensor([[0, 0, 0, 0],
        [2, 3, 4, 5]])

In [14]:
martrix1 @ martrix2.reshape(4, 2)  # 必须满足矩阵代数运算法则

tensor([[7, 7],
        [9, 9]])

In [15]:
torch.matmul(martrix1, martrix2.reshape(4, 2))  # 与上等价

tensor([[7, 7],
        [9, 9]])

#### 高维矩阵 @ 高维矩阵

In [16]:
a = torch.randn(4, 3, 5, 28, 64)
b = torch.randn(4, 3, 5, 64, 32)

In [17]:
out = a @ b
# [4, 3, 5, 28, 64] @ [4, 3, 5, 64, 32] -->
# 1. [4, 3, 5] 不变
# 2. [28, 64] @ [64, 32] --> [28, 64]
# 3. [4, 3, 5, 28, 64]
out.shape

torch.Size([4, 3, 5, 28, 32])

In [18]:
torch.matmul(a, b).shape  # 与上等价

torch.Size([4, 3, 5, 28, 32])

In [19]:
c = torch.randn(4, 1, 5, 64, 32)
# [4, 3, 5, 28, 64] @ [4, 1, 5, 64, 32] -->
# 1. [4, 3, 5] broadcasting [4, 1, 5] --> [4, 3, 5]
# 2. [28, 64] @ [64, 32] --> [28, 64]
# 3. [4, 3, 5, 28, 64]
out1 = a @ c
out1.shape

torch.Size([4, 3, 5, 28, 32])

In [20]:
torch.matmul(a, c).shape  # 与上等价

torch.Size([4, 3, 5, 28, 32])

In [21]:
a1 = torch.randn(4, 1, 5, 28, 64)
b1 = torch.randn(1, 3, 1, 64, 32)
# [4, 1, 5, 28, 64] @ [1, 3, 1, 64, 32] -->
# 1. [4, 1, 5] broadcasting [1, 3, 1] --> [4, 3, 5]
# 2. [28, 64] @ [64, 32] --> [28, 64]
# 3. [4, 3, 5, 28, 64]
out2 = a1 @ b1
out2.shape

torch.Size([4, 3, 5, 28, 32])

In [22]:
torch.matmul(a1, b1).shape  # 与上等价

torch.Size([4, 3, 5, 28, 32])