## 标量/scalar 

In [9]:
import torch

# 完全类似numpy/基本操作数组乘积/数据类型

arr_scalar = torch.tensor(10)  # 标量
print(arr_scalar.ndim)
print(arr_scalar.shape)
print(arr_scalar)

0
torch.Size([])
tensor(10)


## 向量/vector

In [10]:
arr_vector = torch.tensor([1, 2, 3])  # 向量
print(arr_vector.ndim)
print(arr_vector.shape)
print(arr_vector)

1
torch.Size([3])
tensor([1, 2, 3])


## 矩阵/matrix

In [11]:
arr_matrix = torch.tensor([[1, 2, 3], [2, 3, 4]])  # 矩阵
print(arr_matrix.ndim)
print(arr_matrix.shape)
print(arr_matrix)

2
torch.Size([2, 3])
tensor([[1, 2, 3],
        [2, 3, 4]])


### 高维矩阵(ndim>2)

In [12]:
arr_mul_matrix = torch.randn(3, 4, 5)
print(arr_mul_matrix.ndim)
print(arr_mul_matrix.shape)
print(arr_mul_matrix)



3
torch.Size([3, 4, 5])
tensor([[[-0.7762, -0.8524,  0.0841,  0.2402, -0.3819],
         [ 0.4864,  1.6128, -1.3826,  0.0183, -0.9304],
         [-0.9453,  2.0714,  0.5046,  1.4416, -0.6375],
         [ 0.7436, -1.8313, -0.5903, -1.3725,  1.6950]],

        [[-0.8349,  1.2621, -3.1066,  2.0604, -2.5900],
         [ 0.9290,  0.2435, -1.6807, -0.6031,  1.6954],
         [ 1.7398,  0.3766, -0.2210,  0.6239,  0.0878],
         [-0.0439, -1.4329,  0.1314,  2.0392, -0.5045]],

        [[ 0.5777,  1.2851,  0.6542,  0.9174,  0.0164],
         [ 0.8190, -0.3740,  0.6279, -0.6253, -0.4029],
         [ 1.0932, -0.0996, -0.1374,  0.0280, -0.9413],
         [ 2.4625,  0.5879, -0.8928, -0.2727,  0.7472]]])
