In [1]:
import torch

### 参考类似numpy/基本操作数组乘积/数据类型

## 标量/scalar

In [2]:
arr_scalar = torch.tensor(10)  # 标量
print(arr_scalar.ndim)
print(arr_scalar.shape)
print(arr_scalar)

0
torch.Size([])
tensor(10)


#### 向量/vector

In [3]:
arr_vector = torch.tensor([1, 2, 3])  # 向量
print(arr_vector.ndim)
print(arr_vector.shape)
print(arr_vector)

1
torch.Size([3])
tensor([1, 2, 3])


#### 矩阵/matrix

In [4]:
arr_matrix = torch.tensor([[1, 2, 3], [2, 3, 4]])  # 矩阵
print(arr_matrix.ndim)
print(arr_matrix.shape)
print(arr_matrix)

2
torch.Size([2, 3])
tensor([[1, 2, 3],
        [2, 3, 4]])


#### 高维矩阵(ndim>2)

In [5]:
arr_mul_matrix = torch.randn(3, 4, 5)
print(arr_mul_matrix.ndim)
print(arr_mul_matrix.shape)
print(arr_mul_matrix)



3
torch.Size([3, 4, 5])
tensor([[[-1.0916, -0.5561,  0.2494, -1.1408, -0.8258],
         [ 0.9154, -0.2549,  1.2740, -0.8957, -0.4720],
         [ 0.9578,  0.2272,  0.5415,  1.2997,  1.3651],
         [-1.9962,  0.0868, -0.7106,  0.4563, -0.6775]],

        [[ 0.1428,  0.0897, -0.1142, -0.0813, -0.1430],
         [ 0.4661,  0.3535, -1.2587, -0.5259, -0.7321],
         [ 0.4372, -0.5701, -2.0482, -0.3695, -0.5245],
         [ 0.1010, -1.7244,  1.4015,  0.5585, -0.3637]],

        [[-0.2122, -0.5917, -0.2613,  0.3528,  0.2051],
         [ 0.7551, -0.5585, -0.9677,  0.1078, -0.9382],
         [ 0.3475, -1.3767, -0.3611, -0.8340, -1.0467],
         [ 0.6602,  0.7307,  0.2447,  0.4940, -1.3034]]])
