Applies a linear transformation to the incoming data:$$ \mathbf{y} = \mathbf{x} A^T + b  $$

In [8]:
import torch
import torch.nn.functional as F
import torch.nn as nn

In [9]:
enter = torch.tensor([[1, 2, 3, 4, 5, 6],
                      [2, 3, 4, 5, 6, 7]], dtype=torch.float32)
weight = torch.arange(18, dtype=torch.float32).reshape(3, 6)
bias = torch.tensor([1, 2, 1], dtype=torch.float32)

# 函数
linear_f = F.linear(input=enter, weight=weight, bias=bias)
linear_f

tensor([[ 71., 198., 323.],
        [ 86., 249., 410.]])

In [10]:
# 上式计算步骤如下
enter @ weight.T + bias  # (2, 6) x (3, 6)^T + (3)

tensor([[ 71., 198., 323.],
        [ 86., 249., 410.]])

In [11]:
# 类
linear_c = nn.Linear(in_features=6,  # 输入特征的维度
                     out_features=1,  # 输出特征的维度
                     bias=True)  # 是否引入偏置参数;默认bias=True
linear_c(enter)

tensor([[-0.1784],
        [ 0.0159]], grad_fn=<AddmmBackward>)

In [12]:
linear_c.weight  # 内部默认进行了初始化:init.kaiming_uniform_(self.weight, a=math.sqrt(5))

Parameter containing:
tensor([[ 0.1815,  0.2067,  0.0038,  0.0280, -0.1818, -0.0439]],
       requires_grad=True)

In [13]:
linear_c.bias  # 内部默认进行了kaiming_uniform_初始化

Parameter containing:
tensor([0.2760], requires_grad=True)

In [14]:
list(linear_c.parameters())


[Parameter containing:
 tensor([[ 0.1815,  0.2067,  0.0038,  0.0280, -0.1818, -0.0439]],
        requires_grad=True),
 Parameter containing:
 tensor([0.2760], requires_grad=True)]