In [8]:
import torch
import torch.nn as nn

In [9]:
embedding = nn.Embedding(num_embeddings=10,  # 单词表的单词数目
                         embedding_dim=4,  # 输出词向量的维度大小
                         # 默认为False;这个参数的作用是为了加快非常用单词的优化,
                         # 在深度学习模型中,当反向传播获取词向量的梯度以后,如果设置这个参数为True,
                         # 则词向量的梯度会除以这个单词在mini-batch中出现的频率,通过这个缩放操作,
                         # 可以让出现频率较少的单词的梯度比较大,这样可以加快低频词的词向量参数的收敛速度
                         scale_grad_by_freq=True,
                         # 如果这个参数设置为True,则词嵌入矩阵在反向传播中计算得到的矩阵为稀疏矩阵
                         # 这个参数在单词表中单词数目巨大的时候非常有用.
                         # 如果使用稀疏的梯度矩阵,则必须使用稀疏的优化器,如optim.SGD,optim.SparseAdam,optim.AdaGrad
                         sparse=True)  # 默认为False

In [10]:
embedding.weight  # 内部实现了随机初始化

Parameter containing:
tensor([[-0.7507, -1.2996,  0.0727, -0.8509],
        [ 1.3612,  0.0336, -0.4337, -2.2011],
        [ 0.3720,  0.0972,  0.7673, -0.6834],
        [ 1.1067, -0.8155, -0.1443,  0.1406],
        [-2.8583, -2.3611, -0.3777,  0.6712],
        [ 0.7871, -0.2065,  1.0416, -1.0439],
        [ 0.2762,  0.8055, -0.5563,  0.7541],
        [ 0.0955, -0.5150,  0.1556,  1.7652],
        [-0.9722,  0.7946,  0.9326,  0.7953],
        [ 1.7072, -1.1975,  0.7121, -0.2391]], requires_grad=True)

In [11]:
pre_em = torch.arange(40, dtype=torch.float32).reshape(10, 4)
embedding_pre = nn.Embedding.from_pretrained(pre_em, sparse=True,
                                             scale_grad_by_freq=True)  # 从预训练的词嵌入矩阵得到词嵌入模块(类方法,参数含义与上相同)
embedding_pre.weight

Parameter containing:
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.],
        [20., 21., 22., 23.],
        [24., 25., 26., 27.],
        [28., 29., 30., 31.],
        [32., 33., 34., 35.],
        [36., 37., 38., 39.]])

In [12]:
entry = torch.tensor([[0, 1, 2],
                      [5, 6, 7]], dtype=torch.long)

In [13]:
print(embedding_pre(entry))  # 通过取出对应元素索引序号的行,来获取某个元素对应的词向量
print(embedding_pre(entry).shape)  # (2, 3) <--> (10, 4) --> (2, 3, 4)

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]],

        [[20., 21., 22., 23.],
         [24., 25., 26., 27.],
         [28., 29., 30., 31.]]])
torch.Size([2, 3, 4])


In [14]:
entry1 = torch.tensor([1, 2])
print(embedding_pre(entry1))
print(embedding_pre(entry1).shape)  # (2) <-->(10, 4) --> (2, 4)

tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
torch.Size([2, 4])
