In [1]:
import torch
import copy

### 参考numpy.broadcast_to

In [ ]:
x = torch.arange(3).view(1, 3)
y = torch.arange(2).view(2, 1)
a, b = torch.broadcast_tensors(x, y)  # x,y相互之间进行广播(必须确保x,y相互之间可进行广播)

In [2]:
a  # x,y相互之间进行广播后x的形式

tensor([[0, 1, 2],
        [0, 1, 2]])

In [3]:
b  # x,y相互之间进行广播后y的形式

tensor([[0, 0, 0],
        [1, 1, 1]])

In [4]:
a[0][0] = 999
a

tensor([[999,   1,   2],
        [999,   1,   2]])

In [5]:
x  # ★★★★★x也发生改变(If you need to write to the tensors, please clone them first.)

tensor([[999,   1,   2]])

In [6]:
a1, b1 = torch.broadcast_tensors(copy.deepcopy(x), copy.deepcopy(y))
a1[0][0] = 111111
a1

tensor([[111111,      1,      2],
        [111111,      1,      2]])

In [7]:
x  # x不再发生改变

tensor([[999,   1,   2]])

In [8]:
m = torch.ones([1, 12, 8, 1, 4, 1])
n = torch.zeros([5, 4, 1, 1, 3, 1, 4])
M, N = torch.broadcast_tensors(copy.deepcopy(m), copy.deepcopy(n))
print(M.shape)
print(N.shape)  # 广播后M,N shape完全一致

torch.Size([5, 4, 12, 8, 3, 4, 4])
torch.Size([5, 4, 12, 8, 3, 4, 4])
