In [9]:
import torch

### 参考numpy.broadcast_to

In [10]:
x1 = torch.tensor([1, 2, 3]).reshape(-1, 1)
x1

tensor([[1],
        [2],
        [3]])

In [11]:
# Broadcasts input to the shape shape. Equivalent to calling input.expand(shape).
torch.broadcast_to(x1, (3, 3))

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])

In [12]:
x1 = torch.tensor([1, 2, 3]).reshape(1, -1)
x1

tensor([[1, 2, 3]])

In [13]:
torch.broadcast_to(x1, (3, 3))

tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])

In [14]:
torch.broadcast_to(x1, (5, 4, 3))  # 和广播机制规则一致

tensor([[[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]]])

In [15]:
x1  # x不变

tensor([[1, 2, 3]])