In [12]:
import torch

In [ ]:
x = torch.randn(2, 3)
y = x.transpose(0, 1) 

In [ ]:
# Returns True if :attr:`self` tensor is contiguous in memory in the order specified by memory format.
y.is_contiguous()

False

In [15]:
y.reshape(-1)

tensor([-1.7257,  0.4056, -0.2833,  0.0187, -1.5614,  0.9589])

In [ ]:
# eturns a new tensor with the same data as the self tensor but of a different shape.
y.view(-1)

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [ ]:
# Returns a contiguous in memory tensor containing the same data as :attr:`self` tensor.
y_contiguous = y.contiguous()
y_contiguous.is_contiguous()

True

In [18]:
y_contiguous.reshape(-1)

tensor([-1.7257,  0.4056, -0.2833,  0.0187, -1.5614,  0.9589])

In [19]:
y_contiguous.view(-1)

tensor([-1.7257,  0.4056, -0.2833,  0.0187, -1.5614,  0.9589])