In [7]:
import torch

x = torch.tensor([[[0, 1, 3], [2, 3, 4]],
                  [[5, 6, 7], [8, 9, 10]]])
x

tensor([[[ 0,  1,  3],
         [ 2,  3,  4]],

        [[ 5,  6,  7],
         [ 8,  9, 10]]])

In [8]:
x.shape

torch.Size([2, 2, 3])

### 参考numpy.swapaxes

In [ ]:
trans = torch.transpose(x, 0, -1)  # 交换第0个维度和最后一个维度信息(两两交换)
trans

In [10]:
trans.shape

torch.Size([3, 2, 2])

In [11]:
x  # x不变

tensor([[[ 0,  1,  3],
         [ 2,  3,  4]],

        [[ 5,  6,  7],
         [ 8,  9, 10]]])

In [12]:
torch.transpose(x, 0, 2)

tensor([[[ 0,  5],
         [ 2,  8]],

        [[ 1,  6],
         [ 3,  9]],

        [[ 3,  7],
         [ 4, 10]]])