In [21]:
import  torch

x = torch.tensor([[[0, 1], [2, 3]],
              [[4, 5], [6, 7]]])
x

tensor([[[0, 1],
         [2, 3]],

        [[4, 5],
         [6, 7]]])

In [22]:
# 完全类似于numpy.swapaxes
x.transpose(0, 1) # 交换第0个维度和第一个维度信息(两两交换)

tensor([[[0, 1],
         [4, 5]],

        [[2, 3],
         [6, 7]]])

In [23]:
x # x不变

tensor([[[0, 1],
         [2, 3]],

        [[4, 5],
         [6, 7]]])

In [24]:
x.transpose(0, 2)

tensor([[[0, 4],
         [2, 6]],

        [[1, 5],
         [3, 7]]])