In [31]:
import torch

x = torch.tensor([[[0, 1, 3], [2, 3, 4]],
                  [[5, 6, 7], [8, 9, 10]]])
x

tensor([[[ 0,  1,  3],
         [ 2,  3,  4]],

        [[ 5,  6,  7],
         [ 8,  9, 10]]])

In [32]:
x.shape

torch.Size([2, 2, 3])

In [33]:
# 完全类似于numpy.swapaxes
trans = x.transpose(0, -1)  # 交换第0个维度和最后一个维度信息(两两交换)
trans

tensor([[[ 0,  5],
         [ 2,  8]],

        [[ 1,  6],
         [ 3,  9]],

        [[ 3,  7],
         [ 4, 10]]])

In [34]:
trans.shape

torch.Size([3, 2, 2])

In [35]:
x  # x不变

tensor([[[ 0,  1,  3],
         [ 2,  3,  4]],

        [[ 5,  6,  7],
         [ 8,  9, 10]]])

In [36]:
x.transpose(0, 2)

tensor([[[ 0,  5],
         [ 2,  8]],

        [[ 1,  6],
         [ 3,  9]],

        [[ 3,  7],
         [ 4, 10]]])