In [98]:
import torch

### 参考numpy.tile

In [99]:
x = torch.tensor([1, 2, 3])
x

tensor([1, 2, 3])

In [100]:
torch.unsqueeze(x, 0).repeat(4, 2)

tensor([[1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3]])

In [101]:
x.repeat(4, 2)  # 与上等价

tensor([[1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3]])

In [102]:
y = torch.tensor([[1, 2],
                  [3, 4]])
y

tensor([[1, 2],
        [3, 4]])

In [103]:
y.repeat(2, 1)  # 维度0上重复2次(整体重复),维度1上重复1次(即不进行重复)

tensor([[1, 2],
        [3, 4],
        [1, 2],
        [3, 4]])

In [104]:
y.repeat(4, 2)

tensor([[1, 2, 1, 2],
        [3, 4, 3, 4],
        [1, 2, 1, 2],
        [3, 4, 3, 4],
        [1, 2, 1, 2],
        [3, 4, 3, 4],
        [1, 2, 1, 2],
        [3, 4, 3, 4]])

In [105]:
# 解析:
# y.shape=[2, 2]

# y.repeat(1, 2).shape=[2, 4]

# =>torch.unsqueeze(y, 0).repeat(1, 2, 1)
# y.repeat(1, 2, 1).shape=[1, 4, 2]  # 与上等价

# =>torch.unsqueeze(torch.unsqueeze(y, 0), 0).repeat(1, 2, 1, 1)
# y.repeat(1, 2, 1, 1).shape=[1, 2, 2, 2]  # 与上等价

# =>torch.unsqueeze(torch.unsqueeze(torch.unsqueeze(y, 0), 0), 0).repeat(1, 2, 1, 1, 2)
# y.repeat(1, 2, 1, 1, 2).shape=[1, 2, 1, 2, 4]  # 与上等级啊
y.repeat(1, 2, 1, 1, 2).shape

torch.Size([1, 2, 1, 2, 4])

In [106]:
y1 = y.repeat(1, 2, 3)
y1

tensor([[[1, 2, 1, 2, 1, 2],
         [3, 4, 3, 4, 3, 4],
         [1, 2, 1, 2, 1, 2],
         [3, 4, 3, 4, 3, 4]]])

In [107]:
y1[0][0][0] = 999
y1

tensor([[[999,   2,   1,   2,   1,   2],
         [  3,   4,   3,   4,   3,   4],
         [  1,   2,   1,   2,   1,   2],
         [  3,   4,   3,   4,   3,   4]]])

In [108]:
y  # y不变



tensor([[1, 2],
        [3, 4]])