In [30]:
import torch
import copy

In [31]:
x = torch.tensor([[1],
                  [2],
                  [3]])
x

tensor([[1],
        [2],
        [3]])

In [32]:
x.expand(3, 4)  # 维度0尺寸(维度0尺度为3)不变;维度1尺寸由1复制扩展为4(要扩充的维度尺寸必须为1)

tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]])

In [33]:
x1 = x.expand(-1, 3)  # -1表示维度0尺寸不变
x1

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])

In [34]:
x1[1][0] = 999
x1

tensor([[  1,   1,   1],
        [999, 999, 999],
        [  3,   3,   3]])

In [35]:
x  # ★★★★★x也发生改变(If you need to write to the tensors, please clone them first.)

tensor([[  1],
        [999],
        [  3]])

In [36]:
y = copy.deepcopy(x)
x2 = y.expand(-1, 5)
x2[1][0] = 100000
x2

tensor([[     1,      1,      1,      1,      1],
        [100000, 100000, 100000, 100000, 100000],
        [     3,      3,      3,      3,      3]])

In [37]:
x  # x不再发生改变

tensor([[  1],
        [999],
        [  3]])

In [38]:
x = torch.tensor([[1, 2],
                  [3, 4],
                  [5, 6]])
x = torch.unsqueeze(x, 0)
print(x.shape)
x.expand(2, 3, 2)  # 只能对维度大小为1的维度进行扩充

torch.Size([1, 3, 2])


tensor([[[1, 2],
         [3, 4],
         [5, 6]],

        [[1, 2],
         [3, 4],
         [5, 6]]])