In [195]:
import torch
import copy

### expand

In [196]:
x = torch.tensor([[1],
                  [2],
                  [3]])
x

tensor([[1],
        [2],
        [3]])

In [197]:
x.expand(3, 4)  # 维度0尺寸不变;维度1尺寸由1复制扩展为4(要扩充的维度尺寸必须为1)

tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]])

In [198]:
x1 = x.expand(-1, 3)  # -1表示维度0尺寸不变
x1

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])

In [199]:
x1[1][0] = 999
x1

tensor([[  1,   1,   1],
        [999, 999, 999],
        [  3,   3,   3]])

In [200]:
x  # ★★★★★x也发生改变(If you need to write to the tensors, please clone them first.)

tensor([[  1],
        [999],
        [  3]])

In [201]:
y = copy.deepcopy(x)
x2 = y.expand(-1, 5)
x2[1][0] = 100000
x2

tensor([[     1,      1,      1,      1,      1],
        [100000, 100000, 100000, 100000, 100000],
        [     3,      3,      3,      3,      3]])

In [202]:
x  # x不再发生改变

tensor([[  1],
        [999],
        [  3]])

In [203]:
x = torch.tensor([[1, 2],
                  [3, 4],
                  [5, 6]])
x = torch.unsqueeze(x, 0)
print(x.shape)
x.expand(2, 3, 2)  # 只能对维度信息为1的维度进行扩充

torch.Size([1, 3, 2])


tensor([[[1, 2],
         [3, 4],
         [5, 6]],

        [[1, 2],
         [3, 4],
         [5, 6]]])

### repeat_interleave
### 参考numpy.repeat

In [204]:
x = torch.tensor([[1, 2],
                  [3, 4]])
x

tensor([[1, 2],
        [3, 4]])

In [205]:
# By default, use the flattened input array, and return a flat output array.
torch.repeat_interleave(x, 2)  # 默认dim=None

tensor([1, 1, 2, 2, 3, 3, 4, 4])

In [206]:
torch.repeat_interleave(x, 3, dim=1)  # x维度1每条数据连续重复3次

tensor([[1, 1, 1, 2, 2, 2],
        [3, 3, 3, 4, 4, 4]])

In [207]:
x.repeat_interleave(3, dim=0)  # x维度0每条数据连续重复3次

tensor([[1, 2],
        [1, 2],
        [1, 2],
        [3, 4],
        [3, 4],
        [3, 4]])

In [208]:
torch.repeat_interleave(x, torch.tensor([2, 4]), dim=1)  # x维度1第0条数据重复2次,然后x维度1第1条数据重复4次

tensor([[1, 1, 2, 2, 2, 2],
        [3, 3, 4, 4, 4, 4]])

In [209]:
x1 = torch.repeat_interleave(x, torch.tensor([2, 4]), dim=0)  # x维度0第0条数据重复2次,然后x维度0第1条数据重复4次
x1

tensor([[1, 2],
        [1, 2],
        [3, 4],
        [3, 4],
        [3, 4],
        [3, 4]])

In [210]:
x1[0][0] = 999
x1

tensor([[999,   2],
        [  1,   2],
        [  3,   4],
        [  3,   4],
        [  3,   4],
        [  3,   4]])

In [211]:
x  # x不变(不需先进行copy)

tensor([[1, 2],
        [3, 4]])

### repeat
### 参考numpy.tile

In [212]:
x.repeat(4, 2)

tensor([[1, 2, 1, 2],
        [3, 4, 3, 4],
        [1, 2, 1, 2],
        [3, 4, 3, 4],
        [1, 2, 1, 2],
        [3, 4, 3, 4],
        [1, 2, 1, 2],
        [3, 4, 3, 4]])

In [213]:
x.repeat(1, 1, 1, 2)  # 每个维度上重复该tensor的次数(整体重复)

tensor([[[[1, 2, 1, 2],
          [3, 4, 3, 4]]]])

In [214]:
x1 = torch.tensor(4).repeat(4, 2, 4)
x1

tensor([[[4, 4, 4, 4],
         [4, 4, 4, 4]],

        [[4, 4, 4, 4],
         [4, 4, 4, 4]],

        [[4, 4, 4, 4],
         [4, 4, 4, 4]],

        [[4, 4, 4, 4],
         [4, 4, 4, 4]]])

In [215]:
x1[0][0][0] = 999
x1

tensor([[[999,   4,   4,   4],
         [  4,   4,   4,   4]],

        [[  4,   4,   4,   4],
         [  4,   4,   4,   4]],

        [[  4,   4,   4,   4],
         [  4,   4,   4,   4]],

        [[  4,   4,   4,   4],
         [  4,   4,   4,   4]]])

In [216]:
x  # x不变(不需先进行copy)


tensor([[1, 2],
        [3, 4]])