In [39]:
import torch

### 参考numpy.repeat

In [40]:
x = torch.tensor([[1, 2],
                  [3, 4]])
x

tensor([[1, 2],
        [3, 4]])

In [41]:
# By default, use the flattened input array, and return a flat output array.
torch.repeat_interleave(x, 2)  # 默认dim=None

tensor([1, 1, 2, 2, 3, 3, 4, 4])

In [42]:
torch.repeat_interleave(x, 3, dim=1)  # x维度1每条数据连续重复3次

tensor([[1, 1, 1, 2, 2, 2],
        [3, 3, 3, 4, 4, 4]])

In [43]:
x.repeat_interleave(3, dim=0)  # x维度0每条数据连续重复3次

tensor([[1, 2],
        [1, 2],
        [1, 2],
        [3, 4],
        [3, 4],
        [3, 4]])

In [44]:
torch.repeat_interleave(x, torch.tensor([2, 4]), dim=1)  # x维度1第0条数据重复2次,然后x维度1第1条数据重复4次

tensor([[1, 1, 2, 2, 2, 2],
        [3, 3, 4, 4, 4, 4]])

In [45]:
x1 = torch.repeat_interleave(x, torch.tensor([2, 4]), dim=0)  # x维度0第0条数据重复2次,然后x维度0第1条数据重复4次
x1

tensor([[1, 2],
        [1, 2],
        [3, 4],
        [3, 4],
        [3, 4],
        [3, 4]])

In [46]:
x1[0][0] = 999
x1

tensor([[999,   2],
        [  1,   2],
        [  3,   4],
        [  3,   4],
        [  3,   4],
        [  3,   4]])

In [47]:
x  # x不变

tensor([[1, 2],
        [3, 4]])