In [1]:
import torch
import copy

### expand

In [2]:
x = torch.tensor([[1],
                  [2],
                  [3]])
x

tensor([[1],
        [2],
        [3]])

In [3]:
x.expand(3, 4)  # 维度0尺寸不变;维度1尺寸由1复制扩展为4(要扩充的维度尺寸必须为1)

tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]])

In [4]:
x1 = x.expand(-1, 3)  # -1表示维度0尺寸不变
x1

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])

In [5]:
x1[1][0] = 999
x1

tensor([[  1,   1,   1],
        [999, 999, 999],
        [  3,   3,   3]])

In [6]:
x  # ★★★★★x也发生改变(If you need to write to the tensors, please clone them first.)

tensor([[  1],
        [999],
        [  3]])

In [7]:
y = copy.deepcopy(x)
x2 = y.expand(-1, 5)
x2[1][0] = 100000
x2

tensor([[     1,      1,      1,      1,      1],
        [100000, 100000, 100000, 100000, 100000],
        [     3,      3,      3,      3,      3]])

In [8]:
x  # x不再发生改变

tensor([[  1],
        [999],
        [  3]])

### repeat_interleave

In [9]:
x = torch.tensor([[1, 2],
                  [3, 4]])
x

tensor([[1, 2],
        [3, 4]])

In [10]:
# 完全类似于numpy.repeat
x.repeat_interleave(2)  # 默认dim=None

tensor([1, 1, 2, 2, 3, 3, 4, 4])

In [11]:
x.repeat_interleave(3, dim=1)  # x维度1每条数据连续重复3次

tensor([[1, 1, 1, 2, 2, 2],
        [3, 3, 3, 4, 4, 4]])

In [12]:
x.repeat_interleave(3, dim=0)  # x维度0每条数据连续重复3次

tensor([[1, 2],
        [1, 2],
        [1, 2],
        [3, 4],
        [3, 4],
        [3, 4]])

In [13]:
x.repeat_interleave(torch.tensor([2, 4]), dim=1)  # x维度1第0条数据重复2次,然后x维度1第1条数据重复4次

tensor([[1, 1, 2, 2, 2, 2],
        [3, 3, 4, 4, 4, 4]])

In [14]:
x1 = x.repeat_interleave(torch.tensor([2, 4]), dim=0)  # x维度0第0条数据重复2次,然后x维度0第1条数据重复4次
x1

tensor([[1, 2],
        [1, 2],
        [3, 4],
        [3, 4],
        [3, 4],
        [3, 4]])

In [15]:
x1[0][0] = 999
x1

tensor([[999,   2],
        [  1,   2],
        [  3,   4],
        [  3,   4],
        [  3,   4],
        [  3,   4]])

In [16]:
x  # x不变(不需先进行copy)

tensor([[1, 2],
        [3, 4]])

### repeat

In [17]:
# 完全类似于numpy.tile
x.repeat(4, 2)

tensor([[1, 2, 1, 2],
        [3, 4, 3, 4],
        [1, 2, 1, 2],
        [3, 4, 3, 4],
        [1, 2, 1, 2],
        [3, 4, 3, 4],
        [1, 2, 1, 2],
        [3, 4, 3, 4]])

In [18]:
x.repeat(1, 1, 1, 2)  # 每个维度上重复该tensor的次数(整体重复)

tensor([[[[1, 2, 1, 2],
          [3, 4, 3, 4]]]])

In [19]:
x1 = torch.tensor(4).repeat(4, 2, 4)
x1

tensor([[[4, 4, 4, 4],
         [4, 4, 4, 4]],

        [[4, 4, 4, 4],
         [4, 4, 4, 4]],

        [[4, 4, 4, 4],
         [4, 4, 4, 4]],

        [[4, 4, 4, 4],
         [4, 4, 4, 4]]])

In [20]:
x1[0][0][0] = 999
x1

tensor([[[999,   4,   4,   4],
         [  4,   4,   4,   4]],

        [[  4,   4,   4,   4],
         [  4,   4,   4,   4]],

        [[  4,   4,   4,   4],
         [  4,   4,   4,   4]],

        [[  4,   4,   4,   4],
         [  4,   4,   4,   4]]])

In [21]:
x  # x不变(不需先进行copy)


tensor([[1, 2],
        [3, 4]])