In [56]:
import tensorflow as tf
import numpy as np

In [57]:
# Variables are created and tracked via the tf.Variable class.
# A tf.Variable represents a tensor whose value can be changed by running ops on it.
# Specific ops allow you to read and modify the values of this tensor.
x = tf.Variable(3.0)  # 标量
x

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.0>

In [58]:
x = tf.Variable([5.5, 3])  # 向量

print(x)
print(x.dtype)
print(x.shape)
# print(x.ndim)  # 没有ndim属性
print(tf.rank(x))
print(tf.convert_to_tensor(x))
print(x.numpy())

<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([5.5, 3. ], dtype=float32)>
<dtype: 'float32'>
(2,)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor([5.5 3. ], shape=(2,), dtype=float32)
[5.5 3. ]


In [59]:
x = tf.Variable(range(10))
x

<tf.Variable 'Variable:0' shape=(10,) dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [60]:
a = np.array([[1.2, 2, 3],
              [2, 3, 4]])
x = tf.Variable(a)  # 从numpy创建;矩阵
x

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float64, numpy=
array([[1.2, 2. , 3. ],
       [2. , 3. , 4. ]])>

In [61]:
a = np.array([[1.2, 2, 3],
              [2, 3, 4]])
temp = tf.constant(a)
x = tf.Variable(temp)  # 从constant创建
x

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float64, numpy=
array([[1.2, 2. , 3. ],
       [2. , 3. , 4. ]])>

In [62]:
x = tf.Variable([1, 2, 3, 4, 5],
                dtype=tf.float32)  # 指定数据类型
x.dtype

tf.float32

In [63]:
x = tf.Variable(['1', '2'])  # 支持string数据类型
x



<tf.Variable 'Variable:0' shape=(2,) dtype=string, numpy=array([b'1', b'2'], dtype=object)>