In [46]:
import tensorflow as tf

In [47]:
a = tf.ones((2, 3, 4))
a

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>

In [48]:
# This version performs the same function as Dropout, however, it drops entire 1D feature maps instead of individual elements.
layder1d = tf.keras.layers.SpatialDropout1D(rate=0.2)
# 中间1个特征维度进行dropout
layder1d(inputs=a,  # 3D张量
         training=True)  # 是否为训练模式(eval模式下不执行Dropout操作)

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[1.25, 1.25, 0.  , 1.25],
        [1.25, 1.25, 0.  , 1.25],
        [1.25, 1.25, 0.  , 1.25]],

       [[0.  , 1.25, 1.25, 1.25],
        [0.  , 1.25, 1.25, 1.25],
        [0.  , 1.25, 1.25, 1.25]]], dtype=float32)>

In [49]:
b = tf.ones((2, 3, 4, 5))
b

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]], dtype=float32)>

In [50]:
# This version performs the same function as Dropout, however, it drops entire 2D feature maps instead of individual elements.
layder2d = tf.keras.layers.SpatialDropout2D(rate=0.5)
# 中间2个特征维度进行dropout
layder2d(inputs=b,  # 4D张量
         training=True)  # 是否为训练模式(eval模式下不执行Dropout操作)

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[2., 2., 2., 0., 2.],
         [2., 2., 2., 0., 2.],
         [2., 2., 2., 0., 2.],
         [2., 2., 2., 0., 2.]],

        [[2., 2., 2., 0., 2.],
         [2., 2., 2., 0., 2.],
         [2., 2., 2., 0., 2.],
         [2., 2., 2., 0., 2.]],

        [[2., 2., 2., 0., 2.],
         [2., 2., 2., 0., 2.],
         [2., 2., 2., 0., 2.],
         [2., 2., 2., 0., 2.]]],


       [[[0., 2., 2., 2., 0.],
         [0., 2., 2., 2., 0.],
         [0., 2., 2., 2., 0.],
         [0., 2., 2., 2., 0.]],

        [[0., 2., 2., 2., 0.],
         [0., 2., 2., 2., 0.],
         [0., 2., 2., 2., 0.],
         [0., 2., 2., 2., 0.]],

        [[0., 2., 2., 2., 0.],
         [0., 2., 2., 2., 0.],
         [0., 2., 2., 2., 0.],
         [0., 2., 2., 2., 0.]]]], dtype=float32)>