<font color='red' size=4>公式:</font>   
$$ \mathrm{tr}A = \sum_{i=1}^{n} a_{ii} $$

<font color='red' size=4>性质:</font>
1. 若$A$与$B$均为$n \times n $矩阵,则$\mathrm{tr}(A \pm B) =\mathrm{tr}(A) \pm \mathrm{tr}(B) $
2. 若$A \in \mathbb{C}^{m \times n }, B \in \mathbb{C}^{n \times m}$,则$\mathrm{tr}(AB) = \mathrm{tr}(BA)$
3. $  \mathrm{tr}(ABC) =  \mathrm{tr}(BCA) = \mathrm{tr}(CAB)$

In [1]:
import  numpy as np
a = np.arange(8).reshape((2,2,2))
np.trace(a)

array([6, 8])

In [3]:
b = np.eye(3)
print(b)
print(np.trace(b))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
3.0
