&emsp;&emsp;矩阵$ A  \in \mathbf{R} $的向量化是一线性变换,它将矩阵$ A = [a_{ij}] $的元素
按列堆栈(column stacking)排列成一个$ mn \times 1 $向量   
$$ \mathrm{vec}(A) = [a_{11}, \dots, a_{m1}, \dots, a_{1n}, \dots, a_{mn}]^T$$    
&emsp;&emsp;矩阵也可以按行堆栈为行向量,称为矩阵的行向量化,用符号$\mathrm{rvec}(A) $表示,定义为   
$$ \mathrm{rvec}(A)= [a_{11}, \dots, a_{1n}, \dots, a_{m1}, \dots, a_{mn}]  $$       
&emsp;&emsp;显然,矩阵的向量化和行向量化之间存在下列关系      
$$ \mathrm{rec}(A) = (\mathrm{vec}(A^T))^T \qquad  \mathrm{vec}(A^T)=(\mathrm{rvec}(A))^T $$   
&emsp;&emsp;显然,对于一个$ m \times n  $矩阵$ A$ ,向量$ \mathrm{vec}(A) $和$ \mathrm{vec}(A^T) $含有相同的元素,但排列
次序不同.因此存在一个唯一的$ mn \times mn $矩阵,可以将一个矩阵的向量化$\mathrm{vec}(A) $变换为其转置矩阵的向量化$ \mathrm{vec}(A^T)  $.这一
置换矩阵称为交换矩阵(commutation matrix).记作$ K_{mn} $,定义为   
$$ K_{mn}  \mathrm{vec}(A) = \mathrm{vec}(A^T)  $$   
&emsp;&emsp;易知$ K_{nm}K_{mn} \mathrm{vec}(A) = K_{nm}\mathrm{vec}(A^T) = \mathrm{vec}(A)  $由于此式对
任意$ m \times n $矩阵均成立,故 $ K_{nm}K_{mn} = I_{mn} $,即有$ K_{mn}^{-1} =K_{nm} $    

<font color='red' size=4>$ mn \times mn  $交换矩阵$ K_{mn}具有以下常用性质 $</font>      
* $$ K_{mn}^T = K_{nm} $$   

&emsp;&emsp;$ mn \times mn  $交换矩阵$ K_{mn} $的构造方法如下,每一行只赋一个元素1,其他元素全部为0.首先,第1行第一个元素为1,然后
这个1元素右移m位,变成第2行该位置的1元素.第2行该位置的1元素再右移m位,又变成第3行该位置的1元素.依此类推,找到下一行1元素的位置.然是,如果
向右移位时超过第mn列,则应该转到下一行继续移位,并且多移1位,再在此位置赋1.例如       
$$ K_{24} =$$
\begin{bmatrix}
1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 \\
0 & 0 & 1 & 0 & 0 & 0 & 0 & 0 \\
0 & 0 & 0 & 0 & 1 & 0 & 0 & 0 \\
0 & 0 & 0 & 0 & 0 & 0 & 1 & 0 \\
0 & 1 & 0 & 0 & 0 & 0 & 0 & 0 \\
0 & 0 & 0 & 1 & 0 & 0 & 0 & 0 \\
0 & 0 & 0 & 0 & 0 & 1 & 0 & 0 \\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 1 \\
\end{bmatrix}  

$$ K_{42} =$$
\begin{bmatrix}
1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 \\
0 & 0 & 0 & 0 & 1 & 0 & 0 & 0 \\
0 & 1 & 0 & 0 & 0 & 0 & 0 & 0 \\
0 & 0 & 0 & 0 & 0 & 1 & 0 & 0 \\
0 & 0 & 1 & 0 & 0 & 0 & 0 & 0 \\
0 & 0 & 0 & 0 & 0 & 0 & 1 & 0 \\
0 & 0 & 0 & 1 & 0 & 0 & 0 & 0 \\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 1 \\
\end{bmatrix}

In [53]:
import numpy as np
matrix = np.array([[1,2], [3,4]])
matrix_t = matrix.T
print(matrix)
print(matrix_t)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [54]:
vec = matrix.flatten(order='F').reshape(-1, 1) # 按列向量化
vec # vec(A)

array([[1],
       [3],
       [2],
       [4]])

In [55]:
rvec = matrix.flatten(order='C').reshape(1, -1) # 按行向量化
rvec # rvec(A)

array([[1, 2, 3, 4]])

In [56]:
matrix_t.flatten(order='F').reshape(-1, 1).T # vec(A.T).T 

array([[1, 2, 3, 4]])

In [51]:
def commutaion_matrix(m, n):
    """构造交换矩阵"""
    shape = m*n
    ma = np.zeros((shape, shape))
    columns = 0
    for i in range(shape):
        ma[i, columns] = 1
        columns += m
        if columns > shape-1:
            columns = columns + 1 - shape
    
    return ma


print(commutaion_matrix(2, 4))

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]
