&emsp;&emsp;若$ A= [a_{ij}]$是一个$ m \times n $矩阵,则$ A $ 的装置记作$ A^T$,是一
个$ n \times m $ 矩阵,其元素定义为$ [A^T]_{ij}=a_{ji} $;矩阵$ A^*$的负数共轭仍然是一
个$ m \times n $矩阵,其元素定义为$ [A^*]_{ij} = a^*_{ij} $;而矩阵 $A $的复共轭矩阵转置
记作$ A^H$,它是一个$ n \times m $矩阵,定义为    

$$ A^H =
\begin{bmatrix}
a^*_{11} & a^*_{21} & \dots  & a^*_{m1} \\
a^*_{12} & a^*_{22} & \dots  & a^*_{m2} \\
\vdots   & \vdots   & \ddots & \vdots   \\
a^*_{1n} & a^*_{2n} & \dots  & a^*_{mn} 
\end{bmatrix} 
$$
     
共轭转置又叫Hermitian伴随,Hermitian转置或Hermitian共轭.   
&emsp;&emsp;满足$ A^T = A $的正方实矩阵和$ A^H = A $的正方复矩阵分别称为对称矩阵和
Hermitian矩阵(复共轭对称矩阵).    
&emsp;&emsp;共轭转置与转置之间存在下列关系:   
$$  A^H = (A^*)^T = (A^T)^*$$   

<font color='red' size=4>性质</font>  
1. $ (A + B)^T = A ^T + B^T $ 
2. $  (aA)^T = (aA^T) $
3. $ (AB)^T = B^T A^T $
4. $ (A^T)^T = A $
 
</font>

In [5]:
import  numpy as np

matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

print((matrix1 + matrix2).T)
print(matrix1.T + matrix2.T) # 与上相等

print((matrix1 @ matrix2).T)
print(matrix2.T @ matrix1.T) # 与上相等

[[ 6 10]
 [ 8 12]]
[[ 6 10]
 [ 8 12]]
[[19 43]
 [22 50]]
[[19 43]
 [22 50]]


In [ ]:
a = np.array([[1+2j, 3+4j, 5+6j], [3-4j, 8+3j, 3], [8, 11, 2+1j]])
a

In [4]:
# 计算矩阵的转置
a.T

array([[ 1.+2.j,  3.-4.j,  8.+0.j],
       [ 3.+4.j,  8.+3.j, 11.+0.j],
       [ 5.+6.j,  3.+0.j,  2.+1.j]])

In [5]:
# 计算矩阵的共轭转置
np.conj(a.T)

array([[ 1.-2.j,  3.+4.j,  8.-0.j],
       [ 3.-4.j,  8.-3.j, 11.-0.j],
       [ 5.-6.j,  3.-0.j,  2.-1.j]])

In [6]:

np.conj(a).T # 与上等价

array([[ 1.-2.j,  3.+4.j,  8.-0.j],
       [ 3.-4.j,  8.-3.j, 11.-0.j],
       [ 5.-6.j,  3.-0.j,  2.-1.j]])