In [7]:
import tensorflow as tf
import numpy as np
import random

In [8]:
def set_seed(seed):
    """TensorFlow随机数种子设置大全"""
    np.random.seed(seed)
    random.seed(seed)
    tf.random.set_seed(23)  # Sets the global random seed.

In [10]:
num = 0
while num < 5:
    set_seed(3)
    print(np.random.randn(2, 3))
    print(tf.random.normal(mean=0, stddev=1, shape=(2, 3)), end='\n\n')
    num += 1

print(end='\n\n\n')
print(np.random.randn(2, 3))
print(tf.random.normal(mean=0, stddev=1, shape=(2, 3)))

[[ 1.78862847  0.43650985  0.09649747]
 [-1.8634927  -0.2773882  -0.35475898]]
tf.Tensor(
[[ 0.7354863   1.0494297   0.614072  ]
 [ 0.10622141  1.4849378  -0.03285756]], shape=(2, 3), dtype=float32)

[[ 1.78862847  0.43650985  0.09649747]
 [-1.8634927  -0.2773882  -0.35475898]]
tf.Tensor(
[[ 0.7354863   1.0494297   0.614072  ]
 [ 0.10622141  1.4849378  -0.03285756]], shape=(2, 3), dtype=float32)

[[ 1.78862847  0.43650985  0.09649747]
 [-1.8634927  -0.2773882  -0.35475898]]
tf.Tensor(
[[ 0.7354863   1.0494297   0.614072  ]
 [ 0.10622141  1.4849378  -0.03285756]], shape=(2, 3), dtype=float32)

[[ 1.78862847  0.43650985  0.09649747]
 [-1.8634927  -0.2773882  -0.35475898]]
tf.Tensor(
[[ 0.7354863   1.0494297   0.614072  ]
 [ 0.10622141  1.4849378  -0.03285756]], shape=(2, 3), dtype=float32)

[[ 1.78862847  0.43650985  0.09649747]
 [-1.8634927  -0.2773882  -0.35475898]]
tf.Tensor(
[[ 0.7354863   1.0494297   0.614072  ]
 [ 0.10622141  1.4849378  -0.03285756]], shape=(2, 3), dtype=float32)

