In [1]:
from sklearn.datasets import load_iris
from sklearn.model_selection  import train_test_split
import numpy as np

In [2]:
iris = load_iris() # 鸢尾花数据集
X, y =  iris.data, iris.target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [3]:
np.unique(y) # 多分类任务

array([0, 1, 2])

In [4]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier

tree = DecisionTreeClassifier(max_depth=2, min_samples_split=2) # 多个超参数需要在此处调节

clf = AdaBoostClassifier(base_estimator=tree, # 基本分类器.如果为None,则为DecisionTreeClassifier(max_depth=1),即决策树桩
                         n_estimators=100, # 基本分类器的数量
                         learning_rate=1) # Learning rate shrinks the contribution of each classifier by learning_rate(默认learning_rate=1)
'''
learning_ratefloat, optional (default=1.)
    Learning rate shrinks the contribution of each classifier by learning_rate. 
    There is a trade-off between learning_rate and n_estimators.
'''

clf.fit(X_train, y_train) # 可以处理多分类任务(基本分类器决策树可以处理多分类任务)

AdaBoostClassifier(algorithm='SAMME.R',
                   base_estimator=DecisionTreeClassifier(ccp_alpha=0.0,
                                                         class_weight=None,
                                                         criterion='gini',
                                                         max_depth=2,
                                                         max_features=None,
                                                         max_leaf_nodes=None,
                                                         min_impurity_decrease=0.0,
                                                         min_impurity_split=None,
                                                         min_samples_leaf=1,
                                                         min_samples_split=2,
                                                         min_weight_fraction_leaf=0.0,
                                                         presort='deprecated',
                          

In [5]:
clf.predict(X_test) # 特征的重要性(值越大,重要程度越高)

array([1, 2, 1, 2, 2, 0, 1, 0, 0, 0, 2, 1, 1, 2, 0, 2, 0, 0, 0, 1, 0, 2,
       0, 0, 1, 1, 1, 0, 1, 2])

In [45]:
# 预测结果可以输出为概率向量
proba = clf.predict_proba(X_test)
proba

array([[8.16937238e-11, 9.99939128e-01, 6.08717434e-05],
       [5.71338646e-14, 6.88545876e-02, 9.31145412e-01],
       [5.60482843e-11, 9.99885206e-01, 1.14793496e-04],
       [2.45226299e-16, 3.06890490e-11, 1.00000000e+00],
       [5.72656122e-14, 7.02012116e-02, 9.29798788e-01],
       [9.99999339e-01, 6.52595570e-07, 8.59666689e-09],
       [9.95093251e-11, 9.99952422e-01, 4.75783592e-05],
       [9.99999363e-01, 6.28753197e-07, 8.63349168e-09],
       [9.99999363e-01, 6.28753197e-07, 8.63349168e-09],
       [9.99999339e-01, 6.52595570e-07, 8.59666689e-09],
       [2.45226299e-16, 3.06890490e-11, 1.00000000e+00],
       [7.20680537e-12, 9.99601081e-01, 3.98918692e-04],
       [8.16937238e-11, 9.99939128e-01, 6.08717434e-05],
       [2.45226299e-16, 3.06890490e-11, 1.00000000e+00],
       [9.99999339e-01, 6.52595570e-07, 8.59666689e-09],
       [3.66695335e-15, 4.43052650e-09, 9.99999996e-01],
       [9.99999369e-01, 6.22619877e-07, 8.54927527e-09],
       [9.99999369e-01, 6.22619

In [46]:
a = np.max(proba, axis=1)
a # 每条数据输出的概率向量中最大的概率

array([0.99993913, 0.93114541, 0.99988521, 1.        , 0.92979879,
       0.99999934, 0.99995242, 0.99999936, 0.99999936, 0.99999934,
       1.        , 0.99960108, 0.99993913, 1.        , 0.99999934,
       1.        , 0.99999937, 0.99999937, 0.99999936, 0.91435039,
       0.99999934, 0.92392672, 0.99999934, 0.99999934, 0.99993913,
       0.99992629, 0.99995337, 0.99999934, 0.99993913, 0.92865277])

In [49]:
b = list()
for i in range(proba.shape[0]):
    b.append(np.argwhere(proba[i,:] == a[i])[0][0])
np.array(b) # 最大概率属于的类

array([1, 2, 1, 2, 2, 0, 1, 0, 0, 0, 2, 1, 1, 2, 0, 2, 0, 0, 0, 1, 0, 2,
       0, 0, 1, 1, 1, 0, 1, 2], dtype=int64)

In [12]:
clf.score(X_test, y_test)

0.9

In [8]:
clf.estimator_errors_ # 各个基本分类器的分类错误率

array([3.33333333e-02, 2.55269494e-02, 1.14025324e-01, 5.95571380e-03,
       1.79318815e-02, 3.85582803e-03, 2.01872573e-02, 5.97714864e-05,
       7.20350269e-05, 1.37487096e-04, 6.55067507e-03, 2.45260394e-05,
       1.83957690e-05, 1.70122853e-04, 1.61740436e-03, 3.60127084e-05,
       8.23874649e-06, 2.16965865e-04, 5.21481506e-04, 5.22529590e-05,
       5.17835444e-06, 2.50513732e-04, 2.13835736e-04, 7.03023136e-05,
       4.15367067e-06, 2.67397210e-04, 1.07724964e-04, 8.83854014e-05,
       4.01530027e-06, 2.70129593e-04, 6.45296903e-05, 1.04971405e-04,
       4.47255737e-06, 2.61482617e-04, 4.46725926e-05, 1.19002659e-04,
       5.53043378e-06, 2.45662079e-04, 3.49612183e-05, 1.30008483e-04,
       7.37322954e-06, 2.26729462e-04, 3.05409675e-05, 1.38025480e-04,
       1.03032524e-05, 2.08363725e-04, 2.95697429e-05, 1.43556086e-04,
       1.45093162e-05, 1.93868953e-04, 3.11148497e-05, 1.47694737e-04,
       1.96419152e-05, 1.71691846e-04, 1.30377781e-05, 1.68530162e-04,
      

In [9]:
clf.feature_importances_ # 特征的相对重要性(值越大,重要程度越高)

array([0.0018299 , 0.39273444, 0.39785661, 0.20757905])