In [34]:
import numpy as np
import copy

In [35]:
x = np.arange(3).reshape(1, 3)
y = np.arange(2).reshape(2, 1)
a, b = np.broadcast_arrays(x, y)  # x,y相互之间进行广播(必须确保x,y相互之间可进行广播)

In [36]:
a  # x,y相互之间进行广播后x的形式

array([[0, 1, 2],
       [0, 1, 2]])

In [37]:
b  # x,y相互之间进行广播后y的形式

array([[0, 0, 0],
       [1, 1, 1]])

In [38]:
a[0][0] = 999
a

C:\Users\dcdmm\AppData\Local\Temp\ipykernel_25544\1930231521.py:1: DeprecationWarning: Numpy has detected that you (may be) writing to an array with
overlapping memory from np.broadcast_arrays. If this is intentional
set the WRITEABLE flag True or make a copy immediately before writing.
  a[0][0] = 999


array([[999,   1,   2],
       [999,   1,   2]])

In [39]:
# If this is intentional set the WRITEABLE flag True or make a copy immediately before writing.
x  # ★★★★★x也发生改变

array([[999,   1,   2]])

In [40]:
a1, b1 = np.broadcast_arrays(copy.deepcopy(x), copy.deepcopy(y))
a1[0][0] = 111111
a1

C:\Users\dcdmm\AppData\Local\Temp\ipykernel_25544\909767244.py:2: DeprecationWarning: Numpy has detected that you (may be) writing to an array with
overlapping memory from np.broadcast_arrays. If this is intentional
set the WRITEABLE flag True or make a copy immediately before writing.
  a1[0][0] = 111111


array([[111111,      1,      2],
       [111111,      1,      2]])

In [41]:
x  # x不再发生改变

array([[999,   1,   2]])

In [42]:
m = np.ones([1, 12, 8, 1, 4, 1])
n = np.zeros([5, 4, 1, 1, 3, 1, 4])
M, N = np.broadcast_arrays(copy.deepcopy(m), copy.deepcopy(n))
print(M.shape)
print(N.shape)  # 广播后M,N shape完全一致


(5, 4, 12, 8, 3, 4, 4)
(5, 4, 12, 8, 3, 4, 4)
