In [15]:
import numpy as np

x1 = np.array([1, 2, 3]).reshape(-1, 1)
x1

array([[1],
       [2],
       [3]])

In [16]:
np.broadcast_to(x1, (3, 3)) # Broadcast an array to a new shape.

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [17]:
x1 = np.array([1, 2, 3]).reshape(1, -1)
x1

array([[1, 2, 3]])

In [18]:
np.broadcast_to(x1, (3, 3)) # Broadcast an array to a new shape.

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [19]:
np.broadcast_to(x1, (5, 4, 3)) # 和广播机制规则一致

array([[[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]])

In [20]:
x1 # x不变

array([[1, 2, 3]])