In [84]:
import numpy as np

In [85]:
a = np.arange(64)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [86]:
a.shape  # ndim=1

(64,)

In [87]:
a.reshape(2, 32)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63]])

In [88]:
a  # a不变

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [89]:
b = np.reshape(a, (8, 8))
# b = a.reshape(8, 8)   # 与上等价
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [90]:
b.reshape(-1, 1)  #  等价于b.reshape(64, 1);ndim=2

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29],
       [30],
       [31],
       [32],
       [33],
       [34],
       [35],
       [36],
       [37],
       [38],
       [39],
       [40],
       [41],
       [42],
       [43],
       [44],
       [45],
       [46],
       [47],
       [48],
       [49],
       [50],
       [51],
       [52],
       [53],
       [54],
       [55],
       [56],
       [57],
       [58],
       [59],
       [60],
       [61],
       [62],
       [63]])

In [91]:
b.reshape(-1, )  #  等价于b.reshape(64, );ndim=1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [92]:
b.flatten().reshape(8, 8) - b  # 不变

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [93]:
arr = np.random.randn(2, 7, 7)
arr

array([[[ 1.2080218 , -0.0226539 , -0.1717574 ,  0.44498104,
         -1.08934724, -1.20474554,  0.4963677 ],
        [ 0.12387299, -0.72141478,  0.41599749, -0.47686165,
         -0.33727082, -1.85355239, -1.21105582],
        [-0.34888314, -2.21426403,  0.9728497 ,  1.42977273,
         -0.09579781, -0.21411207, -0.12256741],
        [-0.54674742,  0.14850897, -0.04793247,  0.31116198,
          0.72755053, -0.31194425,  0.67268069],
        [-0.87341973, -0.0352391 , -0.94136816, -0.12091696,
          0.68738898, -0.89312653,  0.26153078],
        [ 0.86518219,  0.10028373,  1.35395387, -0.33356073,
         -0.46977778,  1.2021321 ,  0.0358146 ],
        [ 0.30426468, -1.89039406, -0.00562147,  0.13321193,
          1.58303573,  0.77398124,  0.81999899]],

       [[ 0.46006134,  0.38006856,  0.61847678, -1.90822008,
         -1.8615244 , -0.29805925,  1.1036025 ],
        [-0.2832052 , -0.0674514 ,  0.52731064, -1.13645234,
          0.30694716, -0.47429788, -0.76730167],
        

In [94]:
arr1 = arr.reshape(2, 7 * 7)  # 向量化数据
arr1

array([[ 1.2080218 , -0.0226539 , -0.1717574 ,  0.44498104, -1.08934724,
        -1.20474554,  0.4963677 ,  0.12387299, -0.72141478,  0.41599749,
        -0.47686165, -0.33727082, -1.85355239, -1.21105582, -0.34888314,
        -2.21426403,  0.9728497 ,  1.42977273, -0.09579781, -0.21411207,
        -0.12256741, -0.54674742,  0.14850897, -0.04793247,  0.31116198,
         0.72755053, -0.31194425,  0.67268069, -0.87341973, -0.0352391 ,
        -0.94136816, -0.12091696,  0.68738898, -0.89312653,  0.26153078,
         0.86518219,  0.10028373,  1.35395387, -0.33356073, -0.46977778,
         1.2021321 ,  0.0358146 ,  0.30426468, -1.89039406, -0.00562147,
         0.13321193,  1.58303573,  0.77398124,  0.81999899],
       [ 0.46006134,  0.38006856,  0.61847678, -1.90822008, -1.8615244 ,
        -0.29805925,  1.1036025 , -0.2832052 , -0.0674514 ,  0.52731064,
        -1.13645234,  0.30694716, -0.47429788, -0.76730167, -0.33122857,
        -0.69580294, -0.99412397, -0.53049595,  0.43135795, -0.

In [95]:
arr2 = arr1.reshape(2, 7, 7)  # 按原顺序恢复成原shape(本质上不会改变张量元素的存储顺序)
arr2 - arr

array([[[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]]])

In [96]:
mul_arr = np.arange(120).reshape((2, 3, 4, 5))
mul_arr

array([[[[  0,   1,   2,   3,   4],
         [  5,   6,   7,   8,   9],
         [ 10,  11,  12,  13,  14],
         [ 15,  16,  17,  18,  19]],

        [[ 20,  21,  22,  23,  24],
         [ 25,  26,  27,  28,  29],
         [ 30,  31,  32,  33,  34],
         [ 35,  36,  37,  38,  39]],

        [[ 40,  41,  42,  43,  44],
         [ 45,  46,  47,  48,  49],
         [ 50,  51,  52,  53,  54],
         [ 55,  56,  57,  58,  59]]],


       [[[ 60,  61,  62,  63,  64],
         [ 65,  66,  67,  68,  69],
         [ 70,  71,  72,  73,  74],
         [ 75,  76,  77,  78,  79]],

        [[ 80,  81,  82,  83,  84],
         [ 85,  86,  87,  88,  89],
         [ 90,  91,  92,  93,  94],
         [ 95,  96,  97,  98,  99]],

        [[100, 101, 102, 103, 104],
         [105, 106, 107, 108, 109],
         [110, 111, 112, 113, 114],
         [115, 116, 117, 118, 119]]]])

In [97]:
"""
解析:
mul_arr[0, 0, 0]填充到mul_arr1[0]
mul_arr[0, 0, 1]填充到mul_arr1[0]
mul_arr[0, 0, 2]填充到mul_arr1[0]
mul_arr[0, 0, 3]填充到mul_arr1[0]  ==>mul_arr1[0]填充完毕

mul_arr[0, 1, 0]填充到mul_arr1[0]
mul_arr[0, 1, 1]填充到mul_arr1[0]
mul_arr[0, 1, 2]填充到mul_arr1[0]
mul_arr[0, 1, 3]填充到mul_arr1[0]  ==>mul_arr1[1]填充完毕

mul_arr[0, 2, 0]填充到mul_arr1[0]
mul_arr[0, 2, 1]填充到mul_arr1[0]
mul_arr[0, 2, 2]填充到mul_arr1[0]
mul_arr[0, 2, 3]填充到mul_arr1[0]  ==>mul_arr1[2]填充完毕


mul_arr[1, 0, 0]填充到mul_arr1[0]
mul_arr[1, 0, 1]填充到mul_arr1[0]
mul_arr[1, 0, 2]填充到mul_arr1[0]
mul_arr[1, 0, 3]填充到mul_arr1[0]  ==>mul_arr1[3]填充完毕

mul_arr[1, 1, 0]填充到mul_arr1[0]
mul_arr[1, 1, 1]填充到mul_arr1[0]
mul_arr[1, 1, 2]填充到mul_arr1[0]
mul_arr[1, 1, 3]填充到mul_arr1[0]  ==>mul_arr1[4]填充完毕

mul_arr[1, 2, 0]填充到mul_arr1[0]
mul_arr[1, 2, 1]填充到mul_arr1[0]
mul_arr[1, 2, 2]填充到mul_arr1[0]
mul_arr[1, 2, 3]填充到mul_arr1[0]  ==>mul_arr1[5]填充完毕

填充完成
"""
mul_arr1 = mul_arr.reshape(6, 20)
mul_arr1

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32,
         33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
         53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,
         73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,
         93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
        113, 114, 115, 116, 117, 118, 119]])

In [98]:
"""
解析:
mul_arr1[0, 0:5]填充到mul_arr2[0, 0, 0]
mul_arr1[0, 5:10]填充到mul_arr2[0, 0, 1]
mul_arr1[0, 10:15]填充到mul_arr2[0, 0, 2]
mul_arr1[0, 15:20]填充到mul_arr2[0, 0, 3]

mul_arr1[1, 0:5]填充到mul_arr2[0, 1, 0]
mul_arr1[1, 5:10]填充到mul_arr2[0, 1, 1]
mul_arr1[1, 10:15]填充到mul_arr2[0, 1, 2]
mul_arr1[1, 15:20]填充到mul_arr2[0, 1, 3]

mul_arr1[2, 0:5]填充到mul_arr2[0, 2, 0]
mul_arr1[2, 5:10]填充到mul_arr2[0, 2, 1]
mul_arr1[2, 10:15]填充到mul_arr2[0, 2, 2]
mul_arr1[2, 15:20]填充到mul_arr2[0, 2, 3]

mul_arr1[3, 0:5]填充到mul_arr2[1, 0, 0]
mul_arr1[3, 5:10]填充到mul_arr2[1, 0, 1]
mul_arr1[3, 10:15]填充到mul_arr2[1, 0, 2]
mul_arr1[3, 15:20]填充到mul_arr2[1, 0, 3]

mul_arr1[4, 0:5]填充到mul_arr2[1, 1, 0]
mul_arr1[4, 5:10]填充到mul_arr2[1, 1, 1]
mul_arr1[4, 10:15]填充到mul_arr2[1, 1, 2]
mul_arr1[4, 15:20]填充到mul_arr2[1, 1, 3]

mul_arr1[5, 0:5]填充到mul_arr2[1, 2, 0]
mul_arr1[5, 5:10]填充到mul_arr2[1, 2, 1]
mul_arr1[5, 10:15]填充到mul_arr2[1, 2, 2]
mul_arr1[5, 15:20]填充到mul_arr2[1, 2, 3]

填充完成
"""
mul_arr2 = mul_arr1.reshape((2, 3, 4, 5))
mul_arr2

array([[[[  0,   1,   2,   3,   4],
         [  5,   6,   7,   8,   9],
         [ 10,  11,  12,  13,  14],
         [ 15,  16,  17,  18,  19]],

        [[ 20,  21,  22,  23,  24],
         [ 25,  26,  27,  28,  29],
         [ 30,  31,  32,  33,  34],
         [ 35,  36,  37,  38,  39]],

        [[ 40,  41,  42,  43,  44],
         [ 45,  46,  47,  48,  49],
         [ 50,  51,  52,  53,  54],
         [ 55,  56,  57,  58,  59]]],


       [[[ 60,  61,  62,  63,  64],
         [ 65,  66,  67,  68,  69],
         [ 70,  71,  72,  73,  74],
         [ 75,  76,  77,  78,  79]],

        [[ 80,  81,  82,  83,  84],
         [ 85,  86,  87,  88,  89],
         [ 90,  91,  92,  93,  94],
         [ 95,  96,  97,  98,  99]],

        [[100, 101, 102, 103, 104],
         [105, 106, 107, 108, 109],
         [110, 111, 112, 113, 114],
         [115, 116, 117, 118, 119]]]])