In [1]:
import numpy as np

In [2]:
arr1 = np.arange(14)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [3]:
np.resize(arr1, (3, 7))  # 3*7 > 14,继续使用arr1进行填充

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [ 0,  1,  2,  3,  4,  5,  6]])

In [4]:
np.resize(arr1, (2, 4))  # 2*4 < 14,截断处理

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [5]:
arr1  # arr1不变

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [6]:
arr2 = np.random.randint(4, 7, size=5)
np.resize(arr2, (5, 6))

array([[4, 6, 4, 4, 5, 4],
       [6, 4, 4, 5, 4, 6],
       [4, 4, 5, 4, 6, 4],
       [4, 5, 4, 6, 4, 4],
       [5, 4, 6, 4, 4, 5]])

In [7]:
arr2

array([4, 6, 4, 4, 5])