In [18]:
import numpy as np

In [19]:
x = np.array([[[0, 1], [2, 3]],
              [[4, 5], [6, 7]]])
x

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [20]:
np.swapaxes(x, 0, 1)  # 交换维度0和维度1

array([[[0, 1],
        [4, 5]],

       [[2, 3],
        [6, 7]]])

In [21]:
x  # x不变

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [22]:
np.swapaxes(x, 0, 2)

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])