In [1]:
import numpy as np
a = np.array([[1, 2, 3],
              [3, 4, 5], 
              [4, 5, 6]])
a

array([[1, 2, 3],
       [3, 4, 5],
       [4, 5, 6]])

In [2]:
a.flatten() # Return a copy of the array collapsed into one dimension

array([1, 2, 3, 3, 4, 5, 4, 5, 6])

In [3]:
a.reshape(-1, ) # 与上等价

array([1, 2, 3, 3, 4, 5, 4, 5, 6])

In [4]:
a.ravel() # 与上等价


array([1, 2, 3, 3, 4, 5, 4, 5, 6])