In [57]:
import numpy as np

In [58]:
arr = np.arange(25).reshape(5, 5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [59]:
v_bt_ = np.broadcast_to(np.array([1, 2, 3, 4, 5]).reshape(1, 5), (5, 5))
print(v_bt_)
v_bt = np.broadcast_to(np.array([1, 2, 3, 4, 5]), (5, 5))  # shape=(5, )的向量广播时会被转换为shape=(1, 5)矩阵
print(v_bt)  # 与上等价

print(arr - v_bt)
print(arr - np.array([1, 2, 3, 4, 5]))  # 与上等价

[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]
[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]
[[-1 -1 -1 -1 -1]
 [ 4  4  4  4  4]
 [ 9  9  9  9  9]
 [14 14 14 14 14]
 [19 19 19 19 19]]
[[-1 -1 -1 -1 -1]
 [ 4  4  4  4  4]
 [ 9  9  9  9  9]
 [14 14 14 14 14]
 [19 19 19 19 19]]


In [60]:
a = np.array([[1], 
              [2]])
b = np.array([1, 2, 3, 4])
print(a.shape, b.shape)
# 计算步骤: 
# 1. b.shape=(4,  ) -转换-> b.shape=(1, 4)
#   b=[[1, 2, 3, 4]]
# 2. a.shape=(2, 1) -广播-> a.shape=(2, 4)
#   a = [[1, 1, 1, 1], [2, 2, 2, 2]]
# 3. b.shape=(1, 4) -广播-> b.shape=(2, 4)
#   b = [[1, 2, 3, 4], [1, 2, 3, 4]]
print(a + b)  # (a + b).shape=(2, 4)

(2, 1) (4,)
[[2 3 4 5]
 [3 4 5 6]]


In [61]:
arr0 = np.array([1, 2, 3]).reshape(1, 3)
arr1 = np.array([1, 2, 3]).reshape(3, 1)

In [62]:
print(np.broadcast_to(arr0, (3, 3)) + np.broadcast_to(arr1, (3, 3)))
print(arr0 + arr1)  # 与上等价

[[2 3 4]
 [3 4 5]
 [4 5 6]]
[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [63]:
x = np.random.randn(4, 32, 32, 3)
x.shape

(4, 32, 32, 3)

In [64]:
(x + 4).shape  # 等价于x + np.broadcast_to(4, x.shape)

(4, 32, 32, 3)

In [65]:
(x * 4).shape  # 等价于x * np.broadcast_to(4, x.shape)

(4, 32, 32, 3)

In [66]:
(x ** 3).shape

(4, 32, 32, 3)

In [67]:
(x == 4).shape

(4, 32, 32, 3)

In [68]:
# it starts with the trailing dimensions, and works its way forward
(x + np.random.randn(3)).shape  # [4, 32, 32, 3] broadcasting [3, ] --> [4, 32, 32, 3]

(4, 32, 32, 3)

In [69]:
# if current dim==1,expand to same
# if either has no dim,insert one dim and expand to same
(x + np.random.randn(1, 3)).shape  # [4, 32, 32, 3] boradcasting [1, 3] --> [4, 32, 32, 3]

(4, 32, 32, 3)

In [70]:
(x + np.random.randn(32, 32, 1)).shape  # [4, 32, 32, 3] boradcasting [32, 32, 1] --> [4, 32, 32, 3]

(4, 32, 32, 3)

In [71]:
(x + np.random.randn(4, 1, 1, 1)).shape  # [4, 32, 32, 3] boradcasting [4, 1, 1, 1] --> [4, 32, 32, 3]

(4, 32, 32, 3)

In [72]:
a = np.ones([1, 12, 8, 1, 4, 1])
b = np.zeros([5, 4, 1, 1, 3, 1, 4])
# [1, 12, 8, 1, 4, 1] boradcasting [5, 4, 1, 1, 3, 1, 4] --> [5, 4, 12, 8, 3, 4, 4]

(a + b).shape

(5, 4, 12, 8, 3, 4, 4)

In [73]:
# 显式的使用broadcast_to函数完成此操作(不推荐)
a1 = np.broadcast_to(a, (5, 4, 12, 8, 3, 4, 4))
a1.shape

(5, 4, 12, 8, 3, 4, 4)

In [74]:
b1 = np.broadcast_to(b, (5, 4, 12, 8, 3, 4, 4))
b1.shape

(5, 4, 12, 8, 3, 4, 4)

In [75]:
(a + b) - (a1 + b1)

array([[[[[[[0., 0., 0., 0.],
            [0., 0., 0., 0.],
            [0., 0., 0., 0.],
            [0., 0., 0., 0.]],

           [[0., 0., 0., 0.],
            [0., 0., 0., 0.],
            [0., 0., 0., 0.],
            [0., 0., 0., 0.]],

           [[0., 0., 0., 0.],
            [0., 0., 0., 0.],
            [0., 0., 0., 0.],
            [0., 0., 0., 0.]]],


          [[[0., 0., 0., 0.],
            [0., 0., 0., 0.],
            [0., 0., 0., 0.],
            [0., 0., 0., 0.]],

           [[0., 0., 0., 0.],
            [0., 0., 0., 0.],
            [0., 0., 0., 0.],
            [0., 0., 0., 0.]],

           [[0., 0., 0., 0.],
            [0., 0., 0., 0.],
            [0., 0., 0., 0.],
            [0., 0., 0., 0.]]],


          [[[0., 0., 0., 0.],
            [0., 0., 0., 0.],
            [0., 0., 0., 0.],
            [0., 0., 0., 0.]],

           [[0., 0., 0., 0.],
            [0., 0., 0., 0.],
            [0., 0., 0., 0.],
            [0., 0., 0., 0.]],

           [[0., 0.,