In [165]:
import numpy as np

In [166]:
np.repeat(3, 4)  # 等价于np.repeat([3], 4)

array([3, 3, 3, 3])

In [167]:
x = np.array([[1, 2],
              [3, 4]])
# 先展开再重复
np.repeat(x, 2)  # 默认axis=None

array([1, 1, 2, 2, 3, 3, 4, 4])

In [168]:
np.repeat(x, 3, axis=1)  # x维度1每条数据依次重复3次

array([[1, 1, 1, 2, 2, 2],
       [3, 3, 3, 4, 4, 4]])

In [169]:
np.repeat(x, 3, axis=0)  # x维度0每条数据依次重复3次

array([[1, 2],
       [1, 2],
       [1, 2],
       [3, 4],
       [3, 4],
       [3, 4]])

In [170]:
np.repeat(x, [2, 4], axis=1)  # x维度1第0条数据重复2次,x维度1第1条数据重复4次

array([[1, 1, 2, 2, 2, 2],
       [3, 3, 4, 4, 4, 4]])

In [171]:
x1 = np.repeat(x, [2, 4], axis=0)  # x维度0第0条数据重复2次,x维度0第1条数据重复4次
x1

array([[1, 2],
       [1, 2],
       [3, 4],
       [3, 4],
       [3, 4],
       [3, 4]])

In [172]:
x1[0][0] = 999
x1

array([[999,   2],
       [  1,   2],
       [  3,   4],
       [  3,   4],
       [  3,   4],
       [  3,   4]])

In [173]:
x  # x不变

array([[1, 2],
       [3, 4]])

In [174]:
np.tile(3, 4)  # 等价于np.tile([3], 4)

array([3, 3, 3, 3])

In [175]:
np.tile(x, (2, 4))  # x维度0数据整体重复2次,维度1数据整体重复4次

array([[1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4]])

In [176]:
np.tile(np.expand_dims(np.expand_dims(x, 0), 0), (1, 1, 1, 2))

array([[[[1, 2, 1, 2],
         [3, 4, 3, 4]]]])

In [177]:
# 与上等价
x2 = np.tile(x,
             (1, 1, 1, 2))  # 每个维度上重复该array的次数(整体重复)
x2

array([[[[1, 2, 1, 2],
         [3, 4, 3, 4]]]])

In [178]:
x2[0][0][0][0] = 9999
x2

array([[[[9999,    2,    1,    2],
         [   3,    4,    3,    4]]]])

In [179]:
x  # x不变

array([[1, 2],
       [3, 4]])