In [1]:
import torch

解析:

$ z = [x_0^2, x_1^2, x_2^2] $

$ \frac{\partial z}{ \partial x_0} = \lambda_0 * (\frac{\partial z_0}{\partial x_0}) + \lambda_1 * (\frac{\partial z_1}{\partial x_0})   + \lambda_2 * (\frac{\partial z_2}{\partial x_0})$

$ \frac{\partial z}{ \partial x_1} = \lambda_0 * (\frac{\partial z_0}{\partial x_1}) + \lambda_1 * (\frac{\partial z_1}{\partial x_1})   + \lambda_2 * (\frac{\partial z_2}{\partial x_1})$

$ \frac{\partial z}{ \partial x_2} = \lambda_0 * (\frac{\partial z_0}{\partial x_2}) + \lambda_1 * (\frac{\partial z_1}{\partial x_2})   + \lambda_2 * (\frac{\partial z_2}{\partial x_2})$

In [2]:
x = torch.tensor([1, 2, 3],
                  requires_grad=True,
                  dtype=torch.float32) # x为向量


z = x ** 2
v = torch.tensor([0.1, 1, 10], dtype=torch.float) # 权重向量(与z同形)
print(z)
z.backward(v)
print(x.grad) # 与x同型

tensor([1., 4., 9.], grad_fn=<PowBackward0>)
tensor([ 0.2000,  4.0000, 60.0000])


解析:
$z = $
\begin{pmatrix}
A[0][0]*vec[0] + A[0][1]*vec[1] + A[0][2]*vec[2] \\
A[1][0]*vec[0] + A[1][1]*vec[1] + A[1][2]*vec[2]  \\
A[2][0]*vec[0] + A[2][1]*vec[1] + A[2][2]*vec[2]  
\end{pmatrix}

$ \frac{\partial z}{\partial vec[0]}  = \lambda_0 * \frac{\partial z[0]}{\partial vec[0]} + \lambda_1 * \frac{\partial z[1]}{\partial vec[0]} + \lambda_2 * \frac{\partial z[2]}{\partial vec[0]} $

$ \frac{\partial z}{\partial vec[1]}  = \lambda_0 * \frac{\partial z[0]}{\partial vec[1]} + \lambda_1 * \frac{\partial z[1]}{\partial vec[1]} + \lambda_2 * \frac{\partial z[2]}{\partial vec[1]} $

$ \frac{\partial z}{\partial vec[2]}  = \lambda_0 * \frac{\partial z[0]}{\partial vec[2]} + \lambda_1 * \frac{\partial z[1]}{\partial vec[2]} + \lambda_3 * \frac{\partial z[2]}{\partial vec[2]} $

In [3]:
A = torch.tensor([[1., 2., 3.],
                  [4., 5., 6.],
                  [7., 8., 9.]], requires_grad=True)
vec = torch.tensor([[1.],
                    [2.],
                    [3.]], requires_grad=True)

r_vec = A @ vec
r_vec.backward(gradient=torch.tensor([[2.],
                                      [3.],
                                      [5]])) # 权值向量(与r_vec同型)
vec.grad # 与vec同型

tensor([[49.],
        [59.],
        [69.]])

解析
$z = $
\begin{pmatrix}
A[0][0]*vec[0] + A[0][1]*vec[1] + A[0][2]*vec[2] \\
A[1][0]*vec[0] + A[1][1]*vec[1] + A[1][2]*vec[2]  \\
A[2][0]*vec[0] + A[2][1]*vec[1] + A[2][2]*vec[2]  
\end{pmatrix}

$ \frac{\partial z}{\partial A[0][0]}  = \lambda_0 * \frac{\partial z[0]}{\partial A[0][0]} + \lambda_1 * \frac{\partial z[1]}{\partial A[0][0]} + \lambda_2 * \frac{\partial z[2]}{\partial A[0][0]} $

$ \frac{\partial z}{\partial A[0][1]}  = \lambda_0 * \frac{\partial z[0]}{\partial A[0][1]} + \lambda_1 * \frac{\partial z[1]}{\partial A[0][1]} + \lambda_2 * \frac{\partial z[2]}{\partial A[0][1]} $

$ \vdots \qquad \qquad \vdots \qquad \qquad  \vdots $

$ \frac{\partial z}{\partial A[2][2]}  = \lambda_0 * \frac{\partial z[1]}{\partial A[2][2]} + \lambda_1 * \frac{\partial z[1]}{\partial A[2][2]} + \lambda_2 * \frac{\partial z[2]}{\partial A[2][2]} $


In [4]:
A.grad # 与A同型

tensor([[ 2.,  4.,  6.],
        [ 3.,  6.,  9.],
        [ 5., 10., 15.]])