In [4]:
import torch

In [5]:
s0 = torch.tensor([1.], requires_grad=True)  # s0为标量
s1 = torch.tensor([2.], requires_grad=True)

s2 = torch.add(s0, s1)
s2.retain_grad()

s3 = torch.add(s0, 1)

loss = torch.cat([s2, s3], dim=0)
grad_tensors = torch.tensor([2., 3.])  # 权重向量(与loss同形)
loss

tensor([3., 2.], grad_fn=<CatBackward>)

In [6]:
mind = torch.ones_like(loss)
loss.backward(gradient=grad_tensors)

print(s0.grad)  # loss[0]对s0的梯度*grad_tensors[0] + loss[1]对s0的梯度*grad_tensors[1]
print(s2.grad)  # loss[0]对s2的梯度*grad_tensors[0] + loss[1]对s2的梯度*grad_tensors[1]


tensor([5.])
tensor([2.])
