In [5]:
import torch

me = $\frac{1}{24} ( mat[0, 0] + mat[0, 1] + \cdots + mat[3, 4] + mat[3, 5]) $

In [6]:
mat = torch.arange(24, dtype=torch.float32).reshape(4, 6) # mat为矩阵
mat.requires_grad_(True)
me = mat.mean()
me.backward() # me对mat每个元素分别进行求导
print(mat.grad)

tensor([[0.0417, 0.0417, 0.0417, 0.0417, 0.0417, 0.0417],
        [0.0417, 0.0417, 0.0417, 0.0417, 0.0417, 0.0417],
        [0.0417, 0.0417, 0.0417, 0.0417, 0.0417, 0.0417],
        [0.0417, 0.0417, 0.0417, 0.0417, 0.0417, 0.0417]])


$ \mathbf{a} $ and $ \mathbf{b} $ are not functions of $ X $,$$ \frac{\partial \mathbf{a}^T X \mathbf{b}}{\partial X} = \mathbf{b} \mathbf{a}^T$$

In [7]:
mat0 = torch.arange(8, dtype=torch.float32).reshape(2, 4)
mat0.requires_grad_(True)
a_t = torch.tensor([[1., 2.]], requires_grad=True)
b = torch.tensor([[1.],
                  [2.],
                  [3.],
                  [4.]])

me0 = a_t @ mat0 @ b
me0.backward() # 分母布局
print(mat0.grad) # 与mat0同型

tensor([[1., 2., 3., 4.],
        [2., 4., 6., 8.]])


In [8]:
(b @ a_t).T # 分子布局转置即得分母布局

tensor([[1., 2., 3., 4.],
        [2., 4., 6., 8.]], grad_fn=<PermuteBackward>)