In [25]:
import torch

vec0 = torch.tensor([[1.],
                     [2.],
                     [3.]], requires_grad=True) # vec0为向量
vec1 = torch.tensor([[2., 4., 6.]], requires_grad=True)

re = vec0 @ vec1
weight = torch.ones_like(re)

re.backward(weight) # 与re同型

In [26]:
re

tensor([[ 2.,  4.,  6.],
        [ 4.,  8., 12.],
        [ 6., 12., 18.]], grad_fn=<MmBackward>)

In [27]:
# 与向量vs向量计算步骤相同
vec0.grad # 与vec0同型

tensor([[12.],
        [12.],
        [12.]])

In [28]:
vec1.grad

tensor([[6., 6., 6.]])

In [29]:
A = torch.tensor([[1, 2, 3],
                  [4, 5, 6]], requires_grad=True, dtype=torch.float32)
B = torch.tensor([[1, 1],
                  [2, 2],
                  [3, 3]], requires_grad=True, dtype=torch.float32)

C = A @ B
C.backward(torch.ones_like(C))
C

tensor([[14., 14.],
        [32., 32.]], grad_fn=<MmBackward>)

In [30]:
# 与向量vs矩阵计算步骤相同
A.grad

tensor([[2., 4., 6.],
        [2., 4., 6.]])

In [31]:
B.grad

tensor([[5., 5.],
        [7., 7.],
        [9., 9.]])