In [1]:
import torch

x = torch.linspace(0, 1, 10)
x

tensor([0.0000, 0.1111, 0.2222, 0.3333, 0.4444, 0.5556, 0.6667, 0.7778, 0.8889,
        1.0000])

In [2]:
# 完全类似numpy.sin/cos/tan
torch.sin(x)

tensor([0.0000, 0.1109, 0.2204, 0.3272, 0.4300, 0.5274, 0.6184, 0.7017, 0.7764,
        0.8415])

In [3]:
torch.cos(x)

tensor([1.0000, 0.9938, 0.9754, 0.9450, 0.9028, 0.8496, 0.7859, 0.7125, 0.6303,
        0.5403])

In [4]:
torch.tan(x)

tensor([0.0000, 0.1116, 0.2260, 0.3463, 0.4762, 0.6208, 0.7868, 0.9849, 1.2318,
        1.5574])