In [9]:
import torch

x = torch.linspace(0, 1, 10)
x

tensor([0.0000, 0.1111, 0.2222, 0.3333, 0.4444, 0.5556, 0.6667, 0.7778, 0.8889,
        1.0000])

### 完全类似numpy.sin/cos/tan

In [ ]:
torch.sin(x)

In [11]:
torch.cos(x)

tensor([1.0000, 0.9938, 0.9754, 0.9450, 0.9028, 0.8496, 0.7859, 0.7125, 0.6303,
        0.5403])

In [12]:
torch.tan(x)

tensor([0.0000, 0.1116, 0.2260, 0.3463, 0.4762, 0.6208, 0.7868, 0.9849, 1.2318,
        1.5574])