In [99]:
import torch

## 加法add

In [100]:
a = torch.tensor([1.])
b = torch.tensor([2.])
print(a + b)
print(torch.add(a, b))

tensor([3.])
tensor([3.])


## 减法sub

## 乘法mul

In [101]:
a = torch.tensor([1.])
b = torch.tensor([2.])
print(a * b)
print(torch.mul(a, b))

tensor([2.])
tensor([2.])


## 除法div

In [102]:
a = torch.tensor([-5, 5, 7, 9, -13])
b = torch.tensor([2, 3, 4, 2, 4])

print(torch.div(a, b))
print(a / b)

tensor([-2.5000,  1.6667,  1.7500,  4.5000, -3.2500])
tensor([-2.5000,  1.6667,  1.7500,  4.5000, -3.2500])


In [103]:
# 地板除法
print(torch.div(a, b, rounding_mode='floor'))
print(a // b)

tensor([-3,  1,  1,  4, -4])
tensor([-2,  1,  1,  4, -3])


In [104]:
a % b  # 取余(结果必大于0)

tensor([1, 2, 3, 1, 3])

In [105]:
print(a > b)
print(torch.gt(a, b))  # 与上等价

tensor([False,  True,  True,  True, False])
tensor([False,  True,  True,  True, False])


In [106]:
print(a >= b)
print(torch.ge(a, b))  # 与上等价

tensor([False,  True,  True,  True, False])
tensor([False,  True,  True,  True, False])


In [107]:
print(a < b)
print(torch.lt(a, b))  # 与上等价

tensor([ True, False, False, False,  True])
tensor([ True, False, False, False,  True])


In [108]:
print(a <= b)
print(torch.le(a, b))  # 与上等价

tensor([ True, False, False, False,  True])
tensor([ True, False, False, False,  True])


In [109]:
print(a == b)
print(torch.eq(a, b))  # 与上等价

tensor([False, False, False, False, False])
tensor([False, False, False, False, False])


In [110]:
a.equal(b)  # 所有元素是否相等;等价于torch.all(a.eq(b))

False

In [111]:
print(a != b)
print(torch.ne(a, b))  # 与上等价




tensor([True, True, True, True, True])
tensor([True, True, True, True, True])
