In [14]:
import  torch

## 加法add

In [15]:
a = torch.tensor([1.])
b = torch.tensor([2.])
print(a + b)
print(torch.add(a, b))
print(a)

tensor([3.])
tensor([3.])
tensor([1.])


## 减法sub

## 乘法mul

In [16]:
a = torch.tensor([1.])
b = torch.tensor([2.])
print(a * b)
print(torch.mul(a, b))
print(a)

tensor([2.])
tensor([2.])
tensor([1.])


## 除法div

In [17]:
a = torch.tensor([-5, 5, 7, 9, -13])
b = torch.tensor([2, 3, 4, 2, 4])

print(torch.div(a.to(torch.float32), b.to(torch.float32))) # ★★★★★真正的除法(必须需指定数据类型为浮点型)
print(a.to(torch.float32) / b.to(torch.float32)) # 与上等价

tensor([-2.5000,  1.6667,  1.7500,  4.5000, -3.2500])
tensor([-2.5000,  1.6667,  1.7500,  4.5000, -3.2500])


In [18]:
a // b # 地板除法

tensor([-2,  1,  1,  4, -3])

In [19]:
a % b # 取余(结果必大于0)

tensor([1, 2, 3, 1, 3])

In [20]:
print(a > b)
print(torch.gt(a, b)) # 与上等价

tensor([False,  True,  True,  True, False])
tensor([False,  True,  True,  True, False])


In [21]:
print(a >= b)
print(torch.ge(a, b)) # 与上等价

tensor([False,  True,  True,  True, False])
tensor([False,  True,  True,  True, False])


In [22]:
print(a < b)
print(torch.lt(a, b)) # 与上等价

tensor([ True, False, False, False,  True])
tensor([ True, False, False, False,  True])


In [23]:
print(a <= b)
print(torch.le(a, b)) # 与上等价

tensor([ True, False, False, False,  True])
tensor([ True, False, False, False,  True])


In [24]:
print(a == b)
print(torch.eq(a, b)) # 与上等价

tensor([False, False, False, False, False])
tensor([False, False, False, False, False])


In [25]:
a.equal(b) # 所有元素是否相等;等价于torch.all(a.eq(b))

False

In [26]:
print(a != b)
print(torch.ne(a, b)) # 与上等价




tensor([True, True, True, True, True])
tensor([True, True, True, True, True])
