In [7]:
import torch

### 参考numpy.power

In [8]:
x1 = torch.arange(6)

print(torch.pow(x1, 0.5))
print(torch.pow(x1, 1))
print(torch.pow(x1, 2))

tensor([0.0000, 1.0000, 1.4142, 1.7321, 2.0000, 2.2361])
tensor([0, 1, 2, 3, 4, 5])
tensor([ 0,  1,  4,  9, 16, 25])


In [9]:
print(x1 ** 3)
print(torch.pow(x1, 3))  # 与上等价

tensor([  0,   1,   8,  27,  64, 125])
tensor([  0,   1,   8,  27,  64, 125])


In [10]:
torch.pow(3, x1)  # 与3 ** x1等价

tensor([  1,   3,   9,  27,  81, 243])

In [11]:
x2 = torch.tensor([1, 2, 3, 3, 2, 1])
torch.pow(x1, x2)

tensor([ 0,  1,  8, 27, 16,  5])

In [12]:
x1 ** x2  # 与上等价

tensor([ 0,  1,  8, 27, 16,  5])