In [15]:
import torch

# 完全类似numpy.power
x1 = torch.arange(6)
print(torch.pow(x1, 1))
print(torch.pow(x1, 2))

tensor([0, 1, 2, 3, 4, 5])
tensor([ 0,  1,  4,  9, 16, 25])


In [16]:
torch.pow(x1, 3) # 与x1 ** 3等价

tensor([  0,   1,   8,  27,  64, 125])

In [17]:
torch.pow(3, x1) # 与3 ** x1等价

tensor([  1,   3,   9,  27,  81, 243])

In [18]:
x2 = torch.tensor([1, 2, 3, 3, 2, 1])
torch.pow(x1, x2)

tensor([ 0,  1,  8, 27, 16,  5])

In [19]:
x1 ** x2 # 与上等价

tensor([ 0,  1,  8, 27, 16,  5])