In [4]:
import torch
import numpy as np

# 完全类似numpy.sqrt
torch.sqrt(torch.tensor([1, 4, 9], dtype=torch.double))

tensor([1., 2., 3.], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [5]:
torch.sqrt(torch.tensor([4, -1.0, np.inf]))

tensor([2., nan, inf])

tensor([2., nan, inf])

In [6]:
torch.sqrt(torch.tensor(1 / 4))

tensor(0.5000)

tensor(0.5000)