In [1]:
import torch

In [2]:
a = torch.randn(2, 3, 4)
torch.var(a)

tensor(0.7020)

In [3]:
torch.var(a, dim=(1, 2))  # 注意:var函数dim参数也可以为元组;第0个维度上所有数据的方差(无偏)

tensor([0.3361, 1.1235])

In [4]:
torch.var(a, dim=(0, 1))

tensor([1.1218, 1.0891, 0.6497, 0.3500])

In [5]:
torch.var(a, dim=(0, 1), unbiased=False)  # whether to use the unbiased estimation or not(默认unbiases=True)

tensor([0.9349, 0.9076, 0.5414, 0.2917])

In [6]:
torch.var(a, dim=(0, 1), keepdim=True).shape  # 保留维度信息(进行广播时使用)



torch.Size([1, 1, 4])