In [1]:
import torch

a = torch.arange(32).reshape(2, 4, 4).to(torch.float32)
a

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.]],

        [[16., 17., 18., 19.],
         [20., 21., 22., 23.],
         [24., 25., 26., 27.],
         [28., 29., 30., 31.]]])

### 参考numpy.max/min

In [2]:
torch.max(a)

tensor(31.)

In [3]:
torch.max(a, dim=0)

torch.return_types.max(
values=tensor([[16., 17., 18., 19.],
        [20., 21., 22., 23.],
        [24., 25., 26., 27.],
        [28., 29., 30., 31.]]),
indices=tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]))

In [7]:
torch.max(a, dim=0).values

tensor([[16., 17., 18., 19.],
        [20., 21., 22., 23.],
        [24., 25., 26., 27.],
        [28., 29., 30., 31.]])

In [8]:
torch.max(a, dim=0).indices

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

In [4]:
torch.max(a, dim=0, keepdim=True)

torch.return_types.max(
values=tensor([[[16., 17., 18., 19.],
         [20., 21., 22., 23.],
         [24., 25., 26., 27.],
         [28., 29., 30., 31.]]]),
indices=tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]]))

In [5]:
torch.min(a)

tensor(0.)

In [6]:
torch.min(a, dim=1)


torch.return_types.min(
values=tensor([[ 0.,  1.,  2.,  3.],
        [16., 17., 18., 19.]]),
indices=tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]]))