In [1]:
import torch

In [2]:
a = torch.randn(2, 3, 4)
torch.std(a)

tensor(0.6255)

In [3]:
torch.std(a, dim=(1, 2))  # 注意:std函数dim参数也可以为元组;第0个维度上所有数据的标准差(无偏)

tensor([0.4629, 0.7749])

In [4]:
torch.std(a, dim=(0, 1))

tensor([0.6802, 0.4569, 0.3747, 0.7047])

In [5]:
torch.std(a, dim=(0, 1), unbiased=False)  # whether to use the unbiased estimation or not(默认unbiases=True)

tensor([0.6210, 0.4171, 0.3420, 0.6433])

In [6]:
torch.std(a, dim=(0, 1), keepdim=True).shape  # 保留维度信息(进行广播时使用)


torch.Size([1, 1, 4])