In [31]:
import torch

### 参考numpy.sum/cumsum

In [32]:
print(torch.sum(torch.tensor([0.5, 0.7, 0.2, 1.5])))  # 求和
print(torch.cumsum(torch.tensor([0.5, 0.7, 0.2, 1.5]), dim=0))  # 累和

tensor(2.9000)
tensor([0.5000, 1.2000, 1.4000, 2.9000])


In [33]:
a = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])
print(torch.sum(a))
print(torch.cumsum(a, dim=0))  # 必须指定dim

tensor(21)
tensor([[1, 2, 3],
        [5, 7, 9]])


In [34]:
print(torch.sum(a, dim=0))  # 列和
print(torch.cumsum(a, dim=1))

tensor([5, 7, 9])
tensor([[ 1,  3,  6],
        [ 4,  9, 15]])


In [35]:
print(torch.cumsum(a.flatten(), dim=0))

tensor([ 1,  3,  6, 10, 15, 21])


In [36]:
a = torch.randn(2, 1, 3)
torch.sum(a, dim=(1, 2))  # 注意:dim参数也可以为元组;第0个维度所有数据的和


tensor([3.2034, 0.6086])

In [37]:
print(a[0, 0, 0] + a[0, 0, 1] + a[0, 0, 2])
print(a[1, 0, 0] + a[1, 0, 1] + a[1, 0, 2])  # 与上等价

tensor(3.2034)
tensor(0.6086)
