Clamp all elements in input into the range [ min, max ] and return a resulting tensor:

\begin{equation}
y_i=\begin{cases}
	    \min, & \text{if} \quad  x < \min \\
        x_i, & \text{if} \quad  \min< x < \max \\
        \max, & \text{if} \quad x> \max
     \end{cases}
\end{equation}

In [12]:
import torch

grad = torch.rand(4, 4) * 15
print(torch.max(grad))
print(torch.min(grad))

tensor(13.2107)
tensor(0.1804)


In [13]:
grad

tensor([[ 5.1421, 10.2116,  5.7492,  0.7315],
        [ 1.8783,  6.9327,  9.9200,  7.9928],
        [ 4.6797,  8.8012,  7.7973, 11.7521],
        [ 2.9439,  0.1804,  4.0468, 13.2107]])

In [14]:
torch.clamp(grad, min=6)

tensor([[ 6.0000, 10.2116,  6.0000,  6.0000],
        [ 6.0000,  6.9327,  9.9200,  7.9928],
        [ 6.0000,  8.8012,  7.7973, 11.7521],
        [ 6.0000,  6.0000,  6.0000, 13.2107]])

In [15]:
torch.clamp(grad, max=6)

tensor([[5.1421, 6.0000, 5.7492, 0.7315],
        [1.8783, 6.0000, 6.0000, 6.0000],
        [4.6797, 6.0000, 6.0000, 6.0000],
        [2.9439, 0.1804, 4.0468, 6.0000]])

In [16]:
torch.clamp(grad, min=6, max=7)

tensor([[6.0000, 7.0000, 6.0000, 6.0000],
        [6.0000, 6.9327, 7.0000, 7.0000],
        [6.0000, 7.0000, 7.0000, 7.0000],
        [6.0000, 6.0000, 6.0000, 7.0000]])