In [14]:
import torch


a = torch.full((8, ), 1)
b = a.reshape(2, 4)
c = a.reshape(2, 2, 2)
print(a)
print(b)
print(c)

tensor([1., 1., 1., 1., 1., 1., 1., 1.])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])


In [15]:
# 完全类似numpy.linalg.norm
print(torch.norm(a, 1)) # L_1范数;p=1
print(torch.norm(b, 1))
print(torch.norm(c, 1))

tensor(8.)
tensor(8.)
tensor(8.)


In [16]:
print(torch.norm(a, p=2)) # 默认p='fro';Frobenisu范数;p=2
print(torch.norm(b))
print(torch.norm(c))

tensor(2.8284)
tensor(2.8284)
tensor(2.8284)


In [17]:
import numpy as np

a1 = torch.arange(8, dtype=torch.double)
b1 = a1.reshape(2, 4)
c1 = a1.reshape(2, 2, 2)
print(torch.norm(a1, p=np.inf)) # 最大范数;p=np.inf
print(torch.norm(b1, p=np.inf))
print(torch.norm(c1, p=np.inf))

tensor(7., dtype=torch.float64)
tensor(7., dtype=torch.float64)
tensor(7., dtype=torch.float64)


In [18]:
matrix = torch.tensor([[ 1, 2, 3],
                       [-1, 1, 4]], dtype=torch.double)
torch.norm(matrix, dim=0) # 计算指定维度上的范数(默认dim=None)

tensor([1.4142, 2.2361, 5.0000], dtype=torch.float64)

In [19]:
a = torch.randn(2, 3, 4)
torch.norm(a, p=2, dim=(1, 2)) # 注意:norm函数dim参数可以为元组;第0个维度所有数据的范数

tensor([3.4364, 3.5918])