In [8]:
import torch

### 参考numpy.all/any/logical_not/logical_and/logical_or

In [ ]:
torch.all(torch.tensor([[True, False], [True, True]]))  # 所有元素为True时才返回True

In [12]:
torch.all(torch.tensor([[True, False],
                        [True, True]]), dim=1)  # 指定轴axis

tensor([False,  True])

In [13]:
torch.any(torch.tensor([[True, False],
                        [True, True]]))  # 所有元素为False才返回False

tensor(True)

In [15]:
torch.any(torch.tensor([[True, False],
                        [True, True]]), dim=0)

tensor([True, True])

In [16]:
tor = torch.tensor([[True, -2.3],
                    [0, 0]])
torch.any(tor, dim=1)  # 除Ture/False还可以为数值型(0为False,其他为True)

tensor([ True, False])

In [18]:
torch.logical_not(torch.tensor(3))  # 转换x的真假

tensor(False)

In [19]:
torch.logical_not(torch.tensor(False))

tensor(True)

In [20]:
torch.logical_not(torch.tensor([True, False, 0, 1]))

tensor([False,  True,  True, False])

In [21]:
# Computes the element-wise logical AND of the given input tensors.
# Zeros are treated as False and nonzeros are treated as True.
torch.logical_and(torch.tensor(True), torch.tensor(False))

tensor(False)

In [23]:
torch.all(torch.tensor([[33, False, True],
                        [True, 0, True]]), dim=0)

tensor([ True, False,  True])

In [24]:
torch.logical_and(torch.tensor([33, False, True]),
                  torch.tensor([True, 0, True]))  # 与上等价

tensor([ True, False,  True])

In [ ]:
# Computes the element-wise logical OR of the given input tensors.
# Zeros are treated as False and nonzeros are treated as True.
torch.logical_or(torch.tensor([True, False]),
                 torch.tensor([0, False]))


