## 标量 $ \times $ 标量 

In [275]:
import numpy as np

scalar1 = np.array(3) # 可以看作一个数(number)
scalar2 = np.array(4)

print(scalar1 * scalar2) # 等价于 3 * 4

12


## 标量 $ \times $ 向量

In [276]:
vector1 = np.array([1, 2, 3, 4])
print(scalar1 * vector1) # 等价于3 * vector1(广播)

[ 3  6  9 12]


## 标量 $ \times $ 矩阵

In [277]:
martrix1 = np.array([[1, 2, 3, 4], [2, 3, 4, 5]])
print(scalar1 * martrix1) # 等价于 3 * martrix1(广播)

[[ 3  6  9 12]
 [ 6  9 12 15]]


## 向量 $ \times @ $ 向量

In [278]:
vector1 = np.array([1, 2, 3, 4])
vector2 = np.array([2, 3, 4, 5])
vector1 * vector2 # 对应元素相乘

array([ 2,  6, 12, 20])

In [279]:
vector1 @ vector2 # ★★★★★向量的内积(点积)

40

In [280]:
np.dot(vector1, vector2) # 于上等价

40

In [281]:
vector1.reshape(4, 1) @ vector2.reshape(1, 4) # [4, 1] @ [1, 4] --> [4, 4](矩阵代数)

array([[ 2,  3,  4,  5],
       [ 4,  6,  8, 10],
       [ 6,  9, 12, 15],
       [ 8, 12, 16, 20]])

## 向量 $ \times @ $ 矩阵

In [282]:
martrix1 = np.array([[1, 2, 3, 4],
                     [2, 3, 4, 5]])
print(vector1 * martrix1) # 广播机制[2, 4] broadcasting [4] --> [2, 4]
print(martrix1 * vector1) # 可交换顺序

[[ 1  4  9 16]
 [ 2  6 12 20]]
[[ 1  4  9 16]
 [ 2  6 12 20]]


In [283]:
np.array([1, 2]) @ martrix1 # [2] @ [2, 4] --> [4]

array([ 5,  8, 11, 14])

In [284]:
martrix1 @ vector1 # [2, 4] @ [4] --> [2]

array([30, 40])

In [285]:
np.dot(martrix1, vector1) # 于上等价

array([30, 40])

In [286]:
martrix1 @ vector1.reshape(4, 1) # [2, 4] @ [4, 1] --> [2, 1](矩阵代数)

array([[30],
       [40]])

## 矩阵 $ \times @ $ 矩阵

In [287]:
martrix1 = np.array([[1, 2, 3, 4],
                     [2, 3, 4, 5]])
martrix2 = np.array([[0, 0, 0, 0],
                     [1, 1, 1, 1]])

martrix1 * martrix2 # 对应元素相乘

array([[0, 0, 0, 0],
       [2, 3, 4, 5]])

In [288]:
martrix1 @ martrix2.reshape(4, 2) # 必须满足矩阵代数运算法则

array([[7, 7],
       [9, 9]])

In [289]:
np.dot(martrix1, martrix2.reshape(4, 2))

array([[7, 7],
       [9, 9]])

### 高维矩阵 @ 高维矩阵

In [290]:
a = np.random.randn(4, 3, 5, 28, 64)
b = np.random.randn(4, 3, 5, 64, 32)

In [291]:
out = a @ b
# [4, 3, 5, 28, 64] @ [4, 3, 5, 64, 32] -->
# 1. [4, 3, 5] 不变
# 2. [28, 64] @ [64, 32] --> [28, 64]
# 3. [4, 3, 5, 28, 64]
out.shape

(4, 3, 5, 28, 32)

In [292]:
c = np.random.randn(4, 1, 5, 64, 32)
# [4, 3, 5, 28, 64] @ [4, 1, 5, 64, 32] -->
# 1. [4, 3, 5] broadcasting [4, 1, 5] --> [4, 3, 5]
# 2. [28, 64] @ [64, 32] --> [28, 64]
# 3. [4, 3, 5, 28, 64]
out1 = a @ c
out1.shape

(4, 3, 5, 28, 32)

In [293]:
a1 = np.random.randn(4, 1, 5, 28, 64)
b1 = np.random.randn(1, 3, 1, 64, 32)
# [4, 1, 5, 28, 64] @ [1, 3, 1, 64, 32] -->
# 1. [4, 1, 5] broadcasting [1, 3, 1] --> [4, 3, 5]
# 2. [28, 64] @ [64, 32] --> [28, 64]
# 3. [4, 3, 5, 28, 64]
out2 = a1 @ b1
out2.shape

(4, 3, 5, 28, 32)

In [294]:
np.dot(a1, b1).shape # 不再等价于a1 @ b1

(4, 1, 5, 28, 1, 3, 1, 32)