In [20]:
import numpy as np

arr_scalar_vetor = np.array(10, ndmin=1) # 标量转向量(法一)
arr_scalar_vetor.shape

(1,)

In [21]:
arr_scalar_vetor1 = np.array(10).reshape(1) # 标量转向量(法二)
arr_scalar_vetor1.shape

(1,)

In [22]:
arr_scalar_matrix = np.array(10, ndmin=2) # 标量转矩阵(法一)
arr_scalar_matrix.shape

(1, 1)

In [23]:
arr_scalar_matrix1 = np.array(10).reshape(1, 1) # 标量转矩阵(法二)
print(arr_scalar_matrix.shape) # (0维度尺寸=1, 1维度尺寸=1)
print(arr_scalar_matrix)

(1, 1)
[[10]]


In [24]:
arr_vector_matrix = np.array([1, 2, 3], ndmin=2) # 向量转矩阵(法一)
print(arr_vector_matrix.shape) # (0维度尺寸=1, 1维度尺寸=3)--->数学中的行向量
print(arr_vector_matrix)

(1, 3)
[[1 2 3]]


In [25]:
arr_vector_matrix1 = np.array([1, 2, 3]).reshape(1, 3) # 向量转矩阵(法二)
print(arr_vector_matrix1.shape) # (0维度尺寸=1, 1维度尺寸=3)--->数学中的行向量
print(arr_vector_matrix1)

(1, 3)
[[1 2 3]]


In [26]:
arr_vector_mul_matrix = np.array([1, 2, 3]).reshape(1, 1, 3, 1, 1) # 高维矩阵
arr_vector_mul_matrix


array([[[[[1]],

         [[2]],

         [[3]]]]])