## 标量/scalar 

In [14]:
import numpy as np

arr_scalar = np.array(10)  # 标量
print(arr_scalar.ndim)
print(arr_scalar.shape)  # 空元组
print(arr_scalar)

0
()
10


## 向量/vector

In [15]:
arr_vector = np.array([1, 2, 3])  # 向量
print(arr_vector.ndim)
print(arr_vector.shape)  # 长度为1的元组
print(arr_vector)

1
(3,)
[1 2 3]


## 矩阵/matrix

In [16]:
arr_matrix = np.array([[1, 2, 3], [2, 3, 4]]) # 矩阵
print(arr_matrix.ndim)
print(arr_matrix.shape)  # 输出为:(行数, 列数)
print(arr_matrix)

2
(2, 3)
[[1 2 3]
 [2 3 4]]


### 高维矩阵(ndim>2)

In [17]:
arr_mul_matrix = np.random.randn(3, 4, 5)
print(arr_mul_matrix.ndim)
print(arr_mul_matrix.shape)
print(arr_mul_matrix)

3
(3, 4, 5)
[[[ 0.63201006  2.35831735 -1.4056994  -1.66322055  0.12468708]
  [ 1.97390402  0.42922964 -1.73112589 -0.38238639  1.64083322]
  [-1.03577388 -0.56260722 -0.68168757  0.20616621  1.33441103]
  [ 0.98832371  1.17020736 -1.72192084  1.27104512  0.02165582]]

 [[-0.22096697 -1.95855045 -0.58741141  0.42364186  2.47236466]
  [ 1.02467909  0.28300463 -0.34994283 -0.09365585 -0.35852483]
  [ 0.95551694  0.9477239  -0.68715749 -1.07265874 -1.42384115]
  [ 0.58984722 -0.2231434  -1.33115613 -0.4342241   1.2654945 ]]

 [[-0.10136997  0.59096891 -0.09312857  1.16756045  2.10909585]
  [-1.05648981  0.03790472  0.97042993 -1.14533909 -1.40218192]
  [ 1.0706974  -0.77192948 -0.97344353  0.03300498 -0.0834474 ]
  [-0.01833848  0.82374045  0.22742704  0.40525311 -0.61637072]]]
