## 标量/scalar 

In [1]:
import numpy as np

arr_scalar = np.array(10)  # 标量
print(arr_scalar.ndim)
print(arr_scalar.shape)  # 空元组
print(arr_scalar)

0
()
10


## 向量/vector

In [2]:
arr_vector = np.array([1, 2, 3])  # 向量
print(arr_vector.ndim)
print(arr_vector.shape)  # 长度为1的元组
print(arr_vector)

1
(3,)
[1 2 3]


## 矩阵/matrix

In [3]:
arr_matrix = np.array([[1, 2, 3], [2, 3, 4]])  # 矩阵
print(arr_matrix.ndim)
print(arr_matrix.shape)  # 输出为:(行数, 列数)
print(arr_matrix)

2
(2, 3)
[[1 2 3]
 [2 3 4]]


### 高维矩阵(ndim>2)

In [4]:
arr_mul_matrix = np.random.randn(3, 4, 5)
print(arr_mul_matrix.ndim)
print(arr_mul_matrix.shape)
print(arr_mul_matrix)

3
(3, 4, 5)
[[[-7.62794717e-01 -5.35980154e-01 -1.16266031e+00 -4.15661740e-01
    7.96767871e-01]
  [ 1.48125790e-01 -2.88769727e-01 -1.42446423e+00 -9.13251350e-01
    1.29086102e+00]
  [-8.84309965e-01  9.20351290e-01  3.26244313e-01 -8.32744218e-01
   -1.11012725e+00]
  [ 7.53834211e-01 -9.75819857e-01  6.27811392e-01  3.93740127e-01
   -2.55775327e+00]]

 [[ 1.46662007e+00 -3.68799663e-01  1.47802670e-01  1.81125034e+00
    5.00763041e-01]
  [ 8.18479327e-01 -1.00932418e+00  1.64906143e-01 -7.83190810e-01
   -1.66920732e+00]
  [-1.34171294e+00  4.00638540e-01  1.28945530e+00 -9.31681649e-01
    3.21086558e-01]
  [ 1.95599085e+00  8.57323137e-01 -2.42234106e-01  1.62389856e-03
   -1.18853377e+00]]

 [[-1.49779846e-01 -2.06278296e+00  3.18311055e-01  6.71170588e-01
    2.69539065e-01]
  [-1.35706885e+00 -3.04418398e-01 -6.28064967e-01  9.12818264e-01
   -7.57542572e-01]
  [ 1.76243911e+00 -1.37194007e+00 -1.76442543e-02 -3.44045799e-01
    5.81944516e-01]
  [ 8.72793172e-01  7.75855