## 换底公式
$$ log_{a}^{b} = \frac{log_{c}^{b}}{log_{c}^{a}}$$

In [29]:
import torch
import numpy as np

# 完全类似numpy.log/log2/log10
torch.log(torch.tensor([1, np.e, np.e**2, 0])) # e为底

tensor([0., 1., 2., -inf])

In [30]:
a = torch.tensor([1, 10, 10**2, 0], dtype=torch.double)
torch.log2(a) # 2为底

tensor([0.0000, 3.3219, 6.6439,   -inf], dtype=torch.float64)

In [31]:
torch.log10(torch.tensor([1.0, 10.0, 10.0**2, 0.0], dtype=torch.double)) # 10为底

tensor([0., 1., 2., -inf], dtype=torch.float64)

In [32]:
torch.log(torch.tensor([1.0, 4.0, 4.0**2, 0.0]))/np.log(4.0) # 4为底(由换底公式)

tensor([0., 1., 2., -inf])