In [12]:
import torch

# 类似numpy.prod/cumprod
print(torch.prod(torch.tensor([0.5, 0.7, 0.2, 1.5]))) # 求和
print(torch.cumprod(torch.tensor([0.5, 0.7, 0.2, 1.5]), dim=0)) # 累和

tensor(0.1050)
tensor([0.5000, 0.3500, 0.0700, 0.1050])


In [13]:
a = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])
print(torch.prod(a))
print(torch.cumprod(a, dim=0)) # 必须指定dim

tensor(720)
tensor([[ 1,  2,  3],
        [ 4, 10, 18]])


In [14]:
print(torch.cumprod(a, dim=1))

tensor([[  1,   2,   6],
        [  4,  20, 120]])


In [15]:
print(torch.cumprod(a.flatten(), dim=0))


tensor([  1,   2,   6,  24, 120, 720])
