In [25]:
import torch

In [26]:
# 完全类似numpy.all/any/logical_not
torch.all(torch.tensor([[True, False], [True, True]])) # 所有元素为True时才返回True

tensor(False)

In [27]:
torch.all(torch.tensor([[True, False], [True, True]]), dim=0) # 指定维度dim

tensor([ True, False])

In [28]:
torch.any(torch.tensor([[True, False], [True, True]])) # 所有元素为False才返回False

tensor(True)

In [29]:
torch.any(torch.tensor([[True, False], [True, True]]), dim=0)

tensor([True, True])

In [30]:
tor = torch.tensor([[True, -2],
                   [0, False]])
tor

tensor([[ 1, -2],
        [ 0,  0]])

In [31]:
torch.logical_not(tor) # 转换tor的真假(0为False,其他为True)



tensor([[False, False],
        [ True,  True]])