In [130]:
import catboost as cat
import pandas as pd
from sklearn import datasets
from sklearn.model_selection import train_test_split
import numpy as np

In [131]:
X = datasets.fetch_covtype().data[:3000]
y = datasets.fetch_covtype().target[:3000]
X_train, X_test, y_train, y_test = train_test_split(X, y)

print(X_train.shape)
print(y_train.shape)
print(np.unique(y_train))  # 7分类任务

(2250, 54)
(2250,)
[1 2 3 4 5 6 7]


In [132]:
weight = 1 / np.sqrt(y_train)
weight

array([1.        , 0.40824829, 0.37796447, ..., 0.37796447, 0.70710678,
       0.70710678])

In [133]:
X_train = pd.DataFrame(X_train)
X_train = X_train.astype(np.int32)
X_train


0    1   2    3    4     5    6    7    8     9   ...  44  45  46  47  \
0     3218   67  17   60   22  2711  235  203   94  2711  ...   0   0   0   0   
1     2641  312  26  210   82  1084  142  211  205   648  ...   0   0   1   0   
2     3237  101   8   95   23  2486  235  229  126  2823  ...   0   0   0   0   
3     2860  332   5  485  105  1964  209  234  163  2905  ...   0   0   0   0   
4     2892   48  23  150   51  4337  222  183   85  1140  ...   0   0   0   0   
...    ...  ...  ..  ...  ...   ...  ...  ...  ...   ...  ...  ..  ..  ..  ..   
2245  2651  297  32  180   84  1260  115  211  227   837  ...   0   0   1   0   
2246  2921   70  18   60   -3   553  237  203   91  2384  ...   0   0   0   0   
2247  3312   86  13   60   12  2256  239  217  107  2766  ...   0   0   0   0   
2248  2954  156  10  301   79  4308  232  242  141  1657  ...   0   0   0   0   
2249  2828   31  32  534  239  1271  194  152   75   743  ...   0   0   1   0   

      48  49  50  51  52  53  
0      0   0   0   0   0   0  
1      0   0   0   0   0   0  
2      0   0   0   0   0   0  
3      0   0   0   0   0   0  
4      0   0   0   0   0   0  
...   ..  ..  ..  ..  ..  ..  
2245   0   0   0   0   0   0  
2246   0   0   0   0   0   0  
2247   0   0   0   0   1   0  
2248   0   0   0   0   0   0  
2249   0   0   0   0   0   0  

[2250 rows x 54 columns]

In [134]:
train_dataset = cat.Pool(data=X_train.values,
                         cat_features=[2],
                         label=y_train,
                         # The weight of each object in the input data in the form of a one-dimensional array-like data.
                         # By default, it is set to 1 for all objects.
                         weight=weight)

In [135]:
# return the shape of the dataset.
train_dataset.shape

(2250, 54)

In [136]:
# Return the value of the label assigned to the input data.
train_dataset.get_label()

array([1, 6, 7, ..., 7, 2, 2])

In [137]:
# Return the list of weights for each object of the dataset.
train_dataset.get_weight()

[1.0,
 0.40824830532073975,
 0.37796446681022644,
 0.7071067690849304,
 0.7071067690849304,
 0.5773502588272095,
 0.4472135901451111,
 0.4472135901451111,
 0.5,
 1.0,
 0.7071067690849304,
 1.0,
 0.7071067690849304,
 0.7071067690849304,
 1.0,
 1.0,
 0.4472135901451111,
 0.5,
 0.7071067690849304,
 0.4472135901451111,
 0.4472135901451111,
 0.5773502588272095,
 1.0,
 0.5773502588272095,
 0.7071067690849304,
 0.4472135901451111,
 0.7071067690849304,
 0.4472135901451111,
 1.0,
 0.5,
 0.4472135901451111,
 0.4472135901451111,
 0.7071067690849304,
 1.0,
 0.5,
 0.7071067690849304,
 1.0,
 0.7071067690849304,
 0.40824830532073975,
 0.7071067690849304,
 0.5773502588272095,
 0.37796446681022644,
 0.7071067690849304,
 0.4472135901451111,
 0.37796446681022644,
 0.7071067690849304,
 0.7071067690849304,
 0.5773502588272095,
 0.5773502588272095,
 1.0,
 0.5,
 1.0,
 0.7071067690849304,
 0.4472135901451111,
 0.7071067690849304,
 0.40824830532073975,
 0.4472135901451111,
 0.5,
 0.37796446681022644,
 0.447213