In [121]:
import numpy as np

In [122]:
arr = np.arange(24).reshape(2, 3, 4)
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [123]:
print(arr[:, 0, :])
print(arr[:, 1, :])
print(arr[:, 2, :])

[[ 0  1  2  3]
 [12 13 14 15]]
[[ 4  5  6  7]
 [16 17 18 19]]
[[ 8  9 10 11]
 [20 21 22 23]]


In [124]:
print(np.sum(arr, axis=1).shape)  # print->(2, 4) 
print(np.sum(arr, axis=1)) 
# 分析:
# 1.获取arr axis=1上的所有索引数组
# 2.所有索引数组求和(axis=1消失)
print(arr[:, 0, :] + arr[:, 1, :] + arr[:, 2, :])  # 与上等价

(2, 4)
[[12 15 18 21]
 [48 51 54 57]]
[[12 15 18 21]
 [48 51 54 57]]


In [125]:
print(np.cumsum(arr, axis=1).shape)  # print->(2, 3, 4) 
print(np.cumsum(arr, axis=1)) 
# 分析:
# 1. 获取arr axis=1上的所有索引数组
# 2. 第一次累乘: arr[:, 0, :]
# 3. 第二次累乘: arr[:, 0, :] + arr[:, 1, :]
# 4. 第三次累乘: arr[:, 0, :] + arr[:, 1, :] + arr[:, 2, :]
# 5. 重新在axis=1上堆叠(axis=1不消失)
print(np.stack((arr[:, 0, :], arr[:, 0, :] + arr[:, 1, :], arr[:, 0, :] + arr[:, 1, :] + arr[:, 2, :]), axis=1))  # 与上等价

(2, 3, 4)
[[[ 0  1  2  3]
  [ 4  6  8 10]
  [12 15 18 21]]

 [[12 13 14 15]
  [28 30 32 34]
  [48 51 54 57]]]
[[[ 0  1  2  3]
  [ 4  6  8 10]
  [12 15 18 21]]

 [[12 13 14 15]
  [28 30 32 34]
  [48 51 54 57]]]
