In [44]:
import numpy as np

In [45]:
np.save('data/123', np.array([[1, 2, 3],
                              [4, 5, 6]]))

In [46]:
np.load('data/123.npy')

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([1, 2])
np.savez('data/456.npz', a=a, b=b)  # 保存多个array

In [48]:
data = np.load('data/456.npz')
data  # NpzFile类型(类似字典的对象)

In [49]:
dict(data)

{'a': array([[1, 2, 3],
        [4, 5, 6]]),
 'b': array([1, 2])}

In [50]:
# 通过字典的方式读取
data['a']

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
data['b']

array([1, 2])