In [1]:
%matplotlib
import numpy as np

nx, ny = (3, 4)
x = np.linspace(0, 1, nx)
y = np.linspace(0, 2, ny)
xv, yv = np.meshgrid(x, y, indexing='xy') # Return coordinate matrices from coordinate vectors.
'''
x1, x2,…, xn : array_like
    1-D arrays representing the coordinates of a grid.
    
indexing : {‘xy’, ‘ij’}, optional
    Cartesian (‘xy’, default) or matrix (‘ij’) indexing of output. 
'''
print(xv)
print(yv)

Using matplotlib backend: Qt5Agg
[[0.  0.5 1. ]
 [0.  0.5 1. ]
 [0.  0.5 1. ]
 [0.  0.5 1. ]]
[[0.         0.         0.        ]
 [0.66666667 0.66666667 0.66666667]
 [1.33333333 1.33333333 1.33333333]
 [2.         2.         2.        ]]


In [2]:
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
 
x = np.arange(-5, 5, 0.1)
y = np.arange(-5, 5, 0.1)
xx, yy = np.meshgrid(x, y )  # 转换成二维的矩阵坐标
print(xx)
print(yy)
 
fig = plt.figure(1, figsize=(12, 8))
zz =  (xx**2 + yy**2)
print(zz)
ax = fig.add_subplot(2, 2, 1, projection='3d')
ax.set_top_view()
 
ax.plot_surface(xx, yy, zz, rstride=1, cstride=1, cmap='rainbow')
plt.show()

[[-5.  -4.9 -4.8 ...  4.7  4.8  4.9]
 [-5.  -4.9 -4.8 ...  4.7  4.8  4.9]
 [-5.  -4.9 -4.8 ...  4.7  4.8  4.9]
 ...
 [-5.  -4.9 -4.8 ...  4.7  4.8  4.9]
 [-5.  -4.9 -4.8 ...  4.7  4.8  4.9]
 [-5.  -4.9 -4.8 ...  4.7  4.8  4.9]]
[[-5.  -5.  -5.  ... -5.  -5.  -5. ]
 [-4.9 -4.9 -4.9 ... -4.9 -4.9 -4.9]
 [-4.8 -4.8 -4.8 ... -4.8 -4.8 -4.8]
 ...
 [ 4.7  4.7  4.7 ...  4.7  4.7  4.7]
 [ 4.8  4.8  4.8 ...  4.8  4.8  4.8]
 [ 4.9  4.9  4.9 ...  4.9  4.9  4.9]]
[[50.   49.01 48.04 ... 47.09 48.04 49.01]
 [49.01 48.02 47.05 ... 46.1  47.05 48.02]
 [48.04 47.05 46.08 ... 45.13 46.08 47.05]
 ...
 [47.09 46.1  45.13 ... 44.18 45.13 46.1 ]
 [48.04 47.05 46.08 ... 45.13 46.08 47.05]
 [49.01 48.02 47.05 ... 46.1  47.05 48.02]]
