## numpy.random.seed
seed()用于指定随机数生成时所用算法开始的整数值
1. 如果使用相同的seed()值，则每次生成的随机数都相同    
2. 如果不设置这个值,则系统根据时间来自己选择这个值,此时每次生成的随机数因时间差异而不同

In [16]:
from numpy import  random
import numpy as np

num = 0
while num < 5:
  random.seed(5)
  print(random.random())
  num += 1

0.22199317108973948
0.22199317108973948
0.22199317108973948
0.22199317108973948
0.22199317108973948


In [17]:
num = 0
random.seed(5)
while num < 5:
  print(random.random())
  num += 1

0.22199317108973948
0.8707323061773764
0.20671915533942642
0.9186109079379216
0.48841118879482914


In [18]:
print("1-----------")
np.random.seed(1)
i = 0
while i < 5:
    print("输出：" + str(np.random.randn(1)))
    i += 1
    
print("0-----------")
np.random.seed(0)
i = 0
while i < 5:
    print("输出：" + str(np.random.randn(1)))
    i += 1
    
print("1-----------")
i = 0
np.random.seed(1)
while i < 2:
    print("输出：" + str(np.random.randn(1, 5)))
    i += 1
    
print("0-------------")
np.random.seed(0)
i = 0
while i < 3:
    print("输出：" + str(np.random.randn(1,2)))
    i += 1

1-----------
输出：[1.62434536]
输出：[-0.61175641]
输出：[-0.52817175]
输出：[-1.07296862]
输出：[0.86540763]
0-----------
输出：[1.76405235]
输出：[0.40015721]
输出：[0.97873798]
输出：[2.2408932]
输出：[1.86755799]
1-----------
输出：[[ 1.62434536 -0.61175641 -0.52817175 -1.07296862  0.86540763]]
输出：[[-2.3015387   1.74481176 -0.7612069   0.3190391  -0.24937038]]
0-------------
输出：[[1.76405235 0.40015721]]
输出：[[0.97873798 2.2408932 ]]
输出：[[ 1.86755799 -0.97727788]]


## numpy.random.RandomState
&emsp;&emsp;numpy.random中的数据生成函数共用了一个全局的随机数种子.为了避免全局状态可以
使用numpy.random.RandomState生成一个随机数生成器,使数据独立于其他随机数状态

In [19]:
for i in [1,2,3,4]:
    rng = np.random.RandomState(23455)
    arrayA = rng.uniform(0, 1, (2, 3))
    print(arrayA)

[[0.83494319 0.11482951 0.66899751]
 [0.46594987 0.60181666 0.58838408]]
[[0.83494319 0.11482951 0.66899751]
 [0.46594987 0.60181666 0.58838408]]
[[0.83494319 0.11482951 0.66899751]
 [0.46594987 0.60181666 0.58838408]]
[[0.83494319 0.11482951 0.66899751]
 [0.46594987 0.60181666 0.58838408]]


In [20]:
for i in [1,2,3,4]:
    rng = np.random.RandomState(23455+i)
    arrayA = rng.uniform(0, 1, (2, 3)) 
    print('i = %s' % i)
    print(arrayA)    


i = 1
[[0.32180029 0.32730047 0.92742231]
 [0.31169778 0.16195411 0.36407808]]
i = 2
[[0.81337698 0.42911854 0.67314798]
 [0.23028294 0.35855031 0.22392573]]
i = 3
[[0.2709679  0.49933797 0.80771214]
 [0.92140866 0.34157794 0.9903834 ]]
i = 4
[[0.78487022 0.76004529 0.29867001]
 [0.80117314 0.98157647 0.68529413]]
