In [53]:
import tensorflow as tf

### 参考numpy.einsum

In [54]:
A = tf.reshape(tf.range(25), (5, 5))
A

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])>

In [55]:
# 全部元素求和
tf.einsum('ij->', A) # \sum_{i,j} A_{i,j}

<tf.Tensor: shape=(), dtype=int32, numpy=300>

In [56]:
# 矩阵的迹
# \sum_{i,j} A_{i,i}
# 即:\sum_{i} A_{i,j}
tf.einsum('ii->', A)

<tf.Tensor: shape=(), dtype=int32, numpy=60>

In [57]:
# 某一维度求和
# \sum_j A_{i=0,j}, \sum_j A_{i=1,j}, \sum_j A_{i=2,j}, ......
tf.einsum('ij->i', A)  # 保留维度i

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 10,  35,  60,  85, 110])>

In [58]:
# 提取对角线
# \sum_{j} A_{i,i}
# 即:A_{0,0}, A_{1,1}, A_{2,2}, ......
tf.einsum('ii->i', A)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 0,  6, 12, 18, 24])>

In [59]:
# 转置
# B_{i,j} = A_{j, i}
B = tf.einsum('ij->ji', A)
B

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[ 0,  5, 10, 15, 20],
       [ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24]])>

In [60]:
x = tf.range(5)
y = tf.range(5)
tf.print(x)
tf.print(y)

# 向量内积
tf.print(tf.einsum('i,i->', x, y))  # \sum_i x_i y_i

[0 1 2 3 4]
[0 1 2 3 4]
30


In [61]:
x = tf.range(5)
y = tf.range(4)
tf.print(x)
tf.print(y)

# 向量外积
c = tf.einsum('i,j->ij', x, y)  # c_{ij} = x_i * y_j
tf.print(c)

[0 1 2 3 4]
[0 1 2 3]
[[0 0 0 0]
 [0 1 2 3]
 [0 2 4 6]
 [0 3 6 9]
 [0 4 8 12]]


In [62]:
A = tf.reshape(tf.range(9), (3, 3))
b = tf.range(3)
tf.print(A)
tf.print(b)

# \sum_{i,j} A_{i,j} * b_{j}
tf.print(tf.einsum('ij,j->', A, b))

# \sum_j A_{i=0,j} * b_j, \sum_j A_{i=1,j} * b_j, \sum_j A_{i=2,j} * b_j, ......
tf.print(tf.einsum('ij,j->i', A, b))

# \sum_i A_{i,j=0} * b_j, \sum_i A_{i,j=1} * b_j, \sum_i A_{i,j=2} * b_j, ......
tf.print(tf.einsum('ij,j->j', A, b))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2]
42
[5 14 23]
[0 12 30]


In [63]:
a = tf.reshape(tf.range(0, 6), (2, 3))
b = tf.reshape(tf.range(0, 6), (3, 2))
tf.print(a)
tf.print(b)

# 矩阵乘法
c = tf.einsum('ik,kj->ij', a, b)
tf.print(c)

[[0 1 2]
 [3 4 5]]
[[0 1]
 [2 3]
 [4 5]]
[[10 13]
 [28 40]]


In [64]:
a = tf.reshape(tf.range(0, 6), (2, 3))
b = tf.reshape(tf.range(1, 7), (2, 3))
tf.print(a)
tf.print(b)

# 矩阵对应元素相乘
c0 = tf.einsum('ij,ij->ij', a, b)
tf.print(c0)

# 矩阵对应元素相乘并求和
c1 = tf.einsum('ij,ij->', a, b)
tf.print(c1)

[[0 1 2]
 [3 4 5]]
[[1 2 3]
 [4 5 6]]
[[0 2 6]
 [12 20 30]]
70


In [65]:
ba = tf.reshape(tf.range(0, 24), (2, 3, 4))
bb = tf.reshape(tf.range(0, 24), (2, 4, 3))
tf.print(ba)

# 批量矩阵乘法
bc = tf.einsum('bij,bjk->bjk', ba, bb)
# bc = tf.einsum('...ij,...jk->...jk', ba, bb)  # 与上等价(前面或后面任意个维度可用 ... 代替)
tf.print(bc)

[[[0 1 2 3]
  [4 5 6 7]
  [8 9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[[0 12 24]
  [45 60 75]
  [108 126 144]
  [189 210 231]]

 [[576 624 672]
  [765 816 867]
  [972 1026 1080]
  [1197 1254 1311]]]


In [66]:
# 批量转置
ba = tf.reshape(tf.range(0, 120), (2, 3, 4, 5))
tf.einsum('...ij->...ji', ba).shape  # 最后两个维度转置
# tf.einsum('mnij->mnji', ba)  # 与上等价

TensorShape([2, 3, 5, 4])