In [42]:
import tensorflow as tf

In [43]:
c = tf.constant([1, 2, 3, 4])
c

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4])>

In [44]:
# 常量转numpy数组
c1 = c.numpy()
c1[0] = 111

print(c1)
print(c)  # c不变

[111   2   3   4]
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [45]:
v = tf.Variable([2, 3, 4, 5])
v

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([2, 3, 4, 5])>

In [46]:
# 变量转numpy数组
v.numpy()

array([2, 3, 4, 5])