In [58]:
import tensorflow as tf

### 参考numpy.where

In [59]:
# 只有condition参数
tf.where(condition=[True, False, False, True])  # 返回所有满足条件的位置坐标

<tf.Tensor: shape=(2, 1), dtype=int64, numpy=
array([[0],
       [3]], dtype=int64)>

In [60]:
tf.where([[True, False],
          [False, True]])

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[0, 0],
       [1, 1]], dtype=int64)>

In [61]:
data = tf.reshape(tf.range(9), (3, 3))
data

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])>

In [62]:
'''
condition:  A tf.Tensor of type bool
x:	        If provided, a Tensor which is of the same type as y, and has a shape broadcastable with condition and y.
y:       	If provided, a Tensor which is of the same type as x, and has a shape broadcastable with condition and x.

'''
print(tf.where(data < 5, x=1, y=2))
print(tf.where(data < 5, tf.fill((3, 3), 1), 2))  # 与上等价

tf.Tensor(
[[1 1 1]
 [1 1 2]
 [2 2 2]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[1 1 1]
 [1 1 2]
 [2 2 2]], shape=(3, 3), dtype=int32)


In [63]:
tf.where(data < 5, -1, data)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[-1, -1, -1],
       [-1, -1,  5],
       [ 6,  7,  8]])>

In [64]:
data  # data不发生改变

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])>