In [6]:
import tensorflow as tf

### 参考numpy.argmax/argmin

In [7]:
a = tf.random.stateless_normal(shape=(3, 4), seed=(1, 1))
a

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 1.6652164,  1.366376 ,  0.7786316,  0.9834322],
       [ 1.6551187, -0.6363001, -0.4229284,  0.6319565],
       [ 0.6605189, -0.6906152,  3.1515226,  1.970373 ]], dtype=float32)>

In [8]:
tf.math.argmax(a)  # 默认axis=0

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([0, 0, 2, 2], dtype=int64)>

In [9]:
tf.math.argmax(a, axis=1)

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([0, 0, 2], dtype=int64)>

In [10]:
tf.argmin(a)

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([2, 2, 1, 1], dtype=int64)>