In [25]:
import tensorflow as tf

### 参考torch.utils.data.TensorDataset

In [26]:
x = tf.linspace(0.0, 0.1, 100)
y = tf.reshape(tf.linspace(1, 400, 400), (100, 2, 2))
z = tf.range(1000, 1100)

In [27]:
# Creates a Dataset whose elements are slices of the given tensors.
for i in tf.data.Dataset.from_tensor_slices(x).as_numpy_iterator():
    print(i)

0.0
0.001010101
0.002020202
0.0030303032
0.004040404
0.0050505055
0.0060606063
0.007070707
0.008080808
0.00909091
0.010101011
0.011111111
0.012121213
0.013131314
0.014141414
0.015151516
0.016161617
0.017171718
0.01818182
0.01919192
0.020202022
0.021212121
0.022222223
0.023232324
0.024242425
0.025252527
0.026262628
0.02727273
0.028282829
0.02929293
0.030303031
0.031313132
0.032323234
0.033333335
0.034343436
0.035353538
0.03636364
0.03737374
0.03838384
0.039393943
0.040404044
0.04141414
0.042424243
0.043434344
0.044444446
0.045454547
0.046464648
0.04747475
0.04848485
0.049494952
0.050505053
0.051515155
0.052525256
0.053535357
0.05454546
0.05555556
0.056565657
0.05757576
0.05858586
0.05959596
0.060606062
0.061616164
0.062626265
0.06363637
0.06464647
0.065656565
0.06666667
0.06767677
0.06868687
0.06969697
0.070707075
0.07171717
0.07272728
0.073737375
0.07474748
0.07575758
0.07676768
0.07777778
0.078787886
0.07979798
0.08080809
0.081818186
0.08282828
0.08383839
0.084848486
0.08585859
0.0868

In [28]:
# The given tensors are sliced along their first dimension.
# This operation preserves the structure of the input tensors, removing the first dimension of each tensor and using it as the dataset dimension.
# All input tensors must have the same size in their first dimensions.
dataset = tf.data.Dataset.from_tensor_slices((x, y, z))  # 使用元组打包x,y,z(★★★★★x, y, z维度必须>=1)

print(dataset)
print(len(dataset))  # 数据集元素的第一个维度
print(dataset._tensors)
print(len(dataset._tensors))

<TensorSliceDataset shapes: ((), (2, 2), ()), types: (tf.float32, tf.float64, tf.int32)>
100
[<tf.Tensor: shape=(100,), dtype=float32, numpy=
array([0.        , 0.0010101 , 0.0020202 , 0.0030303 , 0.0040404 ,
       0.00505051, 0.00606061, 0.00707071, 0.00808081, 0.00909091,
       0.01010101, 0.01111111, 0.01212121, 0.01313131, 0.01414141,
       0.01515152, 0.01616162, 0.01717172, 0.01818182, 0.01919192,
       0.02020202, 0.02121212, 0.02222222, 0.02323232, 0.02424243,
       0.02525253, 0.02626263, 0.02727273, 0.02828283, 0.02929293,
       0.03030303, 0.03131313, 0.03232323, 0.03333334, 0.03434344,
       0.03535354, 0.03636364, 0.03737374, 0.03838384, 0.03939394,
       0.04040404, 0.04141414, 0.04242424, 0.04343434, 0.04444445,
       0.04545455, 0.04646465, 0.04747475, 0.04848485, 0.04949495,
       0.05050505, 0.05151515, 0.05252526, 0.05353536, 0.05454546,
       0.05555556, 0.05656566, 0.05757576, 0.05858586, 0.05959596,
       0.06060606, 0.06161616, 0.06262626, 0.06363637,

In [29]:
for i in dataset:
    print(i)  # 输出数据集(x[i, ...], y[i, ...], z[i, ...])

(<tf.Tensor: shape=(), dtype=float32, numpy=0.0>, <tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1., 2.],
       [3., 4.]])>, <tf.Tensor: shape=(), dtype=int32, numpy=1000>)
(<tf.Tensor: shape=(), dtype=float32, numpy=0.001010101>, <tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[5., 6.],
       [7., 8.]])>, <tf.Tensor: shape=(), dtype=int32, numpy=1001>)
(<tf.Tensor: shape=(), dtype=float32, numpy=0.002020202>, <tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[ 9., 10.],
       [11., 12.]])>, <tf.Tensor: shape=(), dtype=int32, numpy=1002>)
(<tf.Tensor: shape=(), dtype=float32, numpy=0.0030303032>, <tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[13., 14.],
       [15., 16.]])>, <tf.Tensor: shape=(), dtype=int32, numpy=1003>)
(<tf.Tensor: shape=(), dtype=float32, numpy=0.004040404>, <tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[17., 18.],
       [19., 20.]])>, <tf.Tensor: shape=(), dtype=int32, numpy=1004>)
(<tf.Tensor: shape=(), dtype=float32, nu

In [30]:
dataset = tf.data.Dataset.from_tensor_slices({"x": x, "y": y, "z": z})  # 使用字典打包x,y
dataset

<TensorSliceDataset shapes: {x: (), y: (2, 2), z: ()}, types: {x: tf.float32, y: tf.float64, z: tf.int32}>

In [31]:
dataset._tensors  # 数据集[x, y, z]

[<tf.Tensor: shape=(100,), dtype=float32, numpy=
 array([0.        , 0.0010101 , 0.0020202 , 0.0030303 , 0.0040404 ,
        0.00505051, 0.00606061, 0.00707071, 0.00808081, 0.00909091,
        0.01010101, 0.01111111, 0.01212121, 0.01313131, 0.01414141,
        0.01515152, 0.01616162, 0.01717172, 0.01818182, 0.01919192,
        0.02020202, 0.02121212, 0.02222222, 0.02323232, 0.02424243,
        0.02525253, 0.02626263, 0.02727273, 0.02828283, 0.02929293,
        0.03030303, 0.03131313, 0.03232323, 0.03333334, 0.03434344,
        0.03535354, 0.03636364, 0.03737374, 0.03838384, 0.03939394,
        0.04040404, 0.04141414, 0.04242424, 0.04343434, 0.04444445,
        0.04545455, 0.04646465, 0.04747475, 0.04848485, 0.04949495,
        0.05050505, 0.05151515, 0.05252526, 0.05353536, 0.05454546,
        0.05555556, 0.05656566, 0.05757576, 0.05858586, 0.05959596,
        0.06060606, 0.06161616, 0.06262626, 0.06363637, 0.06464647,
        0.06565657, 0.06666667, 0.06767677, 0.06868687, 0.06969697,

In [32]:
for i in dataset:
    print(i)  # 输出{"x": x[i, ...], "y": y[i, ...], "z": z[i, ...]}

{'x': <tf.Tensor: shape=(), dtype=float32, numpy=0.0>, 'y': <tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1., 2.],
       [3., 4.]])>, 'z': <tf.Tensor: shape=(), dtype=int32, numpy=1000>}
{'x': <tf.Tensor: shape=(), dtype=float32, numpy=0.001010101>, 'y': <tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[5., 6.],
       [7., 8.]])>, 'z': <tf.Tensor: shape=(), dtype=int32, numpy=1001>}
{'x': <tf.Tensor: shape=(), dtype=float32, numpy=0.002020202>, 'y': <tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[ 9., 10.],
       [11., 12.]])>, 'z': <tf.Tensor: shape=(), dtype=int32, numpy=1002>}
{'x': <tf.Tensor: shape=(), dtype=float32, numpy=0.0030303032>, 'y': <tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[13., 14.],
       [15., 16.]])>, 'z': <tf.Tensor: shape=(), dtype=int32, numpy=1003>}
{'x': <tf.Tensor: shape=(), dtype=float32, numpy=0.004040404>, 'y': <tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[17., 18.],
       [19., 20.]])>, 'z': <tf.Tensor: s