In [2]:
import numpy as np

In [3]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(3, 8) # 不含末尾元素8

array([3, 4, 5, 6, 7])

In [5]:
np.arange(3, 8, 2) # 步长为2

array([3, 5, 7])

In [6]:
np.arange(8, 2, -2) # 步长为-2


array([8, 6, 4])