In [18]:
import tensorflow as tf

### 参考torch.nn.Dropout

In [19]:
a = tf.ones((20, 20))
a

<tf.Tensor: shape=(20, 20), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
     

In [21]:
# The Dropout layer randomly sets input units to 0 with a frequency of rate at each step during training time, which helps prevent overfitting.
# Inputs not set to 0 are scaled up by 1/(1 - rate) such that the sum over all inputs is unchanged.
layder = tf.keras.layers.Dropout(rate=0.2)  #  参考nn.Dropout p参数
layder(a,
       training=True)  # 是否为训练模式(eval模式下不执行Dropout操作)

<tf.Tensor: shape=(20, 20), dtype=float32, numpy=
array([[1.25, 0.  , 1.25, 1.25, 0.  , 1.25, 1.25, 1.25, 1.25, 1.25, 1.25,
        1.25, 1.25, 1.25, 1.25, 0.  , 1.25, 1.25, 1.25, 1.25],
       [0.  , 0.  , 1.25, 1.25, 1.25, 1.25, 1.25, 0.  , 1.25, 1.25, 1.25,
        1.25, 1.25, 1.25, 1.25, 0.  , 0.  , 1.25, 1.25, 1.25],
       [1.25, 1.25, 1.25, 1.25, 1.25, 1.25, 0.  , 1.25, 1.25, 1.25, 1.25,
        1.25, 1.25, 1.25, 1.25, 0.  , 1.25, 0.  , 1.25, 1.25],
       [1.25, 1.25, 1.25, 1.25, 1.25, 1.25, 1.25, 1.25, 1.25, 0.  , 1.25,
        0.  , 1.25, 1.25, 0.  , 1.25, 1.25, 1.25, 1.25, 1.25],
       [1.25, 0.  , 1.25, 1.25, 1.25, 1.25, 0.  , 1.25, 1.25, 1.25, 0.  ,
        1.25, 0.  , 1.25, 1.25, 1.25, 1.25, 1.25, 1.25, 0.  ],
       [0.  , 1.25, 1.25, 0.  , 0.  , 1.25, 1.25, 1.25, 1.25, 1.25, 1.25,
        1.25, 1.25, 1.25, 0.  , 1.25, 1.25, 1.25, 1.25, 1.25],
       [1.25, 1.25, 0.  , 1.25, 1.25, 1.25, 0.  , 1.25, 1.25, 1.25, 1.25,
        1.25, 1.25, 1.25, 0.  , 1.25, 1.25, 1.25, 0.  