In [261]:
import tensorflow as tf

### sigmoid激活函数
### 参考torch.sigmoid/torch.nn.Sigmoid

In [262]:
x = tf.linspace(-5, 5, 30)

In [263]:
# 函数
print(tf.nn.sigmoid(x), end='\n\n')

# 函数
print(tf.math.sigmoid(x))

tf.Tensor(
[0.00669285 0.00942264 0.01325097 0.0186055  0.02606656 0.03640861
 0.05064057 0.07003141 0.09609567 0.13049925 0.17483739 0.23025063
 0.29690726 0.37349752 0.45700301 0.54299699 0.62650248 0.70309274
 0.76974937 0.82516261 0.86950075 0.90390433 0.92996859 0.94935943
 0.96359139 0.97393344 0.9813945  0.98674903 0.99057736 0.99330715], shape=(30,), dtype=float64)

tf.Tensor(
[0.00669285 0.00942264 0.01325097 0.0186055  0.02606656 0.03640861
 0.05064057 0.07003141 0.09609567 0.13049925 0.17483739 0.23025063
 0.29690726 0.37349752 0.45700301 0.54299699 0.62650248 0.70309274
 0.76974937 0.82516261 0.86950075 0.90390433 0.92996859 0.94935943
 0.96359139 0.97393344 0.9813945  0.98674903 0.99057736 0.99330715], shape=(30,), dtype=float64)


In [264]:
# 类
layer = tf.keras.layers.Activation(tf.nn.sigmoid, name='sigmoid')  # 可在网络层中简写为:'sigmoid'
output = layer(x)

print(layer.name)
print(output)

sigmoid
tf.Tensor(
[0.00669285 0.00942264 0.01325097 0.0186055  0.02606656 0.03640861
 0.05064056 0.07003141 0.09609567 0.13049924 0.17483738 0.23025063
 0.29690725 0.37349752 0.457003   0.54299694 0.62650245 0.70309275
 0.7697494  0.8251626  0.8695008  0.9039043  0.9299686  0.9493594
 0.96359134 0.9739335  0.9813945  0.986749   0.99057734 0.9933072 ], shape=(30,), dtype=float32)


### softmax激活函数
### 参考tofch.nn.functional.softmax/torch.nn.Softmax

In [265]:
x = tf.linspace(-5, 5, 30)

In [266]:
# 函数
tf.nn.softmax(x)  # 等价与tf.math.softmax(x)

<tf.Tensor: shape=(30,), dtype=float64, numpy=
array([1.32416572e-05, 1.86938631e-05, 2.63909957e-05, 3.72573956e-05,
       5.25979976e-05, 7.42550388e-05, 1.04829291e-04, 1.47992384e-04,
       2.08927729e-04, 2.94952988e-04, 4.16398847e-04, 5.87849613e-04,
       8.29894630e-04, 1.17160083e-03, 1.65400337e-03, 2.33503346e-03,
       3.29647530e-03, 4.65378745e-03, 6.56996811e-03, 9.27512945e-03,
       1.30941315e-02, 1.84855942e-02, 2.60969728e-02, 3.68423099e-02,
       5.20120018e-02, 7.34277612e-02, 1.03661384e-01, 1.46343596e-01,
       2.06600059e-01, 2.91666909e-01])>

In [267]:
layer = tf.keras.layers.Activation(tf.nn.softmax, name='softmax')  # 可在网络层中简写为:'softmax'
output = layer(x)

print(layer.name)
print(output)

softmax
tf.Tensor(
[1.32416581e-05 1.86938669e-05 2.63910006e-05 3.72574068e-05
 5.25980140e-05 7.42550692e-05 1.04829291e-04 1.47992381e-04
 2.08927755e-04 2.94953032e-04 4.16398747e-04 5.87849587e-04
 8.29894561e-04 1.17160077e-03 1.65400351e-03 2.33503385e-03
 3.29647609e-03 4.65378864e-03 6.56996854e-03 9.27513093e-03
 1.30941318e-02 1.84855945e-02 2.60969736e-02 3.68423164e-02
 5.20120002e-02 7.34277666e-02 1.03661396e-01 1.46343589e-01
 2.06600055e-01 2.91666925e-01], shape=(30,), dtype=float32)


### 激活函数tanh
### 参考torch.tanh/torch.nn.Tanh

In [268]:
x = tf.linspace(-20, 20, 50)

In [269]:
tf.nn.tanh(x)  # 等价与tf.math.tanh(x)

<tf.Tensor: shape=(50,), dtype=float64, numpy=
array([-1.        , -1.        , -1.        , -1.        , -1.        ,
       -1.        , -1.        , -1.        , -1.        , -1.        ,
       -1.        , -1.        , -1.        , -0.99999999, -0.99999993,
       -0.99999963, -0.99999812, -0.99999038, -0.99995078, -0.99974812,
       -0.99871171, -0.99342468, -0.96680063, -0.8409736 , -0.38691202,
        0.38691202,  0.8409736 ,  0.96680063,  0.99342468,  0.99871171,
        0.99974812,  0.99995078,  0.99999038,  0.99999812,  0.99999963,
        0.99999993,  0.99999999,  1.        ,  1.        ,  1.        ,
        1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
        1.        ,  1.        ,  1.        ,  1.        ,  1.        ])>

In [270]:
layer = tf.keras.layers.Activation(tf.nn.tanh)  # 可在网络层中简写为:'tanh'
output = layer(x)
output

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([-1.        , -1.        , -1.        , -1.        , -1.        ,
       -1.        , -1.        , -1.        , -1.        , -1.        ,
       -1.        , -1.        , -1.        , -1.        , -1.        ,
       -0.99999964, -0.9999983 , -0.9999904 , -0.99995077, -0.9997481 ,
       -0.99871165, -0.99342465, -0.9668005 , -0.84097356, -0.38691205,
        0.38691205,  0.84097356,  0.9668005 ,  0.99342465,  0.99871165,
        0.9997481 ,  0.99995077,  0.9999904 ,  0.9999983 ,  0.99999964,
        1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
        1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
        1.        ,  1.        ,  1.        ,  1.        ,  1.        ],
      dtype=float32)>

### 激活函数Swish 

Swish activation function which returns $ x * sigmoid(x)$.
It is a smooth, non-monotonic function that consistently matches or outperforms ReLU on deep networks, it is unbounded above and bounded below.

In [271]:
x = tf.constant([-20, -1.0, 0.0, 1.0, 20], dtype=tf.float32)

In [272]:
# 函数
tf.nn.swish(x)

<tf.Tensor: shape=(5,), dtype=float32, numpy=
array([-4.1223068e-08, -2.6894143e-01,  0.0000000e+00,  7.3105854e-01,
        2.0000000e+01], dtype=float32)>

In [273]:
layer = tf.keras.layers.Activation(tf.nn.swish)
output = layer(x)
output

<tf.Tensor: shape=(5,), dtype=float32, numpy=
array([-4.1223068e-08, -2.6894143e-01,  0.0000000e+00,  7.3105854e-01,
        2.0000000e+01], dtype=float32)>

### 激活函数relu
### 参考torch.functional.relu/torch.nn.ReLU

In [274]:
x = tf.linspace(-5, 5, 100)

In [275]:
# 函数
tf.nn.relu(x)

<tf.Tensor: shape=(100,), dtype=float64, numpy=
array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.05050505, 0.15151515, 0.25252525, 0.35353535, 0.45454545,
       0.55555556, 0.65656566, 0.75757576, 0.85858586, 0.95959596,
       1.06060606, 1.16161616, 1.26262626, 1.36363636, 1.46464646,
       1.56565657, 1.66666667, 1.76767677, 1.86868687, 1.96969697,
       2.07070

In [276]:
layer = tf.keras.layers.Activation(tf.nn.relu)  # 可在网络层中简写为:'relu'
output = layer(x)
output

<tf.Tensor: shape=(100,), dtype=float32, numpy=
array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.05050505, 0.15151516, 0.25252524, 0.35353535, 0.45454547,
       0.5555556 , 0.65656567, 0.75757575, 0.85858583, 0.959596  ,
       1.060606  , 1.1616162 , 1.2626263 , 1.3636364 , 1.4646465 ,
       1.5656565 , 1.6666666 , 1.7676767 , 1.8686869 , 1.969697  ,
       2.07070

### 激活函数leaky_relu
### 参考torch.nn.LeakyReLU

In [277]:
x = tf.linspace(-5, 5, 200)

In [278]:
# 函数
tf.nn.leaky_relu(x,
                 alpha=0.1)  # alpha: Slope of the activation function at x < 0.

<tf.Tensor: shape=(200,), dtype=float64, numpy=
array([-5.00000007e-01, -4.94974882e-01, -4.89949756e-01, -4.84924630e-01,
       -4.79899505e-01, -4.74874379e-01, -4.69849253e-01, -4.64824128e-01,
       -4.59799002e-01, -4.54773876e-01, -4.49748750e-01, -4.44723625e-01,
       -4.39698499e-01, -4.34673373e-01, -4.29648248e-01, -4.24623122e-01,
       -4.19597996e-01, -4.14572870e-01, -4.09547745e-01, -4.04522619e-01,
       -3.99497493e-01, -3.94472368e-01, -3.89447242e-01, -3.84422116e-01,
       -3.79396991e-01, -3.74371865e-01, -3.69346739e-01, -3.64321613e-01,
       -3.59296488e-01, -3.54271362e-01, -3.49246236e-01, -3.44221111e-01,
       -3.39195985e-01, -3.34170859e-01, -3.29145734e-01, -3.24120608e-01,
       -3.19095482e-01, -3.14070356e-01, -3.09045231e-01, -3.04020105e-01,
       -2.98994979e-01, -2.93969854e-01, -2.88944728e-01, -2.83919602e-01,
       -2.78894477e-01, -2.73869351e-01, -2.68844225e-01, -2.63819099e-01,
       -2.58793974e-01, -2.53768848e-01, -2.48743722

In [279]:
# 自定义leaky_relu激活函数层
class MyLeakyRelu(tf.keras.layers.Layer):  # This is the class from which all layers inherit.
    pass