In [26]:
import numpy as np
from sklearn.impute import SimpleImputer

In [27]:
imp_mean = SimpleImputer(missing_values=np.nan,
                         # 每列的平均值填充缺失值
                         strategy='mean')
imp_mean.fit_transform([[7, 2, 3],
                        [4, np.nan, 6],
                        [10, 5, np.nan],
                        [10, 5, 9],
                        [10, 3, 5],
                        [10, 1, 10],
                        [10, 5, 9],
                        [10, 2, 9],
                        ])


array([[ 7.        ,  2.        ,  3.        ],
       [ 4.        ,  3.28571429,  6.        ],
       [10.        ,  5.        ,  7.28571429],
       [10.        ,  5.        ,  9.        ],
       [10.        ,  3.        ,  5.        ],
       [10.        ,  1.        , 10.        ],
       [10.        ,  5.        ,  9.        ],
       [10.        ,  2.        ,  9.        ]])

In [28]:
X = [[np.nan, 2, 3],
     [4, np.nan, 6],
     [10, np.nan, 9]]
print(imp_mean.transform(X))

[[ 8.875       2.          3.        ]
 [ 4.          3.28571429  6.        ]
 [10.          3.28571429  9.        ]]


In [29]:
imp_median = SimpleImputer(missing_values=np.nan,
                           # 每列的中位数填充缺失值
                           strategy='median')
imp_median.fit_transform([[7, 2, 3],
                          [4, np.nan, 6],
                          [10, 5, np.nan],
                          [10, 5, 9],
                          [10, 3, 5],
                          [10, 1, 10],
                          [10, 5, 9],
                          [10, 2, 9],
                          ])

array([[ 7.,  2.,  3.],
       [ 4.,  3.,  6.],
       [10.,  5.,  9.],
       [10.,  5.,  9.],
       [10.,  3.,  5.],
       [10.,  1., 10.],
       [10.,  5.,  9.],
       [10.,  2.,  9.]])

In [30]:
imp_most_frequent = SimpleImputer(missing_values=np.nan,
                                  # 每列频率最高的值填充缺失值
                                  strategy='most_frequent')
imp_most_frequent.fit_transform([[7, 2, 3],
                                 [4, np.nan, 6],
                                 [10, 5, np.nan],
                                 [10, 5, 9],
                                 [10, 3, 5],
                                 [10, 1, 10],
                                 [10, 5, 9],
                                 [10, 2, 9],
                                 ])

array([[ 7.,  2.,  3.],
       [ 4.,  5.,  6.],
       [10.,  5.,  9.],
       [10.,  5.,  9.],
       [10.,  3.,  5.],
       [10.,  1., 10.],
       [10.,  5.,  9.],
       [10.,  2.,  9.]])

In [31]:
imp_constant = SimpleImputer(missing_values=np.nan,
                                  # 使用fill_value填充缺失值
                                  strategy='constant', fill_value=-1)
imp_constant.fit_transform([[7, 2, 3],
                                 [4, np.nan, 6],
                                 [10, 5, np.nan],
                                 [10, 5, 9],
                                 [10, 3, 5],
                                 [10, 1, 10],
                                 [10, 5, 9],
                                 [10, 2, 9],
                                 ])


array([[ 7.,  2.,  3.],
       [ 4., -1.,  6.],
       [10.,  5., -1.],
       [10.,  5.,  9.],
       [10.,  3.,  5.],
       [10.,  1., 10.],
       [10.,  5.,  9.],
       [10.,  2.,  9.]])