In [2]:
import tensorflow as tf

In [3]:
@tf.function
def myadd(a, b):
    for i in tf.range(3):
        tf.print(i)
    c = a + b
    print("tracing")  # Python operations execute only once per trace
    return c

In [4]:
'''
执行步骤:
1. 创建计算图
2. 执行计算图
'''
myadd(tf.constant("hello"), tf.constant("world"))

tracing
0
1
2


<tf.Tensor: shape=(), dtype=string, numpy=b'helloworld'>

In [5]:
'''
相同的参数类型执行

执行步骤:
1. 执行计算图
'''
myadd(tf.constant("good"), tf.constant("morning"))

0
1
2


<tf.Tensor: shape=(), dtype=string, numpy=b'goodmorning'>

In [6]:
'''
不同的的输入参数类型调用(参数类型改变,之前的计算图不能再次使用)

执行步骤:
1. 创建计算图
2. 执行计算图
'''
myadd(tf.constant(1), tf.constant(2))

tracing
0
1
2


<tf.Tensor: shape=(), dtype=int32, numpy=3>