In [1]:
from transformers import BertModel, AutoModel, TFAutoModel
import torch.nn as nn
from transformers import BertTokenizer
import torch

In [2]:
# 加载预训练模型
'''
BertModek(可通过`__init__()`实例化):
    The model can behave as an encoder (with only self-attention) as well as a decoder, in which case a layer of
    cross-attention is added between the self-attention layers, following the architecture described in [Attention is
    all you need](https://arxiv.org/abs/1706.03762) by Ashish Vaswani, Noam Shazeer, Niki Parmar, Jakob Uszkoreit,
    Llion Jones, Aidan N. Gomez, Lukasz Kaiser and Illia Polosukhin.
'''
# from_pretrained(类方法): Instantiate a pretrained pytorch model from a pre-trained model configuration.
pretrained_model = BertModel.from_pretrained(pretrained_model_name_or_path='bert-base-chinese')
pretrained_model

Some weights of the model checkpoint at bert-base-chinese were not used when initializing BertModel: ['cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.seq_relationship.bias', 'cls.predictions.decoder.weight', 'cls.predictions.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.dense.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


BertModel(
  (embeddings): BertEmbeddings(
    (word_embeddings): Embedding(21128, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (token_type_embeddings): Embedding(2, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): BertEncoder(
    (layer): ModuleList(
      (0): BertLayer(
        (attention): BertAttention(
          (self): BertSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          

In [3]:
# 模型参数
pretrained_model.config

BertConfig {
  "_name_or_path": "bert-base-chinese",
  "architectures": [
    "BertForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "directionality": "bidi",
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "pooler_fc_size": 768,
  "pooler_num_attention_heads": 12,
  "pooler_num_fc_layers": 3,
  "pooler_size_per_head": 128,
  "pooler_type": "first_token_transform",
  "position_embedding_type": "absolute",
  "transformers_version": "4.17.0",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 21128
}

In [4]:
# 与上等价
# 不能通过`__init__()`方法实例化
pretrained_auto = AutoModel.from_pretrained(pretrained_model_name_or_path='bert-base-chinese')
pretrained_auto

Some weights of the model checkpoint at bert-base-chinese were not used when initializing BertModel: ['cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.seq_relationship.bias', 'cls.predictions.decoder.weight', 'cls.predictions.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.dense.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


BertModel(
  (embeddings): BertEmbeddings(
    (word_embeddings): Embedding(21128, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (token_type_embeddings): Embedding(2, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): BertEncoder(
    (layer): ModuleList(
      (0): BertLayer(
        (attention): BertAttention(
          (self): BertSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          

In [5]:
# BertModel:this model is also a PyTorch torch.nn.Module subclass.
# TFBertModel:This model is also a tf.keras.Model subclass
print(issubclass(BertModel, nn.Module))

True


In [6]:
# 报错:XLM-RoBERTa模型只有PyTorch权重
tf_xlmr = TFAutoModel.from_pretrained("xlm-roberta-base")

OSError: xlm-roberta-base does not appear to have a file named tf_model.h5 but there is a file for PyTorch weights. Use `from_pt=True` to load this model from those weights.

In [7]:
# from_pt (bool, optional, defaults to False) — Load the model weights from a PyTorch checkpoint save file
# from_tf (bool, optional, defaults to False) — Load the model weights from a TensorFlow checkpoint save file
# rom_flax (bool, optional, defaults to False) — Load the model weights from a Flax checkpoint save file
tf_xlmr_ = TFAutoModel.from_pretrained("xlm-roberta-base", from_pt=True)
tf_xlmr_  # TensorFlow 2.x 实例

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFXLMRobertaModel: ['lm_head.layer_norm.bias', 'lm_head.bias', 'lm_head.decoder.weight', 'lm_head.layer_norm.weight', 'lm_head.dense.bias', 'lm_head.dense.weight']
- This IS expected if you are initializing TFXLMRobertaModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFXLMRobertaModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFXLMRobertaModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFXLMRobertaModel for predictions without further training.


In [8]:
sents = [
    '选择珠江花园的原因就是方便。',
    '笔记本的键盘确实爽。',
    '房间太小。其他的都一般。',
    '今天才知道这书还有第6卷,真有点郁闷.',
    '机器背面似乎被撕了张什么标签，残胶还在。',
]

tokenizer = BertTokenizer.from_pretrained(
    pretrained_model_name_or_path='bert-base-chinese',
)
# 批量编码句子
batch_encode_plus_ = tokenizer.batch_encode_plus(
    batch_text_or_text_pairs=sents,
    padding=True,
    return_token_type_ids=True,
    return_attention_mask=True,
    return_special_tokens_mask=True,
)

In [9]:
# batch_size=5
# 序列长度=22
torch.tensor(batch_encode_plus_['input_ids']).shape

torch.Size([5, 22])

In [10]:
# 调用forward函数
model_result = pretrained_model(input_ids=torch.tensor(batch_encode_plus_['input_ids']),
                                attention_mask=torch.tensor(batch_encode_plus_['attention_mask']),
                                token_type_ids=torch.tensor(batch_encode_plus_['token_type_ids']),
                                output_attentions=True)
model_result

BaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=tensor([[[-0.2515,  0.0995,  0.3412,  ..., -0.5911, -0.3708, -0.2213],
         [ 0.1122,  0.6720, -0.2852,  ..., -0.0901,  0.4799, -0.1238],
         [-0.1219, -0.4409, -0.0171,  ...,  0.4984,  0.5670, -0.1073],
         ...,
         [ 0.2094, -0.1150,  0.0347,  ..., -0.2581, -0.3346, -0.6071],
         [ 0.1895, -0.2040, -0.0295,  ..., -0.3647, -0.1584, -0.5131],
         [-0.1528, -0.2291, -0.0188,  ..., -0.4964, -0.2382, -0.5914]],

        [[ 0.4465,  0.5529,  0.0847,  ...,  0.0216, -0.4657, -0.2294],
         [-0.5805,  0.1990, -0.1573,  ..., -0.1635, -0.2357,  0.3088],
         [-0.6433, -0.3418,  0.2136,  ...,  1.2298,  0.1446, -0.0442],
         ...,
         [-0.0168,  0.0354, -0.3531,  ...,  0.6999, -0.4942, -0.3936],
         [ 0.0245,  0.0088, -0.6094,  ...,  0.5770, -0.4299, -0.4338],
         [ 0.2108, -0.1378, -0.4722,  ...,  0.2757, -0.2669, -0.5684]],

        [[ 0.0278,  0.8293,  0.1254,  ..., -0.9356,  

In [11]:
# shape=(batch_size, sequence_length, hidden_size)
# Sequence of hidden-states at the output of the last layer of the model.
print(model_result.last_hidden_state)
print(model_result.last_hidden_state.shape)

# Return vector for [CLS] token
print(model_result.last_hidden_state[:, 0, :])

tensor([[[-0.2515,  0.0995,  0.3412,  ..., -0.5911, -0.3708, -0.2213],
         [ 0.1122,  0.6720, -0.2852,  ..., -0.0901,  0.4799, -0.1238],
         [-0.1219, -0.4409, -0.0171,  ...,  0.4984,  0.5670, -0.1073],
         ...,
         [ 0.2094, -0.1150,  0.0347,  ..., -0.2581, -0.3346, -0.6071],
         [ 0.1895, -0.2040, -0.0295,  ..., -0.3647, -0.1584, -0.5131],
         [-0.1528, -0.2291, -0.0188,  ..., -0.4964, -0.2382, -0.5914]],

        [[ 0.4465,  0.5529,  0.0847,  ...,  0.0216, -0.4657, -0.2294],
         [-0.5805,  0.1990, -0.1573,  ..., -0.1635, -0.2357,  0.3088],
         [-0.6433, -0.3418,  0.2136,  ...,  1.2298,  0.1446, -0.0442],
         ...,
         [-0.0168,  0.0354, -0.3531,  ...,  0.6999, -0.4942, -0.3936],
         [ 0.0245,  0.0088, -0.6094,  ...,  0.5770, -0.4299, -0.4338],
         [ 0.2108, -0.1378, -0.4722,  ...,  0.2757, -0.2669, -0.5684]],

        [[ 0.0278,  0.8293,  0.1254,  ..., -0.9356,  0.2104, -0.1087],
         [ 0.1050,  1.1256,  1.0845,  ..., -0

In [12]:
# shape=(batch_size, hidden_size)
# Last layer hidden-state of the first token of the sequence (classification token) after further processing through the layers used for the auxiliary pretraining task.
# E.g. for BERT-family of models, this returns the classification token after processing through a linear layer and a tanh activation function.
# The linear layer weights are trained from the next sentence prediction (classification) objective during pretraining.
print(model_result.pooler_output)
print(model_result.pooler_output.shape)

tensor([[ 1.0000,  1.0000,  0.9968,  ..., -0.9959, -0.9996,  0.9813],
        [ 0.9998,  1.0000,  0.9995,  ..., -0.9950, -0.9992,  0.6948],
        [ 0.9986,  1.0000,  0.9857,  ..., -0.9723, -0.9992,  0.8432],
        [ 0.9999,  0.9999,  0.9991,  ..., -0.8323, -0.9999,  0.9680],
        [ 0.9999,  0.9998,  0.9997,  ..., -0.9931, -0.9989,  0.3954]],
       grad_fn=<TanhBackward0>)
torch.Size([5, 768])


In [14]:
# Tuple of torch.FloatTensor (one for each layer) of shape (batch_size, num_heads, sequence_length, sequence_length).
# Attentions weights after the attention softmax, used to compute the weighted average in the self-attention heads.
print(model_result.attentions)

(tensor([[[[6.3310e-04, 1.6055e-03, 6.4253e-04,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [3.2706e-02, 1.4263e-01, 1.0638e-01,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [3.0440e-02, 4.3397e-02, 6.5812e-02,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          ...,
          [6.1235e-01, 2.1990e-02, 2.8031e-02,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [5.7082e-01, 2.4627e-02, 3.0766e-02,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [6.5823e-01, 1.9549e-02, 2.4565e-02,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00]],

         [[1.4318e-02, 8.0103e-03, 2.6602e-02,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [2.2854e-02, 8.0141e-03, 9.3140e-01,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [1.7589e-01, 6.1927e-01, 5.4582e-02,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          ...,
          [6.6166e-01, 1.4089e-04, 4.1154e-03,  ..., 0.000

In [15]:
# Attentions weights of the decoder’s cross-attention layer, after the attention softmax, used to compute the weighted average in the cross-attention heads.
# Tuple of torch.FloatTensor (one for each layer) of shape (batch_size, num_heads, sequence_length, sequence_length).
print(model_result.cross_attentions)

None


In [16]:
# Save a model and its configuration file to a directory, so that it can be re-loaded using the `[`~PreTrainedModel.from_pretrained`]` class method.
pretrained_model.save_pretrained('save_model/')

In [17]:
# 本地加载预训练模型
pretrained_model1 = BertModel.from_pretrained('save_model/')
pretrained_model1

BertModel(
  (embeddings): BertEmbeddings(
    (word_embeddings): Embedding(21128, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (token_type_embeddings): Embedding(2, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): BertEncoder(
    (layer): ModuleList(
      (0): BertLayer(
        (attention): BertAttention(
          (self): BertSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          