In [6]:
import numpy as np

In [7]:
'''
unique(ar, return_index=False, return_inverse=False, return_counts=False, axis=None)
                                 Returns the sorted unique elements of an array.
'''
arr = np.array([[5, 5, 2, 2, 3, 3], 
               [3, 3, 4, 4, 5, 5]])
arr

array([[5, 5, 2, 2, 3, 3],
       [3, 3, 4, 4, 5, 5]])

In [8]:
np.unique(arr) # 返回数组arr的唯一值并排序

array([2, 3, 4, 5])

In [9]:
np.unique(arr, return_counts=True) # 返回唯一值和唯一值出现的次数

(array([2, 3, 4, 5]), array([2, 4, 2, 4], dtype=int64))

In [10]:
np.unique(arr, axis=1)

array([[2, 3, 5],
       [4, 5, 3]])

In [11]:
np.unique(arr, axis=0)

array([[3, 3, 4, 4, 5, 5],
       [5, 5, 2, 2, 3, 3]])