In [18]:
import  numpy as np
'''
numpy.where(condition[, x, y])
    Return elements chosen from x or y depending on condition.

    Parameters:
    condition : array_like, bool
        Where True, yield x, otherwise yield y.

    x, y : array_like
        Values from which to choose. x, y and condition need to be broadcastable to some shape.

    Returns:
    out : ndarray
        An array with elements from x where condition is True, and elements from y elsewhere.
'''
x = np.arange(9.).reshape(3, 3)
x

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [19]:
np.where(x < 5, 0, 1.0)

array([[0., 0., 0.],
       [0., 0., 1.],
       [1., 1., 1.]])

In [20]:
np.where(x < 5, x, -1)

array([[ 0.,  1.,  2.],
       [ 3.,  4., -1.],
       [-1., -1., -1.]])

In [21]:
np.where(x == 1, 100, x)

array([[  0., 100.,   2.],
       [  3.,   4.,   5.],
       [  6.,   7.,   8.]])

In [22]:
np.where(x ==1, np.full_like(x, 100), x) # 于上等价

array([[  0., 100.,   2.],
       [  3.,   4.,   5.],
       [  6.,   7.,   8.]])

In [23]:
x # x不发生改变

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])