In [28]:
import numpy as np

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [29]:
np.delete(arr, 1, axis=0) # If `axis` is None, `obj` is applied to the flattened array.

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [30]:
arr[[0, 2]] # 于上等价

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [31]:
np.delete(arr, 1, axis=1)

array([[ 1,  3,  4],
       [ 5,  7,  8],
       [ 9, 11, 12]])

In [32]:
arr[:, [0, 2, 3]] # 于上等价

array([[ 1,  3,  4],
       [ 5,  7,  8],
       [ 9, 11, 12]])

In [33]:
np.delete(arr, [1], axis=None) # If `axis` is None, `obj` is applied to the flattened array.

array([ 1,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [34]:
np.delete(arr, [1, 3, 5], None)

array([ 1,  3,  5,  7,  8,  9, 10, 11, 12])

In [35]:
arr # arr不变

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])