In [50]:
import numpy as np

x = np.array([[3, 0, 0],
              [0, 4, 0],
              [5, 6, 0]])
x

array([[3, 0, 0],
       [0, 4, 0],
       [5, 6, 0]])

In [51]:
np.nonzero(x) # 返回非零元素的索引(易知,索引为:[0, 0], [1, 1], [2, 0], [2, 1])

(array([0, 1, 2, 2], dtype=int64), array([0, 1, 0, 1], dtype=int64))

In [52]:
x[np.nonzero(x)] # x中所有的非零元素

array([3, 4, 5, 6])

In [53]:
x[x != 0] # 于上等价

array([3, 4, 5, 6])

In [54]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a > 3

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [55]:
np.nonzero(a > 3)

(array([1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2], dtype=int64))

In [56]:
a[np.nonzero(a > 3)]

array([4, 5, 6, 7, 8, 9])

In [57]:
a[a > 3] # 布尔索引(与上等价)



array([4, 5, 6, 7, 8, 9])