In [29]:
import tensorflow as tf
import torch

### 参考numpy.var

In [30]:
a = tf.random.stateless_normal(shape=(2, 3, 4), seed=(1, 2))
a

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[ 0.5441101 ,  0.20738031,  0.07356433,  0.04643455],
        [-1.30159   , -0.95385665,  0.84172857,  1.9396868 ],
        [ 0.6512578 ,  1.1048867 ,  1.3746228 ,  1.148752  ]],

       [[ 1.0821314 ,  0.55104923,  0.07009614,  0.707385  ],
        [ 0.88857085, -0.46432722,  1.2084333 , -0.79011595],
        [-0.7304904 , -0.7207538 ,  0.36527526, -0.16950758]]],
      dtype=float32)>

In [31]:
b = torch.tensor(a.numpy())
torch.var(b, unbiased=False)

tensor(0.6711)

In [32]:
tf.math.reduce_variance(a)  # 有偏估计

<tf.Tensor: shape=(), dtype=float32, numpy=0.67109966>

In [33]:
# The dimensions to reduce. If None (the default), reduces all dimensions.
tf.math.reduce_variance(a, axis=0)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[7.23667219e-02, 2.95270830e-02, 3.00707802e-06, 1.09213874e-01],
       [1.19920099e+00, 5.99097647e-02, 3.36180851e-02, 1.86295557e+00],
       [4.77307022e-01, 8.33240747e-01, 2.54695624e-01, 4.34452057e-01]],
      dtype=float32)>

In [34]:
# # 注意:axis参数也可以为元组;第0个维度上所有数据的方差
tf.math.reduce_variance(a, axis=(1, 2))

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.79916316, 0.49603343], dtype=float32)>

In [35]:
tf.math.reduce_variance(a, axis=0, keepdims=True).shape  # 保留维度信息(进行广播时使用)

TensorShape([1, 3, 4])