In [125]:
import tensorflow as tf

### 参考numpy/基本操作/数组乘积/数据类型之间的乘积

#### 标量 $ \times $ 标量

In [126]:
scalar1 = tf.constant(3)
scalar2 = tf.constant(4)

scalar1 * scalar2

<tf.Tensor: shape=(), dtype=int32, numpy=12>

#### 标量 $ \times $ 向量

In [127]:
vector1 = tf.constant([1, 2, 3, 4])
print(scalar1 * vector1)  # 等价于3 * vector1(广播)

tf.Tensor([ 3  6  9 12], shape=(4,), dtype=int32)


#### 标量 $ \times $ 矩阵

In [128]:
martrix1 = tf.constant([[1, 2, 3, 4],
                        [2, 3, 4, 5]])
print(scalar1 * martrix1)  # 等价于 3 * martrix1(广播机制)

tf.Tensor(
[[ 3  6  9 12]
 [ 6  9 12 15]], shape=(2, 4), dtype=int32)


#### 向量 $ \times @ $ 向量

In [129]:
vector1 = tf.constant([1, 2, 3, 4])
vector2 = tf.constant([2, 3, 4, 5])
vector1 * vector2  # 对应元素相乘

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 2,  6, 12, 20])>

In [130]:
tf.reduce_sum(vector1 * vector2)  # ★★★★★向量的(典范)内积(点积,数量积)

<tf.Tensor: shape=(), dtype=int32, numpy=40>

In [131]:
tf.reshape(vector1, (4, 1)) @ tf.reshape(vector2, (1, 4))  # [4, 1] @ [1, 4] --> [4, 4](矩阵代数)

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[ 2,  3,  4,  5],
       [ 4,  6,  8, 10],
       [ 6,  9, 12, 15],
       [ 8, 12, 16, 20]])>

#### 向量 $ \times @ $ 矩阵

In [132]:
martrix1 = tf.constant([[1, 2, 3, 4],
                        [2, 3, 4, 5]])
print(vector1 * martrix1)  # 广播机制[2, 4] broadcasting [4] --> [2, 4]
print(martrix1 * vector1)  # 可交换顺序

tf.Tensor(
[[ 1  4  9 16]
 [ 2  6 12 20]], shape=(2, 4), dtype=int32)
tf.Tensor(
[[ 1  4  9 16]
 [ 2  6 12 20]], shape=(2, 4), dtype=int32)


In [133]:
tf.constant([[1, 2]]) @ martrix1  # [1, 2] @ [2, 4] --> [1, 4]

<tf.Tensor: shape=(1, 4), dtype=int32, numpy=array([[ 5,  8, 11, 14]])>

In [134]:
martrix1 @ tf.reshape(vector1, (-1, 1))  # [2, 4] @ [4, 1] --> [2, 1]

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[30],
       [40]])>

In [135]:
# Both matrices must be of the same type
# The inputs must, following any transpositions, be tensors of rank >= 2 where the inner 2 dimensions specify valid matrix multiplication dimensions, and any further outer dimensions specify matching batch size.
tf.matmul(martrix1, tf.reshape(vector1, (-1, 1)))  # 与上等价;

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[30],
       [40]])>

#### 矩阵 $ \times @ $ 矩阵

In [136]:
martrix1 = tf.constant([[1, 2, 3, 4], [2, 3, 4, 5]])
martrix2 = tf.constant([[0, 0, 0, 0], [1, 1, 1, 1]])

martrix1 * martrix2  # 对应元素相乘

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[0, 0, 0, 0],
       [2, 3, 4, 5]])>

In [137]:
martrix1 @ tf.reshape(martrix2, (4, 2))  # 必须满足矩阵代数运算法则

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[7, 7],
       [9, 9]])>

In [138]:
tf.matmul(martrix1, tf.reshape(martrix2, (4, 2)))  # 与上等价

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[7, 7],
       [9, 9]])>

#### 高维矩阵 @ 高维矩阵

In [139]:
a = tf.random.stateless_normal(shape=(4, 3, 5, 12, 9), seed=(1, 2))
b = tf.random.stateless_normal(shape=(4, 3, 5, 9, 7), seed=(1, 2))

print(a.shape)
print(b.shape)

(4, 3, 5, 12, 9)
(4, 3, 5, 9, 7)


In [140]:
out = a @ b
# [4, 3, 5, 12, 9] @ [4, 3, 5, 9, 7] -->
# 1. [4, 3, 5] 不变(批次的概念)
# 2. [12, 9] @ [9, 7] --> [12, 7]
# 3. [4, 3, 5, 12, 7]
out.shape

TensorShape([4, 3, 5, 12, 7])

In [141]:
tf.matmul(a, b).shape  # 与上等价

TensorShape([4, 3, 5, 12, 7])

In [142]:
c = tf.random.stateless_normal(shape=(4, 1, 5, 9, 8), seed=(1, 2))
# [4, 3, 5, 12, 9] @ [4, 1, 5, 9, 8] -->
# 1. [4, 3, 5] broadcasting [4, 1, 5] --> [4, 3, 5]
# 2. [12, 9] @ [9, 8] --> [12, 8]
# 3. [4, 3, 5, 12, 8]
out1 = a @ c
out1.shape

TensorShape([4, 3, 5, 12, 8])

In [143]:
tf.matmul(a, c).shape  # 与上等价

TensorShape([4, 3, 5, 12, 8])

In [144]:
a1 = tf.random.stateless_normal(shape=(4, 1, 5, 28, 64), seed=(1, 2))
b1 = tf.random.stateless_normal(shape=(1, 3, 1, 64, 32), seed=(1, 2))
# [4, 1, 5, 28, 64] @ [1, 3, 1, 64, 32] -->
# 1. [4, 1, 5] broadcasting [1, 3, 1] --> [4, 3, 5]
# 2. [28, 64] @ [64, 32] --> [28, 64]
# 3. [4, 3, 5, 28, 64]
out2 = a1 @ b1
out2.shape

TensorShape([4, 3, 5, 28, 32])

In [145]:
tf.matmul(a1, b1).shape  # 与上等价

TensorShape([4, 3, 5, 28, 32])