In [12]:
import tensorflow as tf

### 参考类似numpy/基本操作/数组乘积/数据类型之间的转换

In [13]:
tor_scalar_vetor = tf.reshape(tf.constant(10), (1,))  # 标量转向量(法一)
tor_scalar_vetor.shape

TensorShape([1])

In [14]:
tor_scalar_vetor1 = tf.expand_dims(tf.constant(10), 0)  # 标量转向量(法二)
tor_scalar_vetor1

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([10])>

In [15]:
tor_scalar_matrix = tf.reshape(tf.constant(10), (1, 1))  # 标量转矩阵(法一)
tor_scalar_matrix.shape

TensorShape([1, 1])

In [16]:
tor_scalar_matrix1 = tf.expand_dims(tf.expand_dims(tf.constant(10), 0), 0)  # 标量转矩阵(法二)
print(tor_scalar_matrix.shape)  # (0维度尺寸=1, 1维度尺寸=1)
print(tor_scalar_matrix)

(1, 1)
tf.Tensor([[10]], shape=(1, 1), dtype=int32)


In [17]:
tor_vector_matrix = tf.reshape(tf.constant([1, 2, 3]), (1, 3))  # 向量转矩阵(法一)
print(tor_vector_matrix.shape)  # (0维度尺寸=1, 1维度尺寸=3)
print(tor_vector_matrix)

(1, 3)
tf.Tensor([[1 2 3]], shape=(1, 3), dtype=int32)


In [18]:
tor_vector_matrix1 = tf.expand_dims(tf.constant([1, 2, 3]), 0)  # 向量转矩阵(法二)
print(tor_vector_matrix1.shape)  # (0维度尺寸=1, 1维度尺寸=3)--->数学中的行向量
print(tor_vector_matrix1)

(1, 3)
tf.Tensor([[1 2 3]], shape=(1, 3), dtype=int32)


In [19]:
tor_vector_mul_matrix = tf.reshape(tf.constant([1, 2, 3]), (1, 1, 3, 1, 1))  # 高维矩阵
tor_vector_mul_matrix

<tf.Tensor: shape=(1, 1, 3, 1, 1), dtype=int32, numpy=
array([[[[[1]],

         [[2]],

         [[3]]]]])>

In [20]:
tor_vector_mul_matrix = tf.expand_dims(
    tf.expand_dims(
        tf.expand_dims(
            tf.expand_dims(
                tf.constant([1, 2, 3]), 0), 0), -1), -1)  # 高维矩阵;与上等价
tor_vector_mul_matrix

<tf.Tensor: shape=(1, 1, 3, 1, 1), dtype=int32, numpy=
array([[[[[1]],

         [[2]],

         [[3]]]]])>