In [ ]:
import tensorflow as tf

### 参考类似numpy/基本操作数组乘积/数据类型

## 标量/scalar

In [ ]:
arr_scalar = tf.constant(10)  # 标量
print(arr_scalar.ndim)
print(arr_scalar.shape)
print(arr_scalar)

#### 向量/vector

In [12]:
arr_vector = tf.constant([1, 2, 3])  # 向量
print(arr_vector.ndim)
print(arr_vector.shape)
print(arr_vector)

1
(3,)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)


#### 矩阵/matrix

In [13]:
arr_matrix = tf.constant([[1, 2, 3], [2, 3, 4]])  # 矩阵
print(arr_matrix.ndim)
print(arr_matrix.shape)
print(arr_matrix)

2
(2, 3)
tf.Tensor(
[[1 2 3]
 [2 3 4]], shape=(2, 3), dtype=int32)


#### 高维矩阵(ndim>2)

In [14]:
arr_mul_matrix = tf.random.stateless_normal(shape=(3, 4, 5), seed=(1, 2))
print(arr_mul_matrix.ndim)
print(arr_mul_matrix.shape)
print(arr_mul_matrix)



3
(3, 4, 5)
tf.Tensor(
[[[ 0.5441101   0.20738031  0.07356433  0.04643455 -1.30159   ]
  [-0.95385665  0.84172857  1.9396868   0.6512578   1.1048867 ]
  [ 1.3746228   1.148752    1.0821314   0.55104923  0.07009614]
  [ 0.707385    0.88857085 -0.46432722  1.2084333  -0.79011595]]

 [[-0.7304904  -0.7207538   0.36527526 -0.16950758  0.20318079]
  [-0.90232295 -0.65045786  2.4152768   0.5703469   0.8770354 ]
  [ 0.36876458 -0.57617044 -0.66170377 -1.0227758   0.6109012 ]
  [-0.2563904   2.1067173  -0.04597485 -0.2069098   0.6324636 ]]

 [[ 0.42266     0.05165391 -0.73736423 -1.1144085   0.4858592 ]
  [-1.4368211   1.7883171   0.47844714 -1.3764827   0.79399854]
  [-2.1332254  -0.17303157 -1.7487346  -0.46926638 -1.5576217 ]
  [-0.8941696   0.21992801  0.148727   -0.8418422  -1.4702468 ]]], shape=(3, 4, 5), dtype=float32)
