In [13]:
import tensorflow as tf

### 参考numpy布尔索引

In [14]:
target = tf.constant([1, 2, 3, 1, 3, 2, 2])
data = tf.random.stateless_normal(shape=(7, 4), seed=(1, 2))
print(target)
print(data)

tf.Tensor([1 2 3 1 3 2 2], shape=(7,), dtype=int32)
tf.Tensor(
[[ 0.5441101   0.20738031  0.07356433  0.04643455]
 [-1.30159    -0.95385665  0.84172857  1.9396868 ]
 [ 0.6512578   1.1048867   1.3746228   1.148752  ]
 [ 1.0821314   0.55104923  0.07009614  0.707385  ]
 [ 0.88857085 -0.46432722  1.2084333  -0.79011595]
 [-0.7304904  -0.7207538   0.36527526 -0.16950758]
 [ 0.20318079 -0.90232295 -0.65045786  2.4152768 ]], shape=(7, 4), dtype=float32)


In [15]:
check = target == 1
print(check.dtype)
print(check)

<dtype: 'bool'>
tf.Tensor([ True False False  True False False False], shape=(7,), dtype=bool)


In [16]:
# mask: K-D boolean Tensor, K <= N and K must be known statically.
# tensorflow布尔索引必须使用boolean_mask方法
tf.boolean_mask(data, mask=check)  # 默认axis=0

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[0.5441101 , 0.20738031, 0.07356433, 0.04643455],
       [1.0821314 , 0.55104923, 0.07009614, 0.707385  ]], dtype=float32)>

In [17]:
tf.boolean_mask(data, check[:4], axis=1)  # # 第一个维度上的布尔索引

<tf.Tensor: shape=(7, 2), dtype=float32, numpy=
array([[ 0.5441101 ,  0.04643455],
       [-1.30159   ,  1.9396868 ],
       [ 0.6512578 ,  1.148752  ],
       [ 1.0821314 ,  0.707385  ],
       [ 0.88857085, -0.79011595],
       [-0.7304904 , -0.16950758],
       [ 0.20318079,  2.4152768 ]], dtype=float32)>

In [18]:
tf.boolean_mask(data, target == 1)[:, 2:]

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.07356433, 0.04643455],
       [0.07009614, 0.707385  ]], dtype=float32)>

In [19]:
print(target != 1)
print(~(target != 1))  # ~:取反
print(tf.boolean_mask(data, ~(target != 1)))

tf.Tensor([False  True  True False  True  True  True], shape=(7,), dtype=bool)
tf.Tensor([ True False False  True False False False], shape=(7,), dtype=bool)
tf.Tensor(
[[0.5441101  0.20738031 0.07356433 0.04643455]
 [1.0821314  0.55104923 0.07009614 0.707385  ]], shape=(2, 4), dtype=float32)


In [20]:
mask = (target == 1) | (target == 3)  # |:并集,不能使用关键字or
print(mask)
print(tf.boolean_mask(data, mask))

tf.Tensor([ True False  True  True  True False False], shape=(7,), dtype=bool)
tf.Tensor(
[[ 0.5441101   0.20738031  0.07356433  0.04643455]
 [ 0.6512578   1.1048867   1.3746228   1.148752  ]
 [ 1.0821314   0.55104923  0.07009614  0.707385  ]
 [ 0.88857085 -0.46432722  1.2084333  -0.79011595]], shape=(4, 4), dtype=float32)


In [21]:
mask1 = (target == 1) & (target == 3)  # &:交集,不能使用关键字and
print(mask1)
print(tf.boolean_mask(data, mask1))

tf.Tensor([False False False False False False False], shape=(7,), dtype=bool)
tf.Tensor([], shape=(0, 4), dtype=float32)


In [22]:
s = data < 0
s

<tf.Tensor: shape=(7, 4), dtype=bool, numpy=
array([[False, False, False, False],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True, False,  True],
       [ True,  True, False,  True],
       [False,  True,  True, False]])>

In [23]:
# 所有s中不为False处的元素
print(tf.boolean_mask(data, s).shape)
print(tf.boolean_mask(data, s))

(9,)
tf.Tensor(
[-1.30159    -0.95385665 -0.46432722 -0.79011595 -0.7304904  -0.7207538
 -0.16950758 -0.90232295 -0.65045786], shape=(9,), dtype=float32)
