In [1]:
import torch
import numpy as np

a = np.array([[1.2, 2, 3],
              [2, 3, 4]])
x = torch.tensor(a) 
x

tensor([[1.2000, 2.0000, 3.0000],
        [2.0000, 3.0000, 4.0000]], dtype=torch.float64)

In [2]:
# 类似numpy相关属性
x.dtype

torch.float64

In [3]:
print(x.ndim)
print(x.dim()) # 与上等价

2
2


In [4]:
print(x.shape)
print(x.size()) # 与上等价

torch.Size([2, 3])
torch.Size([2, 3])


In [5]:
list(x.shape)

[2, 3]

In [6]:
x.shape[0]

2

In [7]:
x.shape[1]

3

In [8]:
y = torch.randn(3, 5, 7)
y.shape

torch.Size([3, 5, 7])

In [9]:
y.T.shape # 若self.ndim <2则返回其本身

torch.Size([7, 5, 3])

In [10]:
torch.transpose(y, 0, -1).shape # 与上等价

torch.Size([7, 5, 3])

In [11]:
y.device

device(type='cpu')

In [12]:
# y.data与y共享数据内存地址
# y.data的任何改变都会致使y改变
y.data = torch.tensor([1, 2, 3])
print(y)
y.data.fill_(0)
print(y)


# y1与y共享数据内存地址
# 只有不改变y1内存地址的操作时才会指使y改变
y1 = y.detach()
y1.fill_(2)
print(y)

y1.add_(10) # in-place操作,y1内存地址不变
print(y) # y发生相应改变

print(id(y1))
y1 = [-1, -2, -3]
print(id(y1)) # y1内存地址改变
print(y) # y不变

tensor([1, 2, 3])
tensor([0, 0, 0])
tensor([2, 2, 2])
tensor([12, 12, 12])
140559389839864
140559390669000
tensor([12, 12, 12])


In [13]:
y.data = torch.ones_like(y) # 任意修改y.data
y # y发生相应改变

tensor([1, 1, 1])

In [16]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
y = y.to(device)
print(y)
print(y.is_cuda) # Is True if the Tensor is stored on the GPU, False otherwise.

tensor([1, 1, 1], device='cuda:0')
True
