In [27]:
import tensorflow as tf

In [28]:
tor = tf.constant([1, 1, 2, 4, 4, 4, 7, 8, 8])  # tor必须为1维张量
tor

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 1, 2, 4, 4, 4, 7, 8, 8])>

### 参考numpy.unique

In [29]:
# This operation returns a tensor y containing all of the unique elements of x sorted in the same order that they occur in x.
# This operation also returns a tensor idx the same size as x that contains the index of each value of x in the unique output y.
# Finally, it returns a third tensor count that contains the count of each element of y in x. In other words:
a = tf.unique_with_counts(tor)  # Finds unique elements in a 1-D tensor.

print(a.y)  # 唯一值(顺序保持不变)
print(a.idx)  # 唯一值索引
print(a.count)  # 唯一值出现的次数

tf.Tensor([1 2 4 7 8], shape=(5,), dtype=int32)
tf.Tensor([0 0 1 2 2 2 3 4 4], shape=(9,), dtype=int32)
tf.Tensor([2 1 3 1 2], shape=(5,), dtype=int32)
