In [32]:
import tensorflow as tf

### 参考arr.astype

In [33]:
# tensorflow常见数据类型
# tf.int16:     Signed 16-bit integer.
# tf.int32:     Signed 32-bit integer.
# tf.int64:     Signed 64-bit integer.
# tf.float16:   16-bit (half precision) floating-point.
# tf.float32:   32-bit (single precision) floating-point.
# tf.float64:   64-bit (double precision) floating-point.
# tf.double:    64-bit (double precision) floating-point.
# tf.bool:      Boolean

# tf.string:    Variable-length string, represented as byte array.v


In [34]:
x = tf.constant([1.8, 2.2], dtype=tf.float32)
tf.cast(x, tf.int32)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2])>

In [35]:
y = tf.constant([1, 2])

print(tf.cast(y, tf.bool))
print(tf.cast(y, tf.double))

tf.Tensor([ True  True], shape=(2,), dtype=bool)
tf.Tensor([1. 2.], shape=(2,), dtype=float64)


In [36]:
z = tf.constant(['2', '3'])
z.dtype

tf.string

In [39]:
# 不支持string类型和数字类型的转换
tf.cast(z, tf.int32)

UnimplementedError: Cast string to int32 is not supported [Op:Cast]