In [36]:
import tensorflow as tf

### zeros/zeros_like
1. 完全类似numpy.zeros
2. 完全类似numpy.zeros_like

In [37]:
tf.zeros((2, 3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [38]:
tensor = tf.constant([[1, 2, 3],
                      [4, 5, 6]])
tf.zeros_like(tensor)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0]])>

### ones/ones_like
1. 完全类似numpy.ones
2. 完全类似numpy.ones_like

In [39]:
tf.ones((2, 3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

### eye
1. 类似numpy.eye

In [40]:
# 对角线元素为1
tf.eye(3)  # 默认num_rows=num_columns

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [41]:
tf.eye(num_rows=3,  # 行数
       num_columns=6)  # 列数

<tf.Tensor: shape=(3, 6), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]], dtype=float32)>

### fill
1. 完全类似numpy.full

In [42]:
tf.fill((2, 3), 3.141592)


<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[3.141592, 3.141592, 3.141592],
       [3.141592, 3.141592, 3.141592]], dtype=float32)>