In [1]:
import torch

x = torch.ones((2, 3))
x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [2]:
y = torch.zeros((2, 3))
y

tensor([[0., 0., 0.],
        [0., 0., 0.]])

### 参考numpy.stack

In [ ]:
# All tensors need to be of the same size.
a = torch.stack((x, y), dim=0)  # Concatenates sequence of tensors along a new dimension.
a

In [4]:
a[0]  # 即x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [5]:
a[1]  # 即y

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
b = torch.stack((x, y), dim=1)
b

tensor([[[1., 1., 1.],
         [0., 0., 0.]],

        [[1., 1., 1.],
         [0., 0., 0.]]])

In [7]:
b[:, 0]  # 即x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
b[:, 1]  # 即y

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
c = torch.stack((x, y), dim=2)
c

tensor([[[1., 0.],
         [1., 0.],
         [1., 0.]],

        [[1., 0.],
         [1., 0.],
         [1., 0.]]])

In [10]:
c[..., 0]  # 即x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [11]:
c[..., 1]  # 即y

tensor([[0., 0., 0.],
        [0., 0., 0.]])