In [89]:
import torch

x = torch.ones((2, 3))
x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [90]:
y = torch.zeros((2, 3))
y

tensor([[0., 0., 0.],
        [0., 0., 0.]])

### 参考numpy.stack

In [91]:
# All tensors need to be of the same size.
a = torch.stack([x, y], dim=0)  # Concatenates sequence of tensors along a new dimension.
a

tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])

In [92]:
a[0]  # 即x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [93]:
a[1]  # 即y

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [94]:
b = torch.stack((x, y), dim=1)
b

tensor([[[1., 1., 1.],
         [0., 0., 0.]],

        [[1., 1., 1.],
         [0., 0., 0.]]])

tensor([[[1., 1., 1.],
         [0., 0., 0.]],

        [[1., 1., 1.],
         [0., 0., 0.]]])

In [95]:
b[:, 0]  # 即x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [96]:
b[:, 1]  # 即y

tensor([[0., 0., 0.],
        [0., 0., 0.]])

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [97]:
c = torch.stack((x, y), dim=2)
c

tensor([[[1., 0.],
         [1., 0.],
         [1., 0.]],

        [[1., 0.],
         [1., 0.],
         [1., 0.]]])

tensor([[[1., 0.],
         [1., 0.],
         [1., 0.]],

        [[1., 0.],
         [1., 0.],
         [1., 0.]]])

In [98]:
c[..., 0]  # 即x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [99]:
c[..., 1]  # 即y

tensor([[0., 0., 0.],
        [0., 0., 0.]])

tensor([[0., 0., 0.],
        [0., 0., 0.]])