In [23]:
import torch

x = torch.ones((2, 3))
x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [24]:
y = torch.zeros((2, 3))
y

tensor([[0., 0., 0.],
        [0., 0., 0.]])

### 参考numpy.stack

In [25]:
# All tensors need to be of the same size.
# Concatenates sequence of tensors along a new dimension.
a = torch.stack([x, y], dim=0)
a

tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])

In [26]:
a[0]  # 即x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [27]:
a[1]  # 即y

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [28]:
b = torch.stack((x, y), dim=1)
b

tensor([[[1., 1., 1.],
         [0., 0., 0.]],

        [[1., 1., 1.],
         [0., 0., 0.]]])

In [29]:
b[:, 0]  # 即x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [30]:
b[:, 1]  # 即y

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [31]:
c = torch.stack((x, y), dim=2)
c

tensor([[[1., 0.],
         [1., 0.],
         [1., 0.]],

        [[1., 0.],
         [1., 0.],
         [1., 0.]]])

In [32]:
c[..., 0]  # 即x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [33]:
c[..., 1]  # 即y

tensor([[0., 0., 0.],
        [0., 0., 0.]])