In [70]:
import torch

In [71]:
x = torch.ones((2, 3))
x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [72]:
y = torch.zeros((2, 3))
y

tensor([[0., 0., 0.],
        [0., 0., 0.]])

### 参考numpy.stack

In [73]:
# All tensors need to be of the same size.
# Concatenates sequence of tensors along a new dimension.
a = torch.stack([x, y], dim=0)
print(a)
print(a.shape)

tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])


In [74]:
a[0]  # 即x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [75]:
a[1]  # 即y

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [76]:
b = torch.stack((x, y), dim=1)
print(b)
print(b.shape)

tensor([[[1., 1., 1.],
         [0., 0., 0.]],

        [[1., 1., 1.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])


In [77]:
b[:, 0]  # 即x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [78]:
b[:, 1]  # 即y

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [79]:
c = torch.stack((x, y), dim=2)
print(c)
print(c.shape)

tensor([[[1., 0.],
         [1., 0.],
         [1., 0.]],

        [[1., 0.],
         [1., 0.],
         [1., 0.]]])
torch.Size([2, 3, 2])


In [80]:
c[..., 0]  # 即x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [81]:
c[..., 1]  # 即y

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [82]:
d = torch.stack((x, y), dim=-1)  # 等价于c
print(d)
print(d.shape)

tensor([[[1., 0.],
         [1., 0.],
         [1., 0.]],

        [[1., 0.],
         [1., 0.],
         [1., 0.]]])
torch.Size([2, 3, 2])
