In [50]:
from sklearn.preprocessing import KBinsDiscretizer

X = [[-2, 1, -4,   -1],
     [-1, 2, -3, -0.5],
     [ 0, 3, -2,  0.5],
     [ 1, 4, -1,    2]]
est = KBinsDiscretizer(n_bins=[3, 2, 2, 4], encode='onehot', strategy='uniform') # 使用onehot进行编码
est.fit(X)

KBinsDiscretizer(encode='onehot', n_bins=[3, 2, 2, 4], strategy='uniform')

In [51]:
Xt = est.transform(X)
Xt # Compressed Sparse Row matrix

<4x11 sparse matrix of type '<class 'numpy.float64'>'
	with 16 stored elements in Compressed Sparse Row format>

In [52]:
Xt.toarray() # 转换为array

array([[1., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 1., 0., 1., 0., 0., 1., 0.],
       [0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 1.]])

In [53]:
est.bin_edges_
# 区间解析(对列/特征进行)
# 特征1:[-2, -1) [-1, 0),[0, 1] -->故-2通过onehot变为1, 0, 0;-1通过onehot变为0, 1, 0,0通过onehot变为0, 0, 1;1通过onehot变为0, 0, 1
# 特征2:[1, 2.5) [2.5, 4]
# 特征3:[-4, -2.5) [-2.5, -1]
# 特征4:[-1, -0.25) [-0.25, 0.5) [0.5, 1.25) [1.25, 2]

array([array([-2., -1.,  0.,  1.]), array([1. , 2.5, 4. ]),
       array([-4. , -2.5, -1. ]),
       array([-1.  , -0.25,  0.5 ,  1.25,  2.  ])], dtype=object)

In [56]:
est1 = KBinsDiscretizer(n_bins=[3, 2, 2, 4], encode='ordinal', strategy='uniform') # 使用ordinal进行编码
est1.fit(X)
Xt1 = est1.transform(X)
Xt1

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [2., 1., 1., 2.],
       [2., 1., 1., 3.]])

In [59]:
est1.bin_edges_
# 区间解析(对列/特征进行)
# 特征1:[-2, -1) [-1, 0),[0, 1] -->故-2通过ordinal变为0;-1通过ordinal变为1;通过ordinal变为2;1通过ordinal变为2
# 特征2:[1, 2.5) [2.5, 4]
# 特征3:[-4, -2.5) [-2.5, -1]
# 特征4:[-1, -0.25) [-0.25, 0.5) [0.5, 1.25) [1.25, 2]

array([array([-2., -1.,  0.,  1.]), array([1. , 2.5, 4. ]),
       array([-4. , -2.5, -1. ]),
       array([-1.  , -0.25,  0.5 ,  1.25,  2.  ])], dtype=object)