In [55]:
import tensorflow as tf

In [56]:
ds = tf.data.Dataset.from_tensor_slices(["hello world", "hello China", "hello Beijing"])
print(ds._tensors)


def func(x):
    return tf.strings.split(x, " ")


# Maps map_func across the elements of this dataset.
'''
map_func:	        A function mapping a dataset element to another dataset element.
num_parallel_calls:	(Optional.) A tf.int64 scalar tf.Tensor, representing the number elements to process asynchronously in parallel.
                    If not specified, elements will be processed sequentially.
                    If the value tf.data.AUTOTUNE is used, then the number of parallel calls is set dynamically based on available CPU.
'''
ds_map = ds.map(func, num_parallel_calls=tf.data.AUTOTUNE)
for x in ds_map.as_numpy_iterator():
    print(x)

[<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'hello world', b'hello China', b'hello Beijing'], dtype=object)>]
[b'hello' b'world']
[b'hello' b'China']
[b'hello' b'Beijing']


In [57]:
dataset = tf.data.Dataset.from_tensor_slices({'a': [1, 2, 3],
                                              'b': ['a', 'b', 'c']})
print(list(dataset.as_numpy_iterator()))


def f(x):
    # The value or values returned by map_func determine the structure of each element in the returned dataset.
    return x['a'], x['b'], tf.constant(["Foo", "Bar", "Baz"])  # 返回值为元组


result = dataset.map(f)
for i in result.as_numpy_iterator():
    print(type(i))  # 元组
    print(i, end='\n\n')

[{'a': 1, 'b': b'a'}, {'a': 2, 'b': b'b'}, {'a': 3, 'b': b'c'}]
<class 'tuple'>
(1, b'a', array([b'Foo', b'Bar', b'Baz'], dtype=object))

<class 'tuple'>
(2, b'b', array([b'Foo', b'Bar', b'Baz'], dtype=object))

<class 'tuple'>
(3, b'c', array([b'Foo', b'Bar', b'Baz'], dtype=object))



In [58]:
x = tf.linspace(0.0, 0.1, 100)
y = tf.reshape(tf.linspace(1, 400, 400), (100, 2, 2))
z = tf.range(1000, 1100)
dataset = tf.data.Dataset.from_tensor_slices((x, y, z))


def g(a, b, c):  # 形参列表与dataset的每个元素一一对应(★★★★★元组进行了自动解包操作)
    return a, tf.reshape(b, (4,)), c


result = dataset.map(g)
for i, j, k in result.as_numpy_iterator():
    print(i)
    print(j)
    print(k)
    print()




0.0
[1. 2. 3. 4.]
1000

0.001010101
[5. 6. 7. 8.]
1001

0.002020202
[ 9. 10. 11. 12.]
1002

0.0030303032
[13. 14. 15. 16.]
1003

0.004040404
[17. 18. 19. 20.]
1004

0.0050505055
[21. 22. 23. 24.]
1005

0.0060606063
[25. 26. 27. 28.]
1006

0.007070707
[29. 30. 31. 32.]
1007

0.008080808
[33. 34. 35. 36.]
1008

0.00909091
[37. 38. 39. 40.]
1009

0.010101011
[41. 42. 43. 44.]
1010

0.011111111
[45. 46. 47. 48.]
1011

0.012121213
[49. 50. 51. 52.]
1012

0.013131314
[53. 54. 55. 56.]
1013

0.014141414
[57. 58. 59. 60.]
1014

0.015151516
[61. 62. 63. 64.]
1015

0.016161617
[65. 66. 67. 68.]
1016

0.017171718
[69. 70. 71. 72.]
1017

0.01818182
[73. 74. 75. 76.]
1018

0.01919192
[77. 78. 79. 80.]
1019

0.020202022
[81. 82. 83. 84.]
1020

0.021212121
[85. 86. 87. 88.]
1021

0.022222223
[89. 90. 91. 92.]
1022

0.023232324
[93. 94. 95. 96.]
1023

0.024242425
[ 97.  98.  99. 100.]
1024

0.025252527
[101. 102. 103. 104.]
1025

0.026262628
[105. 106. 107. 108.]
1026

0.02727273
[109. 110. 111. 112.]