In [18]:
import tensorflow as tf

In [19]:
dataset = tf.data.Dataset.from_tensor_slices([[1, 2, 3],
                                              [-1, -2, -3]])

# Repeats this dataset so each original value is seen count times.
dataset = dataset.repeat(count=3)

list(dataset.as_numpy_iterator())

[array([1, 2, 3]),
 array([-1, -2, -3]),
 array([1, 2, 3]),
 array([-1, -2, -3]),
 array([1, 2, 3]),
 array([-1, -2, -3])]