In [5]:
import numpy as np

a = np.random.randn(3, 4)
a

array([[ 0.30138889,  0.80631459, -0.33968701, -0.35609516],
       [ 0.76241092,  0.31768299, -1.29063805, -1.46778334],
       [-1.15675918,  0.58471511,  1.38115456,  1.47405611]])

In [6]:
# 完全类似numpy.max/min/mean
np.max(a)

1.474056114460356

In [7]:
np.max(a, axis=0)

array([0.76241092, 0.80631459, 1.38115456, 1.47405611])

In [8]:
np.min(a)

-1.4677833447383486

In [9]:
np.min(a, axis=1)

array([-0.35609516, -1.46778334, -1.15675918])