In [6]:
import numpy as np

In [7]:
np.arange(10)  # 创建从0到10的数组(默认从0开始,不含末尾元素10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(3, 8)  # 创建从3到8的数组(不含末尾元素8)

array([3, 4, 5, 6, 7])

In [9]:
np.arange(3, 8, 2)  # 步长为2

array([3, 5, 7])

In [10]:
np.arange(8, 2, -2)  # 步长为-2

array([8, 6, 4])