In [25]:
import numpy as np

In [26]:
arr_scalar = np.array(3)
print(type(arr_scalar))
print(arr_scalar)

<class 'numpy.ndarray'>
3


In [27]:
arr_vector = np.array(range(10), dtype=np.int32)
'''
object : array_like
    An array, any object exposing the array interface, an object whose
    __array__ method returns an array, or any (nested) sequence.

dtype : data-type, optional
    The desired data-type for the array. If not given, then the type will be determined as the minimum type required to hold the objects in the sequence. 

ndmin : int, optional
    Specifies the minimum number of dimensions that the resulting
    array should have.  Ones will be pre-pended to the shape as
    needed to meet this requirement.   
'''
print(arr_vector)

[0 1 2 3 4 5 6 7 8 9]


In [28]:
arr_lst = np.array([1, 2, 3])
print(arr_lst.ndim)
print(arr_lst)
print(arr_lst.T)  # nidim=1的数组,转置不变

1
[1 2 3]
[1 2 3]


In [29]:
arr_matrix = np.array([[1, 2, 3],
                       [2, 3, 4]])
print(arr_matrix.shape)  # 2 * 3的矩阵
print(arr_matrix)

(2, 3)
[[1 2 3]
 [2 3 4]]


In [30]:
a = [1, 2, 3, 4]
b = ['a', 'b', 'c', 'd', 'e']
arr3 = np.array([a, b])
print(arr3)
print(arr3.ndim)
print(arr3[0])  # [a, b]不是方阵!a/b被视为一个整体

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [31]:
a1 = [0, 1, 2, 3, np.nan]
b1 = ['a', 'b', 'c', 'd', 'e']
arr4 = np.array([a1, b1])
print(arr4)
# array元素只能有一种数据类型
print(arr4.dtype)  # dtype被综合成Unicode类型

[['0' '1' '2' '3' 'nan']
 ['a' 'b' 'c' 'd' 'e']]
<U32


In [32]:
class A:
    pass


class B:
    pass


a = A()
b = B()

arr_op = np.array([a, b])
print(arr_op.dtype)  # Object(对象)类型
print(arr_op)

object


In [33]:
lst = ['1', '2', '3', '3', 5]

# 可在数组创建的时将数字型字符串转换为float
# 可在数组创建的时升高数组维度
arr_re = np.array(lst, dtype=np.float64, ndmin=3).T

print(arr_re.dtype)
print(arr_re)

float64
[[[1.]]

 [[2.]]

 [[3.]]

 [[3.]]

 [[5.]]]


In [34]:
dic = {'a': 1, 'b': 2, 'c': 3, 'd': 4}

In [35]:
np.array(dic)  # 注意:dic被视为一个整体

array({'a': 1, 'b': 2, 'c': 3, 'd': 4}, dtype=object)

In [36]:
np.array(dic.values())  # 注意:dic.values被视为一个整体

array(dict_values([1, 2, 3, 4]), dtype=object)

In [37]:
np.array(dic.keys())  # 注意:dic.keys()被视为一个整体

array(dict_keys(['a', 'b', 'c', 'd']), dtype=object)

In [38]:
np.array(list(dic.keys()))  # 可能是你想要的结果

array(['a', 'b', 'c', 'd'], dtype='<U1')