In [1]:
import numpy as np

In [2]:
np.linspace(2.0, 3.0, num=5)  # 在指定的间隔内返回均匀间隔的数字

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [3]:
# np.linlogspace:Return numbers spaced evenly on a log scale
np.logspace(-2, 7, num=10, base=10)  # 以10为底

array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05,
       1.e+06, 1.e+07])

In [4]:
'''
endpoint : bool, optional
    If True, stop is the last sample. Otherwise, it is not included. Default is True.
'''
np.linspace(2.0, 3.0, num=5, endpoint=False)  # 默认num=50

array([2. , 2.2, 2.4, 2.6, 2.8])

In [5]:
'''
retstep : bool, optional
    If True, return (samples, step), where step is the spacing between samples.
'''
np.linspace(2.0, 3.0, num=5, retstep=True)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

In [6]:
np.linspace([1, 2, 4], [3, 6, 12], num=5)  # 返回多列等间隔数字

array([[ 1. ,  2. ,  4. ],
       [ 1.5,  3. ,  6. ],
       [ 2. ,  4. ,  8. ],
       [ 2.5,  5. , 10. ],
       [ 3. ,  6. , 12. ]])