## 特殊数组的创建
1.  numpy.eye
2.  numpy.ones/number.zeros_like
3.  numpy.zeros/number.zeros_like
4.  numpy.empty/numpy.empty_like
5.  numpy.full/number.full_like
5.  numpy.diag

In [32]:
import numpy as np
# Return a 2-D array with ones on the diagonal and zeros elsewhere.
'''
k : int, optional
    Index of the diagonal: 0 (the default) refers to the main diagonal, a positive value
    refers to an upper diagonal, and a negative value to a lower diagonal.
'''
print(np.eye(3))  # 默认k=0,dtype=float
print(np.eye(3, k=1), end='\n\n')
print(np.eye(3, k=2), end='\n\n')
print(np.eye(3, k=-1), end='\n\n')
print(np.eye(3, k=-2), end='\n\n')

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]

[[0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]

[[0. 0. 0.]
 [0. 0. 0.]
 [1. 0. 0.]]



In [33]:
# Return a new array of given shape and type, filled with ones.
print(np.ones(5), end='\n\n')  # 向量/vector
one = np.ones((2, 2))
print(one)
one_like = np.ones_like(one)
print(one_like)

[1. 1. 1. 1. 1.]

[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]


In [34]:
# Return a new array of given shape and type, filled with zeros.
print(np.zeros(5), end='\n\n')
print(np.zeros((2, 2)))

[0. 0. 0. 0. 0.]

[[0. 0.]
 [0. 0.]]


In [35]:
np.empty((2, 4))  # Return a new array of given shape and type, without initializing entries.

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 6.10665138e-321, 1.24611402e-306,
        8.34451927e-308]])

In [36]:
# Return a new array of given shape and type, filled with fill_value.
inf = np.full((2, 2), np.inf)
inf

array([[inf, inf],
       [inf, inf]])

In [37]:
e = np.full_like(inf, np.e)
e

array([[2.71828183, 2.71828183],
       [2.71828183, 2.71828183]])

In [38]:
x = np.arange(9).reshape((3,3))
print(x)
print(np.diag(x))  # Extract a diagonal
'''
k : int, optional
    Diagonal in question. The default is 0. Use k>0 for diagonals above the main 
    diagonal, and k<0 for diagonals below the main diagonal.
'''
print(np.diag(x, k=1))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 4 8]
[1 5]


In [39]:
print(np.diag((2, 3, 4)))  # construct a diagonal array.

[[2 0 0]
 [0 3 0]
 [0 0 4]]
