In [1]:
import numpy as np

In [2]:
'''
a1-D array-like or int
    If an ndarray, a random sample is generated from its elements. If an int, the random sample is generated as if it were np.arange(a)

sizeint or tuple of ints, optional
    Output shape. If the given shape is, e.g., (m, n, k), then m * n * k samples are drawn. Default is None, in which case a single value is returned.

replaceboolean, optional
    Whether the sample is with or without replacement. Default is True, meaning that a value of a can be selected multiple times.

p1-D array-like, optional
    The probabilities associated with each entry in a. If not given, the sample assumes a uniform distribution over all entries in a.
'''
# Generate a uniform random sample from np.arange(5) of size 3:
np.random.choice(5, 3)

array([3, 2, 4])

In [3]:
# np.random.choice(5, 3, p=[0.1, 0, 0.3, 0.6, 0])
np.random.choice(5, 3, p=[0.1, 0, 0.3, 0.6, 0])  # 默认replace=True,即又放回

array([2, 2, 3])

In [4]:
np.random.choice(5, 3, replace=False)

array([1, 0, 2])

In [5]:
aa_milne_arr = ['pooh', 'rabbit', 'piglet', 'Christopher']
np.random.choice(aa_milne_arr, 5, p=[0.5, 0.1, 0.1, 0.3])

array(['Christopher', 'Christopher', 'rabbit', 'Christopher',
       'Christopher'], dtype='<U11')