In [1]:
import numpy as np
import torch

In [ ]:
vocab = {}  # 词到索引的映射字典
token_id = 1  # token_id=0预留给填充符号
lengths = []  # 每句话的长度(即单词个数)

with open('test.txt', 'r') as f:
    for l in f:
        tokens = l.strip().split()  # 简单的英文分词(按空格切分)
        print(tokens)
        lengths.append(len(tokens))
        for t in tokens:
            if t not in vocab:
                vocab[t] = token_id
                token_id += 1
lengths = torch.tensor(lengths)

['like', 'to', 'choose', 'those', 'who', 'are', 'different', 'from', 'themselves', 'while', 'others', 'prefer', 'those', 'who', 'are', 'similar', 'to', 'themselves.']
['People', 'choose', 'friends', 'in', 'differrent', 'ways.']
['For', 'instance,', 'if', 'an', 'active', 'and', 'energetic', 'guy', 'proposes', 'to', 'his', 'equally', 'active', 'and', 'energetic', 'friends', 'that', 'they', 'should', 'have', 'some', 'activities,', 'it', 'is', 'more', 'likely', 'that', 'his', 'will', 'agree', 'at', 'once.']
['When', 'people', 'have', 'friends', 'similar', 'to', 'themselves,', 'they', 'and', 'their', 'friends', 'chat,', 'play,', 'and', 'do', 'thing', 'together', 'natually', 'and', 'harmoniously.']
['The', 'result', 'is', 'that', 'they', 'all', 'can', 'feel', 'relaxed', 'and', 'can', 'trully', 'enjoy', 'each', "other's", 'company.']


In [3]:
print(lengths)
print(vocab)

tensor([18,  6, 32, 20, 16])
{'like': 1, 'to': 2, 'choose': 3, 'those': 4, 'who': 5, 'are': 6, 'different': 7, 'from': 8, 'themselves': 9, 'while': 10, 'others': 11, 'prefer': 12, 'similar': 13, 'themselves.': 14, 'People': 15, 'friends': 16, 'in': 17, 'differrent': 18, 'ways.': 19, 'For': 20, 'instance,': 21, 'if': 22, 'an': 23, 'active': 24, 'and': 25, 'energetic': 26, 'guy': 27, 'proposes': 28, 'his': 29, 'equally': 30, 'that': 31, 'they': 32, 'should': 33, 'have': 34, 'some': 35, 'activities,': 36, 'it': 37, 'is': 38, 'more': 39, 'likely': 40, 'will': 41, 'agree': 42, 'at': 43, 'once.': 44, 'When': 45, 'people': 46, 'themselves,': 47, 'their': 48, 'chat,': 49, 'play,': 50, 'do': 51, 'thing': 52, 'together': 53, 'natually': 54, 'harmoniously.': 55, 'The': 56, 'result': 57, 'all': 58, 'can': 59, 'feel': 60, 'relaxed': 61, 'trully': 62, 'enjoy': 63, 'each': 64, "other's": 65, 'company.': 66}


In [4]:
x = np.zeros((len(lengths), max(lengths)))  # 将所有句子填充为最大的长度

l_no = 0
with open('test', 'r') as f:
    for l in f:
        tokens = l.strip().split()
        for i in range(len(tokens)):
            x[l_no, i] = vocab[tokens[i]]
        l_no += 1

x = torch.tensor(x, requires_grad=True)
x  # 每句话的数字形式(通过vocab字典)

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,  4.,  5.,
          6., 13.,  2., 14.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.],
        [15.,  3., 16., 17., 18., 19.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.],
        [20., 21., 22., 23., 24., 25., 26., 27., 28.,  2., 29., 30., 24., 25.,
         26., 16., 31., 32., 33., 34., 35., 36., 37., 38., 39., 40., 31., 29.,
         41., 42., 43., 44.],
        [45., 46., 34., 16., 13.,  2., 47., 32., 25., 48., 16., 49., 50., 25.,
         51., 52., 53., 54., 25., 55.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.],
        [56., 57., 38., 31., 32., 58., 59., 60., 61., 25., 59., 62., 63., 64.,
         65., 66.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.]], dtype=torch.float64, requires_grad=True)

In [5]:
# 所有句子长度(lenghts)按从大到小排序(降序),并返回排序后的索引idx_sort
lengths_sort, idx_sort = torch.sort(lengths, dim=0, descending=True)
print(lengths_sort)
print("idx_sort:", idx_sort)

tensor([32, 20, 18, 16,  6])
idx_sort: tensor([2, 3, 0, 4, 1])


In [6]:
# 对索引idx_sort进行从小到大排序,返回排序后的索引idx_unsort
idx_sort_sort, idx_unsort = torch.sort(idx_sort, dim=0)
print(idx_sort_sort)
print("idx_unsort:", idx_unsort)

tensor([0, 1, 2, 3, 4])
idx_unsort: tensor([2, 4, 0, 1, 3])


In [7]:
x1 = x[idx_sort]  # 将x根据句子长度进行降序排列
lengths1 = lengths[idx_sort]  # 排序后每个句子的长度(降序)
print("lenghts1:", lengths1)
print("x1的形状与内容:\n", x1)
print(x1.shape)  # 5个句子(可以理解为批次);每个批次的长度为32

lenghts1: tensor([32, 20, 18, 16,  6])
x1的形状与内容:
 tensor([[20., 21., 22., 23., 24., 25., 26., 27., 28.,  2., 29., 30., 24., 25.,
         26., 16., 31., 32., 33., 34., 35., 36., 37., 38., 39., 40., 31., 29.,
         41., 42., 43., 44.],
        [45., 46., 34., 16., 13.,  2., 47., 32., 25., 48., 16., 49., 50., 25.,
         51., 52., 53., 54., 25., 55.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,  4.,  5.,
          6., 13.,  2., 14.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.],
        [56., 57., 38., 31., 32., 58., 59., 60., 61., 25., 59., 62., 63., 64.,
         65., 66.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.],
        [15.,  3., 16., 17., 18., 19.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.]], dtype=tor

In [8]:
# 通过idx_unsort,x得到得到恢复
x2 = x1[idx_unsort]
print("x2的形状与内容:\n", x2)
print(x2.shape)

x2的形状与内容:
 tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,  4.,  5.,
          6., 13.,  2., 14.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.],
        [15.,  3., 16., 17., 18., 19.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.],
        [20., 21., 22., 23., 24., 25., 26., 27., 28.,  2., 29., 30., 24., 25.,
         26., 16., 31., 32., 33., 34., 35., 36., 37., 38., 39., 40., 31., 29.,
         41., 42., 43., 44.],
        [45., 46., 34., 16., 13.,  2., 47., 32., 25., 48., 16., 49., 50., 25.,
         51., 52., 53., 54., 25., 55.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.],
        [56., 57., 38., 31., 32., 58., 59., 60., 61., 25., 59., 62., 63., 64.,
         65., 66.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.]], dtype=torch.float64, grad_fn=<IndexBackward0>)
t

In [9]:
import torch.nn as nn

# x1已经根据长度进行降序排序
# lengths1为x1的长度
x1_packed = nn.utils.rnn.pack_padded_sequence(input=x1,
                                              lengths=lengths1,  # 每个批次序列的长度
                                              # if True, the input is expected in B x T x * format.
                                              batch_first=True)  # 这输入x1的形状为(B x T),故设置batch_fist=True
print(x1_packed)

PackedSequence(data=tensor([20., 45.,  1., 56., 15., 21., 46.,  2., 57.,  3., 22., 34.,  3., 38.,
        16., 23., 16.,  4., 31., 17., 24., 13.,  5., 32., 18., 25.,  2.,  6.,
        58., 19., 26., 47.,  7., 59., 27., 32.,  8., 60., 28., 25.,  9., 61.,
         2., 48., 10., 25., 29., 16., 11., 59., 30., 49., 12., 62., 24., 50.,
         4., 63., 25., 25.,  5., 64., 26., 51.,  6., 65., 16., 52., 13., 66.,
        31., 53.,  2., 32., 54., 14., 33., 25., 34., 55., 35., 36., 37., 38.,
        39., 40., 31., 29., 41., 42., 43., 44.], dtype=torch.float64,
       grad_fn=<PackPaddedSequenceBackward0>), batch_sizes=tensor([5, 5, 5, 5, 5, 5, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3, 3, 2, 2, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1]), sorted_indices=None, unsorted_indices=None)


### x1_packed解析
* 序列的第一个位置的非零元素:20, 45, 1, 56, 15. batch_size=5
* 序列的第二个位置的非零元素:46, 2, 57, 3, 22. batch_size=5
* 序列的第三个位置的非零元素:34, 3, 38, 16, 23. batch_size=5
* 序列的第四个位置的非零元素:16, 4, 31, 17, 24. batch_size=5
* ......

已经按长度降序排列,故sorted_indices=None,unsorted_indices=None

In [10]:
# x1没有根据长度进行降序排序
# lengths为x1的长度
# ★★★★★All RNN modules accept packed sequences as inputs
x_packed = nn.utils.rnn.pack_padded_sequence(input=x, lengths=lengths, batch_first=True,
                                             #  if True, the input is expected to contain sequences sorted by length in a decreasing order.
                                             #  If False, the input will get sorted unconditionally. Default: True.
                                             enforce_sorted=False)
print(x_packed)

PackedSequence(data=tensor([20., 45.,  1., 56., 15., 21., 46.,  2., 57.,  3., 22., 34.,  3., 38.,
        16., 23., 16.,  4., 31., 17., 24., 13.,  5., 32., 18., 25.,  2.,  6.,
        58., 19., 26., 47.,  7., 59., 27., 32.,  8., 60., 28., 25.,  9., 61.,
         2., 48., 10., 25., 29., 16., 11., 59., 30., 49., 12., 62., 24., 50.,
         4., 63., 25., 25.,  5., 64., 26., 51.,  6., 65., 16., 52., 13., 66.,
        31., 53.,  2., 32., 54., 14., 33., 25., 34., 55., 35., 36., 37., 38.,
        39., 40., 31., 29., 41., 42., 43., 44.], dtype=torch.float64,
       grad_fn=<PackPaddedSequenceBackward0>), batch_sizes=tensor([5, 5, 5, 5, 5, 5, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3, 3, 2, 2, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1]), sorted_indices=tensor([2, 3, 0, 4, 1]), unsorted_indices=tensor([2, 4, 0, 1, 3]))


### x_packed解析
1. 先对x进行降序排列,故
    * 序列的第一个位置的非零元素:20, 45, 1, 56, 15. batch_size=5
    * 序列的第二个位置的非零元素:46, 2, 57, 3, 22. batch_size=5
    * 序列的第三个位置的非零元素:34, 3, 38, 16, 23. batch_size=5
    * 序列的第四个位置的非零元素:16, 4, 31, 17, 24. batch_size=5
    * ......
2. sorted_indice为对x的长度排序后的索引
3. unsortd_indice为对sort_indice排序后的索引.其中x[sorted_indice][unsored_indice] = x
