In [ ]:
import torch

### 参考numpy索引切片

In [2]:
tor_mul = torch.randn(5, 7, 4)
tor_mul

tensor([[[-3.3322e-01, -5.4964e-01, -2.0999e+00, -1.4855e+00],
         [ 7.3260e-01, -1.9075e+00,  2.9797e-01,  6.2108e-01],
         [ 2.8965e-01,  3.4892e-01,  7.0525e-01, -7.3717e-01],
         [ 9.2437e-01,  1.8985e+00,  7.5068e-01,  2.3977e-01],
         [-1.0469e+00, -8.8869e-04, -8.1561e-01, -2.5237e-01],
         [-4.6160e-01, -2.0621e-01,  1.1680e+00,  4.0759e-01],
         [ 8.9391e-01,  6.7291e-02,  5.8258e-01, -5.4704e-01]],

        [[-1.4967e+00,  1.5177e+00,  1.1865e+00,  1.4493e+00],
         [ 1.2408e+00, -5.2175e-01,  1.2174e+00,  1.2270e-01],
         [-5.7148e-01, -8.3839e-01,  2.3823e+00,  1.6539e+00],
         [ 8.0902e-01, -4.0109e-02,  1.6013e-01,  1.5525e+00],
         [ 3.1471e-01, -9.0348e-01,  2.0222e-01, -3.2659e+00],
         [-2.0101e+00,  1.4985e+00, -5.0386e-01, -4.0798e-01],
         [ 4.0178e-01,  5.2924e-01,  4.2621e-01,  8.9017e-01]],

        [[-1.3038e+00,  8.0567e-01,  6.5355e-01,  1.4325e+00],
         [ 2.0008e-01, -1.2313e+00,  1.7509e+00, -3

In [3]:
tor_mul[0, 1, 1]  # 索引为标量tensor

tensor(-1.9075)

In [4]:
tor_mul[0]  # 从第零个维度开始索引切片(DataFrame从列开始进行索引切片)

tensor([[-3.3322e-01, -5.4964e-01, -2.0999e+00, -1.4855e+00],
        [ 7.3260e-01, -1.9075e+00,  2.9797e-01,  6.2108e-01],
        [ 2.8965e-01,  3.4892e-01,  7.0525e-01, -7.3717e-01],
        [ 9.2437e-01,  1.8985e+00,  7.5068e-01,  2.3977e-01],
        [-1.0469e+00, -8.8869e-04, -8.1561e-01, -2.5237e-01],
        [-4.6160e-01, -2.0621e-01,  1.1680e+00,  4.0759e-01],
        [ 8.9391e-01,  6.7291e-02,  5.8258e-01, -5.4704e-01]])

In [5]:
tor_mul[0, 0, -1]  # 索引,返回tensor.支持负数索引

tensor(-1.4855)

In [6]:
tor_mul[0:2]  # 切片,返回tensor

tensor([[[-3.3322e-01, -5.4964e-01, -2.0999e+00, -1.4855e+00],
         [ 7.3260e-01, -1.9075e+00,  2.9797e-01,  6.2108e-01],
         [ 2.8965e-01,  3.4892e-01,  7.0525e-01, -7.3717e-01],
         [ 9.2437e-01,  1.8985e+00,  7.5068e-01,  2.3977e-01],
         [-1.0469e+00, -8.8869e-04, -8.1561e-01, -2.5237e-01],
         [-4.6160e-01, -2.0621e-01,  1.1680e+00,  4.0759e-01],
         [ 8.9391e-01,  6.7291e-02,  5.8258e-01, -5.4704e-01]],

        [[-1.4967e+00,  1.5177e+00,  1.1865e+00,  1.4493e+00],
         [ 1.2408e+00, -5.2175e-01,  1.2174e+00,  1.2270e-01],
         [-5.7148e-01, -8.3839e-01,  2.3823e+00,  1.6539e+00],
         [ 8.0902e-01, -4.0109e-02,  1.6013e-01,  1.5525e+00],
         [ 3.1471e-01, -9.0348e-01,  2.0222e-01, -3.2659e+00],
         [-2.0101e+00,  1.4985e+00, -5.0386e-01, -4.0798e-01],
         [ 4.0178e-01,  5.2924e-01,  4.2621e-01,  8.9017e-01]]])

In [7]:
tor_mul[0:2, 0:3, 0]  # 在多个维度上索引切片

tensor([[-0.3332,  0.7326,  0.2896],
        [-1.4967,  1.2408, -0.5715]])

In [8]:
tor_mul[0:2, 0:6:2, 2]  # 第一个维度上的切片步长为2(不支持步长为负数),切片范围为0-6

tensor([[-2.0999,  0.7052, -0.8156],
        [ 1.1865,  2.3823,  0.2022]])

In [9]:
tor_mul[:]  # 等价于tor_mul[:, :, :]

tensor([[[-3.3322e-01, -5.4964e-01, -2.0999e+00, -1.4855e+00],
         [ 7.3260e-01, -1.9075e+00,  2.9797e-01,  6.2108e-01],
         [ 2.8965e-01,  3.4892e-01,  7.0525e-01, -7.3717e-01],
         [ 9.2437e-01,  1.8985e+00,  7.5068e-01,  2.3977e-01],
         [-1.0469e+00, -8.8869e-04, -8.1561e-01, -2.5237e-01],
         [-4.6160e-01, -2.0621e-01,  1.1680e+00,  4.0759e-01],
         [ 8.9391e-01,  6.7291e-02,  5.8258e-01, -5.4704e-01]],

        [[-1.4967e+00,  1.5177e+00,  1.1865e+00,  1.4493e+00],
         [ 1.2408e+00, -5.2175e-01,  1.2174e+00,  1.2270e-01],
         [-5.7148e-01, -8.3839e-01,  2.3823e+00,  1.6539e+00],
         [ 8.0902e-01, -4.0109e-02,  1.6013e-01,  1.5525e+00],
         [ 3.1471e-01, -9.0348e-01,  2.0222e-01, -3.2659e+00],
         [-2.0101e+00,  1.4985e+00, -5.0386e-01, -4.0798e-01],
         [ 4.0178e-01,  5.2924e-01,  4.2621e-01,  8.9017e-01]],

        [[-1.3038e+00,  8.0567e-01,  6.5355e-01,  1.4325e+00],
         [ 2.0008e-01, -1.2313e+00,  1.7509e+00, -3

In [10]:
tor_mul[::2]  # 第一个维度上切片步长为2,范围为整个维度;等价于tor_mul[::2, :, :]

tensor([[[-3.3322e-01, -5.4964e-01, -2.0999e+00, -1.4855e+00],
         [ 7.3260e-01, -1.9075e+00,  2.9797e-01,  6.2108e-01],
         [ 2.8965e-01,  3.4892e-01,  7.0525e-01, -7.3717e-01],
         [ 9.2437e-01,  1.8985e+00,  7.5068e-01,  2.3977e-01],
         [-1.0469e+00, -8.8869e-04, -8.1561e-01, -2.5237e-01],
         [-4.6160e-01, -2.0621e-01,  1.1680e+00,  4.0759e-01],
         [ 8.9391e-01,  6.7291e-02,  5.8258e-01, -5.4704e-01]],

        [[-1.3038e+00,  8.0567e-01,  6.5355e-01,  1.4325e+00],
         [ 2.0008e-01, -1.2313e+00,  1.7509e+00, -3.3574e-03],
         [-3.3365e-01, -5.7154e-02,  7.0654e-01, -3.8136e-01],
         [-1.5576e+00, -7.8075e-01,  1.4863e+00,  7.0017e-02],
         [ 1.4395e+00, -3.6602e-01, -2.3668e-02,  7.8522e-01],
         [ 8.3274e-01, -1.2191e-01, -4.6774e-01,  1.3443e+00],
         [ 5.7129e-02,  3.1716e-01, -2.1138e+00,  8.6043e-01]],

        [[ 1.1753e+00, -2.0141e-01,  4.4343e-01, -1.9345e+00],
         [-3.8294e-01, -1.9696e-01, -2.9355e+00, -9

In [11]:
tor_complex = torch.randn(12, 7, 8, 10, 9, 15, 14)
tor_complex.shape

torch.Size([12, 7, 8, 10, 9, 15, 14])

In [12]:
print(tor_complex[1:5].shape)
print(tor_complex[1:5, :, :, :, :, :].shape)
print(tor_complex[1:5, ...].shape)  # ...:剩余维度上所有数据

torch.Size([4, 7, 8, 10, 9, 15, 14])
torch.Size([4, 7, 8, 10, 9, 15, 14])
torch.Size([4, 7, 8, 10, 9, 15, 14])


In [13]:
print(tor_complex[:, :, :, :, :, :, 2:4].shape)
print(tor_complex[..., 2:4].shape)

torch.Size([12, 7, 8, 10, 9, 15, 2])
torch.Size([12, 7, 8, 10, 9, 15, 2])


In [14]:
print(tor_complex[2:7, :, :, :, :, :, 4].shape)
print(tor_complex[2:7, ..., 4].shape)


torch.Size([5, 7, 8, 10, 9, 15])
torch.Size([5, 7, 8, 10, 9, 15])
