In [45]:
import torch

### 参考numpy索引切片

In [46]:
tor_mul = torch.randn(5, 7, 4)
tor_mul

tensor([[[-1.4768, -0.6350, -1.3025, -0.2932],
         [-1.4520,  1.6642,  1.6535,  0.4967],
         [-0.0514,  1.8107, -0.6424,  0.9632],
         [-0.8048,  1.3048, -0.4318, -0.6461],
         [ 1.6761, -0.1257, -0.1079,  0.6039],
         [ 0.8677,  0.7432,  0.0617,  0.8543],
         [ 0.6777, -2.5085,  2.5443,  1.8222]],

        [[ 0.6246, -0.7943,  0.1869,  1.7707],
         [ 1.8650, -1.0464, -3.0572, -0.1820],
         [ 0.9994, -0.0818, -0.6412, -0.0693],
         [-0.8873,  0.4963, -0.3783, -1.5144],
         [-1.8019,  0.2209, -0.0665, -0.9460],
         [-0.9932, -0.3168, -0.7448, -0.6168],
         [ 1.0877, -0.8348, -0.2445, -1.0626]],

        [[-0.2841, -0.0668,  0.0650,  1.0861],
         [ 1.7238,  0.1338, -0.9160,  1.4335],
         [ 0.1646,  0.3121,  0.3804,  0.4523],
         [ 0.9429, -0.3309,  2.0832,  0.0271],
         [ 0.2542,  1.1734,  1.9814, -0.1633],
         [ 2.1096,  0.3188,  1.0980,  0.4120],
         [-1.0183, -1.6139,  0.2055, -0.6006]],

       

In [47]:
tor_mul[0, 1, 1]  # 索引,返回tensor

tensor(1.6642)

In [48]:
tor_mul[0]  # 从第零个维度开始索引切片(DataFrame从列开始进行索引切片)

tensor([[-1.4768, -0.6350, -1.3025, -0.2932],
        [-1.4520,  1.6642,  1.6535,  0.4967],
        [-0.0514,  1.8107, -0.6424,  0.9632],
        [-0.8048,  1.3048, -0.4318, -0.6461],
        [ 1.6761, -0.1257, -0.1079,  0.6039],
        [ 0.8677,  0.7432,  0.0617,  0.8543],
        [ 0.6777, -2.5085,  2.5443,  1.8222]])

In [49]:
tor_mul[0, 0, -1]  # 索引,返回tensor.支持负数索引

tensor(-0.2932)

In [50]:
tor_mul[0:2]  # 切片,返回tensor

tensor([[[-1.4768, -0.6350, -1.3025, -0.2932],
         [-1.4520,  1.6642,  1.6535,  0.4967],
         [-0.0514,  1.8107, -0.6424,  0.9632],
         [-0.8048,  1.3048, -0.4318, -0.6461],
         [ 1.6761, -0.1257, -0.1079,  0.6039],
         [ 0.8677,  0.7432,  0.0617,  0.8543],
         [ 0.6777, -2.5085,  2.5443,  1.8222]],

        [[ 0.6246, -0.7943,  0.1869,  1.7707],
         [ 1.8650, -1.0464, -3.0572, -0.1820],
         [ 0.9994, -0.0818, -0.6412, -0.0693],
         [-0.8873,  0.4963, -0.3783, -1.5144],
         [-1.8019,  0.2209, -0.0665, -0.9460],
         [-0.9932, -0.3168, -0.7448, -0.6168],
         [ 1.0877, -0.8348, -0.2445, -1.0626]]])

In [51]:
tor_mul[0:2, 0:3, 0]  # 在多个维度上索引切片

tensor([[-1.4768, -1.4520, -0.0514],
        [ 0.6246,  1.8650,  0.9994]])

In [52]:
temp = torch.arange(10)
print(temp)
print(temp[::2])
print(temp[1::2])
print(temp[2:8:3])

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([0, 2, 4, 6, 8])
tensor([1, 3, 5, 7, 9])
tensor([2, 5])


In [53]:
tor_mul[0:2, 0:6:2, 2]  # 第一个维度上的切片步长为2(不支持步长为负数),切片范围为0-6

tensor([[-1.3025, -0.6424, -0.1079],
        [ 0.1869, -0.6412, -0.0665]])

In [54]:
tor_mul[:]  # 等价于tor_mul[:, :, :]

tensor([[[-1.4768, -0.6350, -1.3025, -0.2932],
         [-1.4520,  1.6642,  1.6535,  0.4967],
         [-0.0514,  1.8107, -0.6424,  0.9632],
         [-0.8048,  1.3048, -0.4318, -0.6461],
         [ 1.6761, -0.1257, -0.1079,  0.6039],
         [ 0.8677,  0.7432,  0.0617,  0.8543],
         [ 0.6777, -2.5085,  2.5443,  1.8222]],

        [[ 0.6246, -0.7943,  0.1869,  1.7707],
         [ 1.8650, -1.0464, -3.0572, -0.1820],
         [ 0.9994, -0.0818, -0.6412, -0.0693],
         [-0.8873,  0.4963, -0.3783, -1.5144],
         [-1.8019,  0.2209, -0.0665, -0.9460],
         [-0.9932, -0.3168, -0.7448, -0.6168],
         [ 1.0877, -0.8348, -0.2445, -1.0626]],

        [[-0.2841, -0.0668,  0.0650,  1.0861],
         [ 1.7238,  0.1338, -0.9160,  1.4335],
         [ 0.1646,  0.3121,  0.3804,  0.4523],
         [ 0.9429, -0.3309,  2.0832,  0.0271],
         [ 0.2542,  1.1734,  1.9814, -0.1633],
         [ 2.1096,  0.3188,  1.0980,  0.4120],
         [-1.0183, -1.6139,  0.2055, -0.6006]],

       

In [55]:
tor_mul[::2]  # 第一个维度上切片步长为2,范围为整个维度;等价于tor_mul[::2, :, :]

tensor([[[-1.4768, -0.6350, -1.3025, -0.2932],
         [-1.4520,  1.6642,  1.6535,  0.4967],
         [-0.0514,  1.8107, -0.6424,  0.9632],
         [-0.8048,  1.3048, -0.4318, -0.6461],
         [ 1.6761, -0.1257, -0.1079,  0.6039],
         [ 0.8677,  0.7432,  0.0617,  0.8543],
         [ 0.6777, -2.5085,  2.5443,  1.8222]],

        [[-0.2841, -0.0668,  0.0650,  1.0861],
         [ 1.7238,  0.1338, -0.9160,  1.4335],
         [ 0.1646,  0.3121,  0.3804,  0.4523],
         [ 0.9429, -0.3309,  2.0832,  0.0271],
         [ 0.2542,  1.1734,  1.9814, -0.1633],
         [ 2.1096,  0.3188,  1.0980,  0.4120],
         [-1.0183, -1.6139,  0.2055, -0.6006]],

        [[-1.7904, -0.3652, -0.1886,  0.0518],
         [ 1.0328, -1.4706,  0.9406, -0.3073],
         [-0.9175,  0.3860, -0.0361,  1.0389],
         [-0.8546, -1.7850,  0.5537,  0.1157],
         [ 0.2377,  0.4881,  0.6676,  0.2176],
         [-1.6435,  1.2605,  1.8255,  0.6331],
         [ 1.7128, -0.8149, -0.8403,  1.3795]]])

In [56]:
tor_complex = torch.randn(12, 7, 8, 10, 9, 15, 14)
tor_complex.shape

torch.Size([12, 7, 8, 10, 9, 15, 14])

In [57]:
print(tor_complex[1:5].shape)
print(tor_complex[1:5, :, :, :, :, :].shape)
print(tor_complex[1:5, ...].shape)  # ...:剩余维度上所有数据

torch.Size([4, 7, 8, 10, 9, 15, 14])
torch.Size([4, 7, 8, 10, 9, 15, 14])
torch.Size([4, 7, 8, 10, 9, 15, 14])


In [58]:
print(tor_complex[:, :, :, :, :, :, 2:4].shape)
print(tor_complex[..., 2:4].shape)

torch.Size([12, 7, 8, 10, 9, 15, 2])
torch.Size([12, 7, 8, 10, 9, 15, 2])


In [59]:
print(tor_complex[2:7, :, :, :, :, :, 4].shape)
print(tor_complex[2:7, ..., 4].shape)


torch.Size([5, 7, 8, 10, 9, 15])
torch.Size([5, 7, 8, 10, 9, 15])
