In [1]:
import torch

### 参考numpy索引切片

In [2]:
tor_mul = torch.randn(5, 7, 4)
tor_mul

tensor([[[ 0.9672, -1.6929, -0.5048, -0.2972],
         [ 0.5303, -0.1054,  1.5279, -0.4121],
         [ 0.1771, -1.3289, -0.6828, -1.6901],
         [ 0.4893,  0.3962, -1.1001,  0.3957],
         [ 0.8524, -0.6336, -0.6616,  1.3318],
         [-0.1594,  1.4567, -0.0216, -0.3005],
         [ 0.5914,  1.7116, -0.2129, -0.8229]],

        [[-0.2324, -0.9761,  1.4941,  0.2118],
         [-1.7350,  0.5763, -0.1811,  0.2002],
         [ 1.4847,  0.3684, -0.7969,  0.9902],
         [-1.0704,  0.3925,  1.3898,  1.6254],
         [-0.7718, -0.0184,  0.1712, -0.0478],
         [-0.8331, -1.2002, -1.7076, -1.8246],
         [-0.2920,  0.7690,  0.4669, -0.4152]],

        [[ 0.8127, -0.8381, -1.9896,  0.0340],
         [ 0.0481,  1.4258, -0.9284,  0.1308],
         [ 1.2577,  0.4648, -0.0158,  0.8425],
         [ 0.9101,  0.0743, -1.3114,  0.3598],
         [ 0.7879, -0.4554, -0.2268, -1.4626],
         [-1.2332, -1.0919, -1.4127,  0.1769],
         [-1.0726, -1.6809, -0.6117, -0.7506]],

       

In [3]:
tor_mul[0, 1, 1]  # 索引,返回tensor

tensor(-0.1054)

In [4]:
tor_mul[0]  # 从第零个维度开始索引切片(DataFrame从列开始进行索引切片)

tensor([[ 0.9672, -1.6929, -0.5048, -0.2972],
        [ 0.5303, -0.1054,  1.5279, -0.4121],
        [ 0.1771, -1.3289, -0.6828, -1.6901],
        [ 0.4893,  0.3962, -1.1001,  0.3957],
        [ 0.8524, -0.6336, -0.6616,  1.3318],
        [-0.1594,  1.4567, -0.0216, -0.3005],
        [ 0.5914,  1.7116, -0.2129, -0.8229]])

In [5]:
tor_mul[0, 0, -1]  # 索引,返回tensor.支持负数索引

tensor(-0.2972)

In [6]:
tor_mul[0:2]  # 切片,返回tensor

tensor([[[ 0.9672, -1.6929, -0.5048, -0.2972],
         [ 0.5303, -0.1054,  1.5279, -0.4121],
         [ 0.1771, -1.3289, -0.6828, -1.6901],
         [ 0.4893,  0.3962, -1.1001,  0.3957],
         [ 0.8524, -0.6336, -0.6616,  1.3318],
         [-0.1594,  1.4567, -0.0216, -0.3005],
         [ 0.5914,  1.7116, -0.2129, -0.8229]],

        [[-0.2324, -0.9761,  1.4941,  0.2118],
         [-1.7350,  0.5763, -0.1811,  0.2002],
         [ 1.4847,  0.3684, -0.7969,  0.9902],
         [-1.0704,  0.3925,  1.3898,  1.6254],
         [-0.7718, -0.0184,  0.1712, -0.0478],
         [-0.8331, -1.2002, -1.7076, -1.8246],
         [-0.2920,  0.7690,  0.4669, -0.4152]]])

In [7]:
tor_mul[0:2, 0:3, 0]  # 在多个维度上索引切片

tensor([[ 0.9672,  0.5303,  0.1771],
        [-0.2324, -1.7350,  1.4847]])

In [8]:
tor_mul[0:2, 0:6:2, 2]  # 第一个维度上的切片步长为2(不支持步长为负数),切片范围为0-6

tensor([[-0.5048, -0.6828, -0.6616],
        [ 1.4941, -0.7969,  0.1712]])

In [9]:
tor_mul[:]  # 等价于tor_mul[:, :, :]

tensor([[[ 0.9672, -1.6929, -0.5048, -0.2972],
         [ 0.5303, -0.1054,  1.5279, -0.4121],
         [ 0.1771, -1.3289, -0.6828, -1.6901],
         [ 0.4893,  0.3962, -1.1001,  0.3957],
         [ 0.8524, -0.6336, -0.6616,  1.3318],
         [-0.1594,  1.4567, -0.0216, -0.3005],
         [ 0.5914,  1.7116, -0.2129, -0.8229]],

        [[-0.2324, -0.9761,  1.4941,  0.2118],
         [-1.7350,  0.5763, -0.1811,  0.2002],
         [ 1.4847,  0.3684, -0.7969,  0.9902],
         [-1.0704,  0.3925,  1.3898,  1.6254],
         [-0.7718, -0.0184,  0.1712, -0.0478],
         [-0.8331, -1.2002, -1.7076, -1.8246],
         [-0.2920,  0.7690,  0.4669, -0.4152]],

        [[ 0.8127, -0.8381, -1.9896,  0.0340],
         [ 0.0481,  1.4258, -0.9284,  0.1308],
         [ 1.2577,  0.4648, -0.0158,  0.8425],
         [ 0.9101,  0.0743, -1.3114,  0.3598],
         [ 0.7879, -0.4554, -0.2268, -1.4626],
         [-1.2332, -1.0919, -1.4127,  0.1769],
         [-1.0726, -1.6809, -0.6117, -0.7506]],

       

In [10]:
tor_mul[::2]  # 第一个维度上切片步长为2,范围为整个维度;等价于tor_mul[::2, :, :]

tensor([[[ 0.9672, -1.6929, -0.5048, -0.2972],
         [ 0.5303, -0.1054,  1.5279, -0.4121],
         [ 0.1771, -1.3289, -0.6828, -1.6901],
         [ 0.4893,  0.3962, -1.1001,  0.3957],
         [ 0.8524, -0.6336, -0.6616,  1.3318],
         [-0.1594,  1.4567, -0.0216, -0.3005],
         [ 0.5914,  1.7116, -0.2129, -0.8229]],

        [[ 0.8127, -0.8381, -1.9896,  0.0340],
         [ 0.0481,  1.4258, -0.9284,  0.1308],
         [ 1.2577,  0.4648, -0.0158,  0.8425],
         [ 0.9101,  0.0743, -1.3114,  0.3598],
         [ 0.7879, -0.4554, -0.2268, -1.4626],
         [-1.2332, -1.0919, -1.4127,  0.1769],
         [-1.0726, -1.6809, -0.6117, -0.7506]],

        [[-0.3899,  0.2991, -0.3020, -0.2165],
         [-0.5637,  1.3135,  2.3768,  1.4210],
         [ 0.8325,  0.7553, -1.1089,  0.8665],
         [-1.0062,  2.7672, -0.8069,  1.9880],
         [-0.6108,  0.7017,  1.2076,  1.2303],
         [ 0.2621,  0.3741, -0.5687, -0.7067],
         [ 0.1051, -0.2546,  0.5801, -0.6976]]])

In [11]:
tor_complex = torch.randn(12, 7, 8, 10, 9, 15, 14)
tor_complex.shape

torch.Size([12, 7, 8, 10, 9, 15, 14])

In [12]:
print(tor_complex[1:5].shape)
print(tor_complex[1:5, :, :, :, :, :].shape)
print(tor_complex[1:5, ...].shape)  # ...:剩余维度上所有数据

torch.Size([4, 7, 8, 10, 9, 15, 14])
torch.Size([4, 7, 8, 10, 9, 15, 14])
torch.Size([4, 7, 8, 10, 9, 15, 14])


In [13]:
print(tor_complex[:, :, :, :, :, :, 2:4].shape)
print(tor_complex[..., 2:4].shape)

torch.Size([12, 7, 8, 10, 9, 15, 2])
torch.Size([12, 7, 8, 10, 9, 15, 2])


In [14]:
print(tor_complex[2:7, :, :, :, :, :, 4].shape)
print(tor_complex[2:7, ..., 4].shape)


torch.Size([5, 7, 8, 10, 9, 15])
torch.Size([5, 7, 8, 10, 9, 15])
