In [15]:
import torch
# 完全类似numpy索引切片

In [16]:
tor_mul = torch.randn(5, 7, 4)
tor_mul

tensor([[[ 3.2633e-01, -5.2533e-01,  1.4904e-01,  6.8264e-01],
         [ 1.7054e+00, -5.8023e-01,  8.0247e-04,  7.4988e-01],
         [ 1.2946e+00,  6.7238e-01,  1.7806e-01, -5.5336e-01],
         [-3.8817e-02, -1.4837e+00, -1.3035e+00,  5.0719e-01],
         [-2.0920e+00,  2.1273e-03,  8.0977e-01,  2.5156e-01],
         [-2.5204e+00, -1.5966e+00,  1.3902e-01, -5.7735e-01],
         [ 7.6774e-01,  1.1116e+00,  6.5113e-01, -4.4038e-02]],

        [[-1.1545e+00,  5.0876e-01,  9.3786e-01, -8.7290e-01],
         [-4.6437e-01, -1.1445e+00, -3.8225e-01,  3.6105e-01],
         [-1.1188e+00,  2.6889e-01,  6.3578e-01, -1.0014e+00],
         [ 1.2462e+00,  1.1783e+00,  3.8919e-01,  8.7580e-01],
         [ 5.7511e-01, -3.0567e-01, -2.0028e-01,  3.5388e-01],
         [ 2.0648e-01,  6.0325e-02,  5.0414e-01, -6.4975e-01],
         [-1.1566e+00,  1.5135e-01, -2.5993e-01, -5.5229e-01]],

        [[ 1.4312e+00, -7.7076e-01,  1.0983e+00,  1.3127e+00],
         [ 4.8762e-01,  4.7246e-01,  4.4260e-01,  2

In [17]:
tor_mul[0, 1, 1] # 索引为标量tensor

tensor(-0.5802)

In [18]:
tor_mul[0] # 从第零个维度开始索引切片(DataFrame从列开始进行索引切片)

tensor([[ 3.2633e-01, -5.2533e-01,  1.4904e-01,  6.8264e-01],
        [ 1.7054e+00, -5.8023e-01,  8.0247e-04,  7.4988e-01],
        [ 1.2946e+00,  6.7238e-01,  1.7806e-01, -5.5336e-01],
        [-3.8817e-02, -1.4837e+00, -1.3035e+00,  5.0719e-01],
        [-2.0920e+00,  2.1273e-03,  8.0977e-01,  2.5156e-01],
        [-2.5204e+00, -1.5966e+00,  1.3902e-01, -5.7735e-01],
        [ 7.6774e-01,  1.1116e+00,  6.5113e-01, -4.4038e-02]])

In [19]:
tor_mul[0, 0, -1] # 索引,返回tensor.支持负数索引

tensor(0.6826)

In [20]:
tor_mul[0:2] # 切片,返回tensor

tensor([[[ 3.2633e-01, -5.2533e-01,  1.4904e-01,  6.8264e-01],
         [ 1.7054e+00, -5.8023e-01,  8.0247e-04,  7.4988e-01],
         [ 1.2946e+00,  6.7238e-01,  1.7806e-01, -5.5336e-01],
         [-3.8817e-02, -1.4837e+00, -1.3035e+00,  5.0719e-01],
         [-2.0920e+00,  2.1273e-03,  8.0977e-01,  2.5156e-01],
         [-2.5204e+00, -1.5966e+00,  1.3902e-01, -5.7735e-01],
         [ 7.6774e-01,  1.1116e+00,  6.5113e-01, -4.4038e-02]],

        [[-1.1545e+00,  5.0876e-01,  9.3786e-01, -8.7290e-01],
         [-4.6437e-01, -1.1445e+00, -3.8225e-01,  3.6105e-01],
         [-1.1188e+00,  2.6889e-01,  6.3578e-01, -1.0014e+00],
         [ 1.2462e+00,  1.1783e+00,  3.8919e-01,  8.7580e-01],
         [ 5.7511e-01, -3.0567e-01, -2.0028e-01,  3.5388e-01],
         [ 2.0648e-01,  6.0325e-02,  5.0414e-01, -6.4975e-01],
         [-1.1566e+00,  1.5135e-01, -2.5993e-01, -5.5229e-01]]])

In [21]:
tor_mul[0:2, 0:3, 0] # 在多个维度上索引切片

tensor([[ 0.3263,  1.7054,  1.2946],
        [-1.1545, -0.4644, -1.1188]])

In [22]:
tor_mul[0:2, 0:6:2, 2] # 第一个维度上的切片步长为2(不支持步长为负数),切片范围为0-6

tensor([[ 0.1490,  0.1781,  0.8098],
        [ 0.9379,  0.6358, -0.2003]])

In [23]:
tor_mul[:] # 等价于tor_mul[:, :, :]

tensor([[[ 3.2633e-01, -5.2533e-01,  1.4904e-01,  6.8264e-01],
         [ 1.7054e+00, -5.8023e-01,  8.0247e-04,  7.4988e-01],
         [ 1.2946e+00,  6.7238e-01,  1.7806e-01, -5.5336e-01],
         [-3.8817e-02, -1.4837e+00, -1.3035e+00,  5.0719e-01],
         [-2.0920e+00,  2.1273e-03,  8.0977e-01,  2.5156e-01],
         [-2.5204e+00, -1.5966e+00,  1.3902e-01, -5.7735e-01],
         [ 7.6774e-01,  1.1116e+00,  6.5113e-01, -4.4038e-02]],

        [[-1.1545e+00,  5.0876e-01,  9.3786e-01, -8.7290e-01],
         [-4.6437e-01, -1.1445e+00, -3.8225e-01,  3.6105e-01],
         [-1.1188e+00,  2.6889e-01,  6.3578e-01, -1.0014e+00],
         [ 1.2462e+00,  1.1783e+00,  3.8919e-01,  8.7580e-01],
         [ 5.7511e-01, -3.0567e-01, -2.0028e-01,  3.5388e-01],
         [ 2.0648e-01,  6.0325e-02,  5.0414e-01, -6.4975e-01],
         [-1.1566e+00,  1.5135e-01, -2.5993e-01, -5.5229e-01]],

        [[ 1.4312e+00, -7.7076e-01,  1.0983e+00,  1.3127e+00],
         [ 4.8762e-01,  4.7246e-01,  4.4260e-01,  2

In [24]:
tor_mul[::2] # 第一个维度上切片步长为2,范围为整个维度;等价于tor_mul[::2, :, :]

tensor([[[ 3.2633e-01, -5.2533e-01,  1.4904e-01,  6.8264e-01],
         [ 1.7054e+00, -5.8023e-01,  8.0247e-04,  7.4988e-01],
         [ 1.2946e+00,  6.7238e-01,  1.7806e-01, -5.5336e-01],
         [-3.8817e-02, -1.4837e+00, -1.3035e+00,  5.0719e-01],
         [-2.0920e+00,  2.1273e-03,  8.0977e-01,  2.5156e-01],
         [-2.5204e+00, -1.5966e+00,  1.3902e-01, -5.7735e-01],
         [ 7.6774e-01,  1.1116e+00,  6.5113e-01, -4.4038e-02]],

        [[ 1.4312e+00, -7.7076e-01,  1.0983e+00,  1.3127e+00],
         [ 4.8762e-01,  4.7246e-01,  4.4260e-01,  2.0231e+00],
         [ 4.3441e-01, -1.1901e+00, -1.0600e+00,  2.9732e-01],
         [-9.1057e-01,  5.6357e-01, -9.2712e-01,  2.0063e+00],
         [-1.0933e+00,  1.1788e+00, -1.7199e-01, -6.3963e-02],
         [-1.2603e+00,  5.1896e-01,  1.5758e+00, -6.8232e-01],
         [ 7.4334e-01, -1.9944e+00, -1.1963e-01,  1.3008e+00]],

        [[-1.5881e+00,  7.0902e-01, -4.7713e-01,  3.4808e-01],
         [ 1.5190e+00, -7.1302e-01,  4.9829e-01, -6

In [25]:
tor_complex = torch.randn(12, 7, 8, 10, 9, 15, 14)
tor_complex.shape

torch.Size([12, 7, 8, 10, 9, 15, 14])

In [26]:
print(tor_complex[1:5].shape)
print(tor_complex[1:5, :, :, :, :, :].shape)
print(tor_complex[1:5, ...].shape) # ...:剩余维度上所有数据

torch.Size([4, 7, 8, 10, 9, 15, 14])
torch.Size([4, 7, 8, 10, 9, 15, 14])
torch.Size([4, 7, 8, 10, 9, 15, 14])


In [27]:
print(tor_complex[:, :, :, :, :, :, 2:4].shape)
print(tor_complex[..., 2:4].shape)

torch.Size([12, 7, 8, 10, 9, 15, 2])
torch.Size([12, 7, 8, 10, 9, 15, 2])


In [28]:
print(tor_complex[2:7, :, :, :, :, :, 4].shape)
print(tor_complex[2:7, ..., 4].shape)


torch.Size([5, 7, 8, 10, 9, 15])
torch.Size([5, 7, 8, 10, 9, 15])
