In [15]:
import torch

In [16]:
x = torch.randn(3, 4)
x

tensor([[ 1.0469, -1.0503, -0.3407,  0.9867],
        [-0.4925, -0.3047,  0.2571, -0.3778],
        [-0.5841, -1.0884, -0.2777,  1.7382]])

In [17]:
mask = x.ge(0.5)
mask

tensor([[ True, False, False,  True],
        [False, False, False, False],
        [False, False, False,  True]])

In [18]:
# The shapes of the mask tensor and the input tensor don’t need to match, but they must be broadcastable.
select = torch.masked_select(x, mask)  # ★★★★返回一个新的一维tensor
select

tensor([1.0469, 0.9867, 1.7382])

In [19]:
select[0] = 9999
select

tensor([9.9990e+03, 9.8669e-01, 1.7382e+00])

In [20]:
x  # x不变

tensor([[ 1.0469, -1.0503, -0.3407,  0.9867],
        [-0.4925, -0.3047,  0.2571, -0.3778],
        [-0.5841, -1.0884, -0.2777,  1.7382]])