In [1]:
import torch

### 参考numpy布尔索引

In [2]:
target = torch.tensor([1, 2, 3, 1, 3, 2, 2])
data = torch.randn(7, 4)
print(target)
print(data)

tensor([1, 2, 3, 1, 3, 2, 2])
tensor([[-0.7076,  1.2246,  0.8702, -0.3664],
        [ 0.7045,  0.8347,  1.6005,  0.6004],
        [ 1.1458, -0.9852, -0.2226,  0.3296],
        [-0.1520,  1.8546, -0.4060,  0.4467],
        [-1.1139,  0.2943,  0.5944,  0.4122],
        [-2.2090,  0.0224, -0.5970,  0.2151],
        [-0.0626,  1.7812, -0.4410,  0.5038]])


In [3]:
check = target == 1
print(check.dtype)
print(check)

torch.bool
tensor([ True, False, False,  True, False, False, False])


In [4]:
data[check]  # 第零个维度布尔切片

tensor([[-0.7076,  1.2246,  0.8702, -0.3664],
        [-0.1520,  1.8546, -0.4060,  0.4467]])

In [5]:
data[:, check[:4]]  # 第一个维度上的布尔索引

tensor([[-0.7076, -0.3664],
        [ 0.7045,  0.6004],
        [ 1.1458,  0.3296],
        [-0.1520,  0.4467],
        [-1.1139,  0.4122],
        [-2.2090,  0.2151],
        [-0.0626,  0.5038]])

In [6]:
data[target == 1, 2:]

tensor([[ 0.8702, -0.3664],
        [-0.4060,  0.4467]])

In [7]:
print(target != 1)
print(~(target != 1))  # ~:取反
print(data[~(target != 1)])

tensor([False,  True,  True, False,  True,  True,  True])
tensor([ True, False, False,  True, False, False, False])
tensor([[-0.7076,  1.2246,  0.8702, -0.3664],
        [-0.1520,  1.8546, -0.4060,  0.4467]])


In [8]:
mask = (target == 1) | (target == 3)  # |:并集,不能使用关键字or
print(mask)
print(data[mask])

tensor([ True, False,  True,  True,  True, False, False])
tensor([[-0.7076,  1.2246,  0.8702, -0.3664],
        [ 1.1458, -0.9852, -0.2226,  0.3296],
        [-0.1520,  1.8546, -0.4060,  0.4467],
        [-1.1139,  0.2943,  0.5944,  0.4122]])


In [9]:
mask1 = (target == 1) & (target == 3)  # &:交集,不能使用关键字and
print(mask1)
print(data[mask1])

tensor([False, False, False, False, False, False, False])
tensor([], size=(0, 4))


In [10]:
s = data < 0
s

tensor([[ True, False, False,  True],
        [False, False, False, False],
        [False,  True,  True, False],
        [ True, False,  True, False],
        [ True, False, False, False],
        [ True, False,  True, False],
        [ True, False,  True, False]])

In [11]:
data[s]

tensor([-0.7076, -0.3664, -0.9852, -0.2226, -0.1520, -0.4060, -1.1139, -2.2090,
        -0.5970, -0.0626, -0.4410])

In [12]:
data[s] = 9999  # 逐个元素的布尔索引
data  # data发生改变

tensor([[9.9990e+03, 1.2246e+00, 8.7023e-01, 9.9990e+03],
        [7.0447e-01, 8.3467e-01, 1.6005e+00, 6.0042e-01],
        [1.1458e+00, 9.9990e+03, 9.9990e+03, 3.2963e-01],
        [9.9990e+03, 1.8546e+00, 9.9990e+03, 4.4675e-01],
        [9.9990e+03, 2.9428e-01, 5.9437e-01, 4.1223e-01],
        [9.9990e+03, 2.2443e-02, 9.9990e+03, 2.1514e-01],
        [9.9990e+03, 1.7812e+00, 9.9990e+03, 5.0383e-01]])

In [13]:
data[target != 2] = 7  # ★★★★★和整数索引类似,只能通过对原tensor[索引/切片]直接进行赋值从而修改原tensor
data  # data发生改变

tensor([[7.0000e+00, 7.0000e+00, 7.0000e+00, 7.0000e+00],
        [7.0447e-01, 8.3467e-01, 1.6005e+00, 6.0042e-01],
        [7.0000e+00, 7.0000e+00, 7.0000e+00, 7.0000e+00],
        [7.0000e+00, 7.0000e+00, 7.0000e+00, 7.0000e+00],
        [7.0000e+00, 7.0000e+00, 7.0000e+00, 7.0000e+00],
        [9.9990e+03, 2.2443e-02, 9.9990e+03, 2.1514e-01],
        [9.9990e+03, 1.7812e+00, 9.9990e+03, 5.0383e-01]])