In [1]:
import torch
# 完全类似numpy布尔索引

In [2]:
target = torch.tensor([1, 2, 3, 1, 3, 2, 2])
data = torch.randn(7, 4)
print(target)
print(data)

tensor([1, 2, 3, 1, 3, 2, 2])
tensor([[ 0.0070,  0.0353,  0.1426, -0.5266],
        [ 0.1641, -1.9230,  0.2032,  0.6801],
        [-1.0508, -1.1528, -1.9580,  0.8606],
        [-0.3588,  0.6803, -0.8561,  2.9947],
        [ 0.3328, -0.0737,  1.2392,  0.2713],
        [-0.3227, -0.4676,  0.0051, -0.2128],
        [-0.9383,  1.1651, -0.4958, -0.4953]])


In [3]:
check = target == 1
print(check.dtype)
print(check)

torch.bool
tensor([ True, False, False,  True, False, False, False])


In [4]:
data[check]  # 第零个维度布尔切片

tensor([[ 0.0070,  0.0353,  0.1426, -0.5266],
        [-0.3588,  0.6803, -0.8561,  2.9947]])

In [5]:
data[:, check[:4]]  # 第一个维度上的布尔索引

tensor([[ 0.0070, -0.5266],
        [ 0.1641,  0.6801],
        [-1.0508,  0.8606],
        [-0.3588,  2.9947],
        [ 0.3328,  0.2713],
        [-0.3227, -0.2128],
        [-0.9383, -0.4953]])

In [6]:
print(data[target == 1, 2:])
print(data[target == 1, 2:])

tensor([[ 0.1426, -0.5266],
        [-0.8561,  2.9947]])
tensor([[ 0.1426, -0.5266],
        [-0.8561,  2.9947]])


In [7]:
print(target != 1)
print(~(target != 1))  # ~:取反
print(data[~(target != 1)])

tensor([False,  True,  True, False,  True,  True,  True])
tensor([ True, False, False,  True, False, False, False])
tensor([[ 0.0070,  0.0353,  0.1426, -0.5266],
        [-0.3588,  0.6803, -0.8561,  2.9947]])


In [8]:
mask = (target == 1) | (target == 3)  # |:并集,不能使用关键字or
print(mask)
print(data[mask])

tensor([ True, False,  True,  True,  True, False, False])
tensor([[ 0.0070,  0.0353,  0.1426, -0.5266],
        [-1.0508, -1.1528, -1.9580,  0.8606],
        [-0.3588,  0.6803, -0.8561,  2.9947],
        [ 0.3328, -0.0737,  1.2392,  0.2713]])


In [9]:
mask1 = (target == 1) & (target == 3)  # &:交集,不能使用关键字and
print(mask1)
print(data[mask1])

tensor([False, False, False, False, False, False, False])
tensor([], size=(0, 4))


In [10]:
s = data < 0
s

tensor([[False, False, False,  True],
        [False,  True, False, False],
        [ True,  True,  True, False],
        [ True, False,  True, False],
        [False,  True, False, False],
        [ True,  True, False,  True],
        [ True, False,  True,  True]])

In [11]:
data[s]

tensor([-0.5266, -1.9230, -1.0508, -1.1528, -1.9580, -0.3588, -0.8561, -0.0737,
        -0.3227, -0.4676, -0.2128, -0.9383, -0.4958, -0.4953])

In [12]:
data[s] = 9999  # 逐个元素的布尔索引
data  # data发生改变

tensor([[7.0036e-03, 3.5330e-02, 1.4257e-01, 9.9990e+03],
        [1.6414e-01, 9.9990e+03, 2.0323e-01, 6.8012e-01],
        [9.9990e+03, 9.9990e+03, 9.9990e+03, 8.6057e-01],
        [9.9990e+03, 6.8028e-01, 9.9990e+03, 2.9947e+00],
        [3.3276e-01, 9.9990e+03, 1.2392e+00, 2.7128e-01],
        [9.9990e+03, 9.9990e+03, 5.1223e-03, 9.9990e+03],
        [9.9990e+03, 1.1651e+00, 9.9990e+03, 9.9990e+03]])

In [13]:
data[target != 2] = 7  # ★★★★★和整数索引类似,只能通过对原tensor[索引/切片]直接进行赋值从而修改原tensor
data  # data发生改变

tensor([[7.0000e+00, 7.0000e+00, 7.0000e+00, 7.0000e+00],
        [1.6414e-01, 9.9990e+03, 2.0323e-01, 6.8012e-01],
        [7.0000e+00, 7.0000e+00, 7.0000e+00, 7.0000e+00],
        [7.0000e+00, 7.0000e+00, 7.0000e+00, 7.0000e+00],
        [7.0000e+00, 7.0000e+00, 7.0000e+00, 7.0000e+00],
        [9.9990e+03, 9.9990e+03, 5.1223e-03, 9.9990e+03],
        [9.9990e+03, 1.1651e+00, 9.9990e+03, 9.9990e+03]])