In [1]:
import torch

In [2]:
x = torch.randn(3, 4)
x

tensor([[-0.0647,  0.3779,  1.7190, -1.2434],
        [ 0.3673,  0.4394, -0.5598, -1.5481],
        [-0.6229, -1.3287, -1.2210, -2.3817]])

In [3]:
mask = x.ge(0.5)
mask

tensor([[False, False,  True, False],
        [False, False, False, False],
        [False, False, False, False]])

In [4]:
select = torch.masked_select(x, mask)  # ★★★★返回一个新的一维tensor
select

tensor([1.7190])

In [5]:
select[0] = 9999
select

tensor([9999.])

In [6]:
x  # x不变

tensor([[-0.0647,  0.3779,  1.7190, -1.2434],
        [ 0.3673,  0.4394, -0.5598, -1.5481],
        [-0.6229, -1.3287, -1.2210, -2.3817]])