In [70]:
import torch
# 完全类似numpy布尔索引

In [71]:
target = torch.tensor([1, 2, 3, 1, 3, 2, 2])
data = torch.randn(7, 4)
print(target)
print(data)

tensor([1, 2, 3, 1, 3, 2, 2])
tensor([[ 0.1256, -0.1921,  0.8151, -1.3113],
        [-0.9798,  0.1418, -0.0190, -0.6650],
        [-0.7337,  0.6366, -0.9672, -0.1068],
        [ 1.4221, -1.5907, -1.1329, -1.8081],
        [-0.8528, -0.0483, -0.4625, -0.9620],
        [ 0.0844,  2.3838, -0.8679,  0.1443],
        [ 1.5581,  0.6215,  0.9683, -0.7454]])


In [72]:
check = target == 1
print(check.dtype)
print(check)

torch.bool
tensor([ True, False, False,  True, False, False, False])


In [73]:
data[check] # 第零个维度布尔切片

tensor([[ 0.1256, -0.1921,  0.8151, -1.3113],
        [ 1.4221, -1.5907, -1.1329, -1.8081]])

In [74]:
data[:, check[:4]] # 第一个维度上的布尔索引

tensor([[ 0.1256, -1.3113],
        [-0.9798, -0.6650],
        [-0.7337, -0.1068],
        [ 1.4221, -1.8081],
        [-0.8528, -0.9620],
        [ 0.0844,  0.1443],
        [ 1.5581, -0.7454]])

In [75]:
print(data[target == 1, 2:])
print(data[target == 1, 2:])

tensor([[ 0.8151, -1.3113],
        [-1.1329, -1.8081]])
tensor([[ 0.8151, -1.3113],
        [-1.1329, -1.8081]])


In [76]:
print(target != 1)
print(~(target != 1)) # ~:取反
print(data[~(target != 1)])

tensor([False,  True,  True, False,  True,  True,  True])
tensor([ True, False, False,  True, False, False, False])
tensor([[ 0.1256, -0.1921,  0.8151, -1.3113],
        [ 1.4221, -1.5907, -1.1329, -1.8081]])


In [77]:
mask = (target == 1) | (target == 3) # |:并集,不能使用关键字or
print(mask)
print(data[mask])

tensor([ True, False,  True,  True,  True, False, False])
tensor([[ 0.1256, -0.1921,  0.8151, -1.3113],
        [-0.7337,  0.6366, -0.9672, -0.1068],
        [ 1.4221, -1.5907, -1.1329, -1.8081],
        [-0.8528, -0.0483, -0.4625, -0.9620]])


In [78]:
mask1 = (target == 1) & (target == 3) # &:交集,不能使用关键字and
print(mask1)
print(data[mask1])

tensor([False, False, False, False, False, False, False])
tensor([], size=(0, 4))


In [79]:
s = data < 0
s

tensor([[False,  True, False,  True],
        [ True, False,  True,  True],
        [ True, False,  True,  True],
        [False,  True,  True,  True],
        [ True,  True,  True,  True],
        [False, False,  True, False],
        [False, False, False,  True]])

In [80]:
data[s]

tensor([-0.1921, -1.3113, -0.9798, -0.0190, -0.6650, -0.7337, -0.9672, -0.1068,
        -1.5907, -1.1329, -1.8081, -0.8528, -0.0483, -0.4625, -0.9620, -0.8679,
        -0.7454])

In [81]:
data[s] = 9999  # 逐个元素的布尔索引
data # data发生改变

tensor([[1.2560e-01, 9.9990e+03, 8.1514e-01, 9.9990e+03],
        [9.9990e+03, 1.4181e-01, 9.9990e+03, 9.9990e+03],
        [9.9990e+03, 6.3664e-01, 9.9990e+03, 9.9990e+03],
        [1.4221e+00, 9.9990e+03, 9.9990e+03, 9.9990e+03],
        [9.9990e+03, 9.9990e+03, 9.9990e+03, 9.9990e+03],
        [8.4404e-02, 2.3838e+00, 9.9990e+03, 1.4429e-01],
        [1.5581e+00, 6.2149e-01, 9.6832e-01, 9.9990e+03]])

In [82]:
data[target != 2] = 7 # ★★★★★和整数索引类似,只能通过对原tensor[索引/切片]直接进行赋值从而修改原tensor
data # data发生改变

tensor([[7.0000e+00, 7.0000e+00, 7.0000e+00, 7.0000e+00],
        [9.9990e+03, 1.4181e-01, 9.9990e+03, 9.9990e+03],
        [7.0000e+00, 7.0000e+00, 7.0000e+00, 7.0000e+00],
        [7.0000e+00, 7.0000e+00, 7.0000e+00, 7.0000e+00],
        [7.0000e+00, 7.0000e+00, 7.0000e+00, 7.0000e+00],
        [8.4404e-02, 2.3838e+00, 9.9990e+03, 1.4429e-01],
        [1.5581e+00, 6.2149e-01, 9.6832e-01, 9.9990e+03]])