In [27]:
import torch

### 参考numpy布尔索引

In [28]:
target = torch.tensor([1, 2, 3, 1, 3, 2, 2])
data = torch.randn(7, 4)
print(target)
print(data)

tensor([1, 2, 3, 1, 3, 2, 2])
tensor([[-2.9392,  0.3311, -1.4612,  0.2028],
        [ 1.1122,  1.1066, -0.2456,  0.3342],
        [ 1.0666, -0.4861,  1.0569, -1.2462],
        [-1.3327, -0.1844, -0.7482, -1.3966],
        [ 0.7182,  0.3388,  0.1546,  0.0978],
        [-0.3212,  0.9883, -1.7305,  1.1847],
        [-0.2366, -1.0235,  1.6206,  0.1760]])


In [29]:
check = target == 1
print(check.dtype)
print(check)

torch.bool
tensor([ True, False, False,  True, False, False, False])


In [30]:
data[check]  # 第零个维度布尔切片

tensor([[-2.9392,  0.3311, -1.4612,  0.2028],
        [-1.3327, -0.1844, -0.7482, -1.3966]])

In [31]:
data[:, check[:4]]  # 第一个维度上的布尔索引

tensor([[-2.9392,  0.2028],
        [ 1.1122,  0.3342],
        [ 1.0666, -1.2462],
        [-1.3327, -1.3966],
        [ 0.7182,  0.0978],
        [-0.3212,  1.1847],
        [-0.2366,  0.1760]])

In [32]:
data[target == 1, 2:]

tensor([[-1.4612,  0.2028],
        [-0.7482, -1.3966]])

In [33]:
print(target != 1)
print(~(target != 1))  # ~:取反
print(data[~(target != 1)])

tensor([False,  True,  True, False,  True,  True,  True])
tensor([ True, False, False,  True, False, False, False])
tensor([[-2.9392,  0.3311, -1.4612,  0.2028],
        [-1.3327, -0.1844, -0.7482, -1.3966]])


In [34]:
mask = (target == 1) | (target == 3)  # |:并集,不能使用关键字or
print(mask)
print(data[mask])

tensor([ True, False,  True,  True,  True, False, False])
tensor([[-2.9392,  0.3311, -1.4612,  0.2028],
        [ 1.0666, -0.4861,  1.0569, -1.2462],
        [-1.3327, -0.1844, -0.7482, -1.3966],
        [ 0.7182,  0.3388,  0.1546,  0.0978]])


In [35]:
mask1 = (target == 1) & (target == 3)  # &:交集,不能使用关键字and
print(mask1)
print(data[mask1])

tensor([False, False, False, False, False, False, False])
tensor([], size=(0, 4))


In [36]:
s = data < 0
s

tensor([[ True, False,  True, False],
        [False, False,  True, False],
        [False,  True, False,  True],
        [ True,  True,  True,  True],
        [False, False, False, False],
        [ True, False,  True, False],
        [ True,  True, False, False]])

In [37]:
# 所有s中不为False处的元素
print(data[s].shape)  # 1维tensor
print(data[s])

torch.Size([13])
tensor([-2.9392, -1.4612, -0.2456, -0.4861, -1.2462, -1.3327, -0.1844, -0.7482,
        -1.3966, -0.3212, -1.7305, -0.2366, -1.0235])


In [38]:
data[s] = 9999  # 逐个元素的布尔索引
data  # data发生改变

tensor([[9.9990e+03, 3.3108e-01, 9.9990e+03, 2.0283e-01],
        [1.1122e+00, 1.1066e+00, 9.9990e+03, 3.3419e-01],
        [1.0666e+00, 9.9990e+03, 1.0569e+00, 9.9990e+03],
        [9.9990e+03, 9.9990e+03, 9.9990e+03, 9.9990e+03],
        [7.1823e-01, 3.3877e-01, 1.5459e-01, 9.7802e-02],
        [9.9990e+03, 9.8832e-01, 9.9990e+03, 1.1847e+00],
        [9.9990e+03, 9.9990e+03, 1.6206e+00, 1.7596e-01]])

In [39]:
data[target != 2] = 7  # ★★★★★和整数索引类似,只能通过对原tensor[索引/切片]直接进行赋值从而修改原tensor
data  # data发生改变

tensor([[7.0000e+00, 7.0000e+00, 7.0000e+00, 7.0000e+00],
        [1.1122e+00, 1.1066e+00, 9.9990e+03, 3.3419e-01],
        [7.0000e+00, 7.0000e+00, 7.0000e+00, 7.0000e+00],
        [7.0000e+00, 7.0000e+00, 7.0000e+00, 7.0000e+00],
        [7.0000e+00, 7.0000e+00, 7.0000e+00, 7.0000e+00],
        [9.9990e+03, 9.8832e-01, 9.9990e+03, 1.1847e+00],
        [9.9990e+03, 9.9990e+03, 1.6206e+00, 1.7596e-01]])