In [80]:
import torch

### 参考numpy布尔索引

In [81]:
target = torch.tensor([1, 2, 3, 1, 3, 2, 2])
data = torch.randn(7, 4)
print(target)
print(data)

tensor([1, 2, 3, 1, 3, 2, 2])
tensor([[ 0.9061,  1.3232,  0.6042,  0.6767],
        [ 1.7679, -1.8281, -0.4181, -1.4143],
        [-0.4579,  0.9693,  0.1141,  0.6920],
        [ 0.3613, -1.1792,  0.1941,  1.4430],
        [-0.7636, -2.2736,  0.5939, -0.3412],
        [-1.6486, -0.3177, -1.1767,  0.1879],
        [ 0.5034, -1.0108,  0.6210, -0.9517]])


In [82]:
check = target == 1
print(check.dtype)
print(check)

torch.bool
tensor([ True, False, False,  True, False, False, False])


In [83]:
data[check]  # 第零个维度布尔切片

tensor([[ 0.9061,  1.3232,  0.6042,  0.6767],
        [ 0.3613, -1.1792,  0.1941,  1.4430]])

In [84]:
data[:, check[:4]]  # 第一个维度上的布尔索引

tensor([[ 0.9061,  0.6767],
        [ 1.7679, -1.4143],
        [-0.4579,  0.6920],
        [ 0.3613,  1.4430],
        [-0.7636, -0.3412],
        [-1.6486,  0.1879],
        [ 0.5034, -0.9517]])

In [85]:
data[target == 1, 2:]

tensor([[0.6042, 0.6767],
        [0.1941, 1.4430]])

In [86]:
print(target != 1)
print(~(target != 1))  # ~:取反
print(data[~(target != 1)])

tensor([False,  True,  True, False,  True,  True,  True])
tensor([ True, False, False,  True, False, False, False])
tensor([[ 0.9061,  1.3232,  0.6042,  0.6767],
        [ 0.3613, -1.1792,  0.1941,  1.4430]])


In [87]:
mask = (target == 1) | (target == 3)  # |:并集,不能使用关键字or
print(mask)
print(data[mask])

tensor([ True, False,  True,  True,  True, False, False])
tensor([[ 0.9061,  1.3232,  0.6042,  0.6767],
        [-0.4579,  0.9693,  0.1141,  0.6920],
        [ 0.3613, -1.1792,  0.1941,  1.4430],
        [-0.7636, -2.2736,  0.5939, -0.3412]])


In [88]:
mask1 = (target == 1) & (target == 3)  # &:交集,不能使用关键字and
print(mask1)
print(data[mask1])

tensor([False, False, False, False, False, False, False])
tensor([], size=(0, 4))


In [89]:
s = data < 0
s

tensor([[False, False, False, False],
        [False,  True,  True,  True],
        [ True, False, False, False],
        [False,  True, False, False],
        [ True,  True, False,  True],
        [ True,  True,  True, False],
        [False,  True, False,  True]])

In [90]:
# 所有s中不为False处的元素
print(data[s].shape)
print(data[s])

torch.Size([13])
tensor([-1.8281, -0.4181, -1.4143, -0.4579, -1.1792, -0.7636, -2.2736, -0.3412,
        -1.6486, -0.3177, -1.1767, -1.0108, -0.9517])


In [91]:
data[s] = 9999  # 逐个元素的布尔索引
data  # data发生改变

tensor([[9.0613e-01, 1.3232e+00, 6.0421e-01, 6.7668e-01],
        [1.7679e+00, 9.9990e+03, 9.9990e+03, 9.9990e+03],
        [9.9990e+03, 9.6926e-01, 1.1406e-01, 6.9199e-01],
        [3.6128e-01, 9.9990e+03, 1.9407e-01, 1.4430e+00],
        [9.9990e+03, 9.9990e+03, 5.9392e-01, 9.9990e+03],
        [9.9990e+03, 9.9990e+03, 9.9990e+03, 1.8786e-01],
        [5.0337e-01, 9.9990e+03, 6.2104e-01, 9.9990e+03]])

In [92]:
data[target != 2] = 7  # ★★★★★和整数索引类似,只能通过对原tensor[索引/切片]直接进行赋值从而修改原tensor
data  # data发生改变

tensor([[7.0000e+00, 7.0000e+00, 7.0000e+00, 7.0000e+00],
        [1.7679e+00, 9.9990e+03, 9.9990e+03, 9.9990e+03],
        [7.0000e+00, 7.0000e+00, 7.0000e+00, 7.0000e+00],
        [7.0000e+00, 7.0000e+00, 7.0000e+00, 7.0000e+00],
        [7.0000e+00, 7.0000e+00, 7.0000e+00, 7.0000e+00],
        [9.9990e+03, 9.9990e+03, 9.9990e+03, 1.8786e-01],
        [5.0337e-01, 9.9990e+03, 6.2104e-01, 9.9990e+03]])