In [127]:
import torch
# 类似numpy整数索引

tensor([[ 0.,  0.,  0.,  0.],
        [ 0.,  1.,  2.,  3.],
        [ 0.,  2.,  4.,  6.],
        [ 0.,  3.,  6.,  9.],
        [ 0.,  4.,  8., 12.],
        [ 0.,  5., 10., 15.],
        [ 0.,  6., 12., 18.],
        [ 0.,  7., 14., 21.]])

In [ ]:
tor = torch.empty((8, 4))
for i in range(8):
    for j in range(4):
        tor[i, j] = i * j
tor

In [128]:
tor[[4, 3, 0, 6]] # ★★★★★索引index必须为列表

tensor([[ 0.,  4.,  8., 12.],
        [ 0.,  3.,  6.,  9.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  6., 12., 18.]])

In [129]:
tor[[-3, -5, -7]] # 支持负数索引

tensor([[ 0.,  5., 10., 15.],
        [ 0.,  3.,  6.,  9.],
        [ 0.,  1.,  2.,  3.]])

In [130]:
tor[:, [-1, -2, 0]] # 对第二个维度进行索引

tensor([[ 0.,  0.,  0.],
        [ 3.,  2.,  0.],
        [ 6.,  4.,  0.],
        [ 9.,  6.,  0.],
        [12.,  8.,  0.],
        [15., 10.,  0.],
        [18., 12.,  0.],
        [21., 14.,  0.]])

In [131]:
s = tor[[4, 3, 0, 6]]
s

tensor([[ 0.,  4.,  8., 12.],
        [ 0.,  3.,  6.,  9.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  6., 12., 18.]])

In [132]:
s[0:3] = 100
s

tensor([[100., 100., 100., 100.],
        [100., 100., 100., 100.],
        [100., 100., 100., 100.],
        [  0.,   6.,  12.,  18.]])

In [133]:
tor # ★★★★★整数索引不能通过此方式修改原tensor

tensor([[ 0.,  0.,  0.,  0.],
        [ 0.,  1.,  2.,  3.],
        [ 0.,  2.,  4.,  6.],
        [ 0.,  3.,  6.,  9.],
        [ 0.,  4.,  8., 12.],
        [ 0.,  5., 10., 15.],
        [ 0.,  6., 12., 18.],
        [ 0.,  7., 14., 21.]])

In [134]:
tor1 = torch.arange(32).reshape((8, 4))
tor1

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]])

In [135]:
tor1[[1, 5, 7, 2], [0, 3, 1, 2]] # 选取索引为(1, 0),(5, 3),(7, 1),(2, 2)处的元素值

tensor([ 4, 23, 29, 10])

In [136]:
tor1[[1, 5, 7, 2], [0, 3, 1, 2]] = 11111
tor1 # ★★★★★整数索引修改元素必须使用此方式(即对原tensor索引/切片直接进行赋值)

tensor([[    0,     1,     2,     3],
        [11111,     5,     6,     7],
        [    8,     9, 11111,    11],
        [   12,    13,    14,    15],
        [   16,    17,    18,    19],
        [   20,    21,    22, 11111],
        [   24,    25,    26,    27],
        [   28, 11111,    30,    31]])

In [137]:
# 选取行索引为(1, 5, 7, 2)和列索引为(0, 3, 1, 2)组成的数据矩阵(两次整数索引)
tor1[[1, 5, 7, 2]][:, [0, 3, 1, 2]] # ★★★★★无法对其进行赋值进而修改tor1!如何解决?

tensor([[11111,     7,     5,     6],
        [   20, 11111,    21,    22],
        [   28,    31, 11111,    30],
        [    8,    11,     9, 11111]])

In [138]:
row = [1, 5, 7, 2] 
columns = [0, 3, 1, 2]
for k in row:
    s = tor1[k]
    s[columns] = 333333 # 间接赋值

In [139]:
tor1


tensor([[     0,      1,      2,      3],
        [333333, 333333, 333333, 333333],
        [333333, 333333, 333333, 333333],
        [    12,     13,     14,     15],
        [    16,     17,     18,     19],
        [333333, 333333, 333333, 333333],
        [    24,     25,     26,     27],
        [333333, 333333, 333333, 333333]])