In [1]:
import torch

In [2]:
x = torch.randn(3, 4, 3)
x

tensor([[[ 0.5483,  0.8091,  0.5873],
         [-0.4152,  0.0893,  1.1980],
         [ 0.6379, -0.6911, -0.6690],
         [-0.4665, -0.0722,  0.8793]],

        [[-0.3319,  0.4482,  0.2401],
         [ 1.5087,  1.5446, -2.5330],
         [-1.4839,  0.1689, -1.2980],
         [ 0.6924, -0.5392, -2.3757]],

        [[-0.4162,  1.4420,  2.1816],
         [-0.8604,  0.5881,  0.1512],
         [ 0.5028,  1.1443,  0.0730],
         [-0.8298,  0.8802,  1.4301]]])

In [3]:
indices = torch.tensor([0, 2])

In [4]:
'''
input (Tensor) – the input tensor.
dim (python:int) – the dimension in which we index
index (LongTensor) – the 1-D tensor containing the indices to index
'''
torch.index_select(x, dim=0, index=indices)  # 维度dim上按index索引切片x

tensor([[[ 0.5483,  0.8091,  0.5873],
         [-0.4152,  0.0893,  1.1980],
         [ 0.6379, -0.6911, -0.6690],
         [-0.4665, -0.0722,  0.8793]],

        [[-0.4162,  1.4420,  2.1816],
         [-0.8604,  0.5881,  0.1512],
         [ 0.5028,  1.1443,  0.0730],
         [-0.8298,  0.8802,  1.4301]]])

In [5]:
select = torch.index_select(x, 1, index=indices)  # ★★★★返回一个新的tensor
select

tensor([[[ 0.5483,  0.8091,  0.5873],
         [ 0.6379, -0.6911, -0.6690]],

        [[-0.3319,  0.4482,  0.2401],
         [-1.4839,  0.1689, -1.2980]],

        [[-0.4162,  1.4420,  2.1816],
         [ 0.5028,  1.1443,  0.0730]]])

In [6]:
select[:] = 0
select

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])

In [7]:
x  # x不变

tensor([[[ 0.5483,  0.8091,  0.5873],
         [-0.4152,  0.0893,  1.1980],
         [ 0.6379, -0.6911, -0.6690],
         [-0.4665, -0.0722,  0.8793]],

        [[-0.3319,  0.4482,  0.2401],
         [ 1.5087,  1.5446, -2.5330],
         [-1.4839,  0.1689, -1.2980],
         [ 0.6924, -0.5392, -2.3757]],

        [[-0.4162,  1.4420,  2.1816],
         [-0.8604,  0.5881,  0.1512],
         [ 0.5028,  1.1443,  0.0730],
         [-0.8298,  0.8802,  1.4301]]])