In [82]:
import torch

### 参考numpy整数和网格索引

In [83]:
arr = torch.empty((8, 4))
for i in range(8):
    for j in range(4):
        arr[i, j] = i * j
arr

tensor([[ 0.,  0.,  0.,  0.],
        [ 0.,  1.,  2.,  3.],
        [ 0.,  2.,  4.,  6.],
        [ 0.,  3.,  6.,  9.],
        [ 0.,  4.,  8., 12.],
        [ 0.,  5., 10., 15.],
        [ 0.,  6., 12., 18.],
        [ 0.,  7., 14., 21.]])

### 整数索引

In [84]:
arr[[4, 3, 0, 6]]  # ★★★★★索引index必须为列表

tensor([[ 0.,  4.,  8., 12.],
        [ 0.,  3.,  6.,  9.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  6., 12., 18.]])

In [85]:
arr[[-3, -5, -7]]  # 且支持负数索引

tensor([[ 0.,  5., 10., 15.],
        [ 0.,  3.,  6.,  9.],
        [ 0.,  1.,  2.,  3.]])

In [86]:
arr[:, [-1, -2, 0]]  # 对第一个维度进行索引

tensor([[ 0.,  0.,  0.],
        [ 3.,  2.,  0.],
        [ 6.,  4.,  0.],
        [ 9.,  6.,  0.],
        [12.,  8.,  0.],
        [15., 10.,  0.],
        [18., 12.,  0.],
        [21., 14.,  0.]])

In [87]:
s = arr[[4, 3, 0, 6]]
s

tensor([[ 0.,  4.,  8., 12.],
        [ 0.,  3.,  6.,  9.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  6., 12., 18.]])

In [88]:
s[:] = 100
s

tensor([[100., 100., 100., 100.],
        [100., 100., 100., 100.],
        [100., 100., 100., 100.],
        [100., 100., 100., 100.]])

In [89]:
# 整数索引和基本索引切片的区别:
# 基本索引切片只能对连续行(or/and)列进行索引,整数索引可以对任意位置的行(or/and)列进行索引
# 整数索引总是将数据复制到一个新的数组中
arr  # ★★★★★整数索引下此方式不能修改原数组

tensor([[ 0.,  0.,  0.,  0.],
        [ 0.,  1.,  2.,  3.],
        [ 0.,  2.,  4.,  6.],
        [ 0.,  3.,  6.,  9.],
        [ 0.,  4.,  8., 12.],
        [ 0.,  5., 10., 15.],
        [ 0.,  6., 12., 18.],
        [ 0.,  7., 14., 21.]])

In [90]:
arr[[4, 3, 0, 6]] = 100  # ★★★★★直接对整数索引进行赋值
arr  # arr改变

tensor([[100., 100., 100., 100.],
        [  0.,   1.,   2.,   3.],
        [  0.,   2.,   4.,   6.],
        [100., 100., 100., 100.],
        [100., 100., 100., 100.],
        [  0.,   5.,  10.,  15.],
        [100., 100., 100., 100.],
        [  0.,   7.,  14.,  21.]])

In [91]:
arr0 = torch.arange(32).reshape((8, 4))
arr0

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]])

In [92]:
# 选取行索引为(1, 5, 7, 2)和列索引为(0, 3, 1, 2)组成的数据矩阵(两次整数索引)
arr0[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

tensor([[ 4,  7,  5,  6],
        [20, 23, 21, 22],
        [28, 31, 29, 30],
        [ 8, 11,  9, 10]])

In [93]:
arr0[[1, 5, 7, 2]][:, [0, 3, 1, 2]] = 111111
arr0  # arr不变,如何解决?

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]])

In [94]:
# 解决方法如下:
row = [1, 5, 7, 2]
columns = [0, 3, 1, 2]
for k in row:
    s = arr0[k]
    s[columns] = 333333  # 间接赋值
arr0

tensor([[     0,      1,      2,      3],
        [333333, 333333, 333333, 333333],
        [333333, 333333, 333333, 333333],
        [    12,     13,     14,     15],
        [    16,     17,     18,     19],
        [333333, 333333, 333333, 333333],
        [    24,     25,     26,     27],
        [333333, 333333, 333333, 333333]])

### 网格索引

In [95]:
arr1 = torch.arange(320).reshape((8, 4, 10))
arr1

tensor([[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
         [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
         [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
         [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39]],

        [[ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
         [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
         [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
         [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79]],

        [[ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
         [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
         [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
         [110, 111, 112, 113, 114, 115, 116, 117, 118, 119]],

        [[120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
         [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
         [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
         [150, 151, 152, 153, 154, 155, 156, 157, 158, 159]],

        [[160, 1

In [96]:
arr1[[1, 5, 7, 2], [0, 3, 1, 2]]  # 选取索引为(1, 0),(5, 3),(7, 1),(2, 2)处的元素值

tensor([[ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
        [230, 231, 232, 233, 234, 235, 236, 237, 238, 239],
        [290, 291, 292, 293, 294, 295, 296, 297, 298, 299],
        [100, 101, 102, 103, 104, 105, 106, 107, 108, 109]])

In [97]:
arr1[[1, 5, 7, 2], [0, 3, 1, 2]] = 11111  # 与整数索引同理
arr1  # arr改变

tensor([[[    0,     1,     2,     3,     4,     5,     6,     7,     8,     9],
         [   10,    11,    12,    13,    14,    15,    16,    17,    18,    19],
         [   20,    21,    22,    23,    24,    25,    26,    27,    28,    29],
         [   30,    31,    32,    33,    34,    35,    36,    37,    38,    39]],

        [[11111, 11111, 11111, 11111, 11111, 11111, 11111, 11111, 11111, 11111],
         [   50,    51,    52,    53,    54,    55,    56,    57,    58,    59],
         [   60,    61,    62,    63,    64,    65,    66,    67,    68,    69],
         [   70,    71,    72,    73,    74,    75,    76,    77,    78,    79]],

        [[   80,    81,    82,    83,    84,    85,    86,    87,    88,    89],
         [   90,    91,    92,    93,    94,    95,    96,    97,    98,    99],
         [11111, 11111, 11111, 11111, 11111, 11111, 11111, 11111, 11111, 11111],
         [  110,   111,   112,   113,   114,   115,   116,   117,   118,   119]],

        [[  120,   121