In [202]:
import torch

### 参考numpy整数和网格索引

In [203]:
arr = torch.empty((8, 4))
for i in range(8):
    for j in range(4):
        arr[i, j] = i * j
arr

tensor([[ 0.,  0.,  0.,  0.],
        [ 0.,  1.,  2.,  3.],
        [ 0.,  2.,  4.,  6.],
        [ 0.,  3.,  6.,  9.],
        [ 0.,  4.,  8., 12.],
        [ 0.,  5., 10., 15.],
        [ 0.,  6., 12., 18.],
        [ 0.,  7., 14., 21.]])

### 整数索引

In [204]:
arr[[4, 3, 0, 6]]  # ★★★★★索引index必须为列表

tensor([[ 0.,  4.,  8., 12.],
        [ 0.,  3.,  6.,  9.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  6., 12., 18.]])

In [205]:
arr[[-3, -5, -7]]  # 且支持负数索引

tensor([[ 0.,  5., 10., 15.],
        [ 0.,  3.,  6.,  9.],
        [ 0.,  1.,  2.,  3.]])

In [206]:
arr[:, [-1, -2, 0]]  # 对第一个维度进行索引

tensor([[ 0.,  0.,  0.],
        [ 3.,  2.,  0.],
        [ 6.,  4.,  0.],
        [ 9.,  6.,  0.],
        [12.,  8.,  0.],
        [15., 10.,  0.],
        [18., 12.,  0.],
        [21., 14.,  0.]])

In [207]:
s = arr[[4, 3, 0, 6]]
s

tensor([[ 0.,  4.,  8., 12.],
        [ 0.,  3.,  6.,  9.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  6., 12., 18.]])

In [208]:
s[:] = 100
s

tensor([[100., 100., 100., 100.],
        [100., 100., 100., 100.],
        [100., 100., 100., 100.],
        [100., 100., 100., 100.]])

In [209]:
# 整数索引和基本索引切片的区别:
# 基本索引切片只能对连续行(or/and)列进行索引,整数索引可以对任意位置的行(or/and)列进行索引
# 整数索引总是将数据复制到一个新的数组中
arr  # ★★★★★整数索引下此方式不能修改原数组

tensor([[ 0.,  0.,  0.,  0.],
        [ 0.,  1.,  2.,  3.],
        [ 0.,  2.,  4.,  6.],
        [ 0.,  3.,  6.,  9.],
        [ 0.,  4.,  8., 12.],
        [ 0.,  5., 10., 15.],
        [ 0.,  6., 12., 18.],
        [ 0.,  7., 14., 21.]])

In [210]:
arr[[4, 3, 0, 6]] = 100  # ★★★★★直接对整数索引进行赋值
arr  # arr改变

tensor([[100., 100., 100., 100.],
        [  0.,   1.,   2.,   3.],
        [  0.,   2.,   4.,   6.],
        [100., 100., 100., 100.],
        [100., 100., 100., 100.],
        [  0.,   5.,  10.,  15.],
        [100., 100., 100., 100.],
        [  0.,   7.,  14.,  21.]])

In [211]:
arr0 = torch.arange(32).reshape((8, 4))
arr0

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]])

In [212]:
# 选取行索引为(1, 5, 7, 2)和列索引为(0, 3, 1, 2)组成的数据矩阵(两次整数索引)
arr0[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

tensor([[ 4,  7,  5,  6],
        [20, 23, 21, 22],
        [28, 31, 29, 30],
        [ 8, 11,  9, 10]])

In [213]:
arr0[[1, 5, 7, 2]][:, [0, 3, 1, 2]] = 111111
arr0  # arr不变,如何解决?

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]])

In [214]:
# 解决方法如下:
row = [1, 5, 7, 2]
columns = [0, 3, 1, 2]
for k in row:
    s = arr0[k]
    s[columns] = 333333  # 间接赋值
arr0

tensor([[     0,      1,      2,      3],
        [333333, 333333, 333333, 333333],
        [333333, 333333, 333333, 333333],
        [    12,     13,     14,     15],
        [    16,     17,     18,     19],
        [333333, 333333, 333333, 333333],
        [    24,     25,     26,     27],
        [333333, 333333, 333333, 333333]])

### 网格索引

In [215]:
arr1 = torch.arange(32).reshape((8, 4))
arr1

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]])

In [216]:
arr1[[1, 5, 7, 2], [0, 3, 1, 2]]  # 选取索引为(1, 0),(5, 3),(7, 1),(2, 2)处的元素值

tensor([ 4, 23, 29, 10])

In [217]:
arr1[[1, 5, 7, 2], [0, 3, 1, 2]] = 11111  # 与整数索引同理
arr1  # arr改变

tensor([[    0,     1,     2,     3],
        [11111,     5,     6,     7],
        [    8,     9, 11111,    11],
        [   12,    13,    14,    15],
        [   16,    17,    18,    19],
        [   20,    21,    22, 11111],
        [   24,    25,    26,    27],
        [   28, 11111,    30,    31]])