In [16]:
import torch

### 参考numpy网格索引

In [17]:
tor = torch.arange(32).reshape((8, 4))
tor

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]])

In [18]:
# 选取索引为(1, 0),(5, 3),(7, 1),(2, 2)处的元素值组成[x, x, x, x]
tor[[1, 5, 7, 2], [0, 3, 1, 2]]

tensor([ 4, 23, 29, 10])

In [19]:
# 选取索引为(0, 0),(5, 1),(3, 3),(2, 2),(5, 3),(1, 1)处的元素值组成[[x, x, x], [x, x, x]]
tor[[[0, 5, 3],
     [2, 5, 1]],
    [[0, 1, 3],
     [2, 3, 1]]]

tensor([[ 0, 21, 15],
        [10, 23,  5]])

In [20]:
tor[[1, 5, 7, 2], [0, 3, 1, 2]] = 11111  # 与整数索引同理
tor  # tor改变

tensor([[    0,     1,     2,     3],
        [11111,     5,     6,     7],
        [    8,     9, 11111,    11],
        [   12,    13,    14,    15],
        [   16,    17,    18,    19],
        [   20,    21,    22, 11111],
        [   24,    25,    26,    27],
        [   28, 11111,    30,    31]])

In [21]:
tor1 = torch.arange(120).reshape(5, 4, 6)
tor1

tensor([[[  0,   1,   2,   3,   4,   5],
         [  6,   7,   8,   9,  10,  11],
         [ 12,  13,  14,  15,  16,  17],
         [ 18,  19,  20,  21,  22,  23]],

        [[ 24,  25,  26,  27,  28,  29],
         [ 30,  31,  32,  33,  34,  35],
         [ 36,  37,  38,  39,  40,  41],
         [ 42,  43,  44,  45,  46,  47]],

        [[ 48,  49,  50,  51,  52,  53],
         [ 54,  55,  56,  57,  58,  59],
         [ 60,  61,  62,  63,  64,  65],
         [ 66,  67,  68,  69,  70,  71]],

        [[ 72,  73,  74,  75,  76,  77],
         [ 78,  79,  80,  81,  82,  83],
         [ 84,  85,  86,  87,  88,  89],
         [ 90,  91,  92,  93,  94,  95]],

        [[ 96,  97,  98,  99, 100, 101],
         [102, 103, 104, 105, 106, 107],
         [108, 109, 110, 111, 112, 113],
         [114, 115, 116, 117, 118, 119]]])

In [22]:
# 选取索引为(1, 0, 0),(0, 3, 1),(3, 1, 1),(2, 2, 1)处的元素值组成[x, x, x, x]
tor1[[1, 0, 3, 2], [0, 3, 1, 2], [0, 1, 1, 1]]

tensor([24, 19, 79, 61])

In [23]:
# x_v表示向量(即[x, ...., x])
# 同理x_m表示矩阵(即[[x, ..., x], [x, ..., x])
# 选取索引为(1, 0, :),(0, 3, :),(3, 1, :),(2, 2, :)处的元素值组成[x_v, x_v, x_v, x_v]
tor1[[1, 0, 3, 2], [0, 3, 1, 2], :]

tensor([[24, 25, 26, 27, 28, 29],
        [18, 19, 20, 21, 22, 23],
        [78, 79, 80, 81, 82, 83],
        [60, 61, 62, 63, 64, 65]])

In [24]:
# 选取索引为(0, 0, :),(1, 1, :),(3, 3, :),(2, 2, :),(0, 3, :),(1, 1, 1:)处的元素值
# 组成[[x_v, x_v, x_v],
#     [x_v, x_v, x_v]]
tor1[[[0, 1, 3],
      [2, 0, 1]],
     [[0, 1, 3],
      [2, 3, 1]]]

tensor([[[ 0,  1,  2,  3,  4,  5],
         [30, 31, 32, 33, 34, 35],
         [90, 91, 92, 93, 94, 95]],

        [[60, 61, 62, 63, 64, 65],
         [18, 19, 20, 21, 22, 23],
         [30, 31, 32, 33, 34, 35]]])