$$ l(\mathbf{x}, \mathbf{y}) = L = (l_1, l_2, \cdots, l_N)^T \qquad \text{if  reduction='none'}$$

* $$ l_n = - \mathbf{w}_n [ \mathbf{y}_n \cdot \log \mathbf{x}_n + (1 - \mathbf{y}_n) \cdot ( 1 - \log \mathbf{x}_n )] $$

where N is the batch size. If reduction is not 'none' (default 'mean'), then

\begin{equation}
l(X, \mathbf{y}) =\begin{cases}
		\mathrm{mean}(L), & \text{if  reduction='mean'} \\
        \mathrm{sum}(L), & \text{if  reduction='sum'}
     \end{cases}
\end{equation}

Note that the targets $ \mathbf{y}$ should be numbers between 0 and 1

* Input: $(*)$where * means, any number of additional dimensions

* Target: $(*)$, same shape as the input

* Output: scalar. If reduction is 'none', then (*), same shape as input.

In [22]:
import torch
import torch.nn.functional as F
import torch.nn as nn

In [23]:
# enter.shape=(2, 3)
enter = torch.tensor([[0.5, 0.4, 0.3],
                      [0.3, 0.2, 0.5]])
# target.shape=(2, 3)
target = torch.tensor([[0., 1., 0.],
                       [1., 0., 0.]])

# 二分类交叉熵
print(F.binary_cross_entropy(enter, target, reduction='sum'))
print(F.binary_cross_entropy(enter, target, reduction='mean'))  # 默认reduction='mean'
print(F.binary_cross_entropy(enter, target, reduction='none'))  # shape=(2, )

tensor(4.0864)
tensor(0.6811)
tensor([[0.6931, 0.9163, 0.3567],
        [1.2040, 0.2231, 0.6931]])


In [24]:
# 'none': no reduction will be applied
# 'mean': the sum of the output will be divided by the number of elements in the output,
# 'sum': the output will be summed
#  Default: 'mean'
print(nn.BCELoss(reduction='none',
                 # weight(样本权重,可间接实现类别权重)形状与enter形状相等;默认weight=None,此时weight为全为1的张量
                 weight=torch.ones_like(enter))(enter, target))

tensor([[0.6931, 0.9163, 0.3567],
        [1.2040, 0.2231, 0.6931]])


### 上式计算步骤如下

In [25]:
weight = torch.ones_like(enter)  # 默认权重
weight

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [26]:
step1 = -(target * torch.log(enter) + (1 - target) * torch.log(1 - enter))  # 样本交叉熵
step1  # 对应reduction='none'

tensor([[0.6931, 0.9163, 0.3567],
        [1.2040, 0.2231, 0.6931]])

In [27]:
the_sum = torch.sum(step1 * weight)  # 最终结果
the_sum  # 对应reduction='sum'

tensor(4.0864)

In [28]:
the_mean = torch.mean(step1 * weight)
the_mean  # 对应reduction='mean'


tensor(0.6811)