$$ l(\mathbf{x}, \mathbf{y}) = L = (l_1, l_2, \cdots, l_N)^T \qquad \text{if  reduction='none'}$$

* $$ l_n = - \mathbf{w}_n [ \mathbf{y}_n \cdot \log \mathbf{x}_n + (1 - \mathbf{y}_n) \cdot ( 1 - \log \mathbf{x}_n )] $$

where N is the batch size. If reduction is not 'none' (default 'mean'), then

\begin{equation}
l(X, \mathbf{y}) =\begin{cases}
		\mathrm{mean}(L), & \text{if  reduction='mean'} \\
        \mathrm{sum}(L), & \text{if  reduction='sum'}
     \end{cases}
\end{equation}

Note that the targets $ \mathbf{y}$ should be numbers between 0 and 1

* Input: $(N, *)$where *∗ means, any number of additional dimensions
* Target: $(N, *)$, same shape as the input

In [1]:
import torch
import torch.nn.functional as F
import torch.nn as nn

In [2]:
enter = torch.tensor([[0.5],
                      [0.3]])
target = torch.tensor([[0.],
                       [1.]])
F.binary_cross_entropy(enter, target, reduction='mean')  # 二分类交叉熵

tensor(0.9486)

In [3]:
# 'none': no reduction will be applied
# 'mean': the sum of the output will be divided by the number of elements in the output,
# 'sum': the output will be summed
#  Default: 'mean'
nn.BCELoss(reduction='none',
           weight=torch.ones_like(enter))(enter, target)  # weight形状与enter形状相等;默认weight=None,此时weight为全为1的张量

tensor([[0.6931],
        [1.2040]])

### 上式计算步骤如下

In [4]:
weight = torch.ones_like(enter)  # 默认权重
weight

tensor([[1.],
        [1.]])

In [5]:
step1 = -(target * torch.log(enter) + (1 - target) * torch.log(1 - enter))  # 样本交叉熵
step1  # 对应reduction='none'

tensor([[0.6931],
        [1.2040]])

In [6]:
the_sum = torch.sum(step1 * weight)  # 最终结果
the_sum  # 对应reduction='sum'

tensor(1.8971)

In [7]:
the_mean = torch.mean(step1 * weight)
the_mean  # 对应reduction='mean'


tensor(0.9486)