In [193]:
from collections import namedtuple
import torch
from torch.utils.data.dataloader import default_collate  # torch.utils.data.DataLoader collate_fn方法默认使用的函数

In [194]:
# * `float` -> :class:`torch.Tensor`
# * `int` -> :class:`torch.Tensor`
print(default_collate([0, 1, 2, 3]))
print(default_collate([0., 1., 2., 3.]))

tensor([0, 1, 2, 3])
tensor([0., 1., 2., 3.], dtype=torch.float64)


In [195]:
# * `str` -> `str` (unchanged)
default_collate(['a', 'b', 'c'])

['a', 'b', 'c']

In [196]:
# * `Mapping[K, V_i]` -> `Mapping[K, default_collate([V_1, V_2, ...])]`
default_collate([{'A': 0, 'B': 1},
                 {'A': 100, 'B': 100}])

{'A': tensor([  0, 100]), 'B': tensor([  1, 100])}

In [197]:
default_collate([{'A': [1, 2], 'B': torch.tensor([-1, -2])},
                 {'A': [3, 4], 'B': torch.tensor([-3, -4])}])

{'A': [tensor([1, 3]), tensor([2, 4])],
 'B': tensor([[-1, -2],
         [-3, -4]])}

In [198]:
default_collate([{'A': torch.tensor([1, 2]), 'B': torch.tensor([-1, -2])},
                 {'A': torch.tensor([3, 4]), 'B': torch.tensor([-3, -4])}])  # 相比于列表,tensor合并(new dimension)成一个tensor

{'A': tensor([[1, 2],
         [3, 4]]),
 'B': tensor([[-1, -2],
         [-3, -4]])}

In [199]:
# `NamedTuple[V1_i, V2_i, ...]` -> `NamedTuple[default_collate([V1_1, V1_2, ...]), default_collate([V2_1, V2_2, ...]), ...]`
Point = namedtuple('Point', ['x', 'y'])
default_collate([Point(0, 0), Point(1, 1)])

Point(x=tensor([0, 1]), y=tensor([0, 1]))

In [200]:
# `Sequence[V1_i, V2_i, ...]` -> `Sequence[default_collate([V1_1, V1_2, ...]), default_collate([V2_1, V2_2, ...]), ...]`
default_collate([[0, 1],
                 [2, 3],
                 [4, 5]])

[tensor([0, 2, 4]), tensor([1, 3, 5])]

In [201]:
default_collate([["dc", 1],
                 ["dmm", 3],
                 ["come on!", 5]])

[('dc', 'dmm', 'come on!'), tensor([1, 3, 5])]

In [202]:
default_collate([[[1, 1], 11],
                 [[2, 2], 22],
                 [[3, 3], 33]])

[[tensor([1, 2, 3]), tensor([1, 2, 3])], tensor([11, 22, 33])]

In [203]:
default_collate([(torch.tensor([1, 1]), 11),
                 (torch.tensor([2, 2]), 22),
                 (torch.tensor([3, 3]), 33)])  # 相比于列表,合并(new dimension)成一个tensor

[tensor([[1, 1],
         [2, 2],
         [3, 3]]),
 tensor([11, 22, 33])]

In [204]:
default_collate([(torch.tensor([[1, 1],
                                [-1, -1]]), 11),
                 (torch.tensor([[2, 2],
                                [-2, -2]]), 22),
                 (torch.tensor([[3, 3],
                                [-3, -3]]), 33)])

[tensor([[[ 1,  1],
          [-1, -1]],
 
         [[ 2,  2],
          [-2, -2]],
 
         [[ 3,  3],
          [-3, -3]]]),
 tensor([11, 22, 33])]

In [205]:
default_collate([(torch.tensor([[[1, 1],
                                 [-1, -1]]]), 11),
                 (torch.tensor([[[2, 2],
                                 [-2, -2]]]), 22),
                 (torch.tensor([[[3, 3],
                                 [-3, -3]]]), 33)])

[tensor([[[[ 1,  1],
           [-1, -1]]],
 
 
         [[[ 2,  2],
           [-2, -2]]],
 
 
         [[[ 3,  3],
           [-3, -3]]]]),
 tensor([11, 22, 33])]