## 标量/scalar 

In [10]:
import torch
# 完全类似numpy/基本操作数组乘积/数据类型

arr_scalar = torch.tensor(10) # 可视为一个点
print(arr_scalar.ndim)
print(arr_scalar.shape)
print(arr_scalar)

0
torch.Size([])
tensor(10)


## 向量/vector

In [11]:
arr_vector = torch.tensor([1, 2, 3]) # 可视为一条线
print(arr_vector.ndim)
print(arr_vector.shape)
print(arr_vector)

1
torch.Size([3])
tensor([1, 2, 3])


## 矩阵/matrix

In [12]:
arr_matrix = torch.tensor([[1, 2, 3], [2, 3, 4]]) # 可视为一个方阵
print(arr_matrix.ndim)
print(arr_matrix.shape)
print(arr_matrix)

2
torch.Size([2, 3])
tensor([[1, 2, 3],
        [2, 3, 4]])


### 高维矩阵(ndim>2)

In [13]:
arr_mul_matrix = torch.randn(3, 4, 5)
print(arr_mul_matrix.ndim)
print(arr_mul_matrix.shape)
print(arr_mul_matrix)



3
torch.Size([3, 4, 5])
tensor([[[ 0.8188,  0.0754,  0.3172,  0.4301,  0.7173],
         [-0.6246,  0.9922,  0.9258, -0.3838,  0.1279],
         [-0.3179,  1.4397, -0.2744,  0.7844,  2.6652],
         [-0.1234, -0.7738, -0.9814, -0.8757,  1.3948]],

        [[ 1.6794,  0.3423, -1.2142, -1.5438, -1.4325],
         [-0.8867,  0.6123,  1.0052, -1.0002,  1.1884],
         [-1.2811,  1.6602, -0.9681,  1.3639,  2.6110],
         [ 0.7213,  0.5105, -0.2147,  1.7475,  2.0580]],

        [[-0.1684, -0.3709,  0.4435, -0.0654,  1.1055],
         [ 0.4677, -0.5345,  0.0869, -0.9633, -0.3453],
         [-0.4458, -0.2539,  0.5038, -0.0383, -0.3188],
         [-1.0052,  0.8742,  1.2509,  1.8319,  0.9378]]])
