* input:$(N, C, H_{in}, W_{in})$
* output:$(N, C, H_{out}, W_{out})$

\begin{array}{l}
H_{out} &= \lfloor \frac{H_{in} + 2\times padding[0] - kernel\_size[0] }{stride[0]} +1  \rfloor \\
W_{out} &= \lfloor \frac{W_{in} + 2\times padding[1] - kernel\_size[1] }{stride[1]} +1  \rfloor \\
\end{array}

In [17]:
import torch.nn as nn
import torch
import torch.nn.functional as F

In [18]:
'''
kernel_size – the size of the window to take a max over
stride – the stride of the window. Default value is kernel_size
padding – implicit zero padding to be added on both sides
dilation – a parameter that controls the stride of elements in the window
'''
input_tensor = torch.arange(100, 13400).reshape((1, 1, 70, 190)).to(torch.float32)
max_f = F.max_pool2d(input=input_tensor,
                     kernel_size=(3, 5),  # 池化窗口的大小
                     stride=2,  # 池化窗口移动的步幅
                     padding=(1, 2),  # 输入张量在边缘位置的填充(注意★★★★★:必须为int类型的元组)
                     dilation=2,  # 与卷积运算中dilation的定义相同
                     ceil_mode=False)  # 最后输出大小是否进行向上取整,默认进行向下取整
max_f

tensor([[[[  676.,   678.,   680.,  ...,   856.,   858.,   858.],
          [ 1056.,  1058.,  1060.,  ...,  1236.,  1238.,  1238.],
          [ 1436.,  1438.,  1440.,  ...,  1616.,  1618.,  1618.],
          ...,
          [12456., 12458., 12460.,  ..., 12636., 12638., 12638.],
          [12836., 12838., 12840.,  ..., 13016., 13018., 13018.],
          [13216., 13218., 13220.,  ..., 13396., 13398., 13398.]]]])

In [19]:
'''
return_indices –
    if True, will return the max indices along with the outputs.
    Useful for torch.nn.MaxUnpool2d later
'''
max_f1, max_f1_indices = F.max_pool2d(input=input_tensor, kernel_size=(3, 5), stride=2, dilation=2,
                                      padding=1, ceil_mode=False, return_indices=True)
max_f1_indices

tensor([[[[  577,   579,   581,  ...,   755,   757,   759],
          [  957,   959,   961,  ...,  1135,  1137,  1139],
          [ 1337,  1339,  1341,  ...,  1515,  1517,  1519],
          ...,
          [12357, 12359, 12361,  ..., 12535, 12537, 12539],
          [12737, 12739, 12741,  ..., 12915, 12917, 12919],
          [13117, 13119, 13121,  ..., 13295, 13297, 13299]]]])

In [20]:
max_c = nn.MaxPool2d(kernel_size=(3, 5), stride=2, dilation=2,
                     padding=1, ceil_mode=False, return_indices=True)
max_c0, max_c0_indices = max_c(input_tensor)
max_c0

tensor([[[[  677.,   679.,   681.,  ...,   855.,   857.,   859.],
          [ 1057.,  1059.,  1061.,  ...,  1235.,  1237.,  1239.],
          [ 1437.,  1439.,  1441.,  ...,  1615.,  1617.,  1619.],
          ...,
          [12457., 12459., 12461.,  ..., 12635., 12637., 12639.],
          [12837., 12839., 12841.,  ..., 13015., 13017., 13019.],
          [13217., 13219., 13221.,  ..., 13395., 13397., 13399.]]]])

In [21]:
max_c0_indices.shape

torch.Size([1, 1, 34, 92])