* input:$(N, C, H_{in}, W_{in})$
* output:$(N, C, H_{out}, W_{out})$

\begin{array}{l}
H_{out} &= \lfloor \frac{H_{in} + 2\times padding[0] - kernel\_size[0] }{stride[0]} +1  \rfloor \\
W_{out} &= \lfloor \frac{W_{in} + 2\times padding[1] - kernel\_size[1] }{stride[1]} +1  \rfloor \\
\end{array}

In [1]:
import torch.nn as nn
import torch
import torch.nn.functional as F

In [2]:
input_tensor = torch.ones((1, 1, 70, 190))
avg_f = F.avg_pool2d(input=input_tensor,
                     kernel_size=(3, 5), # 池化窗口的大小
                     stride=2, # 池化窗口移动的步幅
                     padding=1, # 输入张量在边缘位置的填充
                     ceil_mode=False) # 最后输出大小是否进行向上取整,默认进行向下取整
'''
kernel_size – size of the pooling region. Can be a single number or a tuple (kH, kW)
stride – stride of the pooling operation. Can be a single number or a tuple (sH, sW). Default: kernel_size
padding – implicit zero paddings on both sides of the input. Can be a single number or a tuple (padH, padW). Default: 0
ceil_mode – when True, will use ceil instead of floor in the formula to compute the output shape. Default: False
'''
avg_f

tensor([[[[0.5333, 0.6667, 0.6667,  ..., 0.6667, 0.6667, 0.6667],
          [0.8000, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 1.0000],
          [0.8000, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 1.0000],
          ...,
          [0.8000, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 1.0000],
          [0.8000, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 1.0000],
          [0.8000, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 1.0000]]]])

In [3]:
F.avg_pool2d(input=input_tensor, kernel_size=(3, 5), padding=1,
             count_include_pad=False) # 默认count_include_pad=True,即如果pading>0,那么填充的0元素将会参与平均值的计算,否则填充的0元素不参与平均值的计算

tensor([[[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
           1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
           1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
           1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
           1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
           1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
           1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
           1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
           1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
           1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
           1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,

In [51]:
F.avg_pool2d(input=input_tensor, kernel_size=(3, 5),
             divisor_override=100) # 计算Average Pooling时,不实用池化窗口包含元素数目作为分母,而是使用divisor_override指定的整数作为整除的分母

tensor([[[[0.1500, 0.1500, 0.1500, 0.1500, 0.1500, 0.1500, 0.1500, 0.1500,
           0.1500, 0.1500, 0.1500, 0.1500, 0.1500, 0.1500, 0.1500, 0.1500,
           0.1500, 0.1500, 0.1500, 0.1500, 0.1500, 0.1500, 0.1500, 0.1500,
           0.1500, 0.1500, 0.1500, 0.1500, 0.1500, 0.1500, 0.1500, 0.1500,
           0.1500, 0.1500, 0.1500, 0.1500, 0.1500, 0.1500],
          [0.1500, 0.1500, 0.1500, 0.1500, 0.1500, 0.1500, 0.1500, 0.1500,
           0.1500, 0.1500, 0.1500, 0.1500, 0.1500, 0.1500, 0.1500, 0.1500,
           0.1500, 0.1500, 0.1500, 0.1500, 0.1500, 0.1500, 0.1500, 0.1500,
           0.1500, 0.1500, 0.1500, 0.1500, 0.1500, 0.1500, 0.1500, 0.1500,
           0.1500, 0.1500, 0.1500, 0.1500, 0.1500, 0.1500],
          [0.1500, 0.1500, 0.1500, 0.1500, 0.1500, 0.1500, 0.1500, 0.1500,
           0.1500, 0.1500, 0.1500, 0.1500, 0.1500, 0.1500, 0.1500, 0.1500,
           0.1500, 0.1500, 0.1500, 0.1500, 0.1500, 0.1500, 0.1500, 0.1500,
           0.1500, 0.1500, 0.1500, 0.1500, 0.1500, 0.15

In [52]:
avg_c = nn.AvgPool2d(kernel_size=(3, 5), stride=2,
                     padding=1, ceil_mode=False,
                     divisor_override=100)
avg_c(input_tensor)

tensor([[[[0.0800, 0.1000, 0.1000,  ..., 0.1000, 0.1000, 0.1000],
          [0.1200, 0.1500, 0.1500,  ..., 0.1500, 0.1500, 0.1500],
          [0.1200, 0.1500, 0.1500,  ..., 0.1500, 0.1500, 0.1500],
          ...,
          [0.1200, 0.1500, 0.1500,  ..., 0.1500, 0.1500, 0.1500],
          [0.1200, 0.1500, 0.1500,  ..., 0.1500, 0.1500, 0.1500],
          [0.1200, 0.1500, 0.1500,  ..., 0.1500, 0.1500, 0.1500]]]])