In [107]:
import numpy as np

x = np.ones((2, 3))
x

array([[1., 1., 1.],
       [1., 1., 1.]])

In [108]:
y = np.zeros((2, 3))
y

array([[0., 0., 0.],
       [0., 0., 0.]])

In [109]:
# 在新的维度上连接数组x,y
a = np.stack((x, y), axis=0) # Each array must have the same shape
a

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [110]:
a[0] # 即x

array([[1., 1., 1.],
       [1., 1., 1.]])

In [111]:
a[1] # 即y

array([[0., 0., 0.],
       [0., 0., 0.]])

In [112]:
b = np.stack((x, y), axis=1)
b

array([[[1., 1., 1.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [0., 0., 0.]]])

In [113]:
b[:, 0] # 即x

array([[1., 1., 1.],
       [1., 1., 1.]])

In [114]:
b[:, 1] # 即y

array([[0., 0., 0.],
       [0., 0., 0.]])

In [115]:
c = np.stack((x, y), axis=2)
c

array([[[1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.]]])

In [116]:
c[..., 0] # 即x

array([[1., 1., 1.],
       [1., 1., 1.]])

In [117]:
c[..., 1] # 即y

array([[0., 0., 0.],
       [0., 0., 0.]])