In [94]:
import numpy as np

In [95]:
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])

# 在新的维度上连接数组arr1,arr2
print(np.stack((arr1, arr2), axis=1))
print(np.stack((arr1, arr2), axis=0))

[[1 3]
 [2 4]]
[[1 2]
 [3 4]]


In [96]:
x = np.ones((2, 3))
x

array([[1., 1., 1.],
       [1., 1., 1.]])

In [97]:
y = np.zeros((2, 3))
y

array([[0., 0., 0.],
       [0., 0., 0.]])

In [98]:
# 在新的维度上连接数组x,y
# x.dim=2,y.dim=2;故a.dim=3,故axis可选值有0,1,2
a = np.stack((x, y), axis=2)  # Each array must have the same shape
a

array([[[1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.]]])

In [99]:
a[0]  # 即x

array([[1., 0.],
       [1., 0.],
       [1., 0.]])

In [100]:
a[1]  # 即y

array([[1., 0.],
       [1., 0.],
       [1., 0.]])

In [101]:
b = np.stack((x, y), axis=1)
b

array([[[1., 1., 1.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [0., 0., 0.]]])

In [102]:
b[:, 0]  # 即x

array([[1., 1., 1.],
       [1., 1., 1.]])

In [103]:
b[:, 1]  # 即y

array([[0., 0., 0.],
       [0., 0., 0.]])

In [104]:
c = np.stack((x, y), axis=2)
c

array([[[1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.]]])

In [105]:
c[..., 0]  # 即x

array([[1., 1., 1.],
       [1., 1., 1.]])

In [106]:
c[..., 1]  # 即y

array([[0., 0., 0.],
       [0., 0., 0.]])