&emsp;&emsp;设特征空间$ \mathcal{X} $是$ n $ 向量空间$ \mathbf{R}^n,\mathbf{x}_i = (x_i^{(1)},x_i^{(2)}, \dots, x_i^{(n)} ), \mathbf{x}_j = (x_j^{(1)},x_j^{(2)}, \dots, x_j^{(n)},x_i, x_j $的$  L_p$距离定义为   
$$ L_p(\mathbf{x}_i, \mathbf{x}_j) = \left( \sum \limits _{l=1}^{n} |x_i^{(l)} - x_j^{(l)} |^p  \right)^{\frac{1}{p}} $$   
这里$ p \leq 1 $.当$ p=2$,称为欧氏距离,即   
$$ L_2(\mathbf{x}_1, \mathbf{x}_j)  = \left(\sum \limits _{l=1}^{n} |x_i^{(l)} - x_j^{(l)} |^2 \right)^{\frac{1}{2}} $$   
当$p=1$时,称为曼哈顿距离,即     
$$ L_1(\mathbf{x}_1, \mathbf{x}x_j)  = \sum \limits _{l=1}^{n}  \left|x_i^{(l)} - x_j^{(l)} \right | $$  
当$ p=\infty  $,它是各个坐标距离(切比雪夫距离)的最大值,即  
$$ L_{\infty}(\mathbf{x}_1, \mathbf{x}_j)  = \max_l \left |x_i^{(l)} - x_j^{(l)} \right|  $$   

<img src="../../../Other/img/distance.png" style="width=400px;height=300px;float=bottom">

In [7]:
import numpy as np
from scipy.spatial import  distance # scipy实现
x = np.array([1, 3, 5])
y = np.array([2, 4, 6])
mat = np.vstack([x, y])
mat

array([[1, 3, 5],
       [2, 4, 6]])

In [8]:
# 计算(行)向量x,y的距离
distance.pdist(mat) # 默认metric='euclidean'(欧氏距离)

array([1.73205081])

In [9]:
distance.pdist(mat, metric='cityblock') # 曼哈顿距离

array([3.])

In [10]:
distance.pdist(mat, metric='chebyshev') # 切比雪夫距离


array([1.])