In [23]:
import tensorflow as tf

In [24]:
'''
input_signature: A possibly nested sequence of tf.TensorSpec objects specifying the shapes and dtypes of the Tensors that will be supplied to this function.
                 If None, a separate function is instantiated for each inferred input signature.
                 If input_signature is specified, every input to func must be a Tensor, and func cannot accept **kwargs.
'''
@tf.function(input_signature=[tf.TensorSpec(shape=(None, 4), dtype=tf.float32, name='func_f')])
def f(x):
    return x

In [25]:
# shape不一致
f(tf.constant([[1.9, 2.3, 3.4],
               [2.1, 5., 9.2]]))

ValueError: Python inputs incompatible with input_signature:
  inputs: (
    tf.Tensor(
[[1.9 2.3 3.4]
 [2.1 5.  9.2]], shape=(2, 3), dtype=float32))
  input_signature: (
    TensorSpec(shape=(None, 4), dtype=tf.float32, name='func_f')).

In [26]:
# 类型不一致
f(tf.constant([[1.9, 2.3, 3.4, 34.1],
               [2.1, 5., 9.2, -2]], dtype=tf.double))

ValueError: Python inputs incompatible with input_signature:
  inputs: (
    tf.Tensor(
[[ 1.9  2.3  3.4 34.1]
 [ 2.1  5.   9.2 -2. ]], shape=(2, 4), dtype=float64))
  input_signature: (
    TensorSpec(shape=(None, 4), dtype=tf.float32, name='func_f')).

In [27]:
f(tf.constant([[1.9, 2.3, 3.4, 34.1],
               [2.1, 5., 9.2, -2]]))

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[ 1.9,  2.3,  3.4, 34.1],
       [ 2.1,  5. ,  9.2, -2. ]], dtype=float32)>

In [28]:
f.input_signature



(TensorSpec(shape=(None, 4), dtype=tf.float32, name='func_f'),)