In [18]:
import tensorflow as tf

### 参考numpy.stack

In [19]:
x = tf.ones((2, 3))
x

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [20]:
y = tf.zeros((2, 3))
y

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [21]:
# Stacks a list of rank-`R` tensors into one rank-`(R+1)` tensor.
# 在新的维度上连接数组x,y
a = tf.stack([x, y], axis=0)
a

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)>

In [22]:
a[0]  # 即x

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [23]:
a[1]  # 即y

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [24]:
b = tf.stack([x, y], axis=1)
b

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [0., 0., 0.]]], dtype=float32)>

In [25]:
b[:, 0]  # 即x

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [26]:
b[:, 1]  # 即y

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [27]:
c = tf.stack([x, y], axis=2)
c

<tf.Tensor: shape=(2, 3, 2), dtype=float32, numpy=
array([[[1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.]]], dtype=float32)>

In [28]:
c[..., 0]  # 即x

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [29]:
c[..., 1]  # 即y

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>