In [150]:
import numpy as np
import torch

In [151]:
arr_mul = np.random.randn(5, 7, 4)
arr_mul

array([[[ 1.1694984 , -0.39725987,  0.69574073,  0.66706362],
        [-0.06039714, -0.28796528,  0.22059555, -0.35207997],
        [ 0.44726367, -0.74839976,  0.76184   , -1.07978613],
        [-1.23053622, -1.03758163,  0.89012718,  0.68410364],
        [ 0.3425219 , -0.38457719,  0.08602741, -0.47944826],
        [-0.61831976, -0.20837851,  1.3390817 ,  0.38308595],
        [ 0.02566264, -0.73035591, -1.28920487, -1.11307547]],

       [[-0.69641684, -1.69208571, -2.21548585, -0.91708073],
        [-1.06475516,  0.04012136, -0.01248295, -0.22289695],
        [-0.0626557 ,  0.17695787, -0.52132297, -0.04094236],
        [-0.7795427 ,  0.23831546, -0.92723935, -0.73927504],
        [-0.60430073,  0.88369235, -0.42200697, -0.45921842],
        [ 0.42326169, -0.88598169,  0.43138345, -1.18539687],
        [ 0.76371917,  1.02191413, -0.41830038, -0.62873746]],

       [[ 1.05330273, -0.66412836,  0.45664097,  0.43063419],
        [-0.42063499,  0.4921963 ,  0.7191431 , -1.40031218],
    

In [152]:
arr_mul[0, 1, 1]  # 索引标量数值

-0.28796528028525203

In [153]:
arr_mul[0]  # 从第零个维度开始索引/切片(DataFrame从列开始进行索引切片)

array([[ 1.1694984 , -0.39725987,  0.69574073,  0.66706362],
       [-0.06039714, -0.28796528,  0.22059555, -0.35207997],
       [ 0.44726367, -0.74839976,  0.76184   , -1.07978613],
       [-1.23053622, -1.03758163,  0.89012718,  0.68410364],
       [ 0.3425219 , -0.38457719,  0.08602741, -0.47944826],
       [-0.61831976, -0.20837851,  1.3390817 ,  0.38308595],
       [ 0.02566264, -0.73035591, -1.28920487, -1.11307547]])

In [154]:
arr_mul[0, 0, -1]  # 索引,若为标量则返回具体数值(且支持负数索引)

0.6670636212718031

In [155]:
arr_mul[0:2]  # 切片,返回array

array([[[ 1.1694984 , -0.39725987,  0.69574073,  0.66706362],
        [-0.06039714, -0.28796528,  0.22059555, -0.35207997],
        [ 0.44726367, -0.74839976,  0.76184   , -1.07978613],
        [-1.23053622, -1.03758163,  0.89012718,  0.68410364],
        [ 0.3425219 , -0.38457719,  0.08602741, -0.47944826],
        [-0.61831976, -0.20837851,  1.3390817 ,  0.38308595],
        [ 0.02566264, -0.73035591, -1.28920487, -1.11307547]],

       [[-0.69641684, -1.69208571, -2.21548585, -0.91708073],
        [-1.06475516,  0.04012136, -0.01248295, -0.22289695],
        [-0.0626557 ,  0.17695787, -0.52132297, -0.04094236],
        [-0.7795427 ,  0.23831546, -0.92723935, -0.73927504],
        [-0.60430073,  0.88369235, -0.42200697, -0.45921842],
        [ 0.42326169, -0.88598169,  0.43138345, -1.18539687],
        [ 0.76371917,  1.02191413, -0.41830038, -0.62873746]]])

In [156]:
arr_mul[0:2, 0:3, 0]  # 在多个维度上索引/切片

array([[ 1.1694984 , -0.06039714,  0.44726367],
       [-0.69641684, -1.06475516, -0.0626557 ]])

In [157]:
temp = np.arange(10)
print(temp)
print(temp[::2])
print(temp[1::2])
print(temp[2:8:3])

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[1 3 5 7 9]
[2 5]


In [158]:
arr_mul[0:2, 0:6:2, 2]  # 第一个维度上的切片步长为2(最后一步若小于步长,则丢弃),切片范围为0-6

array([[ 0.69574073,  0.76184   ,  0.08602741],
       [-2.21548585, -0.52132297, -0.42200697]])

In [159]:
arr_mul[0:2, -1:0:-1, 2]  # 支持切片步长为负数

array([[-1.28920487,  1.3390817 ,  0.08602741,  0.89012718,  0.76184   ,
         0.22059555],
       [-0.41830038,  0.43138345, -0.42200697, -0.92723935, -0.52132297,
        -0.01248295]])

In [160]:
arr_mul[:]  # 等价于arr_mul[:, :, :]

array([[[ 1.1694984 , -0.39725987,  0.69574073,  0.66706362],
        [-0.06039714, -0.28796528,  0.22059555, -0.35207997],
        [ 0.44726367, -0.74839976,  0.76184   , -1.07978613],
        [-1.23053622, -1.03758163,  0.89012718,  0.68410364],
        [ 0.3425219 , -0.38457719,  0.08602741, -0.47944826],
        [-0.61831976, -0.20837851,  1.3390817 ,  0.38308595],
        [ 0.02566264, -0.73035591, -1.28920487, -1.11307547]],

       [[-0.69641684, -1.69208571, -2.21548585, -0.91708073],
        [-1.06475516,  0.04012136, -0.01248295, -0.22289695],
        [-0.0626557 ,  0.17695787, -0.52132297, -0.04094236],
        [-0.7795427 ,  0.23831546, -0.92723935, -0.73927504],
        [-0.60430073,  0.88369235, -0.42200697, -0.45921842],
        [ 0.42326169, -0.88598169,  0.43138345, -1.18539687],
        [ 0.76371917,  1.02191413, -0.41830038, -0.62873746]],

       [[ 1.05330273, -0.66412836,  0.45664097,  0.43063419],
        [-0.42063499,  0.4921963 ,  0.7191431 , -1.40031218],
    

In [161]:
arr_mul[::2]  # 第一个维度上切片步长为2,范围为整个维度;等价于arr_mul[::2, :, :]

array([[[ 1.1694984 , -0.39725987,  0.69574073,  0.66706362],
        [-0.06039714, -0.28796528,  0.22059555, -0.35207997],
        [ 0.44726367, -0.74839976,  0.76184   , -1.07978613],
        [-1.23053622, -1.03758163,  0.89012718,  0.68410364],
        [ 0.3425219 , -0.38457719,  0.08602741, -0.47944826],
        [-0.61831976, -0.20837851,  1.3390817 ,  0.38308595],
        [ 0.02566264, -0.73035591, -1.28920487, -1.11307547]],

       [[ 1.05330273, -0.66412836,  0.45664097,  0.43063419],
        [-0.42063499,  0.4921963 ,  0.7191431 , -1.40031218],
        [ 0.84070835, -2.17309616, -1.20889728, -0.6198817 ],
        [ 0.95414141, -0.49709024, -0.51589204, -0.69124468],
        [ 0.06055694, -0.81230294,  2.71234357, -1.01829478],
        [ 1.46083991, -0.27600412,  0.2828512 ,  0.66344277],
        [ 1.57871733,  0.00358937,  1.05657305,  0.10508066]],

       [[ 0.06928797,  0.25523819,  1.46194264, -0.96907429],
        [-1.34861519, -1.84468458,  0.72775426, -0.45465267],
    

In [162]:
arr_mul[::-1]  # 第一个维度数据倒序

array([[[ 0.06928797,  0.25523819,  1.46194264, -0.96907429],
        [-1.34861519, -1.84468458,  0.72775426, -0.45465267],
        [ 0.14034052,  1.88605489, -0.12922522, -0.017537  ],
        [-0.69196412,  1.04537738, -0.45611915, -0.78222359],
        [-0.693413  ,  0.59030023,  0.55365132, -0.32239011],
        [-0.41710814,  1.3202363 , -0.69708373,  0.88032656],
        [-1.33136403,  0.43598118,  1.91974242,  0.41222935]],

       [[-1.49188672,  0.03456078,  1.43805243,  0.35876658],
        [-0.22021407,  0.88946274,  0.11668672, -0.19956817],
        [-0.81404586,  0.02617357, -1.74708217, -1.14831061],
        [ 0.66322228, -1.37912151,  0.79409062,  0.66952978],
        [-0.57638823, -1.10867456, -0.54005172, -2.44177759],
        [-0.89267227,  1.39077509,  0.49244173,  1.47938363],
        [ 1.11344373,  0.05519351, -0.3863817 ,  0.4500072 ]],

       [[ 1.05330273, -0.66412836,  0.45664097,  0.43063419],
        [-0.42063499,  0.4921963 ,  0.7191431 , -1.40031218],
    

In [163]:
arr_complex = np.random.randn(12, 7, 8, 10, 9, 15, 14)
arr_complex.shape

(12, 7, 8, 10, 9, 15, 14)

In [164]:
print(arr_complex[1:5].shape)
print(arr_complex[1:5, :, :, :, :, :].shape)
print(arr_complex[1:5, ...].shape)  # ...:剩余维度上所有数据

(4, 7, 8, 10, 9, 15, 14)
(4, 7, 8, 10, 9, 15, 14)
(4, 7, 8, 10, 9, 15, 14)


In [165]:
print(arr_complex[:, :, :, :, :, :, 2:4].shape)
print(arr_complex[..., 2:4].shape)

(12, 7, 8, 10, 9, 15, 2)
(12, 7, 8, 10, 9, 15, 2)


In [166]:
print(arr_complex[2:7, :, :, :, :, :, 4].shape)
print(arr_complex[2:7, ..., 4].shape)


(5, 7, 8, 10, 9, 15)
(5, 7, 8, 10, 9, 15)
