In [30]:
import  numpy as np

arr_mul = np.random.randn(5, 7, 4)
arr_mul

array([[[-0.79787121, -1.22550046,  1.32132378, -0.06994837],
        [ 1.23715659, -1.29930305, -1.02240395,  0.77835968],
        [ 0.10237313, -0.00953213,  0.56100918, -0.26465962],
        [ 0.4451162 , -0.83791557, -0.30005182, -0.44863193],
        [-0.77488657,  0.96933936, -0.66894292,  1.50706651],
        [-0.08954371,  0.65777487,  1.38247974, -0.05551375],
        [-0.46659691,  0.11357909, -0.35726285,  0.68499498]],

       [[-0.33985143,  0.77683387, -0.0096903 , -1.21962556],
        [-0.38163813,  0.01426507, -0.90866111, -0.14158552],
        [-2.14127764, -0.88177151, -0.7590023 ,  0.1010933 ],
        [-0.15761354,  0.21028025, -1.20753647, -0.7934225 ],
        [-0.63705889, -1.09199574, -1.5096076 ,  1.4479186 ],
        [ 1.07620925, -0.52368338,  0.66218968,  2.0336286 ],
        [ 0.92763741, -0.76108308,  0.45799072, -0.40470153]],

       [[-1.04243654, -0.35846992,  0.17626558, -0.3736113 ],
        [ 0.09941122, -1.22436771, -0.89157805, -1.21127537],
    

In [31]:
arr_mul[0, 1, 1]  # 索引标量数值

-1.2993030504185377

In [32]:
arr_mul[0]  # 从第零个维度开始索引/切片(DataFrame从列开始进行索引切片)

array([[-0.79787121, -1.22550046,  1.32132378, -0.06994837],
       [ 1.23715659, -1.29930305, -1.02240395,  0.77835968],
       [ 0.10237313, -0.00953213,  0.56100918, -0.26465962],
       [ 0.4451162 , -0.83791557, -0.30005182, -0.44863193],
       [-0.77488657,  0.96933936, -0.66894292,  1.50706651],
       [-0.08954371,  0.65777487,  1.38247974, -0.05551375],
       [-0.46659691,  0.11357909, -0.35726285,  0.68499498]])

In [33]:
arr_mul[0, 0, -1]  # 索引,若为标量则返回具体数值(且支持负数索引)

-0.06994836948302083

In [34]:
arr_mul[0:2]  # 切片,返回array

array([[[-0.79787121, -1.22550046,  1.32132378, -0.06994837],
        [ 1.23715659, -1.29930305, -1.02240395,  0.77835968],
        [ 0.10237313, -0.00953213,  0.56100918, -0.26465962],
        [ 0.4451162 , -0.83791557, -0.30005182, -0.44863193],
        [-0.77488657,  0.96933936, -0.66894292,  1.50706651],
        [-0.08954371,  0.65777487,  1.38247974, -0.05551375],
        [-0.46659691,  0.11357909, -0.35726285,  0.68499498]],

       [[-0.33985143,  0.77683387, -0.0096903 , -1.21962556],
        [-0.38163813,  0.01426507, -0.90866111, -0.14158552],
        [-2.14127764, -0.88177151, -0.7590023 ,  0.1010933 ],
        [-0.15761354,  0.21028025, -1.20753647, -0.7934225 ],
        [-0.63705889, -1.09199574, -1.5096076 ,  1.4479186 ],
        [ 1.07620925, -0.52368338,  0.66218968,  2.0336286 ],
        [ 0.92763741, -0.76108308,  0.45799072, -0.40470153]]])

In [35]:
arr_mul[0:2, 0:3, 0]  # 在多个维度上索引/切片

array([[-0.79787121,  1.23715659,  0.10237313],
       [-0.33985143, -0.38163813, -2.14127764]])

In [36]:
arr_mul[0:2, 0:6:2, 2]  # 第一个维度上的切片步长为2(最后一步若小于步长,则丢弃),切片范围为0-6

array([[ 1.32132378,  0.56100918, -0.66894292],
       [-0.0096903 , -0.7590023 , -1.5096076 ]])

In [37]:
arr_mul[0:2, -1:0:-1, 2]  # 支持切片步长为负数

array([[-0.35726285,  1.38247974, -0.66894292, -0.30005182,  0.56100918,
        -1.02240395],
       [ 0.45799072,  0.66218968, -1.5096076 , -1.20753647, -0.7590023 ,
        -0.90866111]])

In [38]:
arr_mul[:]  # 等价于arr_mul[:, :, :]

array([[[-0.79787121, -1.22550046,  1.32132378, -0.06994837],
        [ 1.23715659, -1.29930305, -1.02240395,  0.77835968],
        [ 0.10237313, -0.00953213,  0.56100918, -0.26465962],
        [ 0.4451162 , -0.83791557, -0.30005182, -0.44863193],
        [-0.77488657,  0.96933936, -0.66894292,  1.50706651],
        [-0.08954371,  0.65777487,  1.38247974, -0.05551375],
        [-0.46659691,  0.11357909, -0.35726285,  0.68499498]],

       [[-0.33985143,  0.77683387, -0.0096903 , -1.21962556],
        [-0.38163813,  0.01426507, -0.90866111, -0.14158552],
        [-2.14127764, -0.88177151, -0.7590023 ,  0.1010933 ],
        [-0.15761354,  0.21028025, -1.20753647, -0.7934225 ],
        [-0.63705889, -1.09199574, -1.5096076 ,  1.4479186 ],
        [ 1.07620925, -0.52368338,  0.66218968,  2.0336286 ],
        [ 0.92763741, -0.76108308,  0.45799072, -0.40470153]],

       [[-1.04243654, -0.35846992,  0.17626558, -0.3736113 ],
        [ 0.09941122, -1.22436771, -0.89157805, -1.21127537],
    

In [39]:
arr_mul[::2]  # 第一个维度上切片步长为2,范围为整个维度;等价于arr_mul[::2, :, :]

array([[[-0.79787121, -1.22550046,  1.32132378, -0.06994837],
        [ 1.23715659, -1.29930305, -1.02240395,  0.77835968],
        [ 0.10237313, -0.00953213,  0.56100918, -0.26465962],
        [ 0.4451162 , -0.83791557, -0.30005182, -0.44863193],
        [-0.77488657,  0.96933936, -0.66894292,  1.50706651],
        [-0.08954371,  0.65777487,  1.38247974, -0.05551375],
        [-0.46659691,  0.11357909, -0.35726285,  0.68499498]],

       [[-1.04243654, -0.35846992,  0.17626558, -0.3736113 ],
        [ 0.09941122, -1.22436771, -0.89157805, -1.21127537],
        [-0.80940328, -1.00884555, -0.54781836, -0.91999997],
        [ 0.63887338,  0.76462921, -0.8431167 , -0.15799468],
        [ 0.31926508, -1.57119265,  1.33808725, -0.40464091],
        [-0.19927796, -0.00369045, -0.74042169, -0.28425354],
        [ 0.1880086 , -0.15256546, -0.43028768,  0.2995431 ]],

       [[-0.79932373,  1.13146061, -0.6519711 ,  0.86642564],
        [-0.27059619, -0.7736777 ,  0.00726883,  0.541866  ],
    

In [40]:
arr_mul[::-1]  # 第一个维度数据倒序

array([[[-0.79932373,  1.13146061, -0.6519711 ,  0.86642564],
        [-0.27059619, -0.7736777 ,  0.00726883,  0.541866  ],
        [-1.20198218, -1.37054191, -0.78399187, -1.53053725],
        [ 0.78535766, -0.17600868, -1.28534338, -1.52446094],
        [-0.61459051, -2.00109654,  0.81079402,  0.75462706],
        [ 1.25412948,  1.28321339,  1.02003891,  1.34659099],
        [-1.16291342,  0.54809801,  0.41092312,  0.40514547]],

       [[ 0.010559  , -0.28418815,  0.6351871 , -0.15980465],
        [-1.48878503,  0.56962186,  1.51356976, -0.91947793],
        [ 1.417015  ,  0.43347008,  0.89819579, -0.39432443],
        [-1.50713084,  1.89962028, -0.89115002, -0.86590446],
        [-0.75427845,  0.03631964, -2.00992843,  0.58585339],
        [ 0.27692437,  0.98294233, -0.90606528, -0.95473817],
        [-0.14566278,  0.12151433,  0.5915058 , -0.75589934]],

       [[-1.04243654, -0.35846992,  0.17626558, -0.3736113 ],
        [ 0.09941122, -1.22436771, -0.89157805, -1.21127537],
    

In [41]:
arr_complex = np.random.randn(12, 7, 8, 10, 9, 15, 14)
arr_complex.shape

(12, 7, 8, 10, 9, 15, 14)

In [42]:
print(arr_complex[1:5].shape)
print(arr_complex[1:5, :, :, :, :, :].shape)
print(arr_complex[1:5, ...].shape)  # ...:剩余维度上所有数据

(4, 7, 8, 10, 9, 15, 14)
(4, 7, 8, 10, 9, 15, 14)
(4, 7, 8, 10, 9, 15, 14)


In [43]:
print(arr_complex[:, :, :, :, :, :, 2:4].shape)
print(arr_complex[..., 2:4].shape)

(12, 7, 8, 10, 9, 15, 2)
(12, 7, 8, 10, 9, 15, 2)


In [44]:
print(arr_complex[2:7, :, :, :, :, :, 4].shape)
print(arr_complex[2:7, ..., 4].shape)


(5, 7, 8, 10, 9, 15)
(5, 7, 8, 10, 9, 15)
