In [13]:
import numpy as np

names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
print(names)
print(data)

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[-1.86678605 -1.11697981  1.67629489 -1.55692094]
 [-0.18951361  1.99778106 -0.61715899  0.51179054]
 [-1.05670269 -1.77681923 -0.6166837   1.30061051]
 [-0.49493319  0.29427605 -0.45616456  0.4324433 ]
 [ 0.24933667  0.66035225  0.48348888  0.24387146]
 [-1.36662527  0.59120309  0.56429657 -0.76420351]
 [-0.15531136  1.93064765 -0.59574102  0.70030189]]


In [14]:
check = names == 'Bob'
check

array([ True, False, False,  True, False, False, False])

In [15]:
data[check]  # 第零个维度上的布尔索引

array([[-1.86678605, -1.11697981,  1.67629489, -1.55692094],
       [-0.49493319,  0.29427605, -0.45616456,  0.4324433 ]])

In [16]:
data[:, check[:4]]  # 第一个维度上的布尔切片

array([[-1.86678605, -1.55692094],
       [-0.18951361,  0.51179054],
       [-1.05670269,  1.30061051],
       [-0.49493319,  0.4324433 ],
       [ 0.24933667,  0.24387146],
       [-1.36662527, -0.76420351],
       [-0.15531136,  0.70030189]])

In [17]:
print(data[names == 'Bob', 2:])
print(data[names == 'Bob', 2:])

[[ 1.67629489 -1.55692094]
 [-0.45616456  0.4324433 ]]
[[ 1.67629489 -1.55692094]
 [-0.45616456  0.4324433 ]]


In [18]:
print(names != 'Bob')
print(~(names != 'Bob')) # ~:取反
print(data[~(names != 'Bob')])

[False  True  True False  True  True  True]
[ True False False  True False False False]
[[-1.86678605 -1.11697981  1.67629489 -1.55692094]
 [-0.49493319  0.29427605 -0.45616456  0.4324433 ]]


In [19]:
mask = (names == 'Bob') | (names == 'Will')  # |:并集,不能使用关键字or
print(mask)
print(data[mask])

[ True False  True  True  True False False]
[[-1.86678605 -1.11697981  1.67629489 -1.55692094]
 [-1.05670269 -1.77681923 -0.6166837   1.30061051]
 [-0.49493319  0.29427605 -0.45616456  0.4324433 ]
 [ 0.24933667  0.66035225  0.48348888  0.24387146]]


In [20]:
mask1 = (names == 'Bob') & (names == 'Will')  # &:交集,不能使用关键字and
print(mask1)
print(data[mask1])

[False False False False False False False]
[]


In [21]:
s = data < 0
s

array([[ True,  True, False,  True],
       [ True, False,  True, False],
       [ True,  True,  True, False],
       [ True, False,  True, False],
       [False, False, False, False],
       [ True, False, False,  True],
       [ True, False,  True, False]])

In [22]:
# 所有s中不为False处的元素
print(data[s].shape)
print(data[s])

(14,)
[-1.86678605 -1.11697981 -1.55692094 -0.18951361 -0.61715899 -1.05670269
 -1.77681923 -0.6166837  -0.49493319 -0.45616456 -1.36662527 -0.76420351
 -0.15531136 -0.59574102]


In [23]:
data[s] = 0  # 逐个元素的布尔索引
data  # data发生改变

array([[0.        , 0.        , 1.67629489, 0.        ],
       [0.        , 1.99778106, 0.        , 0.51179054],
       [0.        , 0.        , 0.        , 1.30061051],
       [0.        , 0.29427605, 0.        , 0.4324433 ],
       [0.24933667, 0.66035225, 0.48348888, 0.24387146],
       [0.        , 0.59120309, 0.56429657, 0.        ],
       [0.        , 1.93064765, 0.        , 0.70030189]])

In [24]:
data[names != 'Joe'] = 7  # ★★★★★和整数索引类似,只能通过对原array[索引/切片]直接进行赋值从而修改原array
data  # data发生改变

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 1.99778106, 0.        , 0.51179054],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.59120309, 0.56429657, 0.        ],
       [0.        , 1.93064765, 0.        , 0.70030189]])