In [1]:
import numpy as np

names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
print(names)
print(data)

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[ 0.17363904  0.31409139  1.22052156  0.21641319]
 [ 0.70928361 -1.57655306 -1.43326677 -0.36811284]
 [ 0.21056841 -1.91964745  0.36658501 -0.14972258]
 [ 0.97875408  0.58835288 -1.11597737  1.23040249]
 [-0.32469319 -0.83897624  0.48405066  0.12275351]
 [-0.65046578 -1.32606417 -0.58335779  1.32907929]
 [-0.50219632  1.59245389 -0.08571201  0.08692958]]


In [2]:
check = names == 'Bob'
check

array([ True, False, False,  True, False, False, False])

In [3]:
data[check] # 第零个维度上的布尔索引

array([[ 0.17363904,  0.31409139,  1.22052156,  0.21641319],
       [ 0.97875408,  0.58835288, -1.11597737,  1.23040249]])

In [4]:
data[:, check[:4]] # 第一个维度上的布尔切片

array([[ 0.17363904,  0.21641319],
       [ 0.70928361, -0.36811284],
       [ 0.21056841, -0.14972258],
       [ 0.97875408,  1.23040249],
       [-0.32469319,  0.12275351],
       [-0.65046578,  1.32907929],
       [-0.50219632,  0.08692958]])

In [5]:
print(data[names == 'Bob', 2:])
print(data[names == 'Bob', 2:])

[[ 1.22052156  0.21641319]
 [-1.11597737  1.23040249]]
[[ 1.22052156  0.21641319]
 [-1.11597737  1.23040249]]


In [6]:
print(names != 'Bob')
print(~(names != 'Bob')) # ~:取反
print(data[~(names != 'Bob')])

[False  True  True False  True  True  True]
[ True False False  True False False False]
[[ 0.17363904  0.31409139  1.22052156  0.21641319]
 [ 0.97875408  0.58835288 -1.11597737  1.23040249]]


In [7]:
mask = (names == 'Bob') | (names == 'Will') # |:并集,不能使用关键字or
print(mask)
print(data[mask])

[ True False  True  True  True False False]
[[ 0.17363904  0.31409139  1.22052156  0.21641319]
 [ 0.21056841 -1.91964745  0.36658501 -0.14972258]
 [ 0.97875408  0.58835288 -1.11597737  1.23040249]
 [-0.32469319 -0.83897624  0.48405066  0.12275351]]


In [8]:
mask1 = (names == 'Bob') & (names == 'Will') # &:交集,不能使用关键字and
print(mask1)
print(data[mask1])

[False False False False False False False]
[]


In [9]:
s = data < 0
s

array([[False, False, False, False],
       [False,  True,  True,  True],
       [False,  True, False,  True],
       [False, False,  True, False],
       [ True,  True, False, False],
       [ True,  True,  True, False],
       [ True, False,  True, False]])

In [10]:
data[s]

array([-1.57655306, -1.43326677, -0.36811284, -1.91964745, -0.14972258,
       -1.11597737, -0.32469319, -0.83897624, -0.65046578, -1.32606417,
       -0.58335779, -0.50219632, -0.08571201])

In [11]:
data[s] = 0  # 逐个元素的布尔索引
data # data发生改变

array([[0.17363904, 0.31409139, 1.22052156, 0.21641319],
       [0.70928361, 0.        , 0.        , 0.        ],
       [0.21056841, 0.        , 0.36658501, 0.        ],
       [0.97875408, 0.58835288, 0.        , 1.23040249],
       [0.        , 0.        , 0.48405066, 0.12275351],
       [0.        , 0.        , 0.        , 1.32907929],
       [0.        , 1.59245389, 0.        , 0.08692958]])

In [12]:
data[names != 'Joe'] = 7 # ★★★★★和整数索引类似,只能通过对原array[索引/切片]直接进行赋值从而修改原array
data # data发生改变

array([[7.        , 7.        , 7.        , 7.        ],
       [0.70928361, 0.        , 0.        , 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 0.        , 1.32907929],
       [0.        , 1.59245389, 0.        , 0.08692958]])