In [71]:
import numpy as np

In [72]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [73]:
# 选取索引为(1, 0),(5, 3),(7, 1),(2, 2)处的元素值组成[x, x, x, x]
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [74]:
# 选取索引为(0, 0),(5, 1),(3, 3),(2, 2),(5, 3),(1, 1)处的元素值组成[[x, x, x], [x, x, x]]
arr[[[0, 5, 3],
     [2, 5, 1]],
    [[0, 1, 3],
     [2, 3, 1]]]

array([[ 0, 21, 15],
       [10, 23,  5]])

In [75]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]] = 11111  # 与整数索引同理
arr  # arr改变

array([[    0,     1,     2,     3],
       [11111,     5,     6,     7],
       [    8,     9, 11111,    11],
       [   12,    13,    14,    15],
       [   16,    17,    18,    19],
       [   20,    21,    22, 11111],
       [   24,    25,    26,    27],
       [   28, 11111,    30,    31]])

In [76]:
arr1 = np.arange(120).reshape(5, 4, 6)
arr1

array([[[  0,   1,   2,   3,   4,   5],
        [  6,   7,   8,   9,  10,  11],
        [ 12,  13,  14,  15,  16,  17],
        [ 18,  19,  20,  21,  22,  23]],

       [[ 24,  25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34,  35],
        [ 36,  37,  38,  39,  40,  41],
        [ 42,  43,  44,  45,  46,  47]],

       [[ 48,  49,  50,  51,  52,  53],
        [ 54,  55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64,  65],
        [ 66,  67,  68,  69,  70,  71]],

       [[ 72,  73,  74,  75,  76,  77],
        [ 78,  79,  80,  81,  82,  83],
        [ 84,  85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94,  95]],

       [[ 96,  97,  98,  99, 100, 101],
        [102, 103, 104, 105, 106, 107],
        [108, 109, 110, 111, 112, 113],
        [114, 115, 116, 117, 118, 119]]])

In [77]:
# 选取索引为(1, 0, 0),(0, 3, 1),(3, 1, 1),(2, 2, 1)处的元素值组成[x, x, x, x]
arr1[[1, 0, 3, 2], [0, 3, 1, 2], [0, 1, 1, 1]]

array([24, 19, 79, 61])

In [78]:
# x_v表示向量(即[x, ...., x])
# 同理x_m表示矩阵(即[[x, ..., x], [x, ..., x])
# 选取索引为(1, 0, :),(0, 3, :),(3, 1, :),(2, 2, :)处的元素值组成[x_v, x_v, x_v, x_v]
arr1[[1, 0, 3, 2], [0, 3, 1, 2], :]

array([[24, 25, 26, 27, 28, 29],
       [18, 19, 20, 21, 22, 23],
       [78, 79, 80, 81, 82, 83],
       [60, 61, 62, 63, 64, 65]])

In [79]:
# 选取索引为(0, 0, :),(1, 1, :),(3, 3, :),(2, 2, :),(0, 3, :),(1, 1, 1:)处的元素值
# 组成[[x_v, x_v, x_v],
#     [x_v, x_v, x_v]]
arr1[[[0, 1, 3],
      [2, 0, 1]],
     [[0, 1, 3],
      [2, 3, 1]]]

array([[[ 0,  1,  2,  3,  4,  5],
        [30, 31, 32, 33, 34, 35],
        [90, 91, 92, 93, 94, 95]],

       [[60, 61, 62, 63, 64, 65],
        [18, 19, 20, 21, 22, 23],
        [30, 31, 32, 33, 34, 35]]])