In [1]:
import torch

In [2]:
a = torch.randn(2, 3, 4)
torch.var(a)

tensor(0.8478)

In [4]:
torch.var(a, dim=(1, 2)) # 注意:var函数dim参数也可以为元组;第0个维度上所有数据的方差(无偏)

tensor([0.9957, 0.6349])

In [6]:
torch.var(a, dim=(0, 1))

tensor([0.7651, 1.0406, 1.0488, 0.8242])

In [7]:
torch.var(a, dim=(0, 1), unbiased=False) # whether to use the unbiased estimation or not(默认unbiases=True)

tensor([0.6376, 0.8672, 0.8740, 0.6868])

In [8]:
torch.var(a, dim=(0, 1), keepdim=True).shape # 保留维度信息(进行广播时使用)



torch.Size([1, 1, 4])