In [109]:
import numpy as np

In [110]:
np.all([[True, False], [True, True]])  # 所有元素为True时才返回True

False

In [111]:
np.all([[True, False],
        [True, True]], axis=0)  # 指定轴axis

array([ True, False])

In [112]:
np.any([[True, False],
        [True, True]])  # 所有元素为False才返回False

True

In [113]:
np.any([[True, False],
        [True, True]], axis=0)

array([ True,  True])

In [114]:
arr = np.array([[True, -2.3],
                [0, 0]])
np.any(arr, axis=1)  # 除Ture/False还可以为数值型(0为False,其他为True)

array([ True, False])

In [115]:
np.logical_not(3)  # 转换x的真假

False

In [116]:
np.logical_not(False)

True

In [117]:
np.logical_not([True, False, 0, 1])

array([False,  True,  True, False])

In [118]:
np.logical_and(True, False)  # Compute the truth value of x1 AND x2 element-wise

False

In [119]:
np.all([[33, False, True],
        [True, 0, True]], axis=0)

array([ True, False,  True])

In [120]:
np.logical_and([33, False, True],
               [True, 0, True])  # 与上等价

array([ True, False,  True])

In [121]:
np.any([[True, False],
        [0, False]], axis=0)

array([ True, False])

In [122]:
# 与上等价
np.logical_or([True, False],
              [0, False])  # Compute the truth value of x1 OR x2 element-wise.

array([ True, False])