In [27]:
import numpy as np

In [28]:
np.append(arr=[1, 2, 3],
          values=[[4, 5, 6],
                  [7, 8, 9]],
          # The axis along which values are appended.
          # If axis is not given, both arr and values are flattened before use.
          axis=None)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np.concatenate(([[1, 2, 3],
                 [4, 5, 6]], [[7, 8, 9]]), axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
np.append(arr=[[1, 2, 3],
               [4, 5, 6]],
          values=[[7, 8, 9]],
          axis=0)  # 与上等价

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
np.append(arr=[[1, 2, 3],
               [4, 5, 6]],
          values=[[7, 8],
                  [9, 10]],
          axis=1)

array([[ 1,  2,  3,  7,  8],
       [ 4,  5,  6,  9, 10]])