In [11]:
import numpy as np

In [12]:
arr1 = np.arange(40).reshape((4, 10))
arr1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [13]:
a, b, c, d = np.array_split(arr1, [1, 3, 7], axis=1)
print(a)  # 即arr1[:, 0:1]
print(b)  # 即arr1[:, 1:3]
print(c)  # 即arr1[:, 3:7]
print(d)  # 即arr1[:, 7:]

[[ 0]
 [10]
 [20]
 [30]]
[[ 1  2]
 [11 12]
 [21 22]
 [31 32]]
[[ 3  4  5  6]
 [13 14 15 16]
 [23 24 25 26]
 [33 34 35 36]]
[[ 7  8  9]
 [17 18 19]
 [27 28 29]
 [37 38 39]]


In [14]:
m, n, z = np.array_split(arr1, [2, 3], axis=0)
print(m)  # 即arr1[0:2, :]
print(n)  # 即arr1[2:3, :]
print(z)  # 即arr1[3:, :]

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
[[20 21 22 23 24 25 26 27 28 29]]
[[30 31 32 33 34 35 36 37 38 39]]


In [15]:
np.array_split(arr1, 5, axis=1)  # 拆分成大小均等的快

[array([[ 0,  1],
        [10, 11],
        [20, 21],
        [30, 31]]),
 array([[ 2,  3],
        [12, 13],
        [22, 23],
        [32, 33]]),
 array([[ 4,  5],
        [14, 15],
        [24, 25],
        [34, 35]]),
 array([[ 6,  7],
        [16, 17],
        [26, 27],
        [36, 37]]),
 array([[ 8,  9],
        [18, 19],
        [28, 29],
        [38, 39]])]

In [18]:
'''
The only difference between these functions is that array_split allows indices_or_sections to be an integer that does not equally divide the axis.
For an array of length l that should be split into n sections, it returns l % n sub-arrays of size l//n + 1 and the rest of size l//n.
'''
# 拆分后的子数组大小为:[4, 2], [4, 2], [4, 2], [4, 2], [4, 1], [4, 1]
np.array_split(arr1, 6, axis=1)  # 也可以拆分成大小不均等的快

[array([[ 0,  1],
        [10, 11],
        [20, 21],
        [30, 31]]),
 array([[ 2,  3],
        [12, 13],
        [22, 23],
        [32, 33]]),
 array([[ 4,  5],
        [14, 15],
        [24, 25],
        [34, 35]]),
 array([[ 6,  7],
        [16, 17],
        [26, 27],
        [36, 37]]),
 array([[ 8],
        [18],
        [28],
        [38]]),
 array([[ 9],
        [19],
        [29],
        [39]])]