In [147]:
import numpy as np

a = np.array([1, 2, 3])  # shape=(3,).列向量
b = np.array([4, 5, 6])

np.c_[a]  # (3, ) --> (3, 1)

array([[1],
       [2],
       [3]])

In [148]:
np.c_[a, b]  # (3, ) (3, ) --> (3, 2)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [149]:
np.c_[a.reshape(-1, 1), b.reshape(-1, 1)]  # (3, 1) (3, 1) --> (3, 2)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [150]:
np.c_[a.reshape(1, -1), b.reshape(1, -1)]  # (1, 3) (1, 3) --> (1, 6)

array([[1, 2, 3, 4, 5, 6]])

In [151]:
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[0, 0, 0], [1, 1, 1]])
np.c_[c, d]  # (2, 3) (2, 3) --> (2, 6)

array([[1, 2, 3, 0, 0, 0],
       [4, 5, 6, 1, 1, 1]])

In [152]:
np.c_[c, np.array([9, 9])]  # (2, 3) (2, ) --> (2, 4)

array([[1, 2, 3, 9],
       [4, 5, 6, 9]])

In [153]:
np.c_[c, np.array([9, 9]).reshape(-1, 1)]  # (2, 3) (2, 1) --> (2, 4)

array([[1, 2, 3, 9],
       [4, 5, 6, 9]])

In [154]:
np.c_[-1:1:6j]

array([[-1. ],
       [-0.6],
       [-0.2],
       [ 0.2],
       [ 0.6],
       [ 1. ]])

In [155]:
np.c_[np.linspace(-1, 1, 6)]  # 与上等价

array([[-1. ],
       [-0.6],
       [-0.2],
       [ 0.2],
       [ 0.6],
       [ 1. ]])