In [105]:
import numpy as np

In [106]:
a = np.array([[1, 1],
              [2, 2],
              [3, 3]])
a

array([[1, 1],
       [2, 2],
       [3, 3]])

In [107]:
'''
arr: array_like
    Input array.

obj: int, slice or sequence of ints
    Object that defines the index or indices before which values is inserted.
values: array_like
    Values to insert into arr.
    If the type of values is different from that of arr, values is converted to the type of arr.
    values should be shaped so that arr[...,obj,...] = values is legal.

axis: int, optional
    Axis along which to insert values.
    If axis is None then arr is flattened first.
'''
np.insert(arr=a, obj=[1], values=5, axis=None)

array([1, 5, 1, 2, 2, 3, 3])

In [108]:
np.insert(arr=a, obj=[1], values=5, axis=1)

array([[1, 5, 1],
       [2, 5, 2],
       [3, 5, 3]])

In [109]:
np.insert(arr=a, obj=[1], values=[[-1],
                                  [-2],
                                  [-3]], axis=1)

array([[ 1, -1,  1],
       [ 2, -2,  2],
       [ 3, -3,  3]])

In [110]:
x = np.arange(8).reshape(2, 4)
x

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [111]:
np.insert(x, [1, 3], 999, axis=1)

array([[  0, 999,   1,   2, 999,   3],
       [  4, 999,   5,   6, 999,   7]])

In [112]:
np.insert(x, [1, 3], [[1, 2],
                      [-1, -2]], axis=1)

array([[ 0,  1,  1,  2,  2,  3],
       [ 4, -1,  5,  6, -2,  7]])