In [6]:
import numpy as np

In [7]:
arr1 = np.arange(40).reshape((4, 10))
arr1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [8]:
a, b, c, d = np.split(arr1, [1, 3, 7], axis=1)
print(a)  # 即arr1[:, 0:1]
print(b)  # 即arr1[:, 1:3]
print(c)  # 即arr1[:, 3:7]
print(d)  # 即arr1[:, 7:]

[[ 0]
 [10]
 [20]
 [30]]
[[ 1  2]
 [11 12]
 [21 22]
 [31 32]]
[[ 3  4  5  6]
 [13 14 15 16]
 [23 24 25 26]
 [33 34 35 36]]
[[ 7  8  9]
 [17 18 19]
 [27 28 29]
 [37 38 39]]


In [9]:
m, n, z = np.split(arr1, [2, 3], axis=0)
print(m)  # 即arr1[0:2, :]
print(n)  # 即arr1[2:3, :]
print(z)  # 即arr1[3:, :]

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
[[20 21 22 23 24 25 26 27 28 29]]
[[30 31 32 33 34 35 36 37 38 39]]


In [10]:
np.split(arr1, 4, axis=0)  # 拆分成大小均等的快

[array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]]),
 array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29]]),
 array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])]