In [40]:
import numpy as np

In [41]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([3, 4, 5])

# 在新的维度上连接数组arr1,arr2
print(np.stack((arr1, arr2), axis=1))
print(np.stack((arr1, arr2), axis=0))  # 默认axis=0

[[1 3]
 [2 4]
 [3 5]]
[[1 2 3]
 [3 4 5]]


In [42]:
x = np.ones((2, 3))
x

array([[1., 1., 1.],
       [1., 1., 1.]])

In [43]:
y = np.zeros((2, 3))
y

array([[0., 0., 0.],
       [0., 0., 0.]])

In [44]:
# 在新的维度上连接数组x,y
# x.dim=2,y.dim=2;故a.dim=3,故axis可选值有0,1,2
a = np.stack((x, y), axis=2)  # Each array must have the same shape
a

array([[[1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.]]])

In [45]:
a[0]  # 即x

array([[1., 0.],
       [1., 0.],
       [1., 0.]])

In [46]:
a[1]  # 即y

array([[1., 0.],
       [1., 0.],
       [1., 0.]])

In [47]:
b = np.stack((x, y), axis=1)
b

array([[[1., 1., 1.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [0., 0., 0.]]])

In [48]:
b[:, 0]  # 即x

array([[1., 1., 1.],
       [1., 1., 1.]])

In [49]:
b[:, 1]  # 即y

array([[0., 0., 0.],
       [0., 0., 0.]])

In [50]:
c = np.stack((x, y), axis=2)
c

array([[[1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.]]])

In [51]:
c[..., 0]  # 即x

array([[1., 1., 1.],
       [1., 1., 1.]])

In [52]:
c[..., 1]  # 即y

array([[0., 0., 0.],
       [0., 0., 0.]])