In [100]:
import tensorflow as tf

### 参考torch.nn.functional.onehot

In [101]:
indices = [0, 1, 2]
depth = 5
# depth:   	A scalar defining the depth of the one hot dimension.
tf.one_hot(indices,
           depth=depth)  # 类别数量;超过最大类别部分全为0

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]], dtype=float32)>

In [102]:
'''
on_value:	A scalar defining the value to fill in output when indices[j] = i. (default: 1)
off_value:	A scalar defining the value to fill in output when indices[j] != i. (default: 0)
'''
indices = [0, 2, -1, 1]
depth = 4
tf.one_hot(indices, depth,
           on_value=5.0, off_value=-5.0)


<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[ 5., -5., -5., -5.],
       [-5., -5.,  5., -5.],
       [-5., -5., -5., -5.],
       [-5.,  5., -5., -5.]], dtype=float32)>