In [11]:
import numpy as np

In [12]:
arr = np.arange(25).reshape(5, 5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [13]:
no_eys = (1 - np.eye(5)).astype(np.bool)
no_eys

array([[False,  True,  True,  True,  True],
       [ True, False,  True,  True,  True],
       [ True,  True, False,  True,  True],
       [ True,  True,  True, False,  True],
       [ True,  True,  True,  True, False]])

In [14]:
arr[no_eys]

array([ 1,  2,  3,  4,  5,  7,  8,  9, 10, 11, 13, 14, 15, 16, 17, 19, 20,
       21, 22, 23])

In [15]:
# 此时不包含对角线元素(torch/tensorflow同理)
arr[no_eys].reshape(5, 4)

array([[ 1,  2,  3,  4],
       [ 5,  7,  8,  9],
       [10, 11, 13, 14],
       [15, 16, 17, 19],
       [20, 21, 22, 23]])