In [7]:
import numpy as np

In [8]:
np.around([0.37, 1.64])

array([0., 2.])

In [9]:
'''
decimals : int, optional
    Number of decimal places to round to (default: 0). If decimals is negative, it specifies
    the number of positions to the left of the decimal point.
'''
np.around([0.35424, 341.6423], decimals=2)

array([  0.35, 341.64])

In [10]:
np.around([14, 234, 33423, 13241], decimals=-1)

array([   10,   230, 33420, 13240])

In [11]:
import pandas as pd

arr = pd.Series([0.33437, 1.6344])
arr.apply(np.around, decimals=4)

0    0.3344
1    1.6344
dtype: float64

In [15]:
result = np.around(0.234123, decimals=2)
print(result, type(result), float(result))

0.23 <class 'numpy.float64'> 0.23
