python使用j来表示复数的虚部

In [2]:
import  numpy as np
# Return the angle of the complex argument.
print(np.angle([1.0, 1.0j, 1+1j]))
print(np.angle([1.0, 1.0j, 1+1j], deg=True))
'''
deg : bool, optional
    Return angle in degrees if True, radians if False (default).
'''

[0.         1.57079633 0.78539816]
[ 0. 90. 45.]


'\ndeg : bool, optional\n    Return angle in degrees if True, radians if False (default).\n\n'

In [3]:
a = np.array([1+2j, 3+4j, 5+6j])
print(a.real) # The real part of the array
a.real = 10
print(a)
a.real = np.array([9, 8, 7])
print(a)

[1. 3. 5.]
[10.+2.j 10.+4.j 10.+6.j]
[9.+2.j 8.+4.j 7.+6.j]


In [4]:
b = np.array([1+2j, 3+4j, 5+6j])
print(b.imag) # The imaginary part of the array
b.imag = 10
print(b)
b.imag = np.array([9, 8, 7])
print(b)

[2. 4. 6.]
[1.+10.j 3.+10.j 5.+10.j]
[1.+9.j 3.+8.j 5.+7.j]


In [5]:
# Return the complex conjugate, element-wise.
x = np.eye(2) + 1j * np.eye(2)
print(x)
print(np.conj(x))


[[1.+1.j 0.+0.j]
 [0.+0.j 1.+1.j]]
[[1.-1.j 0.-0.j]
 [0.-0.j 1.-1.j]]
