In [9]:
import numpy as np

x1 = np.arange(6)
print(np.power(x1, 1))
print(np.power(x1, 2))

[0 1 2 3 4 5]
[ 0  1  4  9 16 25]


In [10]:
np.power(x1, 3) # x1 ** 3等价

array([  0,   1,   8,  27,  64, 125], dtype=int32)

In [11]:
np.power(3, x1) # 与3 ** x1等价

array([  1,   3,   9,  27,  81, 243], dtype=int32)

In [12]:
x2 = [1.0, 2.0, 3.0, 3.0, 2.0, 1.0]
np.power(x1, x2)

array([ 0.,  1.,  8., 27., 16.,  5.])

In [13]:
np.array(x1) ** np.array(x2) # 与上等价


array([ 0.,  1.,  8., 27., 16.,  5.])