In [ ]:
import numpy as np
import pandas as pd

print(np.prod([0.5, 1.5]))  # 求积
print(np.cumprod([0.5, 1.5]))  # 累积

In [2]:
print(np.prod([0.5, 0.7, 0.2, 1.5], dtype=np.float))
print(np.cumprod([0.5, 0.7, 0.2, 1.5], dtype=np.float))

0.10499999999999998
[0.5   0.35  0.07  0.105]


In [3]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(np.prod(a))
print(np.cumprod(a))

720
[  1   2   6  24 120 720]


In [4]:
print(np.prod(a, axis=0))
print(np.cumprod(a, axis=0))

[ 4 10 18]
[[ 1  2  3]
 [ 4 10 18]]


In [5]:
print(np.prod(a, axis=1))
print(np.cumprod(a, axis=1))

[  6 120]
[[  1   2   6]
 [  4  20 120]]


In [6]:
df = pd.DataFrame([[2.0, 1.0],
                   [3.0, np.nan],
                   [1.0, 0.0]],
                  columns=list('AB'))
df

A    B
0  2.0  1.0
1  3.0  NaN
2  1.0  0.0

In [7]:
df.cumprod()

A    B
0  2.0  1.0
1  6.0  NaN
2  6.0  0.0

In [ ]:
df.cumprod(axis=1)  # 默认aixs=0