In [17]:
import numpy as np

x = np.array([1, 2, 4, 7, 0])
np.diff(x)  # 计算离差

array([ 1,  2,  3, -7])

In [18]:
"""
n : int, optional
    The number of times values are differenced. If zero, the input
    is returned as-is.
axis : int, optional
    The axis along which the difference is taken, default is the
    last axis
"""
print(np.diff(np.diff(x)))
print(np.diff(x, n=2))  # 与上等价;默认n=1

[  1   1 -10]
[  1   1 -10]


In [19]:
y = np.array([[1, 3, 6, 10], [0, 5, 6, 8]])
y

array([[ 1,  3,  6, 10],
       [ 0,  5,  6,  8]])

In [20]:
np.diff(y)

array([[2, 3, 4],
       [5, 1, 2]])

In [21]:
np.diff(y, axis=0)

array([[-1,  2,  0, -2]])