In [27]:
### 转换类型真假(必须为布尔类型)
### 仅适用于numpy/pandas/torch/tensorflow

In [28]:
import numpy as np
import pandas as pd
import torch
import tensorflow as tf

In [29]:
arr0 = np.array([[True, False, False],
                 [False, False, True],
                 [True, True, False]])

print(arr0)
print(~arr0)  # 取反:True===>False;False===>True

[[ True False False]
 [False False  True]
 [ True  True False]]
[[False  True  True]
 [ True  True False]
 [False False  True]]


In [30]:
df0 = pd.DataFrame(arr0)

print(df0)
print(~df0)

       0      1      2
0   True  False  False
1  False  False   True
2   True   True  False
       0      1      2
0  False   True   True
1   True   True  False
2  False  False   True


In [31]:
tor0 = torch.tensor(arr0)

print(tor0)
print(~tor0)

tensor([[ True, False, False],
        [False, False,  True],
        [ True,  True, False]])
tensor([[False,  True,  True],
        [ True,  True, False],
        [False, False,  True]])


In [32]:
cons = tf.constant(arr0)

print(cons)
print(~cons)

tf.Tensor(
[[ True False False]
 [False False  True]
 [ True  True False]], shape=(3, 3), dtype=bool)
tf.Tensor(
[[False  True  True]
 [ True  True False]
 [False False  True]], shape=(3, 3), dtype=bool)


In [33]:
arr1 = np.array([[True, False, False],
                 [False, True, True],
                 [True, False, True]])

print(arr0 & arr1)  # 与:全为True时才为True
print(arr0 | arr1)  # 或:全为False时才为False



[[ True False False]
 [False False  True]
 [ True False False]]
[[ True False False]
 [False  True  True]
 [ True  True  True]]
