## 交集

In [7]:
import numpy as np

'''
Find the intersection of two arrays.

Return the sorted, unique values that are in both of the input arrays.
'''
print(np.intersect1d([1, 3, 4, 3], [3, 1, 2, 1]))  # 返回值为array
print(np.intersect1d([1, 3, 4, 3], []))

[1 3]
[]


In [8]:
# To intersect more than two arrays, use functools.reduce:
from functools import reduce

reduce(np.intersect1d, ([1, 3, 4, 3], [3, 1, 2, 1], [6, 3, 4, 2]))

array([3])

## 并集

In [9]:
print(np.union1d([-1, 0, 1], [-2, 0, 2]))
print(np.union1d([-1, 0, 1], []))

[-2 -1  0  1  2]
[-1.  0.  1.]


In [10]:
# To find the union of more than two arrays, use functools.reduce:
reduce(np.union1d, ([1, 3, 4, 3], [3, 1, 2, 1], [6, 3, 4, 2]))

array([1, 2, 3, 4, 6])

## 差集

In [11]:
a = np.array([1, 2, 3, 2, 4, 1])
b = np.array([3, 4, 5, 6])

print(np.setdiff1d(a, b), type(np.setdiff1d(a, b)))
print(np.setdiff1d(b, a))
print(np.setdiff1d(b, []))

[1 2] <class 'numpy.ndarray'>
[5 6]
[3 4 5 6]
