In [59]:
import tensorflow as tf

### 参考numpy.sum/cumsum

In [60]:
print(tf.math.reduce_sum(tf.constant([0.5, 0.7, 0.2, 1.5])))  # 求和
print(tf.math.cumsum(tf.constant([0.5, 0.7, 0.2, 1.5])))  # 累和

tf.Tensor(2.9, shape=(), dtype=float32)
tf.Tensor([0.5       1.2       1.4000001 2.9      ], shape=(4,), dtype=float32)


In [61]:
a = tf.constant([[1, 2, 3],
                 [4, 5, 6]])
print(tf.math.reduce_sum(a))

# 注意:axis参数也可以为元组
print(tf.math.reduce_sum(a, axis=(0, 1)))
print(tf.math.reduce_sum(a, axis=(0, 1), keepdims=True))  # 保留缩减的维度(广播时使用)

tf.Tensor(21, shape=(), dtype=int32)
tf.Tensor(21, shape=(), dtype=int32)
tf.Tensor([[21]], shape=(1, 1), dtype=int32)


In [62]:
tf.math.cumsum(a, axis=0)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [5, 7, 9]])>

In [63]:
tf.math.cumsum(tf.reshape(a, (-1,)))

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([ 1,  3,  6, 10, 15, 21])>