In [31]:
import numpy as np
import tensorflow as tf
import pandas as pd

In [32]:
def my_func(arg):
    # Converts the given `value` to a `Tensor`
    arg = tf.convert_to_tensor(arg, dtype=tf.float32)
    return arg

In [33]:
my_func([[1.0, 2.0], [3.0, 4.0]])

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [34]:
my_func(np.array([[1.0, 2.0], [3.0, 4.0]]))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [35]:
df = pd.DataFrame([[1.0, 2.0], [3.0, 4.0]])
my_func(df)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [36]:
my_func(tf.Variable([1.0, 2.0], [2, 0, 4.0]))


<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>