In [11]:
import tensorflow as tf

### 参考numpy.arange

In [12]:
tf.range(10, dtype=tf.float32)

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)>

In [13]:
tf.range(3, 8)  # 不含末尾元素8

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([3, 4, 5, 6, 7])>

In [14]:
tf.range(3, 8, 2)  # 步长为2

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 5, 7])>

In [15]:
tf.range(8, 2, -2)  # 步长为-2




<tf.Tensor: shape=(3,), dtype=int32, numpy=array([8, 6, 4])>