In [9]:
import numpy as np
import tensorflow as tf

### 参考numpy.isnan/numpy.isinf
* 仅推荐tensorflow中

In [10]:
arr1 = np.array([1, 0, 0, 4])
arr2 = np.array([3, 4, 0, 0])

result = arr1 / arr2
result = tf.constant(result)
result

C:\Users\duanm\AppData\Local\Temp/ipykernel_16432/4219983085.py:4: RuntimeWarning: divide by zero encountered in true_divide
  result = arr1 / arr2
C:\Users\duanm\AppData\Local\Temp/ipykernel_16432/4219983085.py:4: RuntimeWarning: invalid value encountered in true_divide
  result = arr1 / arr2


<tf.Tensor: shape=(4,), dtype=float64, numpy=array([0.33333333, 0.        ,        nan,        inf])>

In [11]:
print(result[2])  # 单个值

print(tf.math.is_nan(result[2]))
print(tf.math.is_nan(result))

tf.Tensor(nan, shape=(), dtype=float64)
tf.Tensor(True, shape=(), dtype=bool)
tf.Tensor([False False  True False], shape=(4,), dtype=bool)


In [12]:
print(result[3])  # 单个值
print(tf.math.is_inf(result[3]))
print(tf.math.is_inf(result))

tf.Tensor(inf, shape=(), dtype=float64)
tf.Tensor(True, shape=(), dtype=bool)
tf.Tensor([False False False  True], shape=(4,), dtype=bool)
