In [2]:
import tensorflow as tf

In [3]:
data = tf.reshape(tf.range(9.), (3, 3))
data

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]], dtype=float32)>

### 参考numpy.where

In [4]:
data.numpy()

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]], dtype=float32)

In [5]:
data.

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'to_list'

In [ ]:
torch.where(data < 5, torch.tensor(0), torch.tensor(1))

In [3]:
# The tensors condition, x, y must be broadcastable
torch.where(data < 5, data, torch.tensor(-1, dtype=torch.float32))  # x, y数据类型必须一致

tensor([[ 0.,  1.,  2.],
        [ 3.,  4., -1.],
        [-1., -1., -1.]])

In [4]:
torch.where(data < 5, data, torch.full_like(data, -1))  # 于上等价

tensor([[ 0.,  1.,  2.],
        [ 3.,  4., -1.],
        [-1., -1., -1.]])

In [5]:
data  # data不发生改变


tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])