In [1]:
import numpy as np
from numpy import linalg as LA

a = np.arange(4)
a

array([0, 1, 2, 3])

In [2]:
b = a.reshape((2, 2))
b

array([[0, 1],
       [2, 3]])

In [3]:
LA.norm(a)  # 默认为L2范数

3.7416573867739413

In [4]:
LA.norm(a, ord=2)  # 与上等价

3.7416573867739413

In [5]:
LA.norm(a, ord=0)  # L0范数

3.0

In [6]:
LA.norm(a, ord=1)  # L1范数

6.0

In [7]:
LA.norm(a, ord=np.inf)  # 无穷范数

3.0

In [8]:
LA.norm(a, ord=3)  # Lp范数(指定p=3)

3.3019272488946263

In [9]:
LA.norm(b)  # L2范数(元素形式范数)

3.7416573867739413

In [10]:
LA.norm(b, ord=2)  # 与上等价

3.702459173643833

In [11]:
LA.norm(b, ord='fro')  # 与上等价(Frobenisu范数)

3.7416573867739413

In [12]:
LA.norm(b, ord=1)  # L1范数(元素形式范数)

4.0

In [13]:
LA.norm(b, ord=np.inf)  # 最大范数范数(元素形式范数)

5.0

In [14]:
c = np.array([[1, 2, 3],
              [-1, 1, 4]])
LA.norm(c, axis=0)  # 计算指定轴上的范数(默认axis=None)

array([1.41421356, 2.23606798, 5.        ])

In [15]:
LA.norm(c, axis=1)

array([3.74165739, 4.24264069])

In [16]:
def minkowski_1(matrices):
    """矩阵的诱导范数(1范数),即最大绝对列和"""
    max_lst = []
    for j in range(matrices.shape[1]):
        max_columns = 0
        for i in range(matrices.shape[0]):
            max_columns += abs(matrices[i, j])
        max_lst.append(max_columns)

    return max(max_lst)


In [17]:
arr = np.array([[1, -2, 3], [-4, 5, -6],
                [7, -8, -9], [-10, 11, 12]])

arr

array([[  1,  -2,   3],
       [ -4,   5,  -6],
       [  7,  -8,  -9],
       [-10,  11,  12]])

In [18]:
minkowski_1(arr)

30