In [6]:
import xgboost as xgb
from sklearn import datasets
from sklearn.model_selection import train_test_split
import numpy as np

In [7]:
X = datasets.fetch_covtype().data[:3000]
y = datasets.fetch_covtype().target[:3000]
X_train, X_test, y_train, y_test = train_test_split(X, y)

print(X_train.shape)
print(y_train.shape)
print(np.unique(y_train))  # 7分类任务

(2250, 54)
(2250,)
[1 2 3 4 5 6 7]


In [8]:
weight = 1 / y_train
train_dataset = xgb.DMatrix(data=X_train, label=y_train,
                            weight=weight)  # Weight for each instance
train_dataset

In [9]:
# Get the label of the DMatrix.
train_dataset.get_label()

array([3., 5., 4., ..., 5., 2., 5.], dtype=float32)

In [10]:
# Get the weight of the DMatrix.
train_dataset.get_weight()


array([0.33333334, 0.2       , 0.25      , ..., 0.2       , 0.5       ,
       0.2       ], dtype=float32)