In [12]:
import torch

In [13]:
# 类似numpy.arange
torch.arange(10,
             dtype=torch.float32)

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [14]:
torch.arange(3, 8)  # 不含末尾元素8

tensor([3, 4, 5, 6, 7])

In [15]:
torch.arange(3, 8, 2)  # 步长为2

tensor([3, 5, 7])

In [16]:
torch.arange(8, 2, -2)  # 步长为-2

tensor([8, 6, 4])