In [13]:
import numpy as np
import torch

# 从numpy创建tensor方法一:
a = np.array([[1.2, 2, 3],
              [2, 3, 4]])
x = torch.tensor(a)
x

tensor([[1.2000, 2.0000, 3.0000],
        [2.0000, 3.0000, 4.0000]], dtype=torch.float64)

In [14]:
x[0][0] = 1000
print(x)
print(a)
# x,a不指向相同的内存地址,也不共享数据的物理地址
print(id(x), id(a))
print(np.shares_memory(x, a))

tensor([[1000.,    2.,    3.],
        [   2.,    3.,    4.]], dtype=torch.float64)
[[1.2 2.  3. ]
 [2.  3.  4. ]]
2257410211968 2257387872400
False


In [15]:
# 从numpy创建tensor方法二:
y = torch.from_numpy(a)  # 与上等价
y[0][0] = 999
print(y)
print(a)
# y,a共享数据的物理地址
print(id(a), id(y))
print(np.shares_memory(a, y))


tensor([[999.,   2.,   3.],
        [  2.,   3.,   4.]], dtype=torch.float64)
[[999.   2.   3.]
 [  2.   3.   4.]]
2257387872400 2257410918464
True
