In [18]:
import torch
import numpy as np

### 参考numpy.array

In [19]:
x = torch.tensor(3.0)  # 标量
x

tensor(3.)

In [20]:
x = torch.tensor([5.5, 3])  # 向量
x

tensor([5.5000, 3.0000])

In [21]:
x = torch.tensor(range(10))
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
a = np.array([[1.2, 2, 3],
              [2, 3, 4]])
x = torch.tensor(a)  # 从numpy创建tensor(矩阵)
x

tensor([[1.2000, 2.0000, 3.0000],
        [2.0000, 3.0000, 4.0000]], dtype=torch.float64)

In [23]:
x = torch.tensor([1, 2, 3, 4, 5],
                 dtype=torch.float32)  # 指定数据类型
x.dtype

torch.float32

In [24]:
x = torch.tensor(['1', 2])  # 只支持数字类型
x

ValueError: too many dimensions 'str'