In [1]:
import torch

### zeros/zeros_like
1. 完全类似numpy.zeros
2. 完全类似numpy.zeros_like

In [2]:
torch.zeros((2, 3)) # 也可以是torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [3]:
put = torch.empty((2, 3))
torch.zeros_like(put)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

### ones/ones_like
1. 完全类似numpy.ones
2. 完全类似numpy.ones_like

In [4]:
torch.ones((2, 3))

tensor([[1., 1., 1.],
        [1., 1., 1.]])

### eye
1. 类似numpy.eye

In [5]:
# 对角线元素为1
torch.eye(3) # 默认m=n

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [6]:
torch.eye(n=3, # 行数
          m=6) # 列数

tensor([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.]])

### empty/empty_like
1. 完全类似numpy.empty
2. 完全类似numpy.empty_like

In [7]:
torch.empty((2, 3)) # 结果非常不均衡

tensor([[0., 0., 0.],
        [0., 0., 0.]])

### full/full_like
1. 完全类似numpy.full
2. 完全类似numpy_like

In [8]:
torch.full((2, 3), 3.141592)

tensor([[3.1416, 3.1416, 3.1416],
        [3.1416, 3.1416, 3.1416]])

### diag
1. 完全类似numpy.diag

In [9]:
a = torch.randn(3)

In [10]:
# Get the square matrix where the input vector is the diagonal
torch.diag(a)

tensor([[ 0.3737,  0.0000,  0.0000],
        [ 0.0000, -1.2668,  0.0000],
        [ 0.0000,  0.0000, -0.2344]])

In [11]:
torch.diag(a, 1)

tensor([[ 0.0000,  0.3737,  0.0000,  0.0000],
        [ 0.0000,  0.0000, -1.2668,  0.0000],
        [ 0.0000,  0.0000,  0.0000, -0.2344],
        [ 0.0000,  0.0000,  0.0000,  0.0000]])

In [12]:
torch.diag(a, -1)

tensor([[ 0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.3737,  0.0000,  0.0000,  0.0000],
        [ 0.0000, -1.2668,  0.0000,  0.0000],
        [ 0.0000,  0.0000, -0.2344,  0.0000]])

In [13]:
b = torch.randn(3, 3)
b

tensor([[-0.9408, -1.0021,  1.7779],
        [ 0.0540,  0.8580, -0.0195],
        [ 1.3058,  1.2327,  0.6176]])

In [14]:
# Get the k-th diagonal of a given matrix
torch.diag(b)

tensor([-0.9408,  0.8580,  0.6176])

In [15]:
torch.diag(b, -1)

tensor([0.0540, 1.2327])

In [16]:
torch.diag(b, 2)


tensor([1.7779])