In [55]:
import torch

### zeros/zeros_like
1. 参考numpy.zeros
2. 参考numpy.zeros_like

In [56]:
torch.zeros((2, 3))

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [57]:
put = torch.empty((2, 3))
torch.zeros_like(put)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

### ones/ones_like
1. 参考numpy.ones
2. 参考numpy.ones_like

In [58]:
torch.ones((2, 3))

tensor([[1., 1., 1.],
        [1., 1., 1.]])

### eye
1. 类似numpy.eye

In [59]:
# 对角线元素为1
torch.eye(3)  # 默认m=n

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [60]:
torch.eye(n=3,  # 行数
          m=6)  # 列数

tensor([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.]])

### empty/empty_like
1. 参考numpy.empty
2. 参考numpy.empty_like

In [61]:
torch.empty((2, 3))  # 结果非常不均衡

tensor([[6.7203e-07, 2.1159e-07, 2.7179e+23],
        [1.0723e-08, 4.2010e-05, 1.7281e-04]])

### full/full_like
1. 参考numpy.full
2. 参考numpy_like

In [62]:
torch.full((2, 3), 3.141592)

tensor([[3.1416, 3.1416, 3.1416],
        [3.1416, 3.1416, 3.1416]])

### diag
1. 参考numpy.diag

In [63]:
a = torch.randn(3)

In [64]:
# Get the square matrix where the input vector is the diagonal
torch.diag(a)

tensor([[ 0.2237,  0.0000,  0.0000],
        [ 0.0000, -1.0597,  0.0000],
        [ 0.0000,  0.0000, -0.6123]])

In [65]:
torch.diag(a, 1)

tensor([[ 0.0000,  0.2237,  0.0000,  0.0000],
        [ 0.0000,  0.0000, -1.0597,  0.0000],
        [ 0.0000,  0.0000,  0.0000, -0.6123],
        [ 0.0000,  0.0000,  0.0000,  0.0000]])

In [66]:
torch.diag(a, -1)

tensor([[ 0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.2237,  0.0000,  0.0000,  0.0000],
        [ 0.0000, -1.0597,  0.0000,  0.0000],
        [ 0.0000,  0.0000, -0.6123,  0.0000]])

In [67]:
b = torch.randn(3, 3)
b

tensor([[ 0.2245, -0.1563, -2.4369],
        [ 2.3167,  0.9523,  0.5811],
        [-0.7127,  2.8697,  1.0206]])

In [68]:
# Get the k-th diagonal of a given matrix
torch.diag(b)

tensor([0.2245, 0.9523, 1.0206])

In [69]:
torch.diag(b, -1)

tensor([2.3167, 2.8697])

In [70]:
torch.diag(b, 2)


tensor([-2.4369])