In [27]:
import torch

### 参考numpy.random.randint

In [28]:
generator_state = torch.Generator().manual_seed(4)

In [29]:

# Returns a tensor filled with random integers generated uniformly between low (inclusive) and high (exclusive).
torch.randint(3, 8, size=(3, 4))  # 不包括末尾元素

tensor([[3, 5, 6, 5],
        [3, 4, 3, 4],
        [3, 7, 4, 4]])

In [30]:
# Returns a random permutation of integers from 0 to n - 1.
idx = torch.randperm(3, generator=generator_state)
idx

tensor([1, 0, 2])

In [31]:
x1 = torch.tensor([[1, 1, 1], [2, 2, 2], [3, 3, 3]])
x2 = torch.tensor([[1.0, 1.0, 1.0], [2.0, 2.0, 2.0], [3.0, 3.0, 3.0]])
print(x1[idx])
print(x2[idx])  # 实现了sklearn.utils.shuffle函数的功能

tensor([[2, 2, 2],
        [1, 1, 1],
        [3, 3, 3]])
tensor([[2., 2., 2.],
        [1., 1., 1.],
        [3., 3., 3.]])
