In [1]:
import torch

x = torch.tensor([2.], requires_grad=True)
y = x**5

# 高阶导数求解;指定create_graph=True
grad1 = torch.autograd.grad(y, x, create_graph=True) # y对x的一阶导数
print(grad1)

grad2 = torch.autograd.grad(grad1, x, create_graph=True) # y对x的二阶导数
print(grad2)

grad3 = torch.autograd.grad(grad2, x) # y对x的三阶导数
print(grad3)



(tensor([80.], grad_fn=<MulBackward0>),)
(tensor([160.], grad_fn=<MulBackward0>),)
(tensor([240.]),)
