In [116]:
import tensorflow as tf

### 多分类交叉熵损失函数
### 参考nn.CrossEntropyLoss===>对应from_logits=True

In [117]:
y_pred = tf.reshape(tf.range(12, dtype=tf.float32), (4, 3))
y_pred

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]], dtype=float32)>

In [118]:
y_true_scc = tf.constant([1, 2, 0, 2])
y_true_scc

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 0, 2])>

In [119]:
# reduction参数参考tf.keras.losses.BinaryCrossentropy
scc = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True,  # Recommended Usage: (set from_logits=True)
                                                    name='sparse_categorical_crossentropy')
print(scc.name)
print(scc(y_true=y_true_scc,  # 整数向量形式
          y_pred=y_pred).numpy())

sparse_categorical_crossentropy
1.1576061


In [120]:
y_true_cc = tf.one_hot(y_true_scc, depth=3)
y_true_cc

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.]], dtype=float32)>

In [121]:
# reduction参数参考tf.keras.losses.BinaryCrossentropy
cc = tf.keras.losses.CategoricalCrossentropy(from_logits=True,  # Recommended Usage: (set from_logits=True)
                                             name='categorical_crossentropy')
print(cc.name)
print(cc(y_true=y_true_cc,  # 独热编码形式
         y_pred=y_pred).numpy())


categorical_crossentropy
1.1576061
