In [79]:
import tensorflow as tf

In [80]:
tor = tf.range(0, 10)
tor

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [81]:
# Randomly shuffles a tensor along its first dimension.
tf.random.shuffle(tor, seed=23)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([4, 2, 8, 3, 7, 9, 0, 6, 1, 5])>

In [82]:
tor1 = tf.reshape(tf.range(24), (4, 6))
tor1

<tf.Tensor: shape=(4, 6), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])>

In [83]:
# The tensor is shuffled along dimension 0
tf.random.shuffle(tor1)

<tf.Tensor: shape=(4, 6), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4,  5],
       [12, 13, 14, 15, 16, 17],
       [ 6,  7,  8,  9, 10, 11],
       [18, 19, 20, 21, 22, 23]])>