In [157]:
import tensorflow as tf

### 参考np.random.binomial/np.random.multinomial

In [158]:
'''
shape	        A 1-D integer Tensor or Python array. The shape of the output tensor.
seed	        A shape [2] Tensor, the seed to the random number generator.
                Must have dtype int32 or int64. (When using XLA, only int32 is allowed.)
counts	        Tensor. The counts of the binomial distribution.
                Must be broadcastable with probs, and broadcastable with the rightmost dimensions of shape.
probs	        Tensor. The probability of success for the binomial distribution.
                Must be broadcastable with counts and broadcastable with the rightmost dimensions of shape.
output_dtype	The type of the output. Default: tf.int32
'''
counts = tf.constant([[10., 20., 30.]])  # Probability of success.
probs = tf.constant([0.8])

tf.random.stateless_binomial(seed=[1, 2], shape=(10, 1, 3), counts=counts, probs=probs)

<tf.Tensor: shape=(10, 1, 3), dtype=int32, numpy=
array([[[ 7, 15, 22]],

       [[ 8, 16, 25]],

       [[ 7, 16, 22]],

       [[ 8, 16, 22]],

       [[ 6, 17, 24]],

       [[ 8, 17, 25]],

       [[ 7, 16, 25]],

       [[10, 15, 22]],

       [[ 7, 15, 25]],

       [[ 9, 17, 23]]])>

In [159]:
'''
解析:
counts.shape=[2, 3]
probs.shape=[1]
shape=(4, 2, 3)

[1] boradcasting [2, 3] --> [2, 3]
[2, 3] boradcasting [4, 2, 3] --> [4, 2, 3]
'''
counts = tf.constant([[10., 20., 30.],
                      [40., 50., 60.]])
probs = tf.constant([0.8])

tf.random.stateless_binomial(seed=[1, 2], shape=(4, 2, 3), counts=counts, probs=probs)

<tf.Tensor: shape=(4, 2, 3), dtype=int32, numpy=
array([[[ 7, 14, 19],
        [32, 42, 45]],

       [[ 8, 15, 24],
        [32, 41, 52]],

       [[ 7, 14, 23],
        [36, 38, 48]],

       [[ 8, 18, 23],
        [32, 39, 47]]])>