In [2]:
import tensorflow as tf

### 参考numpy.repeat

In [3]:
x = tf.constant([[1, 2],
                 [3, 4]])
x

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [5]:
# By default (axis=None), use the flattened input array, and return a flat output array.
tf.repeat(x, 2)  # 默认dim=None

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([1, 1, 2, 2, 3, 3, 4, 4])>

In [6]:
tf.repeat(x, 3, axis=1)  # x维度1每条数据连续重复3次

<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[1, 1, 1, 2, 2, 2],
       [3, 3, 3, 4, 4, 4]])>

In [8]:
tf.repeat(x, 3, axis=0)  # x维度0每条数据连续重复3次

<tf.Tensor: shape=(6, 2), dtype=int32, numpy=
array([[1, 2],
       [1, 2],
       [1, 2],
       [3, 4],
       [3, 4],
       [3, 4]])>

In [9]:
tf.repeat(x, tf.constant([2, 4]), axis=0)  # x维度0第0条数据重复2次,然后x维度0第1条数据重复4次

<tf.Tensor: shape=(6, 2), dtype=int32, numpy=
array([[1, 2],
       [1, 2],
       [3, 4],
       [3, 4],
       [3, 4],
       [3, 4]])>