| `ord`              | norm for matrices       | norm for vectors              |
| ------------------ | ----------------------- | ----------------------------- |
| None (default)     | Frobenius norm          | 2-norm (see below)            |
| ‘fro’              | Frobenius norm          | – not supported –             |
| ‘nuc’              | nuclear norm            | – not supported –             |
| inf                | max(sum(abs(x), dim=1)) | max(abs(x))                   |
| -inf               | min(sum(abs(x), dim=1)) | min(abs(x))                   |
| 0                  | – not supported –       | sum(x != 0)                   |
| 1                  | max(sum(abs(x), dim=0)) | as below                      |
| -1                 | min(sum(abs(x), dim=0)) | as below                      |
| 2                  | largest singular value  | as below                      |
| -2                 | smallest singular value | as below                      |
| other int or float | – not supported –       | sum(abs(x)^{ord})^{(1 / ord)} |


In [27]:
from torch import linalg as LA
import torch

In [28]:
a = torch.arange(9, dtype=torch.float) - 4
a

tensor([-4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.])

In [29]:
B = a.reshape((3, 3))
B

tensor([[-4., -3., -2.],
        [-1.,  0.,  1.],
        [ 2.,  3.,  4.]])

In [30]:
print(LA.norm(a))
print(LA.norm(a, ord=2))  # 向量:默认ord=2

print(LA.norm(B))
print(LA.norm(B, ord='fro'))  # 矩阵:默认ord='fro'

tensor(7.7460)
tensor(7.7460)
tensor(7.7460)
tensor(7.7460)


In [31]:
print(LA.norm(a, float('inf')))
print(LA.norm(B, float('inf')))

print(LA.norm(a, -float('inf')))
print(LA.norm(B, -float('inf')))

tensor(4.)
tensor(9.)
tensor(0.)
tensor(2.)


In [32]:
A = torch.arange(8, dtype=torch.float).reshape(2, 2, 2)
A

tensor([[[0., 1.],
         [2., 3.]],

        [[4., 5.],
         [6., 7.]]])

In [33]:
print(LA.norm(A, dim=(1, 2)))
print(LA.norm(A[0, :, :]), LA.norm(A[1, :, :]))  # 与上等级

tensor([ 3.7417, 11.2250])
tensor(3.7417) tensor(11.2250)
