In [32]:
import numpy as np
from sklearn.metrics import pairwise_distances

X = np.array([[2, 3],
              [3, 5],
              [5, 8]])
Y = np.array([[1, 0],
              [2, 1]])

In [33]:
# 省略Y,则计算X各行向量之间的距离
pairwise_distances(X)  # 默认metric='euclidean'(欧式距离)

array([[0.        , 2.23606798, 5.83095189],
       [2.23606798, 0.        , 3.60555128],
       [5.83095189, 3.60555128, 0.        ]])

In [34]:
# 计算X,Y各行向量之间的距离
pairwise_distances(X, Y, metric='l2')  # 欧式距离

array([[3.16227766, 2.        ],
       [5.38516481, 4.12310563],
       [8.94427191, 7.61577311]])

计算步骤如下:    
X = [x1, x2, x3]   
y= [y1, y2]    
pairwise_distances(X, Y, metric='l2') =   
[(x1, y1), (x1, y2)]    
[(x2, y1), (x2, y2)]   
[(x3, y1), (x3, y2)]  

In [35]:
pairwise_distances(X, Y, metric='manhattan')  # 曼哈顿距离,等价于metric='l1'

array([[ 4.,  2.],
       [ 7.,  5.],
       [12., 10.]])

In [36]:
pairwise_distances(X, metric='cosine')  # 余弦距离

array([[0.        , 0.00113186, 0.00043225],
       [0.00113186, 0.        , 0.00016525],
       [0.00043225, 0.00016525, 0.        ]])