In [12]:
import numpy as np
from sklearn.neighbors import kneighbors_graph

X = np.array([[0, 1],
              [3, 2],
              [1, 3],
              [4, 0]])  # 矩阵形式(X为4个(行)向量组成的矩阵)
# Computes the (weighted) graph of k-Neighbors for points in X
A = kneighbors_graph(X,
                     n_neighbors=3,  # 最近邻样本个数
                     mode='connectivity',  # 是最近邻样本则返回1,否则返回0
                     include_self=True,  # 是否将自身作为第一个最近邻样本
                     n_jobs=-1)
A.toarray()

array([[1., 1., 1., 0.],
       [0., 1., 1., 1.],
       [1., 1., 1., 0.],
       [1., 1., 0., 1.]])

In [13]:
B = kneighbors_graph(X, n_neighbors=2,  # 最近邻样本个数
                     mode='distance',  # 是最近邻样本则返回样本与最近邻样本的距离,否则返回0
                     include_self=False,
                     n_jobs=-1)
B.toarray()

array([[0.        , 3.16227766, 2.23606798, 0.        ],
       [0.        , 0.        , 2.23606798, 2.23606798],
       [2.23606798, 2.23606798, 0.        , 0.        ],
       [4.12310563, 2.23606798, 0.        , 0.        ]])

In [14]:
C = kneighbors_graph(X, n_neighbors=2,
                     mode='connectivity',
                     include_self=True,
                     metric='minkowski',
                     # 默认metric='minkowski',即minkowski距离.sklearn.neighbors.DistanceMetric类提供了可用指标的列表
                     p=1,  # 默认p=2,即欧式距离(必须指定metric='minkowski')
                     n_jobs=-1)
C.toarray()

array([[1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.]])