In [10]:
import torch

In [11]:
scale = torch.tensor([1.])
scale.item() # Returns the value of this tensor as a standard Python number. This only works for tensors with one element

1.0

In [12]:
tor = torch.tensor([[1, 2, 3, 4, 5],
                    [2, 3, 4, 5, 6]])
tor

tensor([[1, 2, 3, 4, 5],
        [2, 3, 4, 5, 6]])

In [13]:
lst = tor.tolist() # Returns the tensor as a (nested) list
lst

[[1, 2, 3, 4, 5], [2, 3, 4, 5, 6]]

In [14]:
lst[0][0] = 9999
lst

[[9999, 2, 3, 4, 5], [2, 3, 4, 5, 6]]

In [15]:
tor # tor不变

tensor([[1, 2, 3, 4, 5],
        [2, 3, 4, 5, 6]])

In [16]:
arr = tor.numpy() # Returns self tensor as a NumPy ndarray
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]], dtype=int64)

In [17]:
arr[0][0] = 1111111111
arr

array([[1111111111,          2,          3,          4,          5],
       [         2,          3,          4,          5,          6]],
      dtype=int64)

In [18]:
tor # tor发生改变;tor,arr共享内存


tensor([[1111111111,          2,          3,          4,          5],
        [         2,          3,          4,          5,          6]])