In [13]:
import torch

In [14]:
x = torch.randn(3, 4)
x

tensor([[ 0.9654, -1.4568, -1.9760, -0.1793],
        [ 0.4485, -0.1537, -0.3088,  0.5035],
        [-0.8243, -0.9957,  0.4932,  0.2355]])

In [15]:
mask = x.ge(0.5)
mask

tensor([[ True, False, False, False],
        [False, False, False,  True],
        [False, False, False, False]])

In [16]:
select = torch.masked_select(x, mask) # ★★★★返回一个新的一维tensor
select

tensor([0.9654, 0.5035])

In [17]:
select[0] = 9999
select

tensor([9.9990e+03, 5.0346e-01])

In [18]:
x # x不变

tensor([[ 0.9654, -1.4568, -1.9760, -0.1793],
        [ 0.4485, -0.1537, -0.3088,  0.5035],
        [-0.8243, -0.9957,  0.4932,  0.2355]])