### fill_
### zero_
### uniform_

In [1]:
import torch

a = torch.empty((3, 5))
a

tensor([[-1.8014e-26,  4.5682e-43, -1.8014e-26,  4.5682e-43, -1.8014e-26],
        [ 4.5682e-43, -1.8014e-26,  4.5682e-43, -1.8016e-26,  4.5682e-43],
        [-1.8016e-26,  4.5682e-43, -1.8016e-26,  4.5682e-43, -1.8016e-26]])

In [2]:
a.fill_(1) # Fills self tensor with the specified value;In-place操作
a

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [3]:
a.zero_() #  # Fills self tensor with zeros;In-place操作
a

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

Fills self tensor with numbers sampled from the continuous uniform distribution:

$$ P(x) = \frac{1}{b - a}  $$

In [4]:
a.uniform_(2, 5) # a=2,b=5
a

tensor([[2.2680, 4.3221, 4.7835, 3.0305, 3.1994],
        [4.3825, 3.9999, 2.6696, 4.9387, 3.5408],
        [4.2941, 3.3970, 3.4193, 2.5619, 2.3612]])

In [5]:
a.normal_(mean=0, std=4) # Fills self tensor with elements samples from the normal distribution parameterized by mean and std.
a

tensor([[ 3.8410, -4.6787,  4.0485,  0.6278,  0.5921],
        [ 1.9830, -3.0161,  2.9484,  1.5519,  2.1447],
        [ 0.2014,  4.7046,  0.9076,  5.2295,  1.2430]])