In [62]:
import torch

data = torch.arange(9.).reshape(3, 3)
data

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])

In [63]:
# 完全类似numpy.where
torch.where(data < 5, torch.tensor(0), torch.tensor(1))

tensor([[0, 0, 0],
        [0, 0, 1],
        [1, 1, 1]])

In [64]:
# The tensors condition, x, y must be broadcastable
torch.where(data < 5, data, torch.tensor(-1, dtype=torch.float32)) # x, y数据类型必须一致

tensor([[ 0.,  1.,  2.],
        [ 3.,  4., -1.],
        [-1., -1., -1.]])

In [65]:
torch.where(data < 5, data, torch.full_like(data, -1)) # 于上等价

tensor([[ 0.,  1.,  2.],
        [ 3.,  4., -1.],
        [-1., -1., -1.]])

In [66]:
data # data不发生改变


tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])