In [1]:
import torch 

In [2]:
x = torch.randn(3, 4, 3)
x

tensor([[[-1.0052,  0.0584,  1.0592],
         [-0.4666, -1.0112, -1.5281],
         [-1.0136, -0.8335,  0.0250],
         [ 0.9158,  0.8768, -0.1191]],

        [[-0.1837, -1.2411, -1.1486],
         [-0.3158, -1.0028, -1.6560],
         [ 1.3463, -1.3031, -0.2017],
         [-0.7626,  1.0427, -0.4812]],

        [[ 1.0247,  0.8354,  1.2360],
         [-2.0664, -0.3152,  0.2308],
         [-0.6549,  1.2167,  0.6509],
         [-0.4887, -0.8509, -0.6194]]])

In [3]:
indices = torch.tensor([0, 2])

In [4]:
'''
input (Tensor) – the input tensor.
dim (python:int) – the dimension in which we index
index (LongTensor) – the 1-D tensor containing the indices to index
'''
torch.index_select(x, dim=0, index=indices) # 维度dim上按index索引切片x

tensor([[[-1.0052,  0.0584,  1.0592],
         [-0.4666, -1.0112, -1.5281],
         [-1.0136, -0.8335,  0.0250],
         [ 0.9158,  0.8768, -0.1191]],

        [[ 1.0247,  0.8354,  1.2360],
         [-2.0664, -0.3152,  0.2308],
         [-0.6549,  1.2167,  0.6509],
         [-0.4887, -0.8509, -0.6194]]])

In [5]:
select = torch.index_select(x, 1, index=indices) # ★★★★返回一个新的tensor
select

tensor([[[-1.0052,  0.0584,  1.0592],
         [-1.0136, -0.8335,  0.0250]],

        [[-0.1837, -1.2411, -1.1486],
         [ 1.3463, -1.3031, -0.2017]],

        [[ 1.0247,  0.8354,  1.2360],
         [-0.6549,  1.2167,  0.6509]]])

In [6]:
select[:] = 0
select

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])

In [7]:
x # x不变

tensor([[[-1.0052,  0.0584,  1.0592],
         [-0.4666, -1.0112, -1.5281],
         [-1.0136, -0.8335,  0.0250],
         [ 0.9158,  0.8768, -0.1191]],

        [[-0.1837, -1.2411, -1.1486],
         [-0.3158, -1.0028, -1.6560],
         [ 1.3463, -1.3031, -0.2017],
         [-0.7626,  1.0427, -0.4812]],

        [[ 1.0247,  0.8354,  1.2360],
         [-2.0664, -0.3152,  0.2308],
         [-0.6549,  1.2167,  0.6509],
         [-0.4887, -0.8509, -0.6194]]])