In [214]:
import torch

t = torch.arange(24).reshape(2, 3, 4)
t

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [215]:
'''
由t[0, :, :].shape = t[1, :, :].shape = [3, 4]
故index_0.shape必须为[1, 3, 4]或[2, 3, 4]或[3, 3, 4]或[4, 3, 4].....

过程:
t[0,     0,0], t[1,     0,1], t[0,      0,2], t[1,      0,3]
t[1,     1,0], t[0,     1,1], t[1,      1,2], t[0,      1,3]
t[1,     2,0], t[1,     2,1], t[0,      2,2], t[0,      2,3]

t[0,     0,0], t[1,     0,1], t[0,      0,2], t[1,      0,3]
t[1,     1,0], t[0,     1,1], t[1,      1,2], t[0,      1,3]
t[1,     2,0], t[1,     2,1], t[0,      2,2], t[0,      2,3]

t[0,     0,0], t[1,     0,1], t[0,      0,2], t[1,      0,3]
t[1,     1,0], t[0,     1,1], t[1,      1,2], t[0,      1,3]
t[1,     2,0], t[1,     2,1], t[0,      2,2], t[0,      2,3]

t[0,     0,0], t[1,     0,1], t[0,      0,2], t[1,      0,3]
t[1,     1,0], t[0,     1,1], t[1,      1,2], t[0,      1,3]
t[1,     2,0], t[1,     2,1], t[0,      2,2], t[0,      2,3]

'''
index_0 = torch.tensor([[[0, 1, 0, 1],
                         [1, 0, 1, 0],
                         [1, 1, 0, 0]],

                        [[0, 1, 0, 1],
                         [1, 0, 1, 0],
                         [1, 1, 0, 0]],

                        [[0, 1, 0, 1],
                         [1, 0, 1, 0],
                         [1, 1, 0, 0]],

                        [[0, 1, 0, 1],
                         [1, 0, 1, 0],
                         [1, 1, 0, 0]]])
resutl = torch.gather(t, dim=0, index=index_0)
resutl # shape等于index.shape

tensor([[[ 0, 13,  2, 15],
         [16,  5, 18,  7],
         [20, 21, 10, 11]],

        [[ 0, 13,  2, 15],
         [16,  5, 18,  7],
         [20, 21, 10, 11]],

        [[ 0, 13,  2, 15],
         [16,  5, 18,  7],
         [20, 21, 10, 11]],

        [[ 0, 13,  2, 15],
         [16,  5, 18,  7],
         [20, 21, 10, 11]]])

In [216]:
'''
由t[:, 0, :].shape = t[:, 1, :].shape = t[:, 2, :].shape = [2, 4]
故index_0.shape必须为[2, 1, 4]或[2, 2, 4]或[2, 3, 4]或[2, 4, 4].....

过程:
t[0,    0,   0], t[0,    1,    1], t[0,    2,    2], t[0,    1,    3]

t[1,    2,   0], t[1,    1,    1], t[1,    2,    2], t[1,    1,    3]

'''

index_11 = torch.tensor([[[0, 1, 2, 1]],

                         [[2, 1, 2, 1]]])
torch.gather(t, dim=1, index=index_11)


tensor([[[ 0,  5, 10,  7]],

        [[20, 17, 22, 19]]])

In [217]:
'''
过程:
t[0,    0,   0], t[0,    1,    1], t[0,    2,    2], t[0,    1,    3]
t[0,    1,   0], t[0,    2,    1], t[0,    2,    2], t[0,    0,    3]
t[0,    2,   0], t[0,    2,    1], t[0,    1,    2], t[0,    1,    3]
t[0,    0,   0], t[0,    0,    1], t[0,    1,    2], t[0,    1,    3]
t[0,    1,   0], t[0,    1,    1], t[0,    1,    2], t[0,    1,    3]


t[1,    2,   0], t[1,    1,    1], t[1,    2,    2], t[1,    1,    3]
t[1,    0,   0], t[1,    2,    1], t[1,    1,    2], t[1,    2,    3]
t[1,    0,   0], t[1,    0,    1], t[1,    0,    2], t[1,    0,    3]
t[1,    1,   0], t[1,    1,    1], t[1,    1,    2], t[1,    1,    3]
t[1,    2,   0], t[1,    2,    1], t[1,    2,    2], t[1,    2,    3]
'''

index_15 = torch.tensor([[[0, 1, 2, 1],
                          [1, 2, 2, 0],
                          [2, 2, 1, 1],
                          [0, 0, 1, 1],
                          [1, 1, 1, 1]],

                         [[2, 1, 2, 1],
                          [0, 2, 1, 2],
                          [0, 0, 0, 0],
                          [1, 1, 1, 1],
                          [2, 2, 2, 2]]])

torch.gather(t, dim=1, index=index_15)

tensor([[[ 0,  5, 10,  7],
         [ 4,  9, 10,  3],
         [ 8,  9,  6,  7],
         [ 0,  1,  6,  7],
         [ 4,  5,  6,  7]],

        [[20, 17, 22, 19],
         [12, 21, 18, 23],
         [12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [227]:
'''
由t[:, :, 0].shape = t[:, :, 1].shape = t[:, :, 2].shape = t[:, :, 3].shape = [2, 3]
故index_2.shape必须为[2, 3, 1]或[2, 3, 2]或[2, 3, 3]或[2, 3, 4].....
'''

index_2 = torch.tensor([[[1],
                        [2],
                        [0]],

                       [[2],
                        [3],
                        [0]]])

torch.gather(t, dim=2, index=index_2)


tensor([[[ 1],
         [ 6],
         [ 8]],

        [[14],
         [19],
         [20]]])