In [19]:
import torch

### 参考numpy.einsum

In [20]:
A = torch.arange(25).reshape(5, 5)
A

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]])

In [21]:
# 全部元素求和
torch.einsum('ij->', A) # \sum_{i,j} A_{i,j}

tensor(300)

In [22]:
# 矩阵的迹
# \sum_{i,j} A_{i,i}
# 即:\sum_{i} A_{i,j}
torch.einsum('ii->', A)

tensor(60)

In [23]:
# 某一维度求和
# \sum_j A_{i=0,j}, \sum_j A_{i=1,j}, \sum_j A_{i=2,j}, ......
torch.einsum('ij->i', A)  # 保留维度i

tensor([ 10,  35,  60,  85, 110])

In [24]:
# 提取对角线
# \sum_{j} A_{i,i}
# 即:A_{0,0}, A_{1,1}, A_{2,2}, ......
torch.einsum('ii->i', A)

tensor([ 0,  6, 12, 18, 24])

In [25]:
# 转置
# B_{i,j} = A_{j, i}
B = torch.einsum('ij->ji', A)
B

tensor([[ 0,  5, 10, 15, 20],
        [ 1,  6, 11, 16, 21],
        [ 2,  7, 12, 17, 22],
        [ 3,  8, 13, 18, 23],
        [ 4,  9, 14, 19, 24]])

In [37]:
x = torch.arange(5)
y = torch.arange(5)
print(x)
print(y)

# 向量内积
print(torch.einsum('i,i->', x, y))  # \sum_i x_i y_i

tensor([0, 1, 2, 3, 4])
tensor([0, 1, 2, 3, 4])
tensor(30)


In [27]:
x = torch.arange(5)
y = torch.arange(4)
print(x)
print(y)

# 向量外积
c = torch.einsum('i,j->ij', x, y)  # c_{ij} = x_i * y_j
print(c)

tensor([0, 1, 2, 3, 4])
tensor([0, 1, 2, 3])
tensor([[ 0,  0,  0,  0],
        [ 0,  1,  2,  3],
        [ 0,  2,  4,  6],
        [ 0,  3,  6,  9],
        [ 0,  4,  8, 12]])


In [28]:
A = torch.arange(9).reshape(3, 3)
b = torch.arange(3)
print(A)
print(b)

# \sum_{i,j} A_{i,j} * b_{j}
print(torch.einsum('ij,j->', A, b))

# \sum_j A_{i=0,j} * b_j, \sum_j A_{i=1,j} * b_j, \sum_j A_{i=2,j} * b_j, ......
print(torch.einsum('ij,j->i', A, b))

# \sum_i A_{i,j=0} * b_j, \sum_i A_{i,j=1} * b_j, \sum_i A_{i,j=2} * b_j, ......
print(torch.einsum('ij,j->j', A, b))

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([0, 1, 2])
tensor(42)
tensor([ 5, 14, 23])
tensor([ 0, 12, 30])


In [29]:
a = torch.arange(0, 6).reshape(2, 3)
b = torch.arange(0, 6).reshape(3, 2)
print(a)
print(b)

# 矩阵乘法
c = torch.einsum('ik,kj->ij', a, b)
print(c)

tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([[0, 1],
        [2, 3],
        [4, 5]])
tensor([[10, 13],
        [28, 40]])


In [30]:
a = torch.arange(0, 6).reshape(2, 3)
b = torch.arange(1, 7).reshape(2, 3)
print(a)
print(b)

# 矩阵对应元素相乘
c0 = torch.einsum('ij,ij->ij', a, b)
print(c0)

# 矩阵对应元素相乘并求和
c1 = torch.einsum('ij,ij->', a, b)
print(c1)

tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[ 0,  2,  6],
        [12, 20, 30]])
tensor(70)


In [31]:
ba = torch.arange(0, 24).reshape((2, 3, 4))
bb = torch.arange(0, 24).reshape((2, 4, 3))
print(ba)

# 批量矩阵乘法
bc = torch.einsum('bij,bjk->bjk', ba, bb)
# bc = torch.einsum('...ij,...jk->...jk', ba, bb)  # 与上等价(前面或后面任意个维度可用 ... 代替)
print(bc)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
tensor([[[   0,   12,   24],
         [  45,   60,   75],
         [ 108,  126,  144],
         [ 189,  210,  231]],

        [[ 576,  624,  672],
         [ 765,  816,  867],
         [ 972, 1026, 1080],
         [1197, 1254, 1311]]])


In [32]:
# 批量转置
ba = torch.arange(0, 120).reshape((2, 3, 4, 5))
torch.einsum('...ij->...ji', ba).shape  # 最后两个维度转置
# torch.einsum('mnij->mnji', ba)  # 与上等价

torch.Size([2, 3, 5, 4])

In [33]:
a = torch.arange(6).reshape(2, 3)
b = torch.arange(4).reshape(4)

print(a)
print(b, end='\n\n')

# 1
print(torch.einsum('qj,k->qjk', a, b))
print(torch.swapaxes(torch.einsum('qj,k->qjk', a, b), 1, 2))
print(torch.einsum('qj,k->qkj', a, b), end='\n\n')  # 与上等价

# 2
print(torch.sum(torch.einsum('qj,k->qjk', a, b), dim=-1))
print(torch.einsum('qj,k->qj', a, b), end='\n\n')  # 与上等价

# 3
print(torch.sum(torch.einsum('qj,k->qj', a, b), dim=-1))
print(torch.einsum('qj,k->q', a, b), end='\n\n')  # 与上等价

# 4
print(torch.sum(torch.einsum('qj,k->q', a, b), dim=-1))
print(torch.einsum('qj,k->', a, b))  # 与上等价

tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([0, 1, 2, 3])

tensor([[[ 0,  0,  0,  0],
         [ 0,  1,  2,  3],
         [ 0,  2,  4,  6]],

        [[ 0,  3,  6,  9],
         [ 0,  4,  8, 12],
         [ 0,  5, 10, 15]]])
tensor([[[ 0,  0,  0],
         [ 0,  1,  2],
         [ 0,  2,  4],
         [ 0,  3,  6]],

        [[ 0,  0,  0],
         [ 3,  4,  5],
         [ 6,  8, 10],
         [ 9, 12, 15]]])
tensor([[[ 0,  0,  0],
         [ 0,  1,  2],
         [ 0,  2,  4],
         [ 0,  3,  6]],

        [[ 0,  0,  0],
         [ 3,  4,  5],
         [ 6,  8, 10],
         [ 9, 12, 15]]])

tensor([[ 0,  6, 12],
        [18, 24, 30]])
tensor([[ 0,  6, 12],
        [18, 24, 30]])

tensor([18, 72])
tensor([18, 72])

tensor(90)
tensor(90)


In [34]:
Q = torch.rand(32, 20, 8, 1)
K = torch.rand(32, 10, 1, 8)

# 相同部分(n h d)必须满足相等或可广播
M = torch.einsum("nqhd,nkhd->nhqk", Q, K)
print(M.shape)

torch.Size([32, 8, 20, 10])
