In [47]:
import torch
import numpy as np

In [48]:
scale = torch.tensor([1.])
# Returns the value of this tensor as a standard Python number. This only works for tensors with one element
scale.item()

1.0

In [49]:
tor = torch.tensor([[1, 2, 3, 4, 5],
                    [2, 3, 4, 5, 6]])
tor

tensor([[1, 2, 3, 4, 5],
        [2, 3, 4, 5, 6]])

In [50]:
lst = tor.tolist()  # Returns the tensor as a (nested) list
lst

[[1, 2, 3, 4, 5], [2, 3, 4, 5, 6]]

In [51]:
lst[0][0] = 9999
lst

[[9999, 2, 3, 4, 5], [2, 3, 4, 5, 6]]

In [52]:
tor  # tor不变

tensor([[1, 2, 3, 4, 5],
        [2, 3, 4, 5, 6]])

In [53]:
arr = tor.numpy()  # Returns self tensor as a NumPy ndarray
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]], dtype=int64)

In [54]:
arr[0][0] = 1111111111
arr

array([[1111111111,          2,          3,          4,          5],
       [         2,          3,          4,          5,          6]],
      dtype=int64)

In [55]:
# y,a共享数据的物理地址
print(np.shares_memory(arr, tor))
print(tor)  # tor发生改变


True
tensor([[1111111111,          2,          3,          4,          5],
        [         2,          3,          4,          5,          6]])
