In [14]:
import numpy as np
import torch

### 参考numpy.isnan/numpy.isinf
* 仅推荐torch中

In [15]:
arr1 = np.array([1, 0, 0, 4])
arr2 = np.array([3, 4, 0, 0])

result = arr1 / arr2
result = torch.tensor(result)
result

C:\Users\duanm\AppData\Local\Temp/ipykernel_10652/636390702.py:4: RuntimeWarning: divide by zero encountered in true_divide
  result = arr1 / arr2
C:\Users\duanm\AppData\Local\Temp/ipykernel_10652/636390702.py:4: RuntimeWarning: invalid value encountered in true_divide
  result = arr1 / arr2


tensor([0.3333, 0.0000,    nan,    inf], dtype=torch.float64)

In [16]:
print(result[2])  # 单个值

print(torch.isnan(result[2]))
print(torch.isnan(result))

tensor(nan, dtype=torch.float64)
tensor(True)
tensor([False, False,  True, False])


In [17]:
print(result[3])  # 单个值
print(torch.isinf(result[3]))
print(torch.isinf(result))

tensor(inf, dtype=torch.float64)
tensor(True)
tensor([False, False, False,  True])
