In [11]:
import torch
import numpy as np

### 参考ndarray的储存结构.ipynb
### 参考array的修改与共享内存.ipynb

In [12]:
tor = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8])
print(id(tor))

a = tor[4]  # 注意:此处a为标量tensor,故a为可变数据类型
print(np.shares_memory(a, tor))  # a与arr共享数据的物理地址
a += 100  # 可变的类型的追加操作

print(id(tor))  # arr指向的地址不变
print(tor)  # 由于共享数据的物理地址,故arr指向内存的值也发生相应的改变

2270094182464
True
2270094182464
tensor([  1,   2,   3,   4, 105,   6,   7,   8])


In [13]:
a = torch.arange(30)
b = a.reshape(5, 6)

print(a)
print(b, end='\n\n')

print(id(a))
print(id(b), end='\n\n')  # a,b指向的地址不同

# ★★★★★★★★★★★★★★★shape操作共享内存
print(np.shares_memory(a, b), end='\n\n')  # b与a共享数据的物理地址

a[0] = 1000000  # 修改a
print(id(a))
print(a)  # a指向的地址不变
print(b, end='\n\n')  # 由于共享数据的物理地址,故b指向内存的值相应位置也发生改变

b[-1][-1] = 99999999  # 修改b

print(b)
print(a)  # 同理

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29]])

2270094184320
2270094184192

True

2270094184320
tensor([1000000,       1,       2,       3,       4,       5,       6,       7,
              8,       9,      10,      11,      12,      13,      14,      15,
             16,      17,      18,      19,      20,      21,      22,      23,
             24,      25,      26,      27,      28,      29])
tensor([[1000000,       1,       2,       3,       4,       5],
        [      6,       7,       8,       9,      10,      11],
        [     12,      13,      14,      15,      16,      17],
        [     18,      19,      20,      21,      22,      23],
        [     24,      25,      26,      27,      28,      29]])

tensor([[ 1000000

In [14]:
c = a.detach()

# ★★★★★★★★★★★★★★★detach操作共享内存
np.shares_memory(b, c)

True

In [15]:
d = a.clone()

# ★★★★★★★★★★★★★★★clone操作不共享内存★★★★
np.shares_memory(b, d)

False

In [16]:
e = a.flatten()

# ★★★★★★★★★★★★★★★flatten操作共享内存
np.shares_memory(b, e)

True

In [17]:
f = b.transpose(0, 1)

# ★★★★★★★★★★★★★★★transpose操作共享内存
np.shares_memory(b, f)

True

In [18]:
g = b.permute(1, 0)  # b.T同理

# ★★★★★★★★★★★★★★★permute操作共享内存
np.shares_memory(b, g)

True

In [19]:
h = torch.unsqueeze(b, 0)

# ★★★★★★★★★★★★★★★unsqueeze操作共享内存
np.shares_memory(b, h)

True

In [20]:
j = torch.squeeze(h)

# ★★★★★★★★★★★★★★★squeeze操作共享内存
np.shares_memory(h, j)




True