In [11]:
import torch

In [12]:
a = torch.randn(3, 3)
a

tensor([[ 1.5874,  0.4528,  0.5982],
        [-0.8503, -0.0910, -0.4134],
        [-0.9635, -0.4566, -0.0203]])

In [13]:
torch.tril(a)

tensor([[ 1.5874,  0.0000,  0.0000],
        [-0.8503, -0.0910,  0.0000],
        [-0.9635, -0.4566, -0.0203]])

In [14]:
b = torch.randn(4, 6)
b

tensor([[-1.2274,  0.2578,  0.9099, -0.3158,  1.1616, -1.4595],
        [-0.9839,  0.5062,  0.3704,  1.1052,  0.3075,  0.4253],
        [ 0.3074,  0.5135, -1.0224,  1.1606, -0.3370,  1.5241],
        [ 0.2456,  0.1387,  0.3884, -0.4349, -0.4148, -1.2779]])

In [15]:
torch.tril(b)

tensor([[-1.2274,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [-0.9839,  0.5062,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.3074,  0.5135, -1.0224,  0.0000,  0.0000,  0.0000],
        [ 0.2456,  0.1387,  0.3884, -0.4349,  0.0000,  0.0000]])

In [16]:
# diagonal (int, optional) – the diagonal to consider
torch.tril(b, diagonal=1)  # 默认diagonal=0

tensor([[-1.2274,  0.2578,  0.0000,  0.0000,  0.0000,  0.0000],
        [-0.9839,  0.5062,  0.3704,  0.0000,  0.0000,  0.0000],
        [ 0.3074,  0.5135, -1.0224,  1.1606,  0.0000,  0.0000],
        [ 0.2456,  0.1387,  0.3884, -0.4349, -0.4148,  0.0000]])

In [17]:
torch.tril(b, diagonal=-1)

tensor([[ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [-0.9839,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.3074,  0.5135,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.2456,  0.1387,  0.3884,  0.0000,  0.0000,  0.0000]])