In [1]:
import torch

In [2]:
tor = torch.tensor([[5, 5, 2, 2, 3, 3],
                    [3, 3, 4, 4, 5, 5]])
tor

tensor([[5, 5, 2, 2, 3, 3],
        [3, 3, 4, 4, 5, 5]])

In [3]:
# 完全类似numpy.unique
torch.unique(tor)  # Returns the unique elements of the input tensor

tensor([2, 3, 4, 5])

In [4]:
torch.unique(tor, sorted=False)  # 默认sorted=True,即对返回值进行了排序

tensor([5, 2, 3, 4])

In [5]:
torch.unique(tor, return_counts=True)  # 返回唯一值和该唯一值出现的次数

(tensor([2, 3, 4, 5]), tensor([2, 4, 2, 4]))

In [6]:
torch.unique(tor, dim=0)

tensor([[3, 3, 4, 4, 5, 5],
        [5, 5, 2, 2, 3, 3]])

In [7]:
torch.unique(tor, dim=1)

tensor([[2, 3, 5],
        [4, 5, 3]])

In [8]:
torch.unique(tor, dim=0)

tensor([[3, 3, 4, 4, 5, 5],
        [5, 5, 2, 2, 3, 3]])