In [9]:
import torch

In [10]:
tor = torch.tensor([[5, 5, 2, 2, 3, 3],
                    [3, 3, 4, 4, 5, 5]])
tor

tensor([[5, 5, 2, 2, 3, 3],
        [3, 3, 4, 4, 5, 5]])

### 参考numpy.unique

In [11]:
torch.unique(tor)  # Returns the unique elements of the input tensor

tensor([2, 3, 4, 5])

In [12]:
torch.unique(tor, sorted=False)  # 默认sorted=True,即对返回值进行了排序

tensor([5, 2, 3, 4])

In [13]:
torch.unique(tor, return_counts=True)  # 返回唯一值和唯一值出现的次数

(tensor([2, 3, 4, 5]), tensor([2, 4, 2, 4]))

In [14]:
torch.unique(tor, dim=0)

tensor([[3, 3, 4, 4, 5, 5],
        [5, 5, 2, 2, 3, 3]])

In [15]:
torch.unique(tor, dim=1)

tensor([[2, 3, 5],
        [4, 5, 3]])

In [16]:
torch.unique(tor, dim=0)

tensor([[3, 3, 4, 4, 5, 5],
        [5, 5, 2, 2, 3, 3]])