In [86]:
import torch

In [87]:
init = torch.arange(3, dtype=torch.float32, requires_grad=True).reshape(3, 1)
init

tensor([[0.],
        [1.],
        [2.]], grad_fn=<ViewBackward>)

In [88]:
init_co = torch.empty((3, 5))
init_co

tensor([[0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1.],
        [2., 2., 2., 2., 2.]])

In [89]:
init_co.copy_(init) # 将 数据从init复制到init_co(支持广播机制)
init_co # int_co没有脱离计算图

tensor([[0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1.],
        [2., 2., 2., 2., 2.]], grad_fn=<CopyBackwards>)

In [90]:
init_co.fill_(-1)
init_co

tensor([[-1., -1., -1., -1., -1.],
        [-1., -1., -1., -1., -1.],
        [-1., -1., -1., -1., -1.]], grad_fn=<FillBackward0>)

In [91]:
init # init_co不与init共享内存

tensor([[0.],
        [1.],
        [2.]], grad_fn=<ViewBackward>)

In [92]:
init_co_data = torch.empty((3, 5))
init_co_data.data.copy_(init)
init_co_data

tensor([[0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1.],
        [2., 2., 2., 2., 2.]])

In [93]:
init_co_data.fill_(-1)
print(init_co_data)
print(init) # 此时既脱离了计算图又不共享内存

tensor([[-1., -1., -1., -1., -1.],
        [-1., -1., -1., -1., -1.],
        [-1., -1., -1., -1., -1.]])
tensor([[0.],
        [1.],
        [2.]], grad_fn=<ViewBackward>)


In [94]:
init_co_detach = torch.empty((3, 5))
init_co_detach.detach().copy_(init)
init_co_detach

tensor([[0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1.],
        [2., 2., 2., 2., 2.]])

In [95]:
init_co_detach.fill_(-1)
print(init_co_detach)
print(init) # 此时既脱离了计算图又不共享内存


tensor([[-1., -1., -1., -1., -1.],
        [-1., -1., -1., -1., -1.],
        [-1., -1., -1., -1., -1.]])
tensor([[0.],
        [1.],
        [2.]], grad_fn=<ViewBackward>)
