In [1]:
import torch

In [2]:
init = torch.arange(3, dtype=torch.float32, requires_grad=True).reshape(3, 1)
init

tensor([[0.],
        [1.],
        [2.]], grad_fn=<ViewBackward>)

In [3]:
init_co = torch.empty((3, 5))
init_co

tensor([[3.2483e+33, 1.9690e-19, 6.8589e+22, 1.3340e+31, 1.1708e-19],
        [7.2128e+22, 9.2216e+29, 7.5546e+31, 1.6932e+22, 3.0728e+32],
        [2.9514e+29, 2.8940e+12, 7.5338e+28, 1.8037e+28, 3.4740e-12]])

In [4]:
init_co.copy_(init)  # 将 数据从init复制到init_co(支持广播机制)
init_co  # int_co没有脱离计算图

tensor([[0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1.],
        [2., 2., 2., 2., 2.]], grad_fn=<CopyBackwards>)

In [5]:
init_co.fill_(-1)
init_co

tensor([[-1., -1., -1., -1., -1.],
        [-1., -1., -1., -1., -1.],
        [-1., -1., -1., -1., -1.]], grad_fn=<FillBackward0>)

In [6]:
init  # init_co不与init共享内存

tensor([[0.],
        [1.],
        [2.]], grad_fn=<ViewBackward>)

In [7]:
init_co_data = torch.empty((3, 5))
init_co_data.data.copy_(init)
init_co_data

tensor([[0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1.],
        [2., 2., 2., 2., 2.]])

In [8]:
init_co_data.fill_(-1)
print(init_co_data)
print(init)  # 此时既脱离了计算图又不共享内存

tensor([[-1., -1., -1., -1., -1.],
        [-1., -1., -1., -1., -1.],
        [-1., -1., -1., -1., -1.]])
tensor([[0.],
        [1.],
        [2.]], grad_fn=<ViewBackward>)


In [9]:
init_co_detach = torch.empty((3, 5))
init_co_detach.detach().copy_(init)
init_co_detach

tensor([[0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1.],
        [2., 2., 2., 2., 2.]])

In [10]:
init_co_detach.fill_(-1)
print(init_co_detach)
print(init)  # 此时既脱离了计算图又不共享内存


tensor([[-1., -1., -1., -1., -1.],
        [-1., -1., -1., -1., -1.],
        [-1., -1., -1., -1., -1.]])
tensor([[0.],
        [1.],
        [2.]], grad_fn=<ViewBackward>)
