### fill_
### masked_fill_
### zero_
### uniform_

In [1]:
import torch

a = torch.empty((3, 5))
a

tensor([[3.8082e-22, 6.8103e-43, 3.8082e-22, 6.8103e-43, 3.8087e-22],
        [6.8103e-43, 3.8087e-22, 6.8103e-43, 3.8082e-22, 6.8103e-43],
        [3.8082e-22, 6.8103e-43, 3.8082e-22, 6.8103e-43, 3.8082e-22]])

In [2]:
a.fill_(1)  # Fills self tensor with the specified value;In-place操作
a

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [3]:
mask0 = torch.tensor([[False, False, False, False, False],
                      [False, False, True, True, True],
                      [False, False, False, True, True]])
# Fills elements of self tensor with value where mask is True. The shape of mask must be broadcastable with the shape of the underlying tensor.
a.masked_fill_(mask0, 1e-8)
a

tensor([[1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00],
        [1.0000e+00, 1.0000e+00, 1.0000e-08, 1.0000e-08, 1.0000e-08],
        [1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e-08, 1.0000e-08]])

In [4]:
mask1 = torch.tensor([False, False, True, True, True])
a.masked_fill_(mask1, 0)  # 广播
a

tensor([[1., 1., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 0., 0., 0.]])

In [5]:
a.zero_()  #  # Fills self tensor with zeros;In-place操作
a

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

Fills self tensor with numbers sampled from the continuous uniform distribution:

$$ P(x) = \frac{1}{b - a}  $$

In [6]:
a.uniform_(2, 5)  # a=2,b=5
a

tensor([[3.3319, 4.6334, 4.3459, 2.2546, 2.9937],
        [4.3053, 4.4214, 4.1058, 3.5995, 3.7349],
        [4.4602, 3.0060, 2.4232, 4.3268, 4.2459]])

In [7]:
a.normal_(mean=0,
          std=4)  # Fills self tensor with elements samples from the normal distribution parameterized by mean and std.
a

tensor([[-3.0181, -2.4499, -3.3872,  6.1321,  2.4567],
        [ 3.8245,  6.0539,  1.6670, -3.8510,  0.3449],
        [ 4.0506,  6.9538, -6.1005, -4.2823,  0.8628]])