### fill_
### masked_fill_
### zero_
### uniform_
### index_add_

In [160]:
import torch

a = torch.empty((3, 5))
a

tensor([[-1.9397e-26,  2.1076e-42,  2.0000e+00,  1.0000e+02,  1.0000e+02],
        [ 1.0000e+02,  1.1000e+01,  1.1000e+01,  1.1000e+01,  1.0000e+00],
        [ 1.0000e+00,  1.0000e+00, -1.0000e+00, -1.0000e+00, -1.0000e+00]])

In [161]:
a.fill_(1)  # Fills self tensor with the specified value;In-place操作
a

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [162]:
mask0 = torch.tensor([[False, False, False, False, False],
                      [False, False, True, True, True],
                      [False, False, False, True, True]])
# Fills elements of self tensor with value where mask is True. The shape of mask must be broadcastable with the shape of the underlying tensor.
a.masked_fill_(mask0, 1e-8)
a

tensor([[1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00],
        [1.0000e+00, 1.0000e+00, 1.0000e-08, 1.0000e-08, 1.0000e-08],
        [1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e-08, 1.0000e-08]])

In [163]:
mask1 = torch.tensor([False, False, True, True, True])
a.masked_fill_(mask1, 0)  # 广播
a

tensor([[1., 1., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 0., 0., 0.]])

In [164]:
a.zero_()  #  # Fills self tensor with zeros;In-place操作
a

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

Fills self tensor with numbers sampled from the continuous uniform distribution:

$$ P(x) = \frac{1}{b - a}  $$

In [165]:
a.uniform_(2, 5)  # a=2,b=5
a

tensor([[4.8874, 3.8867, 3.7503, 2.7523, 3.5886],
        [2.6227, 2.8578, 4.1125, 3.4638, 2.6060],
        [3.8373, 4.0988, 2.4403, 2.1240, 3.2076]])

In [166]:
a.normal_(mean=0,
          std=4)  # Fills self tensor with elements samples from the normal distribution parameterized by mean and std.
a

tensor([[ 2.9686, -2.3692,  1.1616,  0.7111, -4.8221],
        [ 0.1042, -6.4417,  2.7110, -4.0927, -2.2211],
        [ 4.1143,  0.4843, -1.3862, -7.2945,  0.1106]])

In [167]:
x = torch.ones(5, 3)
t0 = torch.tensor([[1, 1, 1],
                  [-1, -1, -1],
                  [10, 10, 10]], dtype=torch.float)
index0 = torch.tensor([0, 4, 2])
# x.shape=(5, 3)
# index0.shape=(3, )
# t0.shape=(3, 3)
x.index_add_(dim=0, index=index0, source=t0)
print(x)

t1 = torch.tensor([[99, 99, 99],
                  [-1, -1, -1]], dtype=torch.float)
index1 = torch.tensor([1, 4])
# x.shape=(5, 3)
# index0.shape=(2, )
# t0.shape=(2, 3)
x.index_add_(dim=0, index=index1, source=t1)
print(x)

tensor([[ 2.,  2.,  2.],
        [ 1.,  1.,  1.],
        [11., 11., 11.],
        [ 1.,  1.,  1.],
        [ 0.,  0.,  0.]])
tensor([[  2.,   2.,   2.],
        [100., 100., 100.],
        [ 11.,  11.,  11.],
        [  1.,   1.,   1.],
        [ -1.,  -1.,  -1.]])
