### fill_
### masked_fill_
### zero_
### uniform_
### index_add_

In [44]:
import torch

a = torch.empty((3, 5))
a

tensor([[ 0.,  0.,  4.,  1.,  1.],
        [ 1.,  8.,  9., 10.,  1.],
        [ 1.,  1.,  5.,  6.,  7.]])

In [45]:
a.fill_(1)  # Fills self tensor with the specified value;In-place操作
a

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [46]:
mask0 = torch.tensor([[False, False, False, False, False],
                      [False, False, True, True, True],
                      [False, False, False, True, True]])
# Fills elements of self tensor with value where mask is True. The shape of mask must be broadcastable with the shape of the underlying tensor.
a.masked_fill_(mask0, 1e-8)
a

tensor([[1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00],
        [1.0000e+00, 1.0000e+00, 1.0000e-08, 1.0000e-08, 1.0000e-08],
        [1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e-08, 1.0000e-08]])

In [47]:
mask1 = torch.tensor([False, False, True, True, True])
a.masked_fill_(mask1, 0)  # 广播
a

tensor([[1., 1., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 0., 0., 0.]])

In [48]:
a.zero_()  #  # Fills self tensor with zeros;In-place操作
a

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

Fills self tensor with numbers sampled from the continuous uniform distribution:

$$ P(x) = \frac{1}{b - a}  $$

In [49]:
a.uniform_(2, 5)  # a=2,b=5
a

tensor([[3.5688, 2.4763, 2.2815, 2.0823, 4.7152],
        [2.3067, 3.4105, 4.6913, 3.5693, 3.2589],
        [3.9334, 2.2533, 3.6848, 4.7566, 3.7172]])

In [50]:
a.normal_(mean=0,
          std=4)  # Fills self tensor with elements samples from the normal distribution parameterized by mean and std.
a

tensor([[ -2.2059,   1.6760,  -4.1791,   8.7827, -10.0114],
        [  2.4399,  -2.2960,   2.6738,  -6.0702,   1.1659],
        [ -2.0024,   4.3747,   4.2092,   2.6275,  -0.9184]])

In [51]:
x = torch.ones(5, 3)
t = torch.tensor([[1, 2, 3], 
                  [4, 5, 6], 
                  [7, 8, 9]], dtype=torch.float)
index = torch.tensor([0, 4, 2])
x.index_add_(0, index, t)
print(x)

tensor([[ 2.,  3.,  4.],
        [ 1.,  1.,  1.],
        [ 8.,  9., 10.],
        [ 1.,  1.,  1.],
        [ 5.,  6.,  7.]])
