### fill_
### masked_fill_
### zero_
### uniform_

In [39]:
import torch

a = torch.empty((3, 5))
a

tensor([[9.2755e-39, 1.0561e-38, 9.1837e-39, 9.1837e-39, 1.0010e-38],
        [4.2246e-39, 1.0286e-38, 1.0653e-38, 1.0194e-38, 8.4490e-39],
        [1.0469e-38, 9.3674e-39, 9.9184e-39, 8.7245e-39, 9.2755e-39]])

In [40]:
a.fill_(1)  # Fills self tensor with the specified value;In-place操作
a

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [41]:
mask0 = torch.tensor([[False, False, False, False, False],
                      [False, False, True, True, True],
                      [False, False, False, True, True]])
# Fills elements of self tensor with value where mask is True. The shape of mask must be broadcastable with the shape of the underlying tensor.
a.masked_fill_(mask0, 1e-8)
a

tensor([[1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00],
        [1.0000e+00, 1.0000e+00, 1.0000e-08, 1.0000e-08, 1.0000e-08],
        [1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e-08, 1.0000e-08]])

In [42]:
mask1 = torch.tensor([False, False, True, True, True])
a.masked_fill_(mask1, 0)  # 广播
a

tensor([[1., 1., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 0., 0., 0.]])

In [43]:
a.zero_()  #  # Fills self tensor with zeros;In-place操作
a

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

Fills self tensor with numbers sampled from the continuous uniform distribution:

$$ P(x) = \frac{1}{b - a}  $$

In [44]:
a.uniform_(2, 5)  # a=2,b=5
a

tensor([[3.3084, 3.9221, 3.8935, 2.8921, 3.3545],
        [2.2166, 3.9286, 2.6818, 2.8462, 4.9311],
        [3.7981, 3.1473, 2.6065, 2.2692, 4.5232]])

In [45]:
a.normal_(mean=0,
          std=4)  # Fills self tensor with elements samples from the normal distribution parameterized by mean and std.
a

tensor([[ 2.5158,  1.2573, -0.0987,  5.8583,  6.1957],
        [ 0.5122,  4.4833,  9.9761, -1.7671,  3.4772],
        [-3.3233, -0.0557, -5.1338,  8.0115,  3.2196]])