### fill_
### zero_
### uniform_

In [1]:
import torch

a = torch.empty((3, 5))
a

tensor([[1.0010e-38, 8.9082e-39, 8.9082e-39, 1.0194e-38, 9.1837e-39],
        [4.6837e-39, 9.9184e-39, 9.0000e-39, 1.0561e-38, 1.0653e-38],
        [4.1327e-39, 8.9082e-39, 9.8265e-39, 9.4592e-39, 1.0561e-38]])

In [2]:
a.fill_(1)  # Fills self tensor with the specified value;In-place操作
a

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [3]:
a.zero_()  #  # Fills self tensor with zeros;In-place操作
a

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

Fills self tensor with numbers sampled from the continuous uniform distribution:

$$ P(x) = \frac{1}{b - a}  $$

In [4]:
a.uniform_(2, 5)  # a=2,b=5
a

tensor([[3.2896, 4.7666, 3.1572, 3.0192, 2.3778],
        [4.5013, 4.4706, 2.1739, 4.3130, 3.7745],
        [2.4864, 4.4029, 4.7385, 4.6473, 2.4676]])

In [5]:
a.normal_(mean=0,
          std=4)  # Fills self tensor with elements samples from the normal distribution parameterized by mean and std.
a

tensor([[ -1.3282,   2.7844,   4.1562,   3.8488,  -5.3043],
        [  7.5565,   3.0251,  -2.1426,   2.4927,   3.9672],
        [ -0.9524,   1.1364,   3.7419,  -5.6225, -10.1247]])