In [738]:
import torch
import torch.nn.functional as F

### 参考numpy.pad

In [739]:
a = torch.tensor([1, 2, 3, 4, 5])
F.pad(a,
      pad=(2, 3),  # 填充到每个轴边缘的数量
      mode='constant',  # 使用常数进行填充
      value=0)  # 填充的值(默认为0)

tensor([0, 0, 1, 2, 3, 4, 5, 0, 0, 0])

In [740]:
b = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])
b_pad = F.pad(b, (1, 2), 'constant', 0)
print(b_pad.shape)
print(b_pad, end='\n\n')

# 维度0每个向量左边填充数量为1,右边填充数量为2(即维度1shape=3+1+1=5)
print(b_pad[0, :])
print(b_pad[1, :])

torch.Size([2, 6])
tensor([[0, 1, 2, 3, 0, 0],
        [0, 4, 5, 6, 0, 0]])

tensor([0, 1, 2, 3, 0, 0])
tensor([0, 4, 5, 6, 0, 0])


In [741]:
b1 = torch.tensor([[1, 2, 3],
                   [4, 5, 6]])
b1_pad = F.pad(b, (1, 2, 3, 2), 'constant', 0)
print(b1_pad.shape)
print(b1_pad)

torch.Size([7, 6])
tensor([[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 1, 2, 3, 0, 0],
        [0, 4, 5, 6, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]])


In [742]:
# 维度0每个向量左边填充数量为1,右边填充数量为2(即维度1.shape=3+1+2=6)
print(b1_pad[3, :])
print(b1_pad[4, :])
print(b1_pad[5, :])

tensor([0, 1, 2, 3, 0, 0])
tensor([0, 4, 5, 6, 0, 0])
tensor([0, 0, 0, 0, 0, 0])


In [743]:
# 维度1每个向量左边填充数量为3,右边填充数量为2(即维度0.shape=2+3+2=7)
print(b1_pad[:, 1])
print(b1_pad[:, 2])
print(b1_pad[:, 3])

tensor([0, 0, 0, 1, 4, 0, 0])
tensor([0, 0, 0, 2, 5, 0, 0])
tensor([0, 0, 0, 3, 6, 0, 0])


In [744]:
b3 = torch.arange(1, 121).reshape(2, 3, 4, 5)
b3_pad = F.pad(b3, (3, 1, 5, 2, 1, 1, 2, 3), 'constant', 0)
# 原始维度信息: 2(0), 3(1), 4(2), 5(3)
# 增加维度信息: 5(3), 2(2), 7(1), 4(0)   5=2+3,2=1+1,7=5+2,4=3+1
b3_pad.shape

torch.Size([7, 5, 11, 9])

In [745]:
# 维度0每个向量左边填充数量为3,右边填充数量为1(即维度3.shape=5+3+1=9)
print(b3_pad[2, 2, 5, :])
print(b3_pad[2, 2, 6, :])

tensor([ 0,  0,  0, 21, 22, 23, 24, 25,  0])
tensor([ 0,  0,  0, 26, 27, 28, 29, 30,  0])


In [746]:
# 维度1每个向量左边填充数量为5,右边填充数量为2(即维度2.shape=4+5+2)
print(b3_pad[2, 2, :, 3])
print(b3_pad[2, 2, :, 4])

tensor([ 0,  0,  0,  0,  0, 21, 26, 31, 36,  0,  0])
tensor([ 0,  0,  0,  0,  0, 22, 27, 32, 37,  0,  0])


In [747]:
# 维度2每个向量左边填充数量为1,右边填充数量为1(即维度1.shape=3+1+1)
print(b3_pad[3, :, 7, 4])
print(b3_pad[3, :, 7, 5])

tensor([  0,  72,  92, 112,   0])
tensor([  0,  73,  93, 113,   0])


In [748]:
# 维度3每个向量左边填充数量为2,右边填充数量为3(即维度1.shape=2+2+3)
print(b3_pad[:, 3, 7, 4])
print(b3_pad[:, 3, 7, 5])

tensor([  0,   0,  52, 112,   0,   0,   0])
tensor([  0,   0,  53, 113,   0,   0,   0])
