In [16]:
import torch
import torch.nn.functional as F

### 参考numpy.pad

In [17]:
a = torch.tensor([1, 2, 3, 4, 5])
F.pad(a,
      pad=(2, 3),  # 填充到每个轴边缘的数量
      mode='constant',  # 使用常数进行填充
      value=0)  # 填充的值(默认为0)

tensor([0, 0, 1, 2, 3, 4, 5, 0, 0, 0])

In [18]:
# 第一个维度左边填充数量为1,右边填充数量为2
b = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])
F.pad(b, (1, 2), 'constant', 0)

tensor([[0, 1, 2, 3, 0, 0],
        [0, 4, 5, 6, 0, 0]])

In [19]:
# 第一个维度左边填充数量为1,右边填充数量为2
# 第二个维度左边填充数量为3,右边填充数量为2
b = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])
F.pad(b, (1, 2, 3, 2), 'constant', 0)

tensor([[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 1, 2, 3, 0, 0],
        [0, 4, 5, 6, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]])