In [26]:
import torch

# 基本类似numpy.argsort
x = torch.tensor([3, 1, 2])
torch.argsort(x) # Returns the indices that would sort an array.

tensor([1, 2, 0])

In [27]:
x = torch.tensor([[0, 3],
                  [2, 2]])
torch.argsort(x) # 默认dim=-1

tensor([[0, 1],
        [0, 1]])

In [28]:
torch.argsort(x, dim=0)

tensor([[0, 1],
        [1, 0]])

In [29]:
torch.sort(x, dim=0, descending=True)

torch.return_types.sort(
values=tensor([[2, 3],
        [0, 2]]),
indices=tensor([[1, 0],
        [0, 1]]))

In [30]:
torch.argsort(x, dim=0, descending=True) # 降序排列(sort函数的indices部分)

tensor([[1, 0],
        [0, 1]])