In [1]:
import torch

In [2]:
# 类似numpy.sort
x, y = torch.sort(torch.tensor([2, 4, 3, 1]))  # 默认dim=-1
print(x)  # 排序后的tensor
print(y)  # 排序后的tensor在原有tensor上的索引(如:1在原有tensor上的索引为3)

tensor([1, 2, 3, 4])
tensor([3, 0, 2, 1])


In [3]:
a = torch.tensor([[4, 2],
                  [5, 7],
                  [3, 7],
                  [2, 6],
                  [7, 4],
                  [1, 9]])
a

tensor([[4, 2],
        [5, 7],
        [3, 7],
        [2, 6],
        [7, 4],
        [1, 9]])

In [4]:
sort_result = torch.sort(a)
print(sort_result, end='\n\n')
print(sort_result.values, end='\n\n')
print(sort_result.indices)

torch.return_types.sort(
values=tensor([[2, 4],
        [5, 7],
        [3, 7],
        [2, 6],
        [4, 7],
        [1, 9]]),
indices=tensor([[1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1]]))

tensor([[2, 4],
        [5, 7],
        [3, 7],
        [2, 6],
        [4, 7],
        [1, 9]])

tensor([[1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1]])


In [5]:
torch.sort(a, dim=0)

torch.return_types.sort(
values=tensor([[1, 2],
        [2, 4],
        [3, 6],
        [4, 7],
        [5, 7],
        [7, 9]]),
indices=tensor([[5, 0],
        [3, 4],
        [2, 3],
        [0, 1],
        [1, 2],
        [4, 5]]))

In [6]:
torch.sort(a, dim=0, descending=True)  # 降序排列

torch.return_types.sort(
values=tensor([[7, 9],
        [5, 7],
        [4, 7],
        [3, 6],
        [2, 4],
        [1, 2]]),
indices=tensor([[4, 5],
        [1, 1],
        [0, 2],
        [2, 3],
        [3, 4],
        [5, 0]]))

In [7]:
a[torch.argsort(a[:, 0])]  # 只排序0维度的第一组数据(该维度元素对应关系不变)

tensor([[1, 9],
        [2, 6],
        [3, 7],
        [4, 2],
        [5, 7],
        [7, 4]])