In [23]:
import torch

### 参考numpy.isin

In [24]:
a = torch.tensor([[1, 2],
                  [3, 4]])
b = torch.tensor([2, 3])
mask = torch.isin(elements=a, test_elements=b)
mask

tensor([[False,  True],
        [ True, False]])

In [25]:
a[mask]  # element,test_elements共用的元素为2, 3

tensor([2, 3])

In [26]:
torch.nonzero(mask)  # 返回非零元素的索引

tensor([[0, 1],
        [1, 0]])

In [27]:
# invert (bool, optional) –
#   If True, inverts the boolean return tensor, resulting in True values for elements not in test_elements. Default: False
mask_invert = torch.isin(a, b, invert=True)
mask_invert

tensor([[ True, False],
        [False,  True]])

In [28]:
a[mask_invert]

tensor([1, 4])