In [19]:
import torch
import torch.nn.functional as F

独热编码的缺点:
1. 太稀疏.这个问题在单词表中单词数目比较小的情况下不会引起问题,当单词数目比较大的时候,由于编码的大多数值为0,就会造成存储空间的浪费.
2. 在独热编码的条件下,两个单词之间的关系是正交的,也就是任意两个不同的单词,其内积为0,这一点不利于寻找单词之间的相似性.

In [20]:
'''
num_classes (int):  Total number of classes. If set to -1, the number
        of classes will be inferred as one greater than the largest class
        value in the input tensor.
'''
F.one_hot(torch.arange(0, 5),
          num_classes=-1)  # 类别数量

tensor([[1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1]])

In [21]:
F.one_hot(torch.arange(0, 5),
          num_classes=8)  # 超过最大类别部分全为0

tensor([[1, 0, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 1, 0, 0, 0]])

In [22]:
a = F.one_hot(torch.arange(12).reshape(3, 4),
          num_classes=-1)
a

tensor([[[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]]])

In [23]:
a.shape

torch.Size([3, 4, 12])