In [171]:
import torch


x = torch.tensor([[3, 0, 0],
                  [0, 4, 0],
                  [5, 6, 0]])
x

tensor([[3, 0, 0],
        [0, 4, 0],
        [5, 6, 0]])

In [172]:
# 完全类似numpy.nonzero
result = torch.nonzero(x, as_tuple=True) # 返回非零元素的索引
result

(tensor([0, 1, 2, 2]), tensor([0, 1, 0, 1]))

In [173]:
torch.cat((result[0].unsqueeze(0).T, result[1].unsqueeze(0).T), 1)

tensor([[0, 0],
        [1, 1],
        [2, 0],
        [2, 1]])

In [174]:
torch.nonzero(x, as_tuple=False) # 于上等价;默认as_tuple=False

tensor([[0, 0],
        [1, 1],
        [2, 0],
        [2, 1]])

In [175]:
x[torch.nonzero(x, as_tuple=True)] # x中所有的非零元素

tensor([3, 4, 5, 6])

In [176]:
x[x != 0] # 于上等价

tensor([3, 4, 5, 6])

In [177]:
a = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a > 3

tensor([[False, False, False],
        [ True,  True,  True],
        [ True,  True,  True]])

In [178]:
torch.nonzero(a > 3, as_tuple=True)

(tensor([1, 1, 1, 2, 2, 2]), tensor([0, 1, 2, 0, 1, 2]))

In [179]:
a[torch.nonzero(a > 3, as_tuple=True)]

tensor([4, 5, 6, 7, 8, 9])

In [180]:
a[a > 3] # 布尔索引(与上等价)

tensor([4, 5, 6, 7, 8, 9])