In [1]:
import tensorflow as tf

### 二元交叉熵损失函数
### 参考torch.BCELoss===>对应from_logits=False
### 参考torch.BCEWithLogitsLoss===>对应from_logits=True

In [2]:
y_pred = tf.constant([[0.5, 0.4, 0.3],
                      [0.3, 0.2, 0.5]])
y_true = tf.constant([[0., 1., 0.],
                      [1., 0., 0.]])

In [3]:
'''
from_logits: Whether to interpret y_pred as a tensor of logit values.
             By default, we assume that y_pred contains probabilities (i.e., values in [0, 1]).
'''
bce = tf.keras.losses.BinaryCrossentropy(from_logits=False,
                                         # 默认,参考MeanSquaredError
                                         reduction=tf.keras.losses.Reduction.SUM_OVER_BATCH_SIZE,
                                         name='binary_crossentropy')

print(bce.name)
tf.print(bce(y_true, y_pred,
             # 批次样本权重,参考MeanSquaredError
             sample_weight=None))

binary_crossentropy
0.68106246


In [4]:
bce = tf.keras.losses.BinaryCrossentropy(from_logits=True)  # 默认freom_logits=True
bce(y_true, y_pred).numpy()

0.7780031

In [5]:
result = -(y_true * tf.math.log(y_pred) + (1 - y_true) * tf.math.log(1 - y_pred))
result

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.6931472 , 0.9162907 , 0.35667497],
       [1.2039728 , 0.22314353, 0.6931472 ]], dtype=float32)>

In [6]:
'''
默认reduction=losses_utils.ReductionV2.AUTO;参考torch中reduction='mean'
AUTO: Indicates that the reduction option will be determined by the usage context. For almost all cases this defaults to SUM_OVER_BATCH_SIZE
NONE: No additional reduction is applied to the output of the wrapped loss function.
SUM: Scalar sum of weighted losses
SUM_OVER_BATCH_SIZE: Scalar SUM divided by number of elements in losses(即均值)
'''
print(tf.math.reduce_sum(result) / 3)
print(tf.keras.losses.BinaryCrossentropy(from_logits=False,
                                         # 默认reduction=tf.keras.losses.Reduction.SUM_OVER_BATCH_SIZE
                                         reduction=tf.keras.losses.Reduction.SUM)(y_true,
                                                                                  y_pred))  # 与上等价;参考torch中reduction='sum'

tf.Tensor(1.3621254, shape=(), dtype=float32)
tf.Tensor(1.3621249, shape=(), dtype=float32)


In [7]:
print(tf.math.reduce_mean(result, axis=1))
print(tf.keras.losses.BinaryCrossentropy(from_logits=False,
                                         reduction=tf.keras.losses.Reduction.NONE)(y_true,
                                                                                   y_pred))  # 与上等价;参考torch中reduction='none'

tf.Tensor([0.65537095 0.7067545 ], shape=(2,), dtype=float32)
tf.Tensor([0.6553708 0.7067542], shape=(2,), dtype=float32)
