In [55]:
import tensorflow as tf

### 多分类交叉熵损失函数
### 参考nn.CrossEntropyLoss===>对应from_logits=True

In [56]:
y_pred = tf.reshape(tf.range(12, dtype=tf.float32), (4, 3))
y_pred

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]], dtype=float32)>

In [57]:
y_true_scc = tf.constant([1, 2, 1, 2])
y_true_scc

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 1, 2])>

In [58]:
'''
from_logits:    Whether y_pred is expected to be a logits tensor.
                By default, we assume that y_pred encodes a probability distribution.
'''
scc = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True,  # Recommended Usage: (set from_logits=True)
                                                    # 默认reduction=tf.keras.losses.Reduction.SUM_OVER_BATCH_SIZE,参考BinaryCrossentropy
                                                    reduction=tf.keras.losses.Reduction.NONE,
                                                    name='sparse_categorical_crossentropy')
print(scc.name)
tf.print(scc(y_true=y_true_scc,  # ★★★★★要求:整数向量(最小值为0,最大值为y_pred.shape[1]-1)
             y_pred=y_pred,
             # 批次样本权重,参考MeanSquaredError
             sample_weight=None))

sparse_categorical_crossentropy
[1.40760589 0.407605946 1.40760589 0.407605946]


In [59]:
y_true_cc = tf.one_hot(y_true_scc, depth=3)
y_true_cc

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [60]:
cc = tf.keras.losses.CategoricalCrossentropy(from_logits=True,  # Recommended Usage: (set from_logits=True)
                                             name='categorical_crossentropy')
print(cc.name)
tf.print(cc(y_true=y_true_cc,  # 要求:独热编码形式
            y_pred=y_pred,
            # 批次样本权重,参考MeanSquaredError
            sample_weight=None
            ))


categorical_crossentropy
0.907605886
