In [5]:
import torch
import torch.utils.data as Data

x = torch.linspace(0.01, 0.1, 25)
y = torch.linspace(1, 25, 25)
z = torch.arange(1000, 1025)

# 继承Dataset类
# 先将数据集x,y,z(必须为tensor)打包成元组
torch_dataset = Data.TensorDataset(x, y, z)
len(torch_dataset)  # 调用了__len__方法

25

In [6]:
torch_dataset.tensors

(tensor([0.0100, 0.0137, 0.0175, 0.0213, 0.0250, 0.0288, 0.0325, 0.0363, 0.0400,
         0.0437, 0.0475, 0.0512, 0.0550, 0.0587, 0.0625, 0.0662, 0.0700, 0.0738,
         0.0775, 0.0812, 0.0850, 0.0888, 0.0925, 0.0962, 0.1000]),
 tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
         15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.]),
 tensor([1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011,
         1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023,
         1024]))

In [7]:
'''
TensorDataset内部实现
def __getitem__(self, index):
    return tuple(tensor[index] for tensor in self.tensors)  # 第一个维度的索引
'''
for i in torch_dataset:
    print(i)  # 调用了__getitem__方法

(tensor(0.0100), tensor(1.), tensor(1000))
(tensor(0.0137), tensor(2.), tensor(1001))
(tensor(0.0175), tensor(3.), tensor(1002))
(tensor(0.0213), tensor(4.), tensor(1003))
(tensor(0.0250), tensor(5.), tensor(1004))
(tensor(0.0288), tensor(6.), tensor(1005))
(tensor(0.0325), tensor(7.), tensor(1006))
(tensor(0.0363), tensor(8.), tensor(1007))
(tensor(0.0400), tensor(9.), tensor(1008))
(tensor(0.0437), tensor(10.), tensor(1009))
(tensor(0.0475), tensor(11.), tensor(1010))
(tensor(0.0512), tensor(12.), tensor(1011))
(tensor(0.0550), tensor(13.), tensor(1012))
(tensor(0.0587), tensor(14.), tensor(1013))
(tensor(0.0625), tensor(15.), tensor(1014))
(tensor(0.0662), tensor(16.), tensor(1015))
(tensor(0.0700), tensor(17.), tensor(1016))
(tensor(0.0738), tensor(18.), tensor(1017))
(tensor(0.0775), tensor(19.), tensor(1018))
(tensor(0.0812), tensor(20.), tensor(1019))
(tensor(0.0850), tensor(21.), tensor(1020))
(tensor(0.0888), tensor(22.), tensor(1021))
(tensor(0.0925), tensor(23.), tensor(1022

In [8]:
torch_dataset[:7]  # x,y,z的前7组数据

(tensor([0.0100, 0.0137, 0.0175, 0.0213, 0.0250, 0.0288, 0.0325]),
 tensor([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1000, 1001, 1002, 1003, 1004, 1005, 1006]))

In [9]:
torch_dataset_x = Data.TensorDataset(x)

for i in torch_dataset_x:
    print(i)  # 单个数据集也被打包成元组


(tensor(0.0100),)
(tensor(0.0137),)
(tensor(0.0175),)
(tensor(0.0213),)
(tensor(0.0250),)
(tensor(0.0288),)
(tensor(0.0325),)
(tensor(0.0363),)
(tensor(0.0400),)
(tensor(0.0437),)
(tensor(0.0475),)
(tensor(0.0512),)
(tensor(0.0550),)
(tensor(0.0587),)
(tensor(0.0625),)
(tensor(0.0662),)
(tensor(0.0700),)
(tensor(0.0738),)
(tensor(0.0775),)
(tensor(0.0812),)
(tensor(0.0850),)
(tensor(0.0888),)
(tensor(0.0925),)
(tensor(0.0962),)
(tensor(0.1000),)
