In [1]:
import torch
import torch.utils.data as Data

x = torch.linspace(0.01, 0.1, 25)
y = torch.linspace(1, 25, 25)
z = torch.arange(1000, 1025)

torch_dataset = Data.TensorDataset(x, y, z) # 先将x,y,z打包成一个元组
len(torch_dataset) # 调用了__len__方法

25

In [2]:
for i in torch_dataset:
    print(i) # 调用了__getitem__方法;返回值为元组

(tensor(0.0100), tensor(1.), tensor(1000))
(tensor(0.0137), tensor(2.), tensor(1001))
(tensor(0.0175), tensor(3.), tensor(1002))
(tensor(0.0213), tensor(4.), tensor(1003))
(tensor(0.0250), tensor(5.), tensor(1004))
(tensor(0.0288), tensor(6.), tensor(1005))
(tensor(0.0325), tensor(7.), tensor(1006))
(tensor(0.0363), tensor(8.), tensor(1007))
(tensor(0.0400), tensor(9.), tensor(1008))
(tensor(0.0438), tensor(10.), tensor(1009))
(tensor(0.0475), tensor(11.), tensor(1010))
(tensor(0.0513), tensor(12.), tensor(1011))
(tensor(0.0550), tensor(13.), tensor(1012))
(tensor(0.0588), tensor(14.), tensor(1013))
(tensor(0.0625), tensor(15.), tensor(1014))
(tensor(0.0663), tensor(16.), tensor(1015))
(tensor(0.0700), tensor(17.), tensor(1016))
(tensor(0.0737), tensor(18.), tensor(1017))
(tensor(0.0775), tensor(19.), tensor(1018))
(tensor(0.0813), tensor(20.), tensor(1019))
(tensor(0.0850), tensor(21.), tensor(1020))
(tensor(0.0887), tensor(22.), tensor(1021))
(tensor(0.0925), tensor(23.), tensor(1022

In [3]:
torch_dataset[:7] # x,y,z的前7组数据

(tensor([0.0100, 0.0137, 0.0175, 0.0213, 0.0250, 0.0288, 0.0325]),
 tensor([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1000, 1001, 1002, 1003, 1004, 1005, 1006]))