In [1]:
import tensorflow as tf
import numpy as np

In [2]:
a = np.array([[1.2, 2, 3],
              [2, 3, 4]])
x = tf.constant(a, name='x')
x

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[1.2, 2. , 3. ],
       [2. , 3. , 4. ]])>

### 参考array相关属性

In [3]:
print(x.shape)  # TensorShape
print(tf.shape(x))  # tensor

(2, 3)
tf.Tensor([2 3], shape=(2,), dtype=int32)


In [4]:
print(tf.size(x))  # tensor

tf.Tensor(6, shape=(), dtype=int32)


In [5]:
# Returns the rank of a tensor.
print(tf.rank(x))  # tensor

# 变量没有该属性
print(x.ndim)  # int



tf.Tensor(2, shape=(), dtype=int32)
2
