In [1]:
import numpy as np
from sklearn.preprocessing import OrdinalEncoder

In [2]:
arr = np.array([-2.1, 1, 0, 2.5, 5.1, -2.1, 3.5, 0, 1
                - 5, -2.1, 0, 3.5, 2.5, 5.1, -1, -2.1]).reshape(-1, 1)
arr

array([[-2.1],
       [ 1. ],
       [ 0. ],
       [ 2.5],
       [ 5.1],
       [-2.1],
       [ 3.5],
       [ 0. ],
       [-4. ],
       [-2.1],
       [ 0. ],
       [ 3.5],
       [ 2.5],
       [ 5.1],
       [-1. ],
       [-2.1]])

In [3]:
enc = OrdinalEncoder()
arr_enc = enc.fit_transform(arr).astype(np.int_).reshape(-1, )
arr_enc

array([1, 4, 3, 5, 7, 1, 6, 3, 0, 1, 3, 6, 5, 7, 2, 1])

In [4]:
# Count number of occurrences of each value in array of non-negative ints.
freq = np.bincount(arr_enc)  # 要求:arr_enc.shape=(-1, ),arr_enc元素为非负整数
# 元素0的频率为1
# 元素1的频率为4
# 元素2的频率为1
# 元素3的频率为3
# 元素4的频率为1
# 元素5的频率为2
# 元素6的频率为2
# 元素7的频率为2
freq

array([1, 4, 1, 3, 1, 2, 2, 2], dtype=int64)

In [5]:
max_freq = np.argmax(freq)  # 频率最大的元素
max_freq

1

In [6]:
# Convert the data back to the original representation.
enc.inverse_transform(np.array([[max_freq]]))

array([[-2.1]])