In [75]:
import numpy as np

In [76]:
X = np.array([[1, 2, 3],
              [4, 5, 6]])
maxlen = X.shape[1]
valid_len = np.array([1, 2])

In [77]:
temp1 = np.arange(maxlen)[None, :]
temp1

array([[0, 1, 2]])

In [78]:
temp2 = valid_len[:, None]
temp2

array([[1],
       [2]])

In [79]:
# (1, 3) broadcasting (2, 1) --> (2, 3)
mask = temp1 < temp2
mask

array([[ True, False, False],
       [ True,  True, False]])

In [80]:
# 取反操作
X[~mask]

array([2, 3, 6])

In [81]:
X[~mask] = 0
X

array([[1, 0, 0],
       [4, 5, 0]])