In [1]:
import torch

In [2]:
generator_state = torch.Generator().manual_seed(4)

In [3]:
torch.randint(3, 8, size=(3, 4)) # 不包括末尾元素

tensor([[3, 3, 5, 7],
        [6, 4, 7, 4],
        [3, 5, 7, 5]])

In [4]:
idx = torch.randperm(3, generator=generator_state) # Returns a random permutation of integers from 0 to n - 1.
idx

tensor([1, 0, 2])

In [5]:
x1 = torch.tensor([[1, 1, 1], [2, 2, 2], [3, 3, 3]])
x2 = torch.tensor([[1.0, 1.0, 1.0], [2.0, 2.0, 2.0], [3.0, 3.0, 3.0]])
print(x1[idx])
print(x2[idx]) # 实现了sklearn.utils.shuffle函数的功能

tensor([[2, 2, 2],
        [1, 1, 1],
        [3, 3, 3]])
tensor([[2., 2., 2.],
        [1., 1., 1.],
        [3., 3., 3.]])


In [6]:
### 其他分布抽样

In [7]:
from scipy.stats import beta # 贝塔分布
torch.tensor(beta.rvs(a=2, b=2, size=10, random_state=5).reshape(2, 5)) # 先从scipy生成随机样本


tensor([[0.6437, 0.8407, 0.4242, 0.2806, 0.2521],
        [0.1250, 0.3969, 0.5450, 0.5214, 0.7489]], dtype=torch.float64)

In [8]:
from scipy.stats import beta # 贝塔分布
torch.tensor(beta.rvs(a=2, b=2, size=10).reshape(2, 5)) # 先从scipy生成随机样本


tensor([[0.6636, 0.6337, 0.7587, 0.4066, 0.4226],
        [0.1933, 0.2407, 0.3880, 0.6481, 0.6152]], dtype=torch.float64)