In [1]:
import torch
import numpy as np
import random

In [2]:
def set_seed(seed):
    """PyTorch随机数种子设置大全"""
    np.random.seed(seed)
    random.seed(seed)
    torch.manual_seed(seed)  # CPU上设置随机种子
    if torch.cuda.is_available():
        torch.cuda.manual_seed(seed)  # 当前GPU上设置随机种子
        # torch.cuda.manual_seed_all(seed) # 所有GPU上设置随机种子

In [3]:
num = 0
while num < 5:
    set_seed(3)
    print(np.random.randn(2, 3))  # 使用相同的随机种子,则每次生成的随机数都相同
    print(torch.randn(2, 3), end='\n\n')
    num += 1

print(end='\n\n\n')
print(np.random.randn(2, 3))  # 每次生成的随机数因时间差异而不同
print(torch.randn(2, 3))

print(np.random.randn(2, 3))  # 每次生成的随机数因时间差异而不同
print(torch.randn(2, 3))


[[ 1.78862847  0.43650985  0.09649747]
 [-1.8634927  -0.2773882  -0.35475898]]
tensor([[ 0.8033,  0.1748,  0.0890],
        [-0.6137,  0.0462, -1.3683]])

[[ 1.78862847  0.43650985  0.09649747]
 [-1.8634927  -0.2773882  -0.35475898]]
tensor([[ 0.8033,  0.1748,  0.0890],
        [-0.6137,  0.0462, -1.3683]])

[[ 1.78862847  0.43650985  0.09649747]
 [-1.8634927  -0.2773882  -0.35475898]]
tensor([[ 0.8033,  0.1748,  0.0890],
        [-0.6137,  0.0462, -1.3683]])

[[ 1.78862847  0.43650985  0.09649747]
 [-1.8634927  -0.2773882  -0.35475898]]
tensor([[ 0.8033,  0.1748,  0.0890],
        [-0.6137,  0.0462, -1.3683]])

[[ 1.78862847  0.43650985  0.09649747]
 [-1.8634927  -0.2773882  -0.35475898]]
tensor([[ 0.8033,  0.1748,  0.0890],
        [-0.6137,  0.0462, -1.3683]])




[[-0.08274148 -0.62700068 -0.04381817]
 [-0.47721803 -1.31386475  0.88462238]]
tensor([[ 0.3375,  1.0111, -1.4352],
        [ 0.9774,  0.5220,  1.2379]])
[[ 0.88131804  1.70957306  0.05003364]
 [-0.40467741 -0.54535995 -1.