In [1]:
import torch
import numpy as np

In [2]:
a = np.array([[1.2, 2, 3],
              [2, 3, 4]])
x = torch.tensor(a)
x

tensor([[1.2000, 2.0000, 3.0000],
        [2.0000, 3.0000, 4.0000]], dtype=torch.float64)

### 参考array相关属性

In [3]:
x.dtype

torch.float64

In [4]:
print(x.ndim)
print(x.dim())  # 与上等价

2
2


In [5]:
print(x.shape)
print(x.size())  # 与上等价

torch.Size([2, 3])
torch.Size([2, 3])


In [6]:
list(x.shape)

[2, 3]

In [7]:
x.shape[0]

2

In [8]:
x.shape[1]

3

In [9]:
y = torch.randn(3, 5, 7)
y.shape

torch.Size([3, 5, 7])

In [10]:
y.T.shape  # 若self.ndim < 2则返回其本身

C:\Users\dcdmm\AppData\Local\Temp\ipykernel_15568\2685651285.py:1: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matricesor `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at  C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\TensorShape.cpp:2318.)
  y.T.shape  # 若self.ndim < 2则返回其本身


torch.Size([7, 5, 3])

In [11]:
torch.transpose(y, 0, -1).shape  # 与上等价

torch.Size([7, 5, 3])

In [12]:
y.device

device(type='cpu')

In [13]:
# y.data与y共享数据的物理地址
# y.data的任何改变都会致使y改变
print(np.shares_memory(y, y.data))
print(y)
y.data = torch.tensor([1, 2, 3])
print(y)
y.data.fill_(0)
print(y)

# y1与y共享数据的物理地址
# 只有不改变y1内存地址的操作时才会指使y改变
y1 = y.detach()
print(np.shares_memory(y1, y))
y1.fill_(2)
print(y)

y1.add_(10)  # in-place操作,y1内存地址不变
print(y)  # y发生相应改变

print(id(y1))
y1 = [-1, -2, -3]
print(id(y1))  # 重新赋值操作,y1内存地址改变
print(y)  # y不变

True
tensor([[[ 0.0241,  1.3741,  1.0556,  1.3041, -0.6486, -2.6906, -1.2507],
         [ 0.2915, -0.9355,  0.6353,  1.0142, -1.1491,  1.0566,  1.8739],
         [ 0.4936,  0.1391,  0.0677, -0.8961, -0.0057, -1.4293, -0.1383],
         [-0.9509,  1.7960, -0.2852,  0.2607, -1.2618,  0.3613,  0.2403],
         [-0.4701,  1.4007,  0.8983,  0.6325, -0.9324,  0.6111,  1.1223]],

        [[-0.2831,  0.9277,  0.3157,  0.3774,  0.1009,  0.0092, -1.1599],
         [-0.3318, -0.1547,  1.0364,  0.1380, -2.0457,  1.9329, -0.6748],
         [ 1.1735, -1.4019, -0.6595,  0.7673,  0.7168,  0.0191, -0.4773],
         [-0.2690,  1.0208, -0.8962, -1.2613,  0.3015, -0.1322,  1.7307],
         [-1.7923,  0.5658,  0.2756,  0.8516,  0.9547,  0.7264, -0.2342]],

        [[-0.9782, -0.1255,  0.8465,  0.3255, -0.7191, -1.8012,  1.6162],
         [-1.6400,  0.2353,  1.9993,  0.9134, -1.0393,  0.3839,  0.1995],
         [ 0.8598,  2.0485, -1.2952, -0.7263,  0.7567, -0.0407,  0.3047],
         [-0.5897,  0.3339,  

In [14]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
y = y.to(device)
print(y)
print(y.is_cuda)  # Is True if the Tensor is stored on the GPU, False otherwise.

tensor([12, 12, 12], device='cuda:0')
True
