In [82]:
import torch
import numpy as np

a = np.array([[1.2, 2, 3],
              [2, 3, 4]])
x = torch.tensor(a)
x

tensor([[1.2000, 2.0000, 3.0000],
        [2.0000, 3.0000, 4.0000]], dtype=torch.float64)

In [83]:
# 类似numpy相关属性
x.dtype

torch.float64

In [84]:
print(x.ndim)
print(x.dim())  # 与上等价

2
2


In [85]:
print(x.shape)
print(x.size())  # 与上等价

torch.Size([2, 3])
torch.Size([2, 3])


In [86]:
list(x.shape)

[2, 3]

In [87]:
x.shape[0]

2

In [88]:
x.shape[1]

3

In [89]:
y = torch.randn(3, 5, 7)
y.shape

torch.Size([3, 5, 7])

In [90]:
y.T.shape  # 若self.ndim < 2则返回其本身

torch.Size([7, 5, 3])

In [91]:
torch.transpose(y, 0, -1).shape  # 与上等价

torch.Size([7, 5, 3])

In [92]:
y.device

device(type='cpu')

In [93]:
# y.data与y共享数据的物理地址
# y.data的任何改变都会致使y改变
print(np.shares_memory(y, y.data))
print(y)
y.data = torch.tensor([1, 2, 3])
print(y)
y.data.fill_(0)
print(y)

# y1与y共享数据的物理地址
# 只有不改变y1内存地址的操作时才会指使y改变
y1 = y.detach()
print(np.shares_memory(y1, y))
y1.fill_(2)
print(y)

y1.add_(10)  # in-place操作,y1内存地址不变
print(y)  # y发生相应改变

print(id(y1))
y1 = [-1, -2, -3]
print(id(y1))  # 重新赋值操作,y1内存地址改变
print(y)  # y不变

True
tensor([[[ 6.1886e-01,  8.5265e-01,  1.8935e-01, -4.8730e-01, -7.8940e-02,
          -6.0315e-01, -1.6818e+00],
         [ 5.8634e-01,  8.6809e-01, -4.6518e-02,  9.2236e-01,  6.5459e-01,
          -5.4149e-02, -8.6296e-01],
         [-9.7448e-02,  1.4537e+00, -1.3591e+00, -3.1494e+00, -8.5691e-01,
          -1.9755e-01, -1.1873e-01],
         [ 2.0324e+00,  1.0780e-01,  2.2582e-01, -2.7448e-01,  6.5646e-01,
           1.3270e+00,  1.1099e+00],
         [ 1.3571e+00, -1.1998e+00, -9.2712e-01, -9.4179e-01, -4.5110e-01,
           1.0983e+00, -8.8721e-01]],

        [[-8.4508e-01,  5.5681e-02, -8.0660e-01,  1.1896e+00, -1.8299e-01,
          -1.0604e+00, -8.8180e-01],
         [ 8.7887e-01, -1.1167e+00, -4.4651e-01, -3.5200e-02, -3.3430e-01,
           2.1533e-01,  2.2097e-01],
         [ 8.6089e-01,  7.1812e-01, -1.1674e+00,  2.3774e+00, -1.2731e-01,
           6.6976e-01, -1.0368e+00],
         [-8.6212e-01, -3.1558e-02,  2.2734e+00, -4.4129e-01,  4.4848e-01,
           1.3494e+00,

In [94]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
y = y.to(device)
print(y)
print(y.is_cuda)  # Is True if the Tensor is stored on the GPU, False otherwise.

tensor([12, 12, 12], device='cuda:0')
True
