In [70]:
import torch
import numpy as np

In [71]:
t = torch.tensor([0, 1.], requires_grad=True)
t1 = t.data
t2 = t.detach()
# t1.requires_grad=t2.requires_grad=False
print(t.requires_grad, t1.requires_grad, t2.requires_grad)

True False False


In [72]:
y = torch.tensor([-1, -2, -3])
y

tensor([-1, -2, -3])

In [73]:
# y.data与y共享数据的物理地址
# y.data的任何改变都会致使y改变
print(np.shares_memory(y, y.data))
y.data = torch.tensor([1, 2, 3])
print(y)
y.data.fill_(0)
print(y)
print(np.shares_memory(y, y.data))

True
tensor([1, 2, 3])
tensor([0, 0, 0])
True


In [74]:
# y1与y共享数据的物理地址
# 只有不改变y1内存地址的操作时才会指使y改变
y1 = y.detach()
print(np.shares_memory(y1, y))
y1.fill_(2)
print(y)

y1.add_(10)  # in-place操作,y1内存地址不变
print(y)  # y发生相应改变
print(np.shares_memory(y1, y))

print(id(y1))
y1 = [-1, -2, -3]
print(id(y1))  # 重新赋值操作,y1内存地址改变
print(y)  # y不变
print(np.shares_memory(y1, y))

True
tensor([2, 2, 2])
tensor([12, 12, 12])
True
2201782369232
2201780930496
tensor([12, 12, 12])
False


In [75]:
y2 = y.data
print(np.shares_memory(y2, y))
y2.fill_(-2)
print(y)
print(np.shares_memory(y2, y))

print(id(y2))
y2 = [-4, -5, -6]
print(id(y2))  # 重新赋值操作,y2内存地址改变
print(y)  # y不变
print(np.shares_memory(y2, y))

True
tensor([-2, -2, -2])
True
2201775158752
2201782250688
tensor([-2, -2, -2])
False
