In [1]:
import torch
import numpy as np

tensor([[1.2000, 2.0000, 3.0000],
        [2.0000, 3.0000, 4.0000]], dtype=torch.float64)

In [ ]:
a = np.array([[1.2, 2, 3],
              [2, 3, 4]])
x = torch.tensor(a)
x

### 参考numpy

In [2]:
x.dtype

torch.float64

In [3]:
print(x.ndim)
print(x.dim())  # 与上等价

2
2


In [4]:
print(x.shape)
print(x.size())  # 与上等价

torch.Size([2, 3])
torch.Size([2, 3])


In [5]:
list(x.shape)

[2, 3]

In [6]:
x.shape[0]

2

In [7]:
x.shape[1]

3

In [8]:
y = torch.randn(3, 5, 7)
y.shape

torch.Size([3, 5, 7])

In [9]:
y.T.shape  # 若self.ndim < 2则返回其本身

torch.Size([7, 5, 3])

In [10]:
torch.transpose(y, 0, -1).shape  # 与上等价

torch.Size([7, 5, 3])

In [11]:
y.device

device(type='cpu')

In [12]:
# y.data与y共享数据的物理地址
# y.data的任何改变都会致使y改变
print(np.shares_memory(y, y.data))
print(y)
y.data = torch.tensor([1, 2, 3])
print(y)
y.data.fill_(0)
print(y)

# y1与y共享数据的物理地址
# 只有不改变y1内存地址的操作时才会指使y改变
y1 = y.detach()
print(np.shares_memory(y1, y))
y1.fill_(2)
print(y)

y1.add_(10)  # in-place操作,y1内存地址不变
print(y)  # y发生相应改变

print(id(y1))
y1 = [-1, -2, -3]
print(id(y1))  # 重新赋值操作,y1内存地址改变
print(y)  # y不变

True
tensor([[[-0.1239,  2.0319, -0.4593, -0.3831, -0.8514, -1.1898, -0.8982],
         [-0.0981, -0.5160,  0.4089,  0.1621, -0.6950,  0.1783, -1.1064],
         [-1.5057, -0.5905, -0.1286, -0.1469,  1.0022, -1.1172,  0.7924],
         [-1.2794,  0.4728, -0.7023, -0.1966,  0.1293,  1.3839,  1.1003],
         [ 0.7724, -0.4662,  2.0317,  1.0119,  0.7965,  0.3477,  1.0246]],

        [[-0.3930,  0.7748,  0.1660,  1.4839, -0.5683, -0.2081,  0.2160],
         [-0.8198,  0.3912,  0.1024,  0.6727, -0.2265,  1.1770, -0.2324],
         [-0.0549, -0.5036,  1.7659, -1.2267, -0.4922,  1.1779, -0.2036],
         [ 0.0678,  0.3910,  0.6417,  2.5343,  0.8048,  1.0035, -1.6852],
         [ 0.3919,  0.0596, -0.8737,  0.1504,  2.4842,  0.6935,  0.0283]],

        [[ 1.1782, -0.8274, -0.6537, -0.1745, -0.6405,  0.5154, -0.9553],
         [-0.0153,  0.8104,  1.1911, -0.7127, -0.6051,  1.0259,  0.9137],
         [ 2.1133,  0.4417,  0.3550,  0.7554, -1.0359, -0.1797, -0.9592],
         [ 1.3914,  1.0757,  

In [13]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
y = y.to(device)
print(y)
print(y.is_cuda)  # Is True if the Tensor is stored on the GPU, False otherwise.

tensor([12, 12, 12], device='cuda:0')
True
