## 换底公式
$$ log_{a}^{b} = \frac{log_{c}^{b}}{log_{c}^{a}}$$

In [1]:
import  numpy as np
import  pandas as pd

np.log([1, np.e, np.e**2, 0]) # e为底

C:\Users\duanm\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in log
  after removing the cwd from sys.path.


array([  0.,   1.,   2., -inf])

In [2]:
np.log2([1, 10, 10**2, 0]) # 2为底

C:\Users\duanm\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log2
  """Entry point for launching an IPython kernel.


array([0.        , 3.32192809, 6.64385619,       -inf])

In [3]:
np.log10([1, 10, 10**2, 0]) # 10为底

C:\Users\duanm\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log10
  """Entry point for launching an IPython kernel.


array([  0.,   1.,   2., -inf])

In [4]:
np.log([1, 4, 4**2, 0])/np.log(4) # 4为底(由换底公式)

C:\Users\duanm\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([  0.,   1.,   2., -inf])

In [7]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj1 = pd.Series(sdata)
print(obj1.apply(np.log))

Ohio      10.463103
Texas     11.170435
Oregon     9.680344
Utah       8.517193
dtype: float64


In [8]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                     columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [10]:
frame.apply(np.log)

b         d         e
Utah        -inf  0.000000  0.693147
Ohio    1.098612  1.386294  1.609438
Texas   1.791759  1.945910  2.079442
Oregon  2.197225  2.302585  2.397895