In [29]:
import  numpy as np

In [30]:
np.all([[True, False], [True, True]]) # 所有元素为True时才返回True

False

In [31]:
np.all([[True, False], [True, True]], axis=0) # 指定轴axis

array([ True, False])

In [32]:
np.any([[True, False], [True, True]]) # 所有元素为False才返回False

True

In [33]:
np.any([[True, False], [True, True]], axis=0)

array([ True,  True])

In [34]:
arr = np.array([[True, -2], 
                [0, 0]])
np.any(arr, axis=1) # 除Ture/False外还(0为False,其他为True)

array([ True, False])

In [35]:
np.logical_not(3) # 转换x的真假

False

In [36]:
np.logical_not(False)

True

In [37]:
np.logical_not([True, False, 0, 1])

array([False,  True,  True, False])

In [38]:
np.logical_and(True, False) # Compute the truth value of x1 AND x2 element-wise

False

In [39]:
np.logical_and([33, False], 
               [True, 0])

array([ True, False])

In [40]:
np.all([[33, False],
        [True, 0]], axis=0) # 与上等价(除Ture/False外还支持数字,0为False,其他数字为False)

array([ True, False])

In [41]:
np.logical_or([True, False], 
               [0, False]) # Compute the truth value of x1 OR x2 element-wise.

array([ True, False])

In [42]:
np.any([[True, False],
        [0, False]], axis=0) # 与上等价



array([ True, False])