&emsp;&emsp;如果$ A $为$ m \times n $矩阵,$ B$为$ p \times q  $矩阵,则它们的Kronecker积
记为$ A \otimes  B$,定义一个$ mp \times np $矩阵:   
$$ A \otimes B = $$ 
\begin{bmatrix}
a_{11}B  & a_{12}B & \dots  & a_{1n}B \\
a_{21}B  & a_{22}B & \dots  & a_{2n}B \\
\vdots   & \vdots  & \ddots & \vdots \\
a_{m1}B  & a_{m2}B & \dots  & a_{mn}B    
\end{bmatrix}

<font color='red' size=4>Kronecker 积具有以下性质</font>  
* 令$ A \in \mathbf{C}^{m \times n}, B \in \mathbf{C}^{p \times q}, b \in \mathbf{C}^{p} $  
    * $$ K_{pm} (A \otimes B) = (B \otimes A ) K_{qn} $$
    * $$ K_{pm} (A \otimes B) K_{nq} = B \otimes A $$ 
    * $$ K_{pm} (A \otimes \mathbf{b}) = \mathbf{b} \otimes A $$
    * $$ K_{mp} (\mathbf{b} \otimes A) =  A \otimes \mathbf{b} $$

In [6]:

import numpy as np

np.kron([1, 10, 100], [5, 6, 7])  # Kronecker积

array([  5,   6,   7,  50,  60,  70, 500, 600, 700])

In [7]:
np.kron([5, 6, 7], [1, 10, 100])

array([  5,  50, 500,   6,  60, 600,   7,  70, 700])

In [8]:
np.kron(np.eye(2), np.ones((2, 2)))

array([[1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 1., 1.],
       [0., 0., 1., 1.]])

In [9]:
np.kron(np.ones((2, 2)), np.eye(2))

array([[1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.]])