In [1]:
import  numpy as np
from numpy.linalg import matrix_rank

matrix_rank(np.eye(4))

4

In [2]:
I = np.eye(4)
I[-1, -1] = 0
matrix_rank(I)

3

In [3]:
a = np.array([[1, 2, 3, 4], [2, 4, 4, 5],
             [2, 4, 6, 8]])
print(a)
print(matrix_rank(a))

[[1 2 3 4]
 [2 4 4 5]
 [2 4 6 8]]
2
