In [14]:
import torch

In [15]:
tor = torch.tensor([[5, 5, 2, 2, 3, 3],
               [3, 3, 4, 4, 5, 5]])
tor

tensor([[5, 5, 2, 2, 3, 3],
        [3, 3, 4, 4, 5, 5]])

In [16]:
# 完全类似numpy.unique
torch.unique(tor) # Returns the unique elements of the input tensor

tensor([2, 3, 4, 5])

In [17]:
torch.unique(tor, sorted=False) # 默认sorted=True,即对返回值进行了排序

tensor([5, 2, 3, 4])

In [18]:
torch.unique(tor, return_counts=True) # 返回唯一值和该唯一值出现的次数

(tensor([2, 3, 4, 5]), tensor([2, 4, 2, 4]))

In [19]:
torch.unique(tor, dim=0)

tensor([[3, 3, 4, 4, 5, 5],
        [5, 5, 2, 2, 3, 3]])

In [20]:
torch.unique(tor, dim=1)

tensor([[2, 3, 5],
        [4, 5, 3]])

In [21]:
torch.unique(tor, dim=0)

tensor([[3, 3, 4, 4, 5, 5],
        [5, 5, 2, 2, 3, 3]])