In [13]:
import numpy as np
from  sklearn.utils import shuffle

In [14]:
x1 = np.array([1, 2, 3, 4, 5])
shuffle(x1) # 注意和np.random.shuffle的区别

array([5, 1, 3, 2, 4])

In [15]:
x1 # x1不变

array([1, 2, 3, 4, 5])

In [18]:
x2 = np.array([[1, 2, 3, 4, 5],
               [2, 3, 4, 5, 6],
               [3, 4, 5, 6, 7],
               [8, 9, 10, 11, 12]])

y = np.array([1, 2, 3, 4])
z = np.array([['one', 'two'],
              ['three', 'four'],
              ['five', 'six'],
              ['seven', 'eight']])


shuffle(x2, y, z, random_state=8) # 以一致的方式随机排列x2, y, z(按列,即特征) 

[array([[ 3,  4,  5,  6,  7],
        [ 2,  3,  4,  5,  6],
        [ 1,  2,  3,  4,  5],
        [ 8,  9, 10, 11, 12]]),
 array([3, 2, 1, 4]),
 array([['five', 'six'],
        ['three', 'four'],
        ['one', 'two'],
        ['seven', 'eight']], dtype='<U5')]