In [6]:
import numpy as np

a = np.array([[1, 0, 0, 0],
              [0, 0, 0, 4],
              [0, 3, 0, 0],
              [0, 0, 0, 0],
              [2, 0, 0, 0]]) # a.shape = (5, 4)

u, s, v = np.linalg.svd(a)
print(u) # u.shape = (5, 5)
print(s)
print(v) # v.shape=(4, 4)

[[ 0.          0.         -0.4472136   0.         -0.89442719]
 [-1.          0.          0.          0.          0.        ]
 [ 0.         -1.          0.          0.          0.        ]
 [ 0.          0.          0.          1.          0.        ]
 [ 0.          0.         -0.89442719  0.          0.4472136 ]]
[4.         3.         2.23606798 0.        ]
[[-0. -0. -0. -1.]
 [-0. -1. -0. -0.]
 [-1. -0. -0. -0.]
 [-0. -0. -1. -0.]]


In [11]:
t_u = np.concatenate((np.diag(s), np.zeros((1, 4))), axis=0)
t_u # t_u.shape = (5, 4)

array([[4.        , 0.        , 0.        , 0.        ],
       [0.        , 3.        , 0.        , 0.        ],
       [0.        , 0.        , 2.23606798, 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ]])