In [45]:
import tensorflow as tf

### 参考numpy索引切片

In [46]:
tor_mul = tf.random.stateless_normal(shape=(5, 7, 4), seed=(1, 2))
tor_mul

<tf.Tensor: shape=(5, 7, 4), dtype=float32, numpy=
array([[[ 0.5441101 ,  0.20738031,  0.07356433,  0.04643455],
        [-1.30159   , -0.95385665,  0.84172857,  1.9396868 ],
        [ 0.6512578 ,  1.1048867 ,  1.3746228 ,  1.148752  ],
        [ 1.0821314 ,  0.55104923,  0.07009614,  0.707385  ],
        [ 0.88857085, -0.46432722,  1.2084333 , -0.79011595],
        [-0.7304904 , -0.7207538 ,  0.36527526, -0.16950758],
        [ 0.20318079, -0.90232295, -0.65045786,  2.4152768 ]],

       [[ 0.5703469 ,  0.8770354 ,  0.36876458, -0.57617044],
        [-0.66170377, -1.0227758 ,  0.6109012 , -0.2563904 ],
        [ 2.1067173 , -0.04597485, -0.2069098 ,  0.6324636 ],
        [ 0.42266   ,  0.05165391, -0.73736423, -1.1144085 ],
        [ 0.4858592 , -1.4368211 ,  1.7883171 ,  0.47844714],
        [-1.3764827 ,  0.79399854, -2.1332254 , -0.17303157],
        [-1.7487346 , -0.46926638, -1.5576217 , -0.8941696 ]],

       [[ 0.21992801,  0.148727  , -0.8418422 , -1.4702468 ],
        [-0.481

In [47]:
tor_mul[0, 1, 1]  # 索引,返回常量tensor

<tf.Tensor: shape=(), dtype=float32, numpy=-0.95385665>

In [48]:
tor_mul[0]  # 从第零个维度开始索引切片(DataFrame从列开始进行索引切片)

<tf.Tensor: shape=(7, 4), dtype=float32, numpy=
array([[ 0.5441101 ,  0.20738031,  0.07356433,  0.04643455],
       [-1.30159   , -0.95385665,  0.84172857,  1.9396868 ],
       [ 0.6512578 ,  1.1048867 ,  1.3746228 ,  1.148752  ],
       [ 1.0821314 ,  0.55104923,  0.07009614,  0.707385  ],
       [ 0.88857085, -0.46432722,  1.2084333 , -0.79011595],
       [-0.7304904 , -0.7207538 ,  0.36527526, -0.16950758],
       [ 0.20318079, -0.90232295, -0.65045786,  2.4152768 ]],
      dtype=float32)>

In [49]:
tor_mul[0, 0, -1]  # 索引,返回常量tensor.支持负数索引

<tf.Tensor: shape=(), dtype=float32, numpy=0.046434548>

In [50]:
tor_mul[0:2]  # 切片,返回常量tensor

<tf.Tensor: shape=(2, 7, 4), dtype=float32, numpy=
array([[[ 0.5441101 ,  0.20738031,  0.07356433,  0.04643455],
        [-1.30159   , -0.95385665,  0.84172857,  1.9396868 ],
        [ 0.6512578 ,  1.1048867 ,  1.3746228 ,  1.148752  ],
        [ 1.0821314 ,  0.55104923,  0.07009614,  0.707385  ],
        [ 0.88857085, -0.46432722,  1.2084333 , -0.79011595],
        [-0.7304904 , -0.7207538 ,  0.36527526, -0.16950758],
        [ 0.20318079, -0.90232295, -0.65045786,  2.4152768 ]],

       [[ 0.5703469 ,  0.8770354 ,  0.36876458, -0.57617044],
        [-0.66170377, -1.0227758 ,  0.6109012 , -0.2563904 ],
        [ 2.1067173 , -0.04597485, -0.2069098 ,  0.6324636 ],
        [ 0.42266   ,  0.05165391, -0.73736423, -1.1144085 ],
        [ 0.4858592 , -1.4368211 ,  1.7883171 ,  0.47844714],
        [-1.3764827 ,  0.79399854, -2.1332254 , -0.17303157],
        [-1.7487346 , -0.46926638, -1.5576217 , -0.8941696 ]]],
      dtype=float32)>

In [51]:
tor_mul[0:2, 0:3, 0]  # 在多个维度上索引切片

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 0.5441101 , -1.30159   ,  0.6512578 ],
       [ 0.5703469 , -0.66170377,  2.1067173 ]], dtype=float32)>

In [52]:
tor_mul[0:2, 0:6:2, 2]  # 第一个维度上的切片步长为2(不支持步长为负数),切片范围为0-6

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 0.07356433,  1.3746228 ,  1.2084333 ],
       [ 0.36876458, -0.2069098 ,  1.7883171 ]], dtype=float32)>

In [53]:
tor_mul[:]  # 等价于tor_mul[:, :, :]

<tf.Tensor: shape=(5, 7, 4), dtype=float32, numpy=
array([[[ 0.5441101 ,  0.20738031,  0.07356433,  0.04643455],
        [-1.30159   , -0.95385665,  0.84172857,  1.9396868 ],
        [ 0.6512578 ,  1.1048867 ,  1.3746228 ,  1.148752  ],
        [ 1.0821314 ,  0.55104923,  0.07009614,  0.707385  ],
        [ 0.88857085, -0.46432722,  1.2084333 , -0.79011595],
        [-0.7304904 , -0.7207538 ,  0.36527526, -0.16950758],
        [ 0.20318079, -0.90232295, -0.65045786,  2.4152768 ]],

       [[ 0.5703469 ,  0.8770354 ,  0.36876458, -0.57617044],
        [-0.66170377, -1.0227758 ,  0.6109012 , -0.2563904 ],
        [ 2.1067173 , -0.04597485, -0.2069098 ,  0.6324636 ],
        [ 0.42266   ,  0.05165391, -0.73736423, -1.1144085 ],
        [ 0.4858592 , -1.4368211 ,  1.7883171 ,  0.47844714],
        [-1.3764827 ,  0.79399854, -2.1332254 , -0.17303157],
        [-1.7487346 , -0.46926638, -1.5576217 , -0.8941696 ]],

       [[ 0.21992801,  0.148727  , -0.8418422 , -1.4702468 ],
        [-0.481

In [54]:
tor_mul[::2]  # 第一个维度上切片步长为2,范围为整个维度;等价于tor_mul[::2, :, :]

<tf.Tensor: shape=(3, 7, 4), dtype=float32, numpy=
array([[[ 0.5441101 ,  0.20738031,  0.07356433,  0.04643455],
        [-1.30159   , -0.95385665,  0.84172857,  1.9396868 ],
        [ 0.6512578 ,  1.1048867 ,  1.3746228 ,  1.148752  ],
        [ 1.0821314 ,  0.55104923,  0.07009614,  0.707385  ],
        [ 0.88857085, -0.46432722,  1.2084333 , -0.79011595],
        [-0.7304904 , -0.7207538 ,  0.36527526, -0.16950758],
        [ 0.20318079, -0.90232295, -0.65045786,  2.4152768 ]],

       [[ 0.21992801,  0.148727  , -0.8418422 , -1.4702468 ],
        [-0.48143446,  0.91328293,  0.75411063, -0.45545915],
        [-0.5482289 , -0.95850194,  0.17038241,  0.6320987 ],
        [-0.11597513, -0.9985191 , -0.74675995, -1.0898854 ],
        [-0.8605409 , -0.6180766 ,  1.0560111 ,  0.05375697],
        [ 0.17810917,  0.2230358 ,  1.8982831 ,  1.9089541 ],
        [ 1.1501542 ,  0.04781999, -0.29954264, -0.39296842]],

       [[ 0.01143784, -1.0229038 ,  2.0762193 ,  0.43485036],
        [-0.420

In [55]:
tor_complex = tf.random.stateless_normal(shape=(12, 7, 8, 10, 9, 15, 14), seed=(1, 2))
tor_complex.shape

TensorShape([12, 7, 8, 10, 9, 15, 14])

In [56]:
print(tor_complex[1:5].shape)
print(tor_complex[1:5, :, :, :, :, :].shape)
print(tor_complex[1:5, ...].shape)  # ...:剩余维度上所有数据

(4, 7, 8, 10, 9, 15, 14)
(4, 7, 8, 10, 9, 15, 14)
(4, 7, 8, 10, 9, 15, 14)


In [57]:
print(tor_complex[:, :, :, :, :, :, 2:4].shape)
print(tor_complex[..., 2:4].shape)

(12, 7, 8, 10, 9, 15, 2)
(12, 7, 8, 10, 9, 15, 2)


In [58]:
print(tor_complex[2:7, :, :, :, :, :, 4].shape)
print(tor_complex[2:7, ..., 4].shape)





(5, 7, 8, 10, 9, 15)
(5, 7, 8, 10, 9, 15)
