In [118]:
import tensorflow as tf

### 参考numpy整数索引

In [119]:
data = tf.reshape(tf.range(100), (10, 10))
data

<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])>

In [120]:
# 不支持负数索引
print(tf.gather(data, 0))  # 默认axis=0

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)


In [121]:
tf.gather(data, [4, 3, 0, 6])

<tf.Tensor: shape=(4, 10), dtype=int32, numpy=
array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])>

In [122]:
tf.gather(data, [0, 1], axis=1)

<tf.Tensor: shape=(10, 2), dtype=int32, numpy=
array([[ 0,  1],
       [10, 11],
       [20, 21],
       [30, 31],
       [40, 41],
       [50, 51],
       [60, 61],
       [70, 71],
       [80, 81],
       [90, 91]])>

In [123]:
tf.stack([tf.gather(data, [2, 0], axis=0),
          tf.gather(data, [2, 5], axis=0)], axis=0)

<tf.Tensor: shape=(2, 2, 10), dtype=int32, numpy=
array([[[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]],

       [[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]]])>

In [124]:
tf.gather(data, [[2, 0], [2, 5]], axis=0)  # 与上等价

<tf.Tensor: shape=(2, 2, 10), dtype=int32, numpy=
array([[[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]],

       [[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]]])>

In [125]:
# axis=0索引为2和索引为0和axis=1索引为2和索引为5的交集(二次整数索引)
tf.gather(tf.gather(data, [2, 0]), (2, 5), axis=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[22, 25],
       [ 2,  5]])>