In [4]:
import torch

pr = $ vec[0] \times vec[1] \times vec[2] \times vec[3]$

In [5]:
vec = torch.tensor([[1.],
                    [2.],
                    [3.],
                    [4.]], requires_grad=True) # vec为向量

pr = vec.prod()
pr.backward(torch.ones_like(pr)) # pr对vec每个元素分别进行求导
print(vec.grad)

tensor([[24.],
        [12.],
        [ 8.],
        [ 6.]])


$ \mathbf{a} $ is not a function of $ \mathbf{x} $, $$ \frac{\partial \mathbf{a}^T\mathbf{x}}{\partial{\mathbf{x}}} = \frac{\partial \mathbf{x}^T \mathbf{a}}{\partial{\mathbf{x}}} = \mathbf{a}^T $$

In [6]:
vec0 = torch.tensor([[1.],
                     [2.],
                     [3.],
                     [4.]], requires_grad=True)

vec1 = torch.tensor([[2., 3., 4., 5.]], requires_grad=True)

mm = vec1 @ vec0
mm.backward() # 分母布局
print(vec0.grad) # 与vec0同型
print(vec1.grad)

tensor([[2.],
        [3.],
        [4.],
        [5.]])
tensor([[1., 2., 3., 4.]])
