In [1]:
import torch

t = torch.tensor([[[1, 2],
                   [3, 4]],
                  [[5, 6],
                   [7, 8]]])
t

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])

In [2]:
# 类似arr.flatten
t.flatten() # 默认start_dim=0, end_dim=-1,即向量化t[:, :, :]

tensor([1, 2, 3, 4, 5, 6, 7, 8])

In [3]:
t.flatten(start_dim=0, end_dim=1) # 分别向量化t[:, :, 0], t[:, :, 1]

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [4]:
t.reshape(2*2, 2) # 与上等价

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [5]:
t.flatten(start_dim=1, end_dim=-1) # 分别向量化t[0, :, :], t[1, :, :]

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [6]:
t.reshape(2, 2*2) # 与上等价

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])