In [96]:
import numpy as np

In [97]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(id(arr))

arr[2:5] = np.array([0, 0, 0]) # 直接对切片进行赋值

print(id(arr)) # arr指向的地址不变
print(arr) # arr发生相应改变

2469994916800
2469994916800
[1 2 0 0 0 6 7 8]


In [98]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(id(arr))

arr[2] = 100 # 直接对索引值进行赋值

print(id(arr)) # arr指向的地址不变
print(arr) # arr发生相应改变

2469994916960
2469994916960
[  1   2 100   4   5   6   7   8]


In [99]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(id(arr))

a = arr[4] # 此时a为不可变数据类型
print(np.shares_memory(a, arr)) # 此时a与arr不共享数据的物理地址

a = 55

print(id(arr)) # arr指向地址不变
print(arr) # arr输出不变

2469993664144
False
2469993664144
[1 2 3 4 5 6 7 8]


In [100]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

a = arr[4:5] # 注意:此时a为可变数据类型

print('id(arr):', id(arr))
print('id(a):', id(a))

# ★★★★★★★★★★★★★★★切片共享内存
print(np.shares_memory(a, arr)) # a与arr共享数据的物理地址

a += 43 # 可变的类型的追加操作
print('after change id(a):', id(a)) # a指向的地址不变
print(a) # a输出改变

print(arr) # 由于共享数据的物理地址,故arr指向内存的值也发生相应的改变

id(arr): 2469992732832
id(a): 2469993664144
True
after change id(a): 2469993664144
[48]
[ 1  2  3  4 48  6  7  8]


In [101]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

a = arr[4:5] # 注意:此时a为可变数据类型

print('id(arr):', id(arr))
print('id(a):', id(a))

print(np.shares_memory(a, arr)) # a与arr共享内存数据的物理地址

a = a + 43 # 可变的类型的连接操作
print('after change id(a):', id(a)) # a指向新的内存地址
print(a)

print(arr) # 由于共享的物理地址没有改变,故arr指向内存的值不变

id(arr): 2469993450592
id(a): 2469995012864
True
after change id(a): 2469992732832
[48]
[1 2 3 4 5 6 7 8]


In [102]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

a = arr[2:5]
print(id(a))
print(np.shares_memory(a, arr)) # a与arr共享内存数据的物理地址

a = np.array([0, 0, 0]) # 整体重新进行赋值
print(id(a)) # a指向新的地址
print(a)

print(arr) # 共享的物理地址没有改变,故arr指向地址的值不变

2469993450592
True
2469992732832
[0 0 0]
[1 2 3 4 5 6 7 8]


In [103]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

a = arr[2:6]
print(id(a))
print(np.shares_memory(a, arr)) # a与arr共享内存数据的物理地址

a[:2] = np.array([0, 0]) # 对a的切片进行赋值(可进行广播)
print(id(a)) # a指向的地址不变
print(a) # a输出改变

print(arr) # 共享物理地址没有改变,故arr指向内存的值不变

2469993887104
True
2469993887104
[0 0 5 6]
[1 2 0 0 5 6 7 8]


In [104]:
a = np.arange(30)
b = a.reshape(5, 6)

print(a)
print(b, end='\n\n')

print(id(a))
print(id(b), end='\n\n') # 变量a,b指向的地址不同

# ★★★★★★★★★★★★★★★reshape操作共享内存
print(np.shares_memory(a, b), end='\n\n') # b与a共享内存

a[0] = 1000000 # 修改a
print(id(a)) # a指向的地址不变
print(a)
print(b, end='\n\n') # 由于共享数据的物理地址,故b指向内存的值相应位置也发生改变

b[-1][-1] = 99999999 # 修改b
print(a) # 同理

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]

2469992728736
2469993887104

True

2469992728736
[1000000       1       2       3       4       5       6       7       8
       9      10      11      12      13      14      15      16      17
      18      19      20      21      22      23      24      25      26
      27      28      29]
[[1000000       1       2       3       4       5]
 [      6       7       8       9      10      11]
 [     12      13      14      15      16      17]
 [     18      19      20      21      22      23]
 [     24      25      26      27      28      29]]

[ 1000000        1        2        3        4        5        6        7
        8        9       10       11       12       13       14       15
       16       17       18       19       20       21       22       23
       24       25       26   

In [105]:
c = np.transpose(b)

# ★★★★★★★★★★★★★★★transpose操作共享内存
np.shares_memory(b, c)

True

In [106]:
d = np.swapaxes(b, 0, 1) # b.T同理

# ★★★★★★★★★★★★★★★swapaxes操作共享内存
np.shares_memory(b, d)

True

In [107]:
e = np.expand_dims(b, 0)

# ★★★★★★★★★★★★★★★expand_dim操作共享内存
np.shares_memory(b, e)

True

In [108]:
f = np.squeeze(e)

# ★★★★★★★★★★★★★★★squeeze操作共享内存
np.shares_memory(e, f)

True

In [109]:
g = b.ravel()
# ★★★★★★★★★★★★★★★ravel操作共享内存★★★★
np.shares_memory(b, g)

True

In [110]:
h = b.flatten()
# ★★★★★★★★★★★★★★★flatten操作不共享内存★★★★
np.shares_memory(b, h)


False