In [40]:
import numpy as np

In [41]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(id(arr))

arr[2:5] = np.array([0, 0, 0])  # 直接对切片进行赋值

print(id(arr))  # arr指向的地址不变
print(arr)  # arr发生相应改变

2024802918832
2024802918832
[1 2 0 0 0 6 7 8]


In [42]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(id(arr))

arr[2] = 100  # 直接对索引值进行赋值

print(id(arr))  # arr指向的地址不变
print(arr)  # arr发生相应改变

2024811541776
2024811541776
[  1   2 100   4   5   6   7   8]


In [43]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(id(arr))

a = arr[4]  # 此时a为不可变数据类型
print(np.shares_memory(a, arr))  # 此时a与arr不共享数据的物理地址

a = 55

print(id(arr))  # arr指向地址不变
print(arr)  # arr输出不变

2024805806128
False
2024805806128
[1 2 3 4 5 6 7 8]


In [44]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

a = arr[4:5]  # 注意:此时a为可变数据类型

print('id(arr):', id(arr))
print('id(a):', id(a))

# ★★★★★★★★★★★★★★★切片共享内存
print(np.shares_memory(a, arr))  # a与arr共享数据的物理地址

a += 43  # 可变的类型的追加操作
print('after change id(a):', id(a))  # a指向的地址不变
print(a)  # a输出改变

print(arr)  # 由于共享数据的物理地址,故arr指向内存的值也发生相应的改变

id(arr): 2024811542736
id(a): 2024805806128
True
after change id(a): 2024805806128
[48]
[ 1  2  3  4 48  6  7  8]


In [45]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

a = arr[4:5]  # 注意:此时a为可变数据类型

print('id(arr):', id(arr))
print('id(a):', id(a))

print(np.shares_memory(a, arr))  # a与arr共享数据的物理地址

a = a + 43  # 可变的类型的连接操作
print('after change id(a):', id(a))  # a指向新的内存地址
print(a)

print(arr)  # 由于共享的物理地址没有改变,故arr指向内存的值不变

id(arr): 2024813418416
id(a): 2024813418128
True
after change id(a): 2024811542736
[48]
[1 2 3 4 5 6 7 8]


In [46]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

a = arr[2:5]
print(id(a))
print(np.shares_memory(a, arr))  # a与arr共享内存数据的物理地址

a = np.array([0, 0, 0])  # 整体重新进行赋值
print(id(a))  # a指向新的地址
print(a)

print(arr)  # 由于共享的物理地址没有改变,故arr指向地址的值不变

2024813418416
True
2024813418128
[0 0 0]
[1 2 3 4 5 6 7 8]


In [47]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

a = arr[2:6]
print(id(a))
print(np.shares_memory(a, arr))  # a与arr共享内存数据的物理地址

a[:2] = np.array([0, 0])  # 对a的切片进行赋值(可进行广播)
print(id(a))  # a指向的地址不变
print(a)  # a输出改变

print(arr)  # 共享物理地址没有改变,故arr指向内存的值不变

2024813419664
True
2024813419664
[0 0 5 6]
[1 2 0 0 5 6 7 8]


### numpy中共享数据的物理地址的操作

In [48]:
a = np.arange(30)
b = a.reshape(5, 6)

print(a)
print(b, end='\n\n')

print(id(a))
print(id(b), end='\n\n')  # 变量a,b指向的地址不同

# ★★★★★★★★★★★★★★★reshape操作共享内存
print(np.shares_memory(a, b), end='\n\n')  # b与a共享数据的物理地址

a[0] = 1000000  # 修改a
print(id(a))  # a指向的地址不变
print(a)
print(b, end='\n\n')  # 由于共享数据的物理地址,故b指向内存的值相应位置也发生改变

b[-1][-1] = 99999999  # 修改b
print(a)  # 同理

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]

2024794082352
2024811542160

True

2024794082352
[1000000       1       2       3       4       5       6       7       8
       9      10      11      12      13      14      15      16      17
      18      19      20      21      22      23      24      25      26
      27      28      29]
[[1000000       1       2       3       4       5]
 [      6       7       8       9      10      11]
 [     12      13      14      15      16      17]
 [     18      19      20      21      22      23]
 [     24      25      26      27      28      29]]

[ 1000000        1        2        3        4        5        6        7
        8        9       10       11       12       13       14       15
       16       17       18       19       20       21       22       23
       24       25       26   

In [49]:
c = np.transpose(b)

# ★★★★★★★★★★★★★★★transpose操作共享数据的物理地址
np.shares_memory(b, c)

True

In [50]:
d = np.swapaxes(b, 0, 1)  # b.T同理

# ★★★★★★★★★★★★★★★swapaxes操作共享数据的物理地址
np.shares_memory(b, d)

True

In [51]:
e = np.expand_dims(b, 0)

# ★★★★★★★★★★★★★★★expand_dim操作共享数据的物理地址
np.shares_memory(b, e)

True

In [52]:
f = np.squeeze(e)

# ★★★★★★★★★★★★★★★squeeze操作共享数据的物理地址
np.shares_memory(e, f)

True

In [53]:
g = b.ravel()
# ★★★★★★★★★★★★★★★ravel操作共享数据的物理地址
np.shares_memory(b, g)

True

In [54]:
h = b.flatten()
# ★★★★★★★★★★★★★★★flatten操作不共享数据的物理地址
np.shares_memory(b, h)


False