In [180]:
import numpy as np

In [181]:
A = np.arange(25).reshape(5, 5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [182]:
# 全部元素求和(不保留任何维度)
np.einsum('ij->', A)  # \sum_{i,j} A_{i,j}

300

In [183]:
# 矩阵的迹
# \sum_{i,j} A_{i,i}
# 即:\sum_{i} A_{i,j}
np.einsum('ii->', A)

60

In [184]:
# 某一维度求和
# \sum_j A_{i=0,j}, \sum_j A_{i=1,j}, \sum_j A_{i=2,j}, ......
np.einsum('ij->i', A)  # 保留维度i

array([ 10,  35,  60,  85, 110])

In [185]:
# 提取对角线
# \sum_{j} A_{i,i}
# 即:A_{0,0}, A_{1,1}, A_{2,2}, ......
np.einsum('ii->i', A)

array([ 0,  6, 12, 18, 24])

In [186]:
# 转置
# B_{i,j} = A_{j, i}
B = np.einsum('ij->ji', A)
B

array([[ 0,  5, 10, 15, 20],
       [ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24]])

In [187]:
x = np.arange(5)
y = np.arange(5)
print(x)
print(y)

# 向量内积
print(np.einsum('i,i->', x, y))  # \sum_i x_i y_i

[0 1 2 3 4]
[0 1 2 3 4]
30


In [188]:
x = np.arange(5)
y = np.arange(4)
print(x)
print(y)

# 向量外积
c = np.einsum('i,j->ij', x, y)  # c_{ij} = x_i * y_j
print(c)

[0 1 2 3 4]
[0 1 2 3]
[[ 0  0  0  0]
 [ 0  1  2  3]
 [ 0  2  4  6]
 [ 0  3  6  9]
 [ 0  4  8 12]]


In [189]:
A = np.arange(9).reshape(3, 3)
b = np.arange(3)
print(A)
print(b)

# \sum_{i,j} A_{i,j} * b_{j}
print(np.einsum('ij,j->', A, b))

# \sum_j A_{i=0,j} * b_j, \sum_j A_{i=1,j} * b_j, \sum_j A_{i=2,j} * b_j, ......
print(np.einsum('ij,j->i', A, b))

# \sum_i A_{i,j=0} * b_j, \sum_i A_{i,j=1} * b_j, \sum_i A_{i,j=2} * b_j, ......
print(np.einsum('ij,j->j', A, b))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2]
42
[ 5 14 23]
[ 0 12 30]


In [190]:
a = np.arange(0, 6).reshape(2, 3)
b = np.arange(0, 6).reshape(3, 2)
print(a)
print(b)

# 矩阵乘法
c = np.einsum('ik,kj->ij', a, b)
print(c)

[[0 1 2]
 [3 4 5]]
[[0 1]
 [2 3]
 [4 5]]
[[10 13]
 [28 40]]


In [191]:
a = np.arange(0, 6).reshape(2, 3)
b = np.arange(1, 7).reshape(2, 3)
print(a)
print(b)

# 矩阵对应元素相乘
c0 = np.einsum('ij,ij->ij', a, b)
print(c0)

# 矩阵对应元素相乘并求和
c1 = np.einsum('ij,ij->', a, b)
print(c1)

[[0 1 2]
 [3 4 5]]
[[1 2 3]
 [4 5 6]]
[[ 0  2  6]
 [12 20 30]]
70


In [192]:
ba = np.arange(0, 24).reshape((2, 3, 4))
bb = np.arange(0, 24).reshape((2, 4, 3))
print(ba)

# 批量矩阵乘法
bc = np.einsum('bij,bjk->bjk', ba, bb)
# bc = np.einsum('...ij,...jk->...jk', ba, bb)  # 与上等价(前面或后面任意个维度可用 ... 代替)
print(bc)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[[   0   12   24]
  [  45   60   75]
  [ 108  126  144]
  [ 189  210  231]]

 [[ 576  624  672]
  [ 765  816  867]
  [ 972 1026 1080]
  [1197 1254 1311]]]


In [193]:
# 批量转置
ba = np.arange(0, 120).reshape((2, 3, 4, 5))
np.einsum('...ij->...ji', ba).shape  # 最后两个维度转置
# np.einsum('mnij->mnji', ba)  # 与上等价

(2, 3, 5, 4)

## 综合

1. $$  a_{q, j} * b_{k} $$
2. $$ \sum_{k} a_{q, j} * b_{k} $$
3. $$ \sum_{j} \sum_{k} a_{q, j} * b_{k} $$
4. $$ \sum_{q} \sum_{j} \sum_{k} a_{q, j} * b_{k} $$

In [194]:
a = np.arange(6).reshape(2, 3)
b = np.arange(4).reshape(4)

print(a)
print(b, end='\n\n')

# 1
print(np.einsum('qj,k->qjk', a, b))
print(np.swapaxes(np.einsum('qj,k->qjk', a, b), 1, 2))
print(np.einsum('qj,k->qkj', a, b), end='\n\n')  # 与上等价

# 2
print(np.sum(np.einsum('qj,k->qjk', a, b), axis=-1))
print(np.einsum('qj,k->qj', a, b), end='\n\n')  # 与上等价

# 3
print(np.sum(np.einsum('qj,k->qj', a, b), axis=-1))
print(np.einsum('qj,k->q', a, b), end='\n\n')  # 与上等价

# 4
print(np.sum(np.einsum('qj,k->q', a, b), axis=-1))
print(np.einsum('qj,k->', a, b))  # 与上等价

[[0 1 2]
 [3 4 5]]
[0 1 2 3]

[[[ 0  0  0  0]
  [ 0  1  2  3]
  [ 0  2  4  6]]

 [[ 0  3  6  9]
  [ 0  4  8 12]
  [ 0  5 10 15]]]
[[[ 0  0  0]
  [ 0  1  2]
  [ 0  2  4]
  [ 0  3  6]]

 [[ 0  0  0]
  [ 3  4  5]
  [ 6  8 10]
  [ 9 12 15]]]
[[[ 0  0  0]
  [ 0  1  2]
  [ 0  2  4]
  [ 0  3  6]]

 [[ 0  0  0]
  [ 3  4  5]
  [ 6  8 10]
  [ 9 12 15]]]

[[ 0  6 12]
 [18 24 30]]
[[ 0  6 12]
 [18 24 30]]

[18 72]
[18 72]

90
90


In [202]:
Q = np.random.rand(32, 20, 8, 1)
K = np.random.rand(32, 10, 1, 8)

# 相同部分(n h d)必须满足相等或可广播
M = np.einsum("nqhd,nkhd->nhqk", Q, K)
print(M.shape)

(32, 8, 20, 10)
