In [14]:
import numpy as np

arr1 = np.array([1, 0, 0, 4])
arr2 = np.array([3, 4, 0, 0])

result = arr1 / arr2
result

<ipython-input-14-c0fa820627d8>:6: RuntimeWarning: divide by zero encountered in true_divide
  result = arr1 / arr2
<ipython-input-14-c0fa820627d8>:6: RuntimeWarning: invalid value encountered in true_divide
  result = arr1 / arr2


array([0.33333333, 0.        ,        nan,        inf])

In [15]:
result.dtype

dtype('float64')

In [16]:
# 判断是否未nan值
np.isnan(result[2])

True

In [17]:
np.isnan(result)

array([False, False,  True, False])

In [18]:
# 判断是否为inf值
np.isinf(result[3])

True

In [19]:
np.isinf(result)

array([False, False, False,  True])