In [1]:
import numpy as np

arr1 = np.array([1, 0, 0, 4])
arr2 = np.array([3, 4, 0, 0])

result = arr1 / arr2
result

C:\Users\duanm\AppData\Local\Temp/ipykernel_13016/26065487.py:6: RuntimeWarning: divide by zero encountered in true_divide
  result = arr1 / arr2
C:\Users\duanm\AppData\Local\Temp/ipykernel_13016/26065487.py:6: RuntimeWarning: invalid value encountered in true_divide
  result = arr1 / arr2


array([0.33333333, 0.        ,        nan,        inf])

In [2]:
result.dtype

dtype('float64')

In [3]:
result[0] = 'd'
print(type(result[0]))
print(type(result[1]))

ValueError: could not convert string to float: 'd'

In [ ]:
# 判断是否未nan值
np.isnan(result[2])

In [4]:
np.isnan(result)

array([False, False,  True, False])

In [6]:
# 判断是否为inf(inf或-inf)值
np.isinf(result[3])

True

In [7]:
np.isinf(result)

array([False, False, False,  True])