In [14]:
import numpy as np

In [15]:
arr1 = np.array([1, 0, 0, 4])
arr2 = np.array([3, 4, 0, 0])

result = arr1 / arr2
result

C:\Users\duanm\AppData\Local\Temp/ipykernel_23972/4021490111.py:4: RuntimeWarning: divide by zero encountered in true_divide
  result = arr1 / arr2
C:\Users\duanm\AppData\Local\Temp/ipykernel_23972/4021490111.py:4: RuntimeWarning: invalid value encountered in true_divide
  result = arr1 / arr2


array([0.33333333, 0.        ,        nan,        inf])

In [16]:
result.dtype

dtype('float64')

In [17]:
# 判断是否未nan值
np.isnan(result[2])

True

In [18]:
np.isnan(result)

array([False, False,  True, False])

In [19]:
# 判断是否为inf(inf或-inf)值
np.isinf(result[3])

True

In [20]:
np.isinf(result)

array([False, False, False,  True])