In [18]:
import numpy as np

In [19]:
'''
unique(ar, return_index=False, return_inverse=False, return_counts=False, axis=None)
                                 Returns the sorted unique elements of an array.
'''
arr = np.array([[5, 5, 2, 2, 3, 3], 
               [3, 3, 4, 4, 5, 5]])
arr

array([[5, 5, 2, 2, 3, 3],
       [3, 3, 4, 4, 5, 5]])

In [20]:
np.unique(arr)  # 返回数组arr的唯一值并排序

array([2, 3, 4, 5])

In [30]:
# 返回唯一值和唯一值出现的次数
an_ = np.unique(arr, return_counts=True)  # 元组
print(an_)
an_dict = dict(zip(*an_))
print(an_dict)

(array([2, 3, 4, 5]), array([2, 4, 2, 4], dtype=int64))
{2: 2, 3: 4, 4: 2, 5: 4}


In [ ]:
np.unique(arr, axis=1)

In [ ]:
np.unique(arr, axis=0)