In [1]:
import numpy as np

'''
numpy.argwhere(a)         Find the indices of array elements that are non-zero, grouped by element.
'''
x = np.arange(9.).reshape(3, 3)
x

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [2]:
print(np.argwhere(x > -2))
print(np.argwhere(x > -2).shape)

[[0 0]
 [0 1]
 [0 2]
 [1 0]
 [1 1]
 [1 2]
 [2 0]
 [2 1]
 [2 2]]
(9, 2)


In [3]:
np.argwhere(x == 4)

array([[1, 1]], dtype=int64)