In [14]:
import numpy as np

x = np.array([3, 1, 2])
print(np.argsort(x))
print(x[np.argsort(x)])  # Returns the indices that would sort an array.

[1 2 0]
[1 2 3]


In [15]:
x = np.array([[0, 3],
              [2, 1]])
np.argsort(x)  # 默认axis=-1

array([[0, 1],
       [1, 0]], dtype=int64)

In [16]:
np.argsort(x, axis=0)

array([[0, 1],
       [1, 0]], dtype=int64)

In [17]:
np.argsort(x, axis=None)  # If None,the flattened array is used.

array([0, 3, 2, 1], dtype=int64)