In [7]:
import numpy as np

In [8]:
a = np.array([[4, 2],
              [5, 7],
              [3, 7],
              [2, 6],
              [7, 4],
              [1, 9]])
a

array([[4, 2],
       [5, 7],
       [3, 7],
       [2, 6],
       [7, 4],
       [1, 9]])

In [9]:
np.sort(a)  # Return a sorted copy of an array.

array([[2, 4],
       [5, 7],
       [3, 7],
       [2, 6],
       [4, 7],
       [1, 9]])

In [10]:
np.sort(a, axis=0)  # 默认axis=-1

array([[1, 2],
       [2, 4],
       [3, 6],
       [4, 7],
       [5, 7],
       [7, 9]])

In [11]:
'''
axis : int or None, optional
    Axis along which to sort. If None, the array is flattened before sorting. 
    The default is -1, which sorts along the last axis.
'''
np.sort(a, axis=None)

array([1, 2, 2, 3, 4, 4, 5, 6, 7, 7, 7, 9])

In [12]:
a[np.argsort(a[:, 0])]  # 只排序0维度的第一组数据(该维度元素对应关系不变)

array([[1, 9],
       [2, 6],
       [3, 7],
       [4, 2],
       [5, 7],
       [7, 4]])