In [1]:
import  numpy as np

x = np.array([3, 1, 2])
np.argsort(x)  # Returns the indices that would sort an array.

array([1, 2, 0], dtype=int64)

In [9]:
x = np.array([[0, 3],
              [2, 2]])
np.argsort(x)  # 默认axis=-1

array([[0, 1],
       [0, 1]], dtype=int64)

In [12]:
np.argsort(x, axis=0)

array([[0, 1],
       [1, 0]], dtype=int64)

In [14]:
np.argsort(x, axis=None)  # If None,the flattened array is used.

array([0, 2, 3, 1], dtype=int64)