In [33]:
import numpy as np

In [34]:
a = [1, 2, 3, 4, 5]
np.pad(a, (2, 3),   # 填充到每个轴边缘的数量
       'constant',  # 使用常数进行填充
       constant_values=(4, 6))  # 填充的值(默认为0)

array([4, 4, 1, 2, 3, 4, 5, 6, 6, 6])

In [35]:
np.pad(a, (2, 3), 'edge')  # 使用该轴边缘值进行填充

array([1, 1, 1, 2, 3, 4, 5, 5, 5, 5])

In [36]:
np.pad(a, (2, 3), 'mean')  # 使用该轴平均值进行填充

array([3, 3, 1, 2, 3, 4, 5, 3, 3, 3])

In [37]:
np.pad(a, (2, 3), 'maximum')  # 使用该轴最大值进行填充

array([5, 5, 1, 2, 3, 4, 5, 5, 5, 5])

In [38]:
np.pad(a, (2, 3), 'minimum')  # 使用该轴最小值进行填充

array([1, 1, 1, 2, 3, 4, 5, 1, 1, 1])

In [39]:
a = [[1, 2],
     [3, 4]]
np.pad(a, [(1, 2), (3, 4)],
       'constant',
       constant_values=[(1, 11), (9, 99)])


array([[ 9,  9,  9,  1,  1, 99, 99, 99, 99],
       [ 9,  9,  9,  1,  2, 99, 99, 99, 99],
       [ 9,  9,  9,  3,  4, 99, 99, 99, 99],
       [ 9,  9,  9, 11, 11, 99, 99, 99, 99],
       [ 9,  9,  9, 11, 11, 99, 99, 99, 99]])