In [96]:
import numpy as np

'''
def isin(element, test_elements, assume_unique=False, invert=False):
    """
    Calculates `element in test_elements`, broadcasting over `element` only.
    Returns a boolean array of the same shape as `element` that is True
    where an element of `element` is in `test_elements` and False otherwise.

    Parameters
    ----------
    element : array_like
        Input array.
    test_elements : array_like
        The values against which to test each value of `element`.
        This argument is flattened if it is an array or array_like.
        See notes for behavior with non-array-like parameters.
'''
element = 2 * np.arange(4).reshape((2, 2))
element

array([[0, 2],
       [4, 6]])

In [97]:
test_elements = [1, 2, 4, 8]

In [98]:
mask = np.isin(element, test_elements)
mask

array([[False,  True],
       [ True, False]])

In [99]:
element[mask]  # element,test_elements共用的元素为2, 4

array([2, 4])

In [100]:
np.nonzero(mask)  # 返回非零元素的索引

(array([0, 1], dtype=int64), array([1, 0], dtype=int64))

In [101]:
mask_invert = np.isin(element, test_elements, invert=True)
'''
invert : bool, optional
    If True, the values in the returned array are inverted, as if
    calculating `element not in test_elements`. Default is False.
    ``np.isin(a, b, invert=True)`` is equivalent to (but faster
    than) ``np.invert(np.isin(a, b))`
'''
mask_invert

array([[ True, False],
       [False,  True]])

In [102]:
element[mask_invert]  # 元素0, 6是test_element所不含的

array([0, 6])

In [103]:
test_set = {1, 2, 4, 8}

# 失败,Because of how array handles sets, the following does not work as expected:
print(np.isin(element, test_set), end='\n\n')

# 解决方法如下:
print(np.isin(element, list(test_set)))

[[False False]
 [False False]]

[[False  True]
 [ True False]]
