In [1]:
import  numpy as np

'''
def isin(element, test_elements, assume_unique=False, invert=False):
    """
    Calculates `element in test_elements`, broadcasting over `element` only.
    Returns a boolean array of the same shape as `element` that is True
    where an element of `element` is in `test_elements` and False otherwise.

    Parameters
    ----------
    element : array_like
        Input array.
    test_elements : array_like
        The values against which to test each value of `element`.
        This argument is flattened if it is an array or array_like.
        See notes for behavior with non-array-like parameters.
'''
element = 2 * np.arange(4).reshape((2, 2))
element

array([[0, 2],
       [4, 6]])

In [2]:
test_elements = [1, 2, 4, 8]

In [3]:
mask = np.isin(element, test_elements)
mask

array([[False,  True],
       [ True, False]])

In [4]:
element[mask]  # element,test_elements共用的元素为2, 4

array([2, 4])

In [5]:
np.nonzero(mask)  # 返回非零元素的索引

(array([0, 1], dtype=int64), array([1, 0], dtype=int64))

In [6]:
mask_invert = np.isin(element, test_elements, invert=True)
'''
invert : bool, optional
    If True, the values in the returned array are inverted, as if
    calculating `element not in test_elements`. Default is False.
    ``np.isin(a, b, invert=True)`` is equivalent to (but faster
    than) ``np.invert(np.isin(a, b))`
'''
mask_invert

array([[ True, False],
       [False,  True]])

In [7]:
element[mask_invert]  # 元素0, 6是test_element所不含的

array([0, 6])

In [8]:
test_set = {1, 2, 4, 8}
np.isin(element, test_set)  # 失败,Because of how array handles sets, the following does not work as expected:

array([[False, False],
       [False, False]])

In [9]:
# 解决方法如下:
np.isin(element, list(test_set))

array([[False,  True],
       [ True, False]])

### 判断一个数组是否在另一个数组中(将数组看作一个整体)

In [10]:
arr_e = np.array([1, 2, 3, 4, 5], ndmin=2)
arr_c = np.array([[3, 2, 3, 4, 1],
                  [1, 2, 3, 4, 5],
                  [3, 4, 5, 6, 7]])

In [11]:
# 方法一(自定义函数)
def isin_whole(arr, arr1):
    """二维数组的整体包含关系判断"""   
    def put_list(to_list):
        if to_list.shape[0] == 1:
            return to_list.tolist()[0]
        else:
            return to_list.tolist()
        
    if arr.shape[1] != arr1.shape[1]:
        return False
    else:
        try:
            result = put_list(arr).index(put_list(arr1))
        except ValueError:
            return False
        else:
            return result

isin_whole(arr_c, arr_e)

1

In [12]:
# 方法二(利用tolist()先转换为列表,再通过成员运算符in进行判断)

arr_e_list = arr_e.tolist()[0]
arr_e_list

[1, 2, 3, 4, 5]

In [13]:
arr_c_list = arr_c.tolist()
arr_c_list

[[3, 2, 3, 4, 1], [1, 2, 3, 4, 5], [3, 4, 5, 6, 7]]

In [14]:
arr_e_list in arr_c_list

True