In [1]:
import numpy as np

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [2]:
'''
obj : slice, int or array of ints
    Indicate indices of sub-arrays to remove along the specified axis.
'''
np.delete(arr, obj=1, axis=0)  # If `axis` is None, `obj` is applied to the flattened array.

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [3]:
arr[[0, 2]]  # 于上等价

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [4]:
np.delete(arr, 1, axis=1)

array([[ 1,  3,  4],
       [ 5,  7,  8],
       [ 9, 11, 12]])

In [5]:
arr[:, [0, 2, 3]]  # 于上等价

array([[ 1,  3,  4],
       [ 5,  7,  8],
       [ 9, 11, 12]])

In [6]:
np.delete(arr, [1], axis=None)  # If `axis` is None, `obj` is applied to the flattened array.

array([ 1,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [7]:
np.delete(arr, [1, 3, 5], None)

array([ 1,  3,  5,  7,  8,  9, 10, 11, 12])

In [8]:
arr  # arr不变

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])