In [1]:
import  numpy as np

In [2]:
arr1 = np.array([[1., 2., 3.], [4., 5., 6.]])
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

In [3]:
arr1 + arr2  # 对应元素相加

array([[ 1.,  6.,  4.],
       [11.,  7., 18.]])

In [4]:
arr2 - arr1  # 对应元素相减

array([[-1.,  2., -2.],
       [ 3., -3.,  6.]])

In [5]:
arr2 / arr1

array([[0.        , 2.        , 0.33333333],
       [1.75      , 0.4       , 2.        ]])

In [6]:
arr2 // arr1

array([[0., 2., 0.],
       [1., 0., 2.]])

In [7]:
arr2 % arr1

array([[0., 0., 1.],
       [3., 2., 0.]])

In [8]:
arr2 > arr1

array([[False,  True, False],
       [ True, False,  True]])