In [2]:
import numpy as np
# set_printoptions作用于整个.ipynb文件

In [10]:
# Floating point precision can be set:
np.set_printoptions(precision=4) 
print(np.array([1.123456789]))

[1.1235]


In [11]:
# Long arrays can be summarised:
np.set_printoptions(threshold=999) 
s = np.arange(1000)
print(s)
# 若threshold>=len(s),则显示所有s元素
# 若threshold<len(s),则只显示部分元素(前后各三个)

[  0   1   2 ... 997 998 999]


In [12]:
# A custom formatter can be used to display array elements as desired:
np.set_printoptions(formatter={'all':lambda x: 'int: ' + str(-x)}) 
x = np.arange(3)
print(x)
'''
formatter : dict of callables, optional
If not None, the keys should indicate the type(s) that the respective formatting function applies to. Callables
should return a string. Types that are not specified (by their corresponding keys) are handled by the default
formatters. Individual types for which a formatter can be set are:
    ‘bool’
    ‘int’
    ‘timedelta’ : a numpy.timedelta64
    ‘datetime’ : a numpy.datetime64
    ‘float’
    ‘longfloat’ : 128-bit floats
    ‘complexfloat’
    ‘longcomplexfloat’ : composed of two 128-bit floats
    ‘numpystr’ : types numpy.string_ and numpy.unicode_
    ‘object’ : np.object_ arrays
    ‘str’ : all other strings
Other keys that can be used to set a group of types at once are:
    ‘all’ : sets all types
    ‘int_kind’ : sets ‘int’
    ‘float_kind’ : sets ‘float’ and ‘longfloat’
    ‘complex_kind’ : sets ‘complexfloat’ and ‘longcomplexfloat’
    ‘str_kind’ : sets ‘str’ and ‘numpystr’
'''

[int: 0 int: -1 int: -2]


'\nformatter : dict of callables, optional\nIf not None, the keys should indicate the type(s) that the respective formatting function applies to. Callables should return a string. Types that are not specified (by their corresponding keys) are handled by the default formatters. Individual types for which a formatter can be set are:\n\n‘bool’\n‘int’\n‘timedelta’ : a numpy.timedelta64\n‘datetime’ : a numpy.datetime64\n‘float’\n‘longfloat’ : 128-bit floats\n‘complexfloat’\n‘longcomplexfloat’ : composed of two 128-bit floats\n‘numpystr’ : types numpy.string_ and numpy.unicode_\n‘object’ : np.object_ arrays\n‘str’ : all other strings\n    Other keys that can be used to set a group of types at once are:\n‘all’ : sets all types\n‘int_kind’ : sets ‘int’\n‘float_kind’ : sets ‘float’ and ‘longfloat’\n‘complex_kind’ : sets ‘complexfloat’ and ‘longcomplexfloat’\n‘str_kind’ : sets ‘str’ and ‘numpystr’\n'

In [13]:
# To put back the default options, you can use:
np.set_printoptions(edgeitems=3, infstr='inf',
    linewidth=75, nanstr='nan', precision=8,
    suppress=False, threshold=1000, formatter=None) 
print(np.array([1.123456789]))
print(np.arange(10))
print(x)

[1.12345679]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2]


In [14]:
import numpy as np
from contextlib import contextmanager
@contextmanager
def printoptions(*args, **kwargs):
    original_options = np.get_printoptions()
    np.set_printoptions(*args, **kwargs)
    try:
        yield
    finally:
        np.set_printoptions(**original_options)
        
with printoptions(precision=4, threshold=5):
    # 局部设置,用with做代码块区分
    print(np.array([1.123456789]))
    print(np.arange(10))

[1.1235]
[0 1 2 ... 7 8 9]


In [15]:
print(np.array([1.123456789]))
print(np.arange(10)) # 退出with块时,将自动恢复选项值



[1.12345679]
[0 1 2 3 4 5 6 7 8 9]
