In [25]:
import numpy as np

arr = np.linspace(0, 1, 100)
'''
与sklearn.utils.shuffle的区别
1. np.random.shuffle只能对一个数据集进行随机化,sklearn.utils.shuffle可同时对多个数据集进行一致的随机化
2. np.random.shuffle是对arr进行随机化,sklearn.utils.shuffle是对arr的一个副本进行随机化,arr不变
'''
np.random.shuffle(arr)  # 随机排列数组arr

In [26]:
arr  # arr改变

array([0.36363636, 0.94949495, 0.06060606, 0.72727273, 0.88888889,
       0.41414141, 0.92929293, 0.45454545, 0.02020202, 0.63636364,
       0.67676768, 0.58585859, 0.8989899 , 0.60606061, 0.98989899,
       0.43434343, 0.56565657, 0.64646465, 0.37373737, 0.96969697,
       0.04040404, 0.91919192, 0.78787879, 0.31313131, 0.86868687,
       0.97979798, 0.07070707, 0.6969697 , 0.33333333, 0.47474747,
       0.44444444, 0.49494949, 0.24242424, 0.09090909, 0.95959596,
       0.14141414, 0.87878788, 0.08080808, 0.19191919, 0.73737374,
       0.57575758, 0.22222222, 0.18181818, 0.83838384, 0.52525253,
       0.3030303 , 0.        , 0.35353535, 0.51515152, 0.11111111,
       0.29292929, 0.32323232, 0.01010101, 0.39393939, 0.26262626,
       0.42424242, 0.90909091, 0.03030303, 0.50505051, 0.84848485,
       0.21212121, 0.66666667, 0.55555556, 0.80808081, 0.71717172,
       0.76767677, 0.75757576, 0.2020202 , 0.17171717, 0.38383838,
       0.65656566, 0.13131313, 0.15151515, 0.68686869, 0.12121

In [27]:
x2 = np.arange(60).reshape((3, 4, 5))
x2

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [28]:
np.random.shuffle(x2)  # 多维时,按axis=0进行随机排列
x2

array([[[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]],

       [[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]]])