In [1]:
import numpy as np

arr = np.linspace(0, 1, 100)
arr

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [2]:
'''
与sklearn.utils.shuffle的区别
1. np.random.shuffle只能对一个数据集进行随机化,sklearn.utils.shuffle可同时对多个数据集进行一致的随机化
2. np.random.shuffle是对arr进行随机化,sklearn.utils.shuffle是对arr的一个副本进行随机化,arr不变
'''
np.random.shuffle(arr)  # 随机排列数组arr

In [3]:
arr  # arr改变

array([0.        , 0.92929293, 0.50505051, 0.09090909, 0.08080808,
       0.88888889, 0.46464646, 0.33333333, 0.45454545, 0.32323232,
       0.90909091, 0.91919192, 0.17171717, 0.18181818, 0.28282828,
       0.24242424, 0.15151515, 0.44444444, 0.13131313, 0.26262626,
       0.12121212, 0.55555556, 0.47474747, 0.02020202, 0.05050505,
       0.84848485, 0.3030303 , 0.21212121, 0.80808081, 0.4040404 ,
       0.76767677, 0.23232323, 0.77777778, 0.36363636, 0.35353535,
       0.11111111, 0.63636364, 0.49494949, 0.7979798 , 0.2020202 ,
       0.27272727, 0.97979798, 0.38383838, 0.34343434, 0.54545455,
       0.60606061, 0.1010101 , 0.61616162, 0.85858586, 0.03030303,
       0.72727273, 0.39393939, 0.81818182, 0.8989899 , 0.95959596,
       0.96969697, 0.66666667, 0.5959596 , 0.07070707, 0.06060606,
       0.04040404, 0.31313131, 0.48484848, 0.6969697 , 0.82828283,
       0.51515152, 0.25252525, 0.22222222, 0.94949495, 0.56565657,
       0.71717172, 0.19191919, 0.62626263, 0.58585859, 0.65656

In [4]:
x2 = np.arange(12).reshape((3, 4))
x2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [5]:
np.random.shuffle(x2)  # 多维时,按axis=0进行随机排列
x2

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [ 4,  5,  6,  7]])