In [10]:
import torch
import torch.nn as nn

In [11]:
# Input: (N, C, L) or (C, L)
a = torch.ones((2, 3, 4))
a

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [12]:
m1d = nn.Dropout1d(p=0.2)
m1d(a)  # 对最后一个维度整体进行dropout

tensor([[[1.2500, 1.2500, 1.2500, 1.2500],
         [1.2500, 1.2500, 1.2500, 1.2500],
         [0.0000, 0.0000, 0.0000, 0.0000]],

        [[0.0000, 0.0000, 0.0000, 0.0000],
         [1.2500, 1.2500, 1.2500, 1.2500],
         [0.0000, 0.0000, 0.0000, 0.0000]]])

In [13]:
b = torch.ones((2, 3, 4, 5))
b

tensor([[[[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]]],


        [[[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]]]])

In [15]:
# Input: (N, C, H, W) or (N, C, L)
m2d = nn.Dropout2d(p=0.2)
m2d(b)  # 对最后两个个维度整体进行dropout

tensor([[[[1.2500, 1.2500, 1.2500, 1.2500, 1.2500],
          [1.2500, 1.2500, 1.2500, 1.2500, 1.2500],
          [1.2500, 1.2500, 1.2500, 1.2500, 1.2500],
          [1.2500, 1.2500, 1.2500, 1.2500, 1.2500]],

         [[1.2500, 1.2500, 1.2500, 1.2500, 1.2500],
          [1.2500, 1.2500, 1.2500, 1.2500, 1.2500],
          [1.2500, 1.2500, 1.2500, 1.2500, 1.2500],
          [1.2500, 1.2500, 1.2500, 1.2500, 1.2500]],

         [[0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000]]],


        [[[1.2500, 1.2500, 1.2500, 1.2500, 1.2500],
          [1.2500, 1.2500, 1.2500, 1.2500, 1.2500],
          [1.2500, 1.2500, 1.2500, 1.2500, 1.2500],
          [1.2500, 1.2500, 1.2500, 1.2500, 1.2500]],

         [[1.2500, 1.2500, 1.2500, 1.2500, 1.2500],
          [1.2500, 1.2500, 1.2500, 1.2500, 1.2500],
          [1.2500, 1.2500, 1.2500, 1.2500, 1.2500],
  