In [4]:
import torch

x = torch.tensor([[1., 2., 3.0, 4.0],
                  [5., 6., 7.0, 8.0]], requires_grad=True)

pr = torch.prod(x)

pr.backward()
x.grad

tensor([[40320., 20160., 13440., 10080.],
        [ 8064.,  6720.,  5760.,  5040.]])

In [5]:
su = x.sum()
su.backward()
print(x.grad) # x梯度不清零,梯度累加

tensor([[40321., 20161., 13441., 10081.],
        [ 8065.,  6721.,  5761.,  5041.]])


In [6]:
me = x.mean()
x.grad.zero_() # 手动使梯度清零
me.backward()
print(x.grad) # 得到正确的梯度

tensor([[0.1250, 0.1250, 0.1250, 0.1250],
        [0.1250, 0.1250, 0.1250, 0.1250]])
