In [100]:
import torch

x = torch.tensor([1., 2., 3., 4.], requires_grad=True)
print(x, id(x), x.is_leaf, x.requires_grad)

#计算图确定前,可以通过此方式修改x的初始值(也可以通过detach函数),从而改变x.grad
x.data = x.reshape(2, 2)
print(x, id(x), x.is_leaf, x.requires_grad)

# x = x + 39 # 报错,x不是叶tensor

y = x**2 # 计算图确定后,x.grad已经被计算

# 计算图确定后,若通过s修改x的值,将会报错
# s = x.detach()
# s.fill_(10)

# 计算图确定后,通过x.data修改x的值,x得到修改,也不会报错,但不能改变x.grad(比较容易使结果混淆)
x.data = x.reshape(1, -1) # 不推荐使用
print(x, id(x), x.is_leaf, x.requires_grad)

tensor([1., 2., 3., 4.], requires_grad=True) 2266641046168 True True
tensor([[1., 2.],
        [3., 4.]], requires_grad=True) 2266641046168 True True
tensor([[1., 2., 3., 4.]], requires_grad=True) 2266641046168 True True


In [101]:
y.backward(torch.ones_like(y, dtype=torch.float32))
print(x.grad)



tensor([[2., 4.],
        [6., 8.]])
