In [60]:
import torch

x = torch.tensor([1., 2., 3., 4.], requires_grad=True)
print(x, id(x), x.is_leaf, x.requires_grad)

# 计算图确定前,可以通过此方式修改x的初始值(也可以通过detach函数),从而改变x.grad
x.data = x.reshape(2, 2)
print(x, id(x), x.is_leaf, x.requires_grad)

y = x ** 2  # 计算图确定后,x.grad已经被计算
print(y)

# 计算图确定后,通过detach函数或x.data修改x的值,都将会报错
# s = x.detach()
# s.fill_(10)
#
# x.data = x.reshape(1, -1)

tensor([1., 2., 3., 4.], requires_grad=True) 2127003274592 True True
tensor([[1., 2.],
        [3., 4.]], requires_grad=True) 2127003274592 True True
tensor([[ 1.,  4.],
        [ 9., 16.]], grad_fn=<PowBackward0>)


In [61]:
# ★★★★★若y不为标量,则必须指定权重向量gradient
y.backward(gradient=torch.ones_like(y, dtype=torch.float32))
print(x.grad)

tensor([[2., 4.],
        [6., 8.]])


In [62]:
x.data.add_(1)

tensor([[2., 3.],
        [4., 5.]])

In [63]:
y1 = x  # 新的计算题

In [64]:
y1.backward(gradient=torch.ones_like(y, dtype=torch.float32))
x.grad  # 梯度累加

tensor([[3., 5.],
        [7., 9.]])