In [1]:
import tensorflow as tf

### 参考torch.nn.Linear

In [2]:
enter = tf.constant([[1, 2, 3, 4, 5, 6],
                     [2, 3, 4, 5, 6, 7]])


In [3]:
'''
tf.keras.layers.Dense(
    units, activation=None, use_bias=True,
    kernel_initializer='glorot_uniform',
    bias_initializer='zeros', kernel_regularizer=None,
    bias_regularizer=None, activity_regularizer=None, kernel_constraint=None,
    bias_constraint=None, **kwargs
)
'''
x = tf.keras.layers.Dense(units=1,  # 输出特征的维度
                          activation=tf.nn.relu,  # Activation function to use.
                          kernel_initializer='glorot_uniform',  # Initializer for the kernel weights matrix.
                          bias_initializer='zeros',  # Initializer for the bias vector.
                          use_bias=True, name='Dense')  # 是否引入偏置参数
output = x(enter)
output

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[0.        ],
       [0.41651034]], dtype=float32)>

In [4]:
x.kernel

<tf.Variable 'Dense/kernel:0' shape=(6, 1) dtype=float32, numpy=
array([[ 0.7639741 ],
       [-0.04427791],
       [ 0.8689095 ],
       [-0.36983126],
       [-0.09200495],
       [-0.2932937 ]], dtype=float32)>

In [5]:
x.bias

<tf.Variable 'Dense/bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>

In [6]:
x.name

'Dense'