In [1]:
import tensorflow as tf

### 参考numpy.split

In [2]:
tor = tf.reshape(tf.range(40), (4, 10))
tor

<tf.Tensor: shape=(4, 10), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])>

In [3]:
# Splits a tensor `value` into a list of sub tensors.
# 将tor在维度1上拆分为a,b,c
# a的维度1上的尺寸为1,b在维度1上的尺寸为2,b在维度1上的尺寸为7
# a,b,c在维度1上的尺寸之和必须等于tor在维度1上的尺寸
a, b, c = tf.split(tor, [1, 2, 7], axis=1)
print(a)
print(b)
print(c)

tf.Tensor(
[[ 0]
 [10]
 [20]
 [30]], shape=(4, 1), dtype=int32)
tf.Tensor(
[[ 1  2]
 [11 12]
 [21 22]
 [31 32]], shape=(4, 2), dtype=int32)
tf.Tensor(
[[ 3  4  5  6  7  8  9]
 [13 14 15 16 17 18 19]
 [23 24 25 26 27 28 29]
 [33 34 35 36 37 38 39]], shape=(4, 7), dtype=int32)


In [4]:
m, n = tf.split(tor, [1, 3], axis=0)
print(m)
print(n)

tf.Tensor([[0 1 2 3 4 5 6 7 8 9]], shape=(1, 10), dtype=int32)
tf.Tensor(
[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]], shape=(3, 10), dtype=int32)


In [5]:
tf.split(tor, 2, axis=0)  # 拆分成大小均等的两块

[<tf.Tensor: shape=(2, 10), dtype=int32, numpy=
 array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])>,
 <tf.Tensor: shape=(2, 10), dtype=int32, numpy=
 array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])>]