In [369]:
import numpy as np

a = np.array([1, 2, 3]) # shape=(3,)
b = np.array([4, 5, 6])

np.r_[a] # (3, ) --> (3, )

array([1, 2, 3])

In [370]:
np.r_[a, b] # (3, ) (3, ) --> (6, )

array([1, 2, 3, 4, 5, 6])

In [371]:
np.r_[a.reshape(-1, 1), b.reshape(-1, 1)] # (3, 1) (3, 1) --> (6, 1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [372]:
np.r_[a.reshape(1, -1), b.reshape(1, -1)] # (1, 3) (1, 3) --> (2, 6)

array([[1, 2, 3],
       [4, 5, 6]])

In [373]:
c = np.array([[1, 2, 3],[4, 5, 6]])
d = np.array([[0, 0, 0],[1, 1, 1]])
np.r_[c, d] # (2, 3) (2, 3) --> (4, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [0, 0, 0],
       [1, 1, 1]])

In [374]:
np.r_[c, np.array([9, 9, 9]).reshape(1, -1)] # (2, 3) (2, 1) --> (2, 4)

array([[1, 2, 3],
       [4, 5, 6],
       [9, 9, 9]])

In [375]:
np.r_[-1:1:6j]

array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ])