In [ ]:
import  numpy as np 
import pandas as pd

print(np.sum([0.5, 1.5])) # 求和
print(np.cumsum([0.5, 1.5])) # 累和 

In [2]:
print(np.sum([0.5, 0.7, 0.2, 1.5], dtype=np.float))
print(np.cumsum([0.5, 0.7, 0.2, 1.5], dtype=np.float))

2.9
[0.5 1.2 1.4 2.9]


In [3]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(np.sum(a))
print(np.cumsum(a))

21
[ 1  3  6 10 15 21]


In [4]:
print(np.sum(a, axis=0)) # 列和
print(np.cumsum(a, axis=0))

[5 7 9]
[[1 2 3]
 [5 7 9]]


In [5]:
print(np.sum(a, axis=1)) # 行和
print(np.cumsum(a, axis=1))

[ 6 15]
[[ 1  3  6]
 [ 4  9 15]]


In [7]:
idx = pd.MultiIndex.from_arrays([
     ['warm', 'warm', 'cold', 'cold'],
     ['dog', 'falcon', 'fish', 'spider']],
     names=['blooded', 'animal'])
s = pd.Series([4, 2, 0, 8], name='legs', index=idx)
print(s)

blooded  animal
warm     dog       4
         falcon    2
cold     fish      0
         spider    8
Name: legs, dtype: int64


In [9]:
print(s.sum())

14


In [10]:
print(s.sum(level='blooded'))

blooded
warm    6
cold    8
Name: legs, dtype: int64


In [17]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
                   [np.nan, np.nan], [0.75, -1.3]],
                  index=['a', 'b', 'c', 'd'],
                  columns=['one', 'two'])
print(df)

    one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3


In [19]:
print(df.cumsum(axis=1)) # 默认axis=0
print(np.cumsum(df))

    one   two
a  1.40   NaN
b  7.10  2.60
c   NaN   NaN
d  0.75 -0.55
    one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8
