In [1]:
import numpy as np

### 接受的数据类型
1. 布尔型:Ture/False
2. 数值类型(0表示False,其他表示True)

In [2]:
np.all([[True, False],
        [True, True]])  # 所有元素为True时才返回True

False

In [3]:
np.all([[True, False],
        [True, True]], axis=0)  # 指定轴axis

array([ True, False])

In [4]:
np.any([[True, False],
        [True, True]])  # 所有元素为False才返回False

True

In [5]:
np.any([[True, False],
        [True, True]], axis=0)

array([ True,  True])

In [6]:
arr = np.array([[True, -2.3],
                [0, 0]])
np.any(arr, axis=1)

array([ True, False])

In [7]:
np.logical_not(3)  # 转换x的真假

False

In [8]:
np.logical_not(False)

True

In [9]:
np.logical_not([True, False, 0, 1])

array([False,  True,  True, False])

In [10]:
np.logical_and(True, False)  # Compute the truth value of x1 AND x2 element-wise

False

In [11]:
np.all([[33, False, True],
        [True, 0, True]], axis=0)

array([ True, False,  True])

In [12]:
np.logical_and([33, False, True],
               [True, 0, True])  # 与上等价

array([ True, False,  True])

In [13]:
np.any([[True, False],
        [0, False]], axis=0)

array([ True, False])

In [14]:
# 与上等价
np.logical_or([True, False],
              [0, False])  # Compute the truth value of x1 OR x2 element-wise.

array([ True, False])