## 协方差
<font color='red' size='4'>定义:</font>   
&emsp;&emsp;协方差(Covariance)是度量两个变量的变动的同步程度,也就是度量两个变量线性相关性程度.如果两个变量的协方差为0,则统计
学上认为二者线性无关.注意两个无关的变量并非完全独立,只是没有线性相关性而已.   
&emsp;&emsp;随机变量$ X $ 和$ Y $ 的协方差定义为:  
$$ Cov(X,Y) = E((X-E(X)(Y-E(Y)) $$   

<font color='red' size='4'>计算(总体协方差自由度为$n$,样本协方差自由度为$n-1$):</font>

$$ Cov(X,Y) = \frac{{\sum\limits_{i = 1}^n {({X_i} - \overline X)({Y_i} - \overline Y)} }}{{\text{自由度}}} $$

<font color='red' size=4>性质:</font>

1. 设$ X $ 和$ Y $ 是任意随机变量,则  

$$ Cov(X,Y) = EXY - EXEY $$

2. 设$X$和$Y$是一对独立的随机变量,则$ Cov(X,Y)=0 $,且$ \rho_{XY} =0 $



## 协方差矩阵
&emsp;&emsp;设$X=(X_{1},X_{2},...,X_{p})',Y=(Y_{1},Y_{2},...,Y_{p})'$,称   
\begin{equation}
	\begin{split}%加在equation环境中使之有公式编号
		D(X)&=E(X-EX)(X-EX)'\\
		&=\begin{bmatrix}%生成的是中括号的矩阵
			Cov(X_{1},X_{1}) & Cov(X_{1},X_{2}) & \dots  & Cov(X_{1},X_{p}) \\
			Cov(X_{2},X_{1}) & Cov(X_{2},X_{2}) & \dots  & Cov(X_{1},X_{p}) \\
			\vdots           & \vdots           & \vdots & \vdots \\
 			Cov(X_{p},X_{1}) & Cov(X_{p},X_{1}) & \dots & Cov(X_{p},X_{p}) \\
		\end{bmatrix}
	\end{split}
\end{equation}  
为$ X $的方差或协差阵,有时,把$D(X)$简记为$\sum$,$Cov(x_{i},x_{j})$简记为$\sigma_{ij}$从而有$\sum=(\sigma_{ij})_{p \times p}$<br/>

称随机变量$ X $和$ Y $的协差阵为:        
\begin{equation}
	\begin{split}%加在equation环境中使之有公式编号
		Cov(X,Y)&=E(X-EX)(Y-EY)'\\
		&=\begin{bmatrix}%生成的是中括号的矩阵
			Cov(X_{1},Y_{1}) & Cov(X_{1},Y_{2}) & \dots  & Cov(X_{1},Y_{p}) \\
			Cov(X_{2},Y_{1}) & Cov(X_{2},Y_{2}) & \dots  & Cov(X_{1},Y_{p}) \\
			\vdots           & \vdots           & \vdots & \vdots \\
 			Cov(X_{p},Y_{1}) & Cov(X_{p},Y_{1}) & \dots & Cov(X_{p},Y_{p}) \\
		\end{bmatrix}
	\end{split}
\end{equation}


<font color='red' size=4>证明:</font>协方差矩阵$\Sigma$是半正定矩阵

&emsp;&emsp;设$n$给随机变量$X_i(1 \leq i \leq n)$,数据期望$\mu_i = E(X_i)$,则协方差矩阵为:

\begin{equation}\Sigma=\left[\begin{array}{cccc}
E\left[\left(X_{1}-\mu_{1}\right)\left(X_{1}-\mu_{1}\right)\right] & E\left[\left(X_{1}-\mu_{1}\right)\left(X_{2}-\mu_{2}\right)\right] & \cdots & E\left[\left(X_{1}-\mu_{1}\right)\left(X_{n}-\mu_{n}\right)\right] \\
E\left[\left(X_{2}-\mu_{2}\right)\left(X_{1}-\mu_{1}\right)\right] & E\left[\left(X_{2}-\mu_{2}\right)\left(X_{2}-\mu_{2}\right)\right] & \cdots & E\left[\left(X_{2}-\mu_{2}\right)\left(X_{n}-\mu_{n}\right)\right] \\
\cdots & \cdots & \cdots & \cdots \\
E\left[\left(X_{n}-\mu_{n}\right)\left(X_{1}-\mu_{1}\right)\right] & E\left[\left(X_{n}-\mu_{n}\right)\left(X_{2}-\mu_{2}\right)\right] & \cdots & E\left[\left(X_{n}-\mu_{n}\right)\left(X_{n}-\mu_{n}\right)\right]
\end{array}\right]\end{equation}

要证$\Sigma$为半正定矩阵,即证对于任意非零向量$\mathrm{y} = [y_1, y_2, \cdots, y_n]^n$,有$\mathrm{y}^T \Sigma \mathrm{y} \geq 0$

先求$\mathrm{y}^T \Sigma$:

\begin{equation} \mathbf{y}^T \Sigma=  [y_1, y_2, \cdots, y_n] \left[\begin{array}{cccc}
E\left[\left(X_{1}-\mu_{1}\right)\left(X_{1}-\mu_{1}\right)\right] & E\left[\left(X_{1}-\mu_{1}\right)\left(X_{2}-\mu_{2}\right)\right] & \cdots & E\left[\left(X_{1}-\mu_{1}\right)\left(X_{n}-\mu_{n}\right)\right] \\
E\left[\left(X_{2}-\mu_{2}\right)\left(X_{1}-\mu_{1}\right)\right] & E\left[\left(X_{2}-\mu_{2}\right)\left(X_{2}-\mu_{2}\right)\right] & \cdots & E\left[\left(X_{2}-\mu_{2}\right)\left(X_{n}-\mu_{n}\right)\right] \\
\cdots & \cdots & \cdots & \cdots \\
E\left[\left(X_{n}-\mu_{n}\right)\left(X_{1}-\mu_{1}\right)\right] & E\left[\left(X_{n}-\mu_{n}\right)\left(X_{2}-\mu_{2}\right)\right] & \cdots & E\left[\left(X_{n}-\mu_{n}\right)\left(X_{n}-\mu_{n}\right)\right]
\end{array}\right]\end{equation}

易知$\mathrm{y}^T \Sigma$为$1 \times n$矩阵,其第$k$个元素为:

$$\sum_{i=1}^{n} y_{i} E\left[\left(X_{i}-\mu_{i}\right)\left(X_{k}-\mu_{k}\right)\right]=E\left[\sum_{i=1}^{n} y_{i}\left(X_{i}-\mu_{i}\right)\left(X_{k}-\mu_{k}\right)\right]=E\left[\left(\sum_{i=1}^{n} y_{i}\left(X_{i}-\mu_{i}\right)\right)\left(X_{k}-\mu_{k}\right)\right]$$

即有:

$$Y^{T} \Sigma=\left[ E\left[\left(\sum_{i=1}^{n} y_{i}\left(X_{i}-\mu_{i}\right)\right)\left(X_{1}-\mu_{1}\right)\right] \quad E\left[\left(\sum_{i=1}^{n} y_{i}\left(X_{i}-\mu_{i}\right)\right)\left(X_{2}-\mu_{2}\right)\right] \quad \cdots \quad E\left[\left(\sum_{i=1}^{n} y_{i}\left(X_{i}-\mu_{i}\right)\right)\left(X_{n}-\mu_{i}\right)\right]\right]$$

再算$\mathrm{y}^T \Sigma \mathbf{y}$:

\begin{align}
\mathbf{y}^{T} \Sigma \mathbf{y} &= \sum_{k=1}^{n} E\left[\left(\sum_{i=1}^{n} y_{i}\left(X_{i}-\mu_{i}\right)\right)\left(X_{k}-\mu_{k}\right)\right] y_{k} \\
                                 &= E\left[\sum_{k=1}^{n}\left(\sum_{i=1}^{n} y_{i}\left(X_{i}-\mu_{i}\right)\right)\left(X_{k}-\mu_{k}\right) y_{k}\right] \\
                                 &= E\left[\left(\sum_{i=1}^{n} y_{i}\left(X_{i}-\mu_{i}\right)\right)\left(\sum_{k=1}^{n}\left(X_{k}-\mu_{k}\right) y_{k}\right)\right]
\end{align}

令随机变量$Z=\sum_{i=1}^{n} y_{i}\left(X_{i}-\mu_{i}\right)=\sum_{k=1}^{n}\left(X_{k}-\mu_{k}\right) y_{k}$

则$\mathbf{y}^{T} \Sigma \mathbf{y}=E\left(Z^{2}\right) \geq 0$   

In [2]:
import  numpy as np

x = np.array([[0, 2], [1, 1], [2, 0]]) 
print(np.cov(x, rowvar=True), end='\n\n') # 一行代表一个向量
'''
rowvar : bool, optional
    If rowvar is True (default), then each row represents a variable, 
    with observations in the columns. Otherwise, the relationship is 
    transposed: each column represents a variable, while the rows contain observations.
'''
print(np.cov(x, rowvar=False)) # 一行代表一个向量

[[ 2.  0. -2.]
 [ 0.  0.  0.]
 [-2.  0.  2.]]

[[ 1. -1.]
 [-1.  1.]]


In [3]:
a = [-2.1, -1,  4.3]
b = [3,  1.1,  0.12]
Y = np.stack((a, b), axis=0)
Y

array([[-2.1 , -1.  ,  4.3 ],
       [ 3.  ,  1.1 ,  0.12]])

In [9]:
print(np.cov(Y), end='\n\n')
print(np.cov(a, b), end='\n\n') # 与上等价
print(np.cov(a))

[[11.71       -4.286     ]
 [-4.286       2.14413333]]

[[11.71       -4.286     ]
 [-4.286       2.14413333]]

11.709999999999999
