极差是最高值和最低值之间的差异

In [2]:
import  numpy as np
x = np.arange(4).reshape((2,2))
x

array([[0, 1],
       [2, 3]])

In [3]:
np.ptp(x, axis=0)

array([2, 2])

In [4]:
np.ptp(x, axis=1)

array([1, 1])

In [5]:
np.ptp(x, axis=None)

3

In [ ]:
'''
axis : None or int or tuple of ints, optional
    Axis along which to find the peaks. By default, flatten the array. axis may be negative, in which case it counts from the last to the first axis.
'''
