In [10]:
import tensorflow as tf

In [11]:
x = tf.linspace(0.0, 0.1, 100)
y = tf.reshape(tf.linspace(1, 400, 400), (100, 2, 2))
z = tf.range(1000, 1100)

In [12]:
# Creates a Dataset with a single element, comprising the given tensors.
for i in tf.data.Dataset.from_tensors(x):
    print(i)  # 输出x

tf.Tensor(
[0.         0.0010101  0.0020202  0.0030303  0.0040404  0.00505051
 0.00606061 0.00707071 0.00808081 0.00909091 0.01010101 0.01111111
 0.01212121 0.01313131 0.01414141 0.01515152 0.01616162 0.01717172
 0.01818182 0.01919192 0.02020202 0.02121212 0.02222222 0.02323232
 0.02424243 0.02525253 0.02626263 0.02727273 0.02828283 0.02929293
 0.03030303 0.03131313 0.03232323 0.03333334 0.03434344 0.03535354
 0.03636364 0.03737374 0.03838384 0.03939394 0.04040404 0.04141414
 0.04242424 0.04343434 0.04444445 0.04545455 0.04646465 0.04747475
 0.04848485 0.04949495 0.05050505 0.05151515 0.05252526 0.05353536
 0.05454546 0.05555556 0.05656566 0.05757576 0.05858586 0.05959596
 0.06060606 0.06161616 0.06262626 0.06363637 0.06464647 0.06565657
 0.06666667 0.06767677 0.06868687 0.06969697 0.07070708 0.07171717
 0.07272728 0.07373738 0.07474748 0.07575758 0.07676768 0.07777778
 0.07878789 0.07979798 0.08080809 0.08181819 0.08282828 0.08383839
 0.08484849 0.08585859 0.08686869 0.08787879 0.0888

In [13]:
dataset = tf.data.Dataset.from_tensors((x, y, z))  # 使用元组打包x,y,z

print(len(dataset))
print(dataset)
print(len(dataset._tensors))  # 数据集[x, y, z]
print(dataset._tensors)

1
<TensorDataset shapes: ((100,), (100, 2, 2), (100,)), types: (tf.float32, tf.float64, tf.int32)>
3
[<tf.Tensor: shape=(100,), dtype=float32, numpy=
array([0.        , 0.0010101 , 0.0020202 , 0.0030303 , 0.0040404 ,
       0.00505051, 0.00606061, 0.00707071, 0.00808081, 0.00909091,
       0.01010101, 0.01111111, 0.01212121, 0.01313131, 0.01414141,
       0.01515152, 0.01616162, 0.01717172, 0.01818182, 0.01919192,
       0.02020202, 0.02121212, 0.02222222, 0.02323232, 0.02424243,
       0.02525253, 0.02626263, 0.02727273, 0.02828283, 0.02929293,
       0.03030303, 0.03131313, 0.03232323, 0.03333334, 0.03434344,
       0.03535354, 0.03636364, 0.03737374, 0.03838384, 0.03939394,
       0.04040404, 0.04141414, 0.04242424, 0.04343434, 0.04444445,
       0.04545455, 0.04646465, 0.04747475, 0.04848485, 0.04949495,
       0.05050505, 0.05151515, 0.05252526, 0.05353536, 0.05454546,
       0.05555556, 0.05656566, 0.05757576, 0.05858586, 0.05959596,
       0.06060606, 0.06161616, 0.06262626, 0.0

In [6]:
for i in dataset:
    print(i)  # 输出数据集(x, y, z)

(<tf.Tensor: shape=(100,), dtype=float32, numpy=
array([0.        , 0.0010101 , 0.0020202 , 0.0030303 , 0.0040404 ,
       0.00505051, 0.00606061, 0.00707071, 0.00808081, 0.00909091,
       0.01010101, 0.01111111, 0.01212121, 0.01313131, 0.01414141,
       0.01515152, 0.01616162, 0.01717172, 0.01818182, 0.01919192,
       0.02020202, 0.02121212, 0.02222222, 0.02323232, 0.02424243,
       0.02525253, 0.02626263, 0.02727273, 0.02828283, 0.02929293,
       0.03030303, 0.03131313, 0.03232323, 0.03333334, 0.03434344,
       0.03535354, 0.03636364, 0.03737374, 0.03838384, 0.03939394,
       0.04040404, 0.04141414, 0.04242424, 0.04343434, 0.04444445,
       0.04545455, 0.04646465, 0.04747475, 0.04848485, 0.04949495,
       0.05050505, 0.05151515, 0.05252526, 0.05353536, 0.05454546,
       0.05555556, 0.05656566, 0.05757576, 0.05858586, 0.05959596,
       0.06060606, 0.06161616, 0.06262626, 0.06363637, 0.06464647,
       0.06565657, 0.06666667, 0.06767677, 0.06868687, 0.06969697,
       0.0707

In [7]:
dataset = tf.data.Dataset.from_tensors({"x": x, "y": y, "z": z})  # 使用字典打包x,y
dataset

<TensorDataset shapes: {x: (100,), y: (100, 2, 2), z: (100,)}, types: {x: tf.float32, y: tf.float64, z: tf.int32}>

In [8]:
dataset._tensors  # 数据集[x, y]

[<tf.Tensor: shape=(100,), dtype=float32, numpy=
 array([0.        , 0.0010101 , 0.0020202 , 0.0030303 , 0.0040404 ,
        0.00505051, 0.00606061, 0.00707071, 0.00808081, 0.00909091,
        0.01010101, 0.01111111, 0.01212121, 0.01313131, 0.01414141,
        0.01515152, 0.01616162, 0.01717172, 0.01818182, 0.01919192,
        0.02020202, 0.02121212, 0.02222222, 0.02323232, 0.02424243,
        0.02525253, 0.02626263, 0.02727273, 0.02828283, 0.02929293,
        0.03030303, 0.03131313, 0.03232323, 0.03333334, 0.03434344,
        0.03535354, 0.03636364, 0.03737374, 0.03838384, 0.03939394,
        0.04040404, 0.04141414, 0.04242424, 0.04343434, 0.04444445,
        0.04545455, 0.04646465, 0.04747475, 0.04848485, 0.04949495,
        0.05050505, 0.05151515, 0.05252526, 0.05353536, 0.05454546,
        0.05555556, 0.05656566, 0.05757576, 0.05858586, 0.05959596,
        0.06060606, 0.06161616, 0.06262626, 0.06363637, 0.06464647,
        0.06565657, 0.06666667, 0.06767677, 0.06868687, 0.06969697,

In [9]:
for i in dataset:
    print(i)  # 输出{"x": x, "y": y, "z": z}

{'x': <tf.Tensor: shape=(100,), dtype=float32, numpy=
array([0.        , 0.0010101 , 0.0020202 , 0.0030303 , 0.0040404 ,
       0.00505051, 0.00606061, 0.00707071, 0.00808081, 0.00909091,
       0.01010101, 0.01111111, 0.01212121, 0.01313131, 0.01414141,
       0.01515152, 0.01616162, 0.01717172, 0.01818182, 0.01919192,
       0.02020202, 0.02121212, 0.02222222, 0.02323232, 0.02424243,
       0.02525253, 0.02626263, 0.02727273, 0.02828283, 0.02929293,
       0.03030303, 0.03131313, 0.03232323, 0.03333334, 0.03434344,
       0.03535354, 0.03636364, 0.03737374, 0.03838384, 0.03939394,
       0.04040404, 0.04141414, 0.04242424, 0.04343434, 0.04444445,
       0.04545455, 0.04646465, 0.04747475, 0.04848485, 0.04949495,
       0.05050505, 0.05151515, 0.05252526, 0.05353536, 0.05454546,
       0.05555556, 0.05656566, 0.05757576, 0.05858586, 0.05959596,
       0.06060606, 0.06161616, 0.06262626, 0.06363637, 0.06464647,
       0.06565657, 0.06666667, 0.06767677, 0.06868687, 0.06969697,
       0