## 均匀分布随机样本
1. scipy.stats.uniform.rsv
2. numpy.random.uniform 
3. numpy.random.rand

In [1]:
from  scipy.stats import  uniform
import  numpy as np

# draw a single sample
print(uniform.rvs(), end="\n\n")
#rvs(loc=0, scale=1, size=1, random_state=None)	Random variates.

# draw 10 samples
print(uniform.rvs(size=10).reshape(2, 5), end="\n\n")

# adjust mean ('loc') and standard deviation ('scale')
print(uniform.rvs(loc=10, scale=0.1, size=10), end="\n\n")

0.04174127307962583

[[0.5101813  0.14352064 0.05952323 0.8262057  0.99735161]
 [0.93874638 0.89072205 0.84083116 0.80412011 0.26664706]]

[10.09870211 10.02110135 10.00559956 10.00353245 10.09779257 10.00008754
 10.03617099 10.08240988 10.09645651 10.08435906]



In [2]:
s = np.random.uniform(2, 3, size=5) # 与上基本类似
s

array([2.23608286, 2.71019063, 2.56809768, 2.44708788, 2.78243953])

In [3]:
np.random.rand(3, 2)  # 接受任何尺度
# Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).




array([[0.06064523, 0.89419568],
       [0.82960251, 0.49135479],
       [0.92875675, 0.63572807]])