In [1]:
import numpy as np
from sklearn.utils import shuffle

In [2]:
x1 = np.array([1, 2, 3, 4, 5])
shuffle(x1)  # 注意和np.random.shuffle的区别

array([5, 4, 3, 2, 1])

In [3]:
x1  # x1不变

array([1, 2, 3, 4, 5])

In [4]:
x2 = np.array([[1, 2, 3, 4, 5],
               [2, 3, 4, 5, 6],
               [3, 4, 5, 6, 7],
               [8, 9, 10, 11, 12]])

y = np.array([1, 2, 3, 4])
z = np.array([['one', 'two'],
              ['three', 'four'],
              ['five', 'six'],
              ['seven', 'eight']])

# 以一致的方式随机排列x2, y, z
shuffle(x2, y, z, random_state=8)  # 多维时,按axis=0进行随机排列


[array([[ 3,  4,  5,  6,  7],
        [ 2,  3,  4,  5,  6],
        [ 1,  2,  3,  4,  5],
        [ 8,  9, 10, 11, 12]]),
 array([3, 2, 1, 4]),
 array([['five', 'six'],
        ['three', 'four'],
        ['one', 'two'],
        ['seven', 'eight']], dtype='<U5')]