In [18]:
import tensorflow as tf

In [19]:
x = tf.reshape(tf.range(24), (2, 3, 4))
print(x)

# x.shape=(batch, steps, features)
y = tf.keras.layers.GlobalAveragePooling1D()(x)  # Global average pooling operation for temporal data.
print(y)
print(y.shape)

tf.Tensor(
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]], shape=(2, 3, 4), dtype=int32)
tf.Tensor(
[[ 4  5  6  7]
 [16 17 18 19]], shape=(2, 4), dtype=int32)
(2, 4)


In [20]:
# 与上等价
tf.math.reduce_mean(x, axis=1)

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])>