In [21]:
import tensorflow as tf

### sigmoid激活函数
### 参考torch.sigmoid/torch.nn.Sigmoid

In [22]:
x = tf.linspace(-5, 5, 200)

In [23]:
# 函数
tf.nn.sigmoid(x)

<tf.Tensor: shape=(200,), dtype=float64, numpy=
array([0.00669285, 0.00703534, 0.00739523, 0.00777338, 0.00817071,
       0.00858818, 0.00902677, 0.00948756, 0.00997163, 0.01048013,
       0.01101428, 0.01157533, 0.01216461, 0.01278351, 0.01343346,
       0.01411598, 0.01483266, 0.01558515, 0.01637519, 0.01720457,
       0.01807518, 0.018989  , 0.01994809, 0.02095457, 0.0220107 ,
       0.02311881, 0.02428131, 0.02550075, 0.02677974, 0.02812103,
       0.02952746, 0.03100199, 0.03254769, 0.03416773, 0.03586542,
       0.03764418, 0.03950753, 0.04145915, 0.04350281, 0.04564241,
       0.04788198, 0.05022565, 0.0526777 , 0.05524249, 0.05792451,
       0.06072839, 0.06365881, 0.06672059, 0.06991865, 0.07325795,
       0.07674359, 0.08038068, 0.08417443, 0.08813008, 0.09225289,
       0.09654816, 0.10102115, 0.10567713, 0.11052132, 0.11555887,
       0.12079485, 0.12623421, 0.13188177, 0.13774216, 0.14381982,
       0.15011896, 0.15664352, 0.16339714, 0.1703831 , 0.17760434,
       0.18506

In [24]:
# 函数
tf.math.sigmoid(x)

<tf.Tensor: shape=(200,), dtype=float64, numpy=
array([0.00669285, 0.00703534, 0.00739523, 0.00777338, 0.00817071,
       0.00858818, 0.00902677, 0.00948756, 0.00997163, 0.01048013,
       0.01101428, 0.01157533, 0.01216461, 0.01278351, 0.01343346,
       0.01411598, 0.01483266, 0.01558515, 0.01637519, 0.01720457,
       0.01807518, 0.018989  , 0.01994809, 0.02095457, 0.0220107 ,
       0.02311881, 0.02428131, 0.02550075, 0.02677974, 0.02812103,
       0.02952746, 0.03100199, 0.03254769, 0.03416773, 0.03586542,
       0.03764418, 0.03950753, 0.04145915, 0.04350281, 0.04564241,
       0.04788198, 0.05022565, 0.0526777 , 0.05524249, 0.05792451,
       0.06072839, 0.06365881, 0.06672059, 0.06991865, 0.07325795,
       0.07674359, 0.08038068, 0.08417443, 0.08813008, 0.09225289,
       0.09654816, 0.10102115, 0.10567713, 0.11052132, 0.11555887,
       0.12079485, 0.12623421, 0.13188177, 0.13774216, 0.14381982,
       0.15011896, 0.15664352, 0.16339714, 0.1703831 , 0.17760434,
       0.18506

In [25]:
# 类
layer = tf.keras.layers.Activation(tf.nn.sigmoid, name='sigmoid')  # 可在网络层中简写为:'sigmoid'
output = layer(x)

print(layer.name)
print(output)

sigmoid
tf.Tensor(
[0.00669285 0.00703534 0.00739523 0.00777338 0.00817071 0.00858818
 0.00902677 0.00948756 0.00997163 0.01048013 0.01101428 0.01157533
 0.01216461 0.01278351 0.01343345 0.01411598 0.01483266 0.01558516
 0.01637518 0.01720457 0.01807518 0.018989   0.01994809 0.02095457
 0.0220107  0.02311881 0.02428131 0.02550074 0.02677974 0.02812103
 0.02952746 0.03100199 0.03254768 0.03416773 0.03586543 0.03764418
 0.03950754 0.04145915 0.04350282 0.04564242 0.04788198 0.05022566
 0.0526777  0.05524249 0.05792452 0.06072839 0.06365881 0.06672059
 0.06991865 0.07325795 0.07674358 0.08038067 0.08417442 0.08813007
 0.09225289 0.09654815 0.10102116 0.10567714 0.11052132 0.11555887
 0.12079483 0.12623422 0.13188176 0.13774216 0.14381982 0.15011896
 0.15664351 0.16339713 0.1703831  0.17760433 0.18506338 0.19276223
 0.20070249 0.20888522 0.21731082 0.2259792  0.23488958 0.24404058
 0.25342995 0.26305488 0.27291173 0.2829961  0.29330274 0.3038257
 0.3145582  0.32549253 0.3366203  0.34793228

### softmax激活函数
### 参考tofch.nn.functional.softmax/torch.nn.Softmax

In [26]:
x = tf.linspace(-5, 5, 200)

In [27]:
# tf.math.softmax(x)
tf.nn.softmax(x)  # 与上等价

<tf.Tensor: shape=(200,), dtype=float64, numpy=
array([2.22512610e-06, 2.33979857e-06, 2.46038072e-06, 2.58717710e-06,
       2.72050796e-06, 2.86071007e-06, 3.00813753e-06, 3.16316270e-06,
       3.32617714e-06, 3.49759257e-06, 3.67784194e-06, 3.86738051e-06,
       4.06668700e-06, 4.27626481e-06, 4.49664326e-06, 4.72837897e-06,
       4.97205725e-06, 5.22829355e-06, 5.49773506e-06, 5.78106231e-06,
       6.07899091e-06, 6.39227334e-06, 6.72170086e-06, 7.06810551e-06,
       7.43236222e-06, 7.81539100e-06, 8.21815927e-06, 8.64168431e-06,
       9.08703583e-06, 9.55533866e-06, 1.00477756e-05, 1.05655904e-05,
       1.11100909e-05, 1.16826525e-05, 1.22847211e-05, 1.29178175e-05,
       1.35835407e-05, 1.42835721e-05, 1.50196798e-05, 1.57937230e-05,
       1.66076568e-05, 1.74635368e-05, 1.83635248e-05, 1.93098940e-05,
       2.03050346e-05, 2.13514600e-05, 2.24518132e-05, 2.36088734e-05,
       2.48255630e-05, 2.61049551e-05, 2.74502809e-05, 2.88649385e-05,
       3.03525009e-05, 3.1916

In [28]:
layer = tf.keras.layers.Activation(tf.nn.softmax, name='softmax')  # 可在网络层中简写为:'softmax'
output = layer(x)

print(layer.name)
print(output)

softmax
tf.Tensor(
[2.22512608e-06 2.33979790e-06 2.46037939e-06 2.58717751e-06
 2.72050784e-06 2.86071213e-06 3.00813872e-06 3.16316323e-06
 3.32617674e-06 3.49759102e-06 3.67783969e-06 3.86738111e-06
 4.06668642e-06 4.27626719e-06 4.49664458e-06 4.72837928e-06
 4.97205656e-06 5.22829168e-06 5.49773131e-06 5.78106255e-06
 6.07898937e-06 6.39227619e-06 6.72170245e-06 7.06810533e-06
 7.43236023e-06 7.81538711e-06 8.21816047e-06 8.64168305e-06
 9.08703259e-06 9.55534233e-06 1.00477773e-05 1.05655881e-05
 1.11100862e-05 1.16826450e-05 1.22847214e-05 1.29178152e-05
 1.35835489e-05 1.42835761e-05 1.50196811e-05 1.57937193e-05
 1.66076570e-05 1.74635425e-05 1.83635257e-05 1.93098876e-05
 2.03050349e-05 2.13514650e-05 2.24518135e-05 2.36088672e-05
 2.48255601e-05 2.61049609e-05 2.74502800e-05 2.88649280e-05
 3.03524976e-05 3.19167302e-05 3.35615550e-05 3.52911520e-05
 3.71099195e-05 3.90223795e-05 4.10333960e-05 4.31480730e-05
 4.53717112e-05 4.77099638e-05 5.01686955e-05 5.27541633e-05
 5.54

### 激活函数tanh
### 参考torch.tanh/torch.nn.Tanh

In [29]:
x = tf.linspace(-20, 20, 200)

In [30]:
# tf.math.tanh(x)
tf.nn.tanh(x)  # 与上等价

<tf.Tensor: shape=(200,), dtype=float64, numpy=
array([-1.        , -1.        , -1.        , -1.        , -1.        ,
       -1.        , -1.        , -1.        , -1.        , -1.        ,
       -1.        , -1.        , -1.        , -1.        , -1.        ,
       -1.        , -1.        , -1.        , -1.        , -1.        ,
       -1.        , -1.        , -1.        , -1.        , -1.        ,
       -1.        , -1.        , -1.        , -1.        , -1.        ,
       -1.        , -1.        , -1.        , -1.        , -1.        ,
       -1.        , -1.        , -1.        , -1.        , -1.        ,
       -1.        , -1.        , -1.        , -1.        , -1.        ,
       -1.        , -1.        , -1.        , -1.        , -1.        ,
       -1.        , -0.99999999, -0.99999999, -0.99999998, -0.99999998,
       -0.99999997, -0.99999995, -0.99999992, -0.99999989, -0.99999983,
       -0.99999975, -0.99999962, -0.99999943, -0.99999915, -0.99999873,
       -0.999998

In [31]:
layer = tf.keras.layers.Activation(tf.nn.tanh)  # 可在网络层中简写为:'tanh'
output = layer(x)
output

<tf.Tensor: shape=(200,), dtype=float32, numpy=
array([-1.        , -1.        , -1.        , -1.        , -1.        ,
       -1.        , -1.        , -1.        , -1.        , -1.        ,
       -1.        , -1.        , -1.        , -1.        , -1.        ,
       -1.        , -1.        , -1.        , -1.        , -1.        ,
       -1.        , -1.        , -1.        , -1.        , -1.        ,
       -1.        , -1.        , -1.        , -1.        , -1.        ,
       -1.        , -1.        , -1.        , -1.        , -1.        ,
       -1.        , -1.        , -1.        , -1.        , -1.        ,
       -1.        , -1.        , -1.        , -1.        , -1.        ,
       -1.        , -1.        , -1.        , -1.        , -1.        ,
       -1.        , -1.        , -1.        , -1.        , -1.        ,
       -1.        , -1.        , -1.        , -1.        , -1.        ,
       -1.        , -0.9999997 , -0.9999994 , -0.9999993 , -0.99999887,
       -0.999998

### 激活函数Swish 

Swish activation function which returns $ x * sigmoid(x)$.
It is a smooth, non-monotonic function that consistently matches or outperforms ReLU on deep networks, it is unbounded above and bounded below.

In [32]:
x = tf.constant([-20, -1.0, 0.0, 1.0, 20], dtype=tf.float32)

In [33]:
tf.nn.swish(x)

<tf.Tensor: shape=(5,), dtype=float32, numpy=
array([-4.1223068e-08, -2.6894143e-01,  0.0000000e+00,  7.3105854e-01,
        2.0000000e+01], dtype=float32)>

In [34]:
layer = tf.keras.layers.Activation(tf.nn.swish)
output = layer(x)
output

<tf.Tensor: shape=(5,), dtype=float32, numpy=
array([-4.1223068e-08, -2.6894143e-01,  0.0000000e+00,  7.3105854e-01,
        2.0000000e+01], dtype=float32)>

### 激活函数relu
### 参考torch.functional.relu/torch.nn.ReLU

In [35]:
x = tf.linspace(-5, 5, 200)

In [36]:
tf.nn.relu(x)

<tf.Tensor: shape=(200,), dtype=float64, numpy=
array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.     

In [37]:
layer = tf.keras.layers.Activation(tf.nn.relu)  # 可简称为'relu'
output = layer(x)
output

<tf.Tensor: shape=(200,), dtype=float32, numpy=
array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.     

### 激活函数leaky_relu
### 参考torch.nn.LeakyReLU

In [38]:
x = tf.linspace(-5, 5, 200)

In [39]:
tf.nn.leaky_relu(x,
                 alpha=0.1)  # alpha: Slope of the activation function at x < 0.

<tf.Tensor: shape=(200,), dtype=float64, numpy=
array([-5.00000007e-01, -4.94974882e-01, -4.89949756e-01, -4.84924630e-01,
       -4.79899505e-01, -4.74874379e-01, -4.69849253e-01, -4.64824128e-01,
       -4.59799002e-01, -4.54773876e-01, -4.49748750e-01, -4.44723625e-01,
       -4.39698499e-01, -4.34673373e-01, -4.29648248e-01, -4.24623122e-01,
       -4.19597996e-01, -4.14572870e-01, -4.09547745e-01, -4.04522619e-01,
       -3.99497493e-01, -3.94472368e-01, -3.89447242e-01, -3.84422116e-01,
       -3.79396991e-01, -3.74371865e-01, -3.69346739e-01, -3.64321613e-01,
       -3.59296488e-01, -3.54271362e-01, -3.49246236e-01, -3.44221111e-01,
       -3.39195985e-01, -3.34170859e-01, -3.29145734e-01, -3.24120608e-01,
       -3.19095482e-01, -3.14070356e-01, -3.09045231e-01, -3.04020105e-01,
       -2.98994979e-01, -2.93969854e-01, -2.88944728e-01, -2.83919602e-01,
       -2.78894477e-01, -2.73869351e-01, -2.68844225e-01, -2.63819099e-01,
       -2.58793974e-01, -2.53768848e-01, -2.48743722

In [40]:
# 自定义leaky_relu激活函数层
class MyLeakyRelu():
    pass