In [30]:
import  numpy as np

In [31]:
a = np.arange(64)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [32]:
a.shape # ndim=1

(64,)

In [33]:
a.reshape(2, 32)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63]])

In [34]:
a # a不变

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [35]:
b = np.reshape(a, (8, 8))
# b = a.reshape(8, 8) # 与上等价
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [36]:
b.reshape(-1, 1) # 等价于b.reshape(64, 1);ndim=2

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29],
       [30],
       [31],
       [32],
       [33],
       [34],
       [35],
       [36],
       [37],
       [38],
       [39],
       [40],
       [41],
       [42],
       [43],
       [44],
       [45],
       [46],
       [47],
       [48],
       [49],
       [50],
       [51],
       [52],
       [53],
       [54],
       [55],
       [56],
       [57],
       [58],
       [59],
       [60],
       [61],
       [62],
       [63]])

In [37]:
b.reshape(-1, ) # 等价于b.reshape(64, );ndim=1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [38]:
b.flatten().reshape(8, 8) - b # 不变

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [39]:
arr = np.random.randn(2, 7, 7)
arr

array([[[-0.74763357, -0.86061139, -0.24405203, -0.57718736,
         -0.74227206,  1.5740165 ,  1.40262957],
        [-0.27129338,  0.88175884,  1.08232656, -1.9169936 ,
          1.25549791, -1.36709743,  0.72975126],
        [-0.60448178,  0.64525042, -0.68666222, -0.0455718 ,
          1.25203628,  1.79856345,  1.29146155],
        [-0.35880984, -0.65508536,  0.41426343, -0.37853058,
         -2.00073738,  0.72103131, -0.75106579],
        [-0.25501874, -0.54445696, -0.08923135,  0.90070823,
         -0.15869344, -1.13512946,  0.32874418],
        [-0.13398737, -0.93759949, -0.27212749, -0.1307806 ,
          0.67816581, -0.50392241,  0.25896475],
        [ 0.57870612,  0.00371521,  1.57878557,  1.38227307,
         -0.57918059, -0.87777828,  0.79019062]],

       [[ 1.97541446, -1.97875554, -0.13081384,  1.59103446,
         -0.00751638, -1.11156006,  2.60073152],
        [-0.71076626,  0.22651571,  0.21120209,  0.16970176,
         -0.82360758,  2.14265493,  0.39785696],
        

In [40]:
arr1 = arr.reshape(2, 7*7) # 向量化数据
arr1

array([[-0.74763357, -0.86061139, -0.24405203, -0.57718736, -0.74227206,
         1.5740165 ,  1.40262957, -0.27129338,  0.88175884,  1.08232656,
        -1.9169936 ,  1.25549791, -1.36709743,  0.72975126, -0.60448178,
         0.64525042, -0.68666222, -0.0455718 ,  1.25203628,  1.79856345,
         1.29146155, -0.35880984, -0.65508536,  0.41426343, -0.37853058,
        -2.00073738,  0.72103131, -0.75106579, -0.25501874, -0.54445696,
        -0.08923135,  0.90070823, -0.15869344, -1.13512946,  0.32874418,
        -0.13398737, -0.93759949, -0.27212749, -0.1307806 ,  0.67816581,
        -0.50392241,  0.25896475,  0.57870612,  0.00371521,  1.57878557,
         1.38227307, -0.57918059, -0.87777828,  0.79019062],
       [ 1.97541446, -1.97875554, -0.13081384,  1.59103446, -0.00751638,
        -1.11156006,  2.60073152, -0.71076626,  0.22651571,  0.21120209,
         0.16970176, -0.82360758,  2.14265493,  0.39785696,  0.27473773,
        -0.5554765 ,  0.95613409,  0.22992452, -1.8011709 ,  0.

In [41]:
arr2 = arr1.reshape(2, 7, 7) # 按原顺序恢复成原shape
arr2 - arr

array([[[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]]])

In [42]:
mul_arr = np.arange(120).reshape((2, 3, 4, 5))
mul_arr

array([[[[  0,   1,   2,   3,   4],
         [  5,   6,   7,   8,   9],
         [ 10,  11,  12,  13,  14],
         [ 15,  16,  17,  18,  19]],

        [[ 20,  21,  22,  23,  24],
         [ 25,  26,  27,  28,  29],
         [ 30,  31,  32,  33,  34],
         [ 35,  36,  37,  38,  39]],

        [[ 40,  41,  42,  43,  44],
         [ 45,  46,  47,  48,  49],
         [ 50,  51,  52,  53,  54],
         [ 55,  56,  57,  58,  59]]],


       [[[ 60,  61,  62,  63,  64],
         [ 65,  66,  67,  68,  69],
         [ 70,  71,  72,  73,  74],
         [ 75,  76,  77,  78,  79]],

        [[ 80,  81,  82,  83,  84],
         [ 85,  86,  87,  88,  89],
         [ 90,  91,  92,  93,  94],
         [ 95,  96,  97,  98,  99]],

        [[100, 101, 102, 103, 104],
         [105, 106, 107, 108, 109],
         [110, 111, 112, 113, 114],
         [115, 116, 117, 118, 119]]]])

In [43]:
'''
reshape规则:
mul_arr[0, 0, 0, 0] -> mul_arr[0, 0, 0, 1] ...-> mul_arr[0, 0, 0, -1]
mul_arr[0, 0, 1, 0] -> mul_arr[0, 0, 1, 1] ...-> mul_arr[0, 0, 1, -1]
...  ... ...
mul_arr[0, 0, -1, 0] -> mul_arr[0, 0, -1, 1] ...-> mul_arr[0, 0, -1, -1]
mul_arr[0, 1, 0, 0] -> mul_arr[0, 1, 0, 1] ...-> mul_arr[0, 1, 0, -1]
... ... ...
mul_arr[0, -1, -1, 0] -> mul_arr[0, -1, -1, 1] ...-> mul_arr[0, -1, -1, -1]
mul_arr[1, 0, 0, 0] -> mul_arr[0, 0, 0, 1] ...-> mul_arr[0, 0, 0, -1]
... ... ...
mul_arr[-1, -1, -1, 0] -> mul_arr[-1, -1, -1, 1] ...-> mul_arr[-1, -1, -1, -1]
'''
mul_arr.reshape(10, 12)

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23],
       [ 24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47],
       [ 48,  49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71],
       [ 72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83],
       [ 84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107],
       [108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119]])