In [25]:
import  numpy as np

In [26]:
arr1 = np.arange(14)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [27]:
np.resize(arr1, (3, 7)) # 3*7 > 14,继续使用arr1进行填充

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [ 0,  1,  2,  3,  4,  5,  6]])

In [28]:
np.resize(arr1, (2, 4)) # 2*4 < 14,截断处理

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [29]:
arr1 #arr1不变

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [30]:
arr2 = np.random.randint(4, 7, size=5)
np.resize(arr2, (5, 6))

array([[6, 4, 4, 5, 5, 6],
       [4, 4, 5, 5, 6, 4],
       [4, 5, 5, 6, 4, 4],
       [5, 5, 6, 4, 4, 5],
       [5, 6, 4, 4, 5, 5]])

In [31]:
arr2

array([6, 4, 4, 5, 5])