In [7]:
import numpy as np

In [8]:
arr1 = np.arange(16).reshape((2, 2, 4))
arr1

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [9]:
'''
axes : list of ints, optional
    By default, reverse the dimensions, otherwise permute the axes
    according to the values given.
'''
np.transpose(arr1, axes=(2, 1, 0)) # Permute the dimensions of an array.

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

In [10]:
np.transpose(arr1) # 默认交换维度0和维度-1

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

In [11]:
arr1 # arr1不变

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [12]:
np.transpose(np.transpose(arr1, (2, 0, 1)), (1, 2, 0)) # 得到恢复

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])