In [66]:
import  numpy as np

In [67]:
np.repeat(3, 4) # 等价于np.repeat([3], 4)

array([3, 3, 3, 3])

In [68]:
x = np.array([[1, 2],
              [3, 4]])
np.repeat(x, 2) # 默认axis=None

array([1, 1, 2, 2, 3, 3, 4, 4])

In [69]:
np.repeat(x, 3, axis=1) # x维度1每条数据依次重复3次

array([[1, 1, 1, 2, 2, 2],
       [3, 3, 3, 4, 4, 4]])

In [70]:
np.repeat(x, 3, axis=0) # x维度0每条数据依次重复3次

array([[1, 2],
       [1, 2],
       [1, 2],
       [3, 4],
       [3, 4],
       [3, 4]])

In [71]:
np.repeat(x, [2, 4], axis=1) # x维度1第0条数据重复2次,x维度1第1条数据重复4次

array([[1, 1, 2, 2, 2, 2],
       [3, 3, 4, 4, 4, 4]])

In [72]:
x1 = np.repeat(x, [2, 4], axis=0) # x维度0第0条数据重复2次,x维度0第1条数据重复4次
x1

array([[1, 2],
       [1, 2],
       [3, 4],
       [3, 4],
       [3, 4],
       [3, 4]])

In [73]:
x1[0][0] = 999
x1

array([[999,   2],
       [  1,   2],
       [  3,   4],
       [  3,   4],
       [  3,   4],
       [  3,   4]])

In [74]:
x # x不变

array([[1, 2],
       [3, 4]])

In [75]:
np.tile(3, 4) # 等价于np.tile([3], 4)

array([3, 3, 3, 3])

In [76]:
np.tile(x, (2, 4)) # x维度0数据整体重复2次,维度1数据整体重复4次

array([[1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4]])

In [77]:
x2 = np.tile(x,
        (1, 1, 1, 2)) # 每个维度上重复该array的次数(整体重复)
x2

array([[[[1, 2, 1, 2],
         [3, 4, 3, 4]]]])

In [78]:
x2[0][0][0][0] = 9999
x2

array([[[[9999,    2,    1,    2],
         [   3,    4,    3,    4]]]])

In [79]:
x # x不变

array([[1, 2],
       [3, 4]])