In [80]:
import numpy as np
from sklearn import preprocessing

In [81]:
arr = np.array(['yes', 'no', 'no', 'yes']) # 二类标签

lb = preprocessing.LabelBinarizer()
lb.fit_transform(arr)

array([[1],
       [0],
       [0],
       [1]])

In [82]:
lb.classes_

array(['no', 'yes'], dtype='<U3')

In [83]:
oe = preprocessing.OrdinalEncoder()
oe.fit_transform(arr.reshape(-1, 1)) # 与上等价

array([[1.],
       [0.],
       [0.],
       [1.]])

In [84]:
oe.categories_

[array(['no', 'yes'], dtype='<U3')]

In [85]:
arr1 = np.array(['yes', 'no', 'no', 'or']) # 多类标签
lb1 = preprocessing.LabelBinarizer()
lb1.fit_transform(arr1)

array([[0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0]])

In [86]:
lb1.classes_

array(['no', 'or', 'yes'], dtype='<U3')

In [87]:
ohe = preprocessing.OneHotEncoder()
ohe.fit_transform(arr1.reshape(-1, 1)).toarray() # 与上等价

array([[0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [88]:
ohe.categories_



[array(['no', 'or', 'yes'], dtype='<U3')]