In [163]:
import tensorflow as tf

### 参考torch.utils.data.TensorDataset

In [164]:
x = tf.linspace(0.0, 0.1, 100)
y = tf.reshape(tf.linspace(1, 200, 200), (100, 2))
z = tf.range(1000, 1100)

In [165]:
# Creates a Dataset whose elements are slices of the given tensors.
for i in tf.data.Dataset.from_tensor_slices(x).as_numpy_iterator():
    print(i)

0.0
0.001010101
0.002020202
0.0030303032
0.004040404
0.0050505055
0.0060606063
0.007070707
0.008080808
0.00909091
0.010101011
0.011111111
0.012121213
0.013131314
0.014141414
0.015151516
0.016161617
0.017171718
0.01818182
0.01919192
0.020202022
0.021212121
0.022222223
0.023232324
0.024242425
0.025252527
0.026262628
0.02727273
0.028282829
0.02929293
0.030303031
0.031313132
0.032323234
0.033333335
0.034343436
0.035353538
0.03636364
0.03737374
0.03838384
0.039393943
0.040404044
0.04141414
0.042424243
0.043434344
0.044444446
0.045454547
0.046464648
0.04747475
0.04848485
0.049494952
0.050505053
0.051515155
0.052525256
0.053535357
0.05454546
0.05555556
0.056565657
0.05757576
0.05858586
0.05959596
0.060606062
0.061616164
0.062626265
0.06363637
0.06464647
0.065656565
0.06666667
0.06767677
0.06868687
0.06969697
0.070707075
0.07171717
0.07272728
0.073737375
0.07474748
0.07575758
0.07676768
0.07777778
0.078787886
0.07979798
0.08080809
0.081818186
0.08282828
0.08383839
0.084848486
0.08585859
0.0868

In [166]:
dataset = tf.data.Dataset.from_tensor_slices((x, y, z))
print(dataset)
print(len(dataset))

<TensorSliceDataset shapes: ((), (2,), ()), types: (tf.float32, tf.float64, tf.int32)>
100


In [167]:
dataset._tensors

[<tf.Tensor: shape=(100,), dtype=float32, numpy=
 array([0.        , 0.0010101 , 0.0020202 , 0.0030303 , 0.0040404 ,
        0.00505051, 0.00606061, 0.00707071, 0.00808081, 0.00909091,
        0.01010101, 0.01111111, 0.01212121, 0.01313131, 0.01414141,
        0.01515152, 0.01616162, 0.01717172, 0.01818182, 0.01919192,
        0.02020202, 0.02121212, 0.02222222, 0.02323232, 0.02424243,
        0.02525253, 0.02626263, 0.02727273, 0.02828283, 0.02929293,
        0.03030303, 0.03131313, 0.03232323, 0.03333334, 0.03434344,
        0.03535354, 0.03636364, 0.03737374, 0.03838384, 0.03939394,
        0.04040404, 0.04141414, 0.04242424, 0.04343434, 0.04444445,
        0.04545455, 0.04646465, 0.04747475, 0.04848485, 0.04949495,
        0.05050505, 0.05151515, 0.05252526, 0.05353536, 0.05454546,
        0.05555556, 0.05656566, 0.05757576, 0.05858586, 0.05959596,
        0.06060606, 0.06161616, 0.06262626, 0.06363637, 0.06464647,
        0.06565657, 0.06666667, 0.06767677, 0.06868687, 0.06969697,

In [168]:
for i in dataset.as_numpy_iterator():
    print(i)

(0.0, array([1., 2.]), 1000)
(0.001010101, array([3., 4.]), 1001)
(0.002020202, array([5., 6.]), 1002)
(0.0030303032, array([7., 8.]), 1003)
(0.004040404, array([ 9., 10.]), 1004)
(0.0050505055, array([11., 12.]), 1005)
(0.0060606063, array([13., 14.]), 1006)
(0.007070707, array([15., 16.]), 1007)
(0.008080808, array([17., 18.]), 1008)
(0.00909091, array([19., 20.]), 1009)
(0.010101011, array([21., 22.]), 1010)
(0.011111111, array([23., 24.]), 1011)
(0.012121213, array([25., 26.]), 1012)
(0.013131314, array([27., 28.]), 1013)
(0.014141414, array([29., 30.]), 1014)
(0.015151516, array([31., 32.]), 1015)
(0.016161617, array([33., 34.]), 1016)
(0.017171718, array([35., 36.]), 1017)
(0.01818182, array([37., 38.]), 1018)
(0.01919192, array([39., 40.]), 1019)
(0.020202022, array([41., 42.]), 1020)
(0.021212121, array([43., 44.]), 1021)
(0.022222223, array([45., 46.]), 1022)
(0.023232324, array([47., 48.]), 1023)
(0.024242425, array([49., 50.]), 1024)
(0.025252527, array([51., 52.]), 1025)
(0

In [169]:
dataset = tf.data.Dataset.from_tensor_slices({"x": x, "y": y, "z": z})
dataset

<TensorSliceDataset shapes: {x: (), y: (2,), z: ()}, types: {x: tf.float32, y: tf.float64, z: tf.int32}>

In [170]:
dataset._tensors

[<tf.Tensor: shape=(100,), dtype=float32, numpy=
 array([0.        , 0.0010101 , 0.0020202 , 0.0030303 , 0.0040404 ,
        0.00505051, 0.00606061, 0.00707071, 0.00808081, 0.00909091,
        0.01010101, 0.01111111, 0.01212121, 0.01313131, 0.01414141,
        0.01515152, 0.01616162, 0.01717172, 0.01818182, 0.01919192,
        0.02020202, 0.02121212, 0.02222222, 0.02323232, 0.02424243,
        0.02525253, 0.02626263, 0.02727273, 0.02828283, 0.02929293,
        0.03030303, 0.03131313, 0.03232323, 0.03333334, 0.03434344,
        0.03535354, 0.03636364, 0.03737374, 0.03838384, 0.03939394,
        0.04040404, 0.04141414, 0.04242424, 0.04343434, 0.04444445,
        0.04545455, 0.04646465, 0.04747475, 0.04848485, 0.04949495,
        0.05050505, 0.05151515, 0.05252526, 0.05353536, 0.05454546,
        0.05555556, 0.05656566, 0.05757576, 0.05858586, 0.05959596,
        0.06060606, 0.06161616, 0.06262626, 0.06363637, 0.06464647,
        0.06565657, 0.06666667, 0.06767677, 0.06868687, 0.06969697,

In [171]:
for i in dataset.as_numpy_iterator():
    print(i)

{'x': 0.0, 'y': array([1., 2.]), 'z': 1000}
{'x': 0.001010101, 'y': array([3., 4.]), 'z': 1001}
{'x': 0.002020202, 'y': array([5., 6.]), 'z': 1002}
{'x': 0.0030303032, 'y': array([7., 8.]), 'z': 1003}
{'x': 0.004040404, 'y': array([ 9., 10.]), 'z': 1004}
{'x': 0.0050505055, 'y': array([11., 12.]), 'z': 1005}
{'x': 0.0060606063, 'y': array([13., 14.]), 'z': 1006}
{'x': 0.007070707, 'y': array([15., 16.]), 'z': 1007}
{'x': 0.008080808, 'y': array([17., 18.]), 'z': 1008}
{'x': 0.00909091, 'y': array([19., 20.]), 'z': 1009}
{'x': 0.010101011, 'y': array([21., 22.]), 'z': 1010}
{'x': 0.011111111, 'y': array([23., 24.]), 'z': 1011}
{'x': 0.012121213, 'y': array([25., 26.]), 'z': 1012}
{'x': 0.013131314, 'y': array([27., 28.]), 'z': 1013}
{'x': 0.014141414, 'y': array([29., 30.]), 'z': 1014}
{'x': 0.015151516, 'y': array([31., 32.]), 'z': 1015}
{'x': 0.016161617, 'y': array([33., 34.]), 'z': 1016}
{'x': 0.017171718, 'y': array([35., 36.]), 'z': 1017}
{'x': 0.01818182, 'y': array([37., 38.]), 