In [25]:
import torch

x = torch.ones(2, 3)
x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [26]:
y = torch.zeros(2, 4)
y

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [27]:
z = torch.full((4, 3), 2)
z

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])

In [28]:
# All tensors must either have the same shape (except in the concatenating dimension) or be empty.
torch.cat((x, x, z, z), 0)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])

In [29]:
# 完全类似numpy.concatenate
torch.cat((x, x, y, y), 1)

tensor([[1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.]])