In [56]:
import torch

x = torch.ones((2, 3))
x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [57]:
y = torch.zeros((2, 3))
y

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [45]:
# 完全类似于numpy.stack
# All tensors need to be of the same size.
a = torch.stack((x, y), dim=0) # Concatenates sequence of tensors along a new dimension.
a

tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])

In [46]:
a[0] # 即x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [47]:
a[1] # 即y

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [48]:
b = torch.stack((x, y), dim=1)
b

tensor([[[1., 1., 1.],
         [0., 0., 0.]],

        [[1., 1., 1.],
         [0., 0., 0.]]])

In [49]:
b[:, 0] # 即x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [50]:
b[:, 1] # 即y

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [51]:
c = torch.stack((x, y), dim=2)
c

tensor([[[1., 0.],
         [1., 0.],
         [1., 0.]],

        [[1., 0.],
         [1., 0.],
         [1., 0.]]])

In [52]:
c[..., 0] # 即x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [53]:
c[..., 1] # 即y

tensor([[0., 0., 0.],
        [0., 0., 0.]])