In [16]:
import tensorflow as tf

### 参考numpy.concatenate

In [17]:
a = tf.constant([[1, 2],
                 [3, 4]])
b = tf.constant([[5, 6]])

# Concatenates tensors along one dimension.
tf.concat([a, b], axis=0)  # 在原有的维度上连接数组a,b

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]])>

In [18]:
tf.concat((a, tf.reshape(b, (-1, 1))), axis=1)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 5],
       [3, 4, 6]])>

In [19]:
tf.concat((a, tf.reshape(b, (-1, 1))), axis=-1)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 5],
       [3, 4, 6]])>